<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="adc0eed2-1e8b-4695-b4df-e49232921621" description="Autogenerated based on gis data trafo8_lvnetwork1" name="trafo8_lvnetwork1">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="de029f99-4be9-475e-a864-77e6228c0836"/>
  <instance xsi:type="esdl:Instance" id="e8c59bc6-77d4-4a10-aad2-1b66005f3ff6" name="Instance name">
    <area xsi:type="esdl:Area" id="01ef8e79-a199-4a89-a494-7a1f419105cb" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_2" id="8ffe8aef-36a1-411f-9bb9-f4fe61fc97cf">
        <port xsi:type="esdl:InPort" id="85a80d6a-dc8e-4467-8b79-deab837b42d4" name="In" connectedTo="f625eb67-5158-42b5-a937-fcbfac901bd3"/>
        <port xsi:type="esdl:OutPort" id="2f92e3ef-0240-4239-9472-f860c24d5411" name="Out" connectedTo="09ff3300-c555-4eac-9460-5489525d76bc"/>
        <geometry xsi:type="esdl:Point" lat="157884.269" CRS="WGS84" lon="433549.901"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="113.34881695301968" name="lv_cable_trafo8_lvnetwork1_2_main_grid" id="0a92056b-84cc-4739-b35b-f9e4001f3944" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="3922761c-788a-45ec-ab0e-8d875d19007d" name="In" connectedTo="216d9023-95bd-4f44-a65c-6ddc66117d90"/>
        <port xsi:type="esdl:OutPort" id="f625eb67-5158-42b5-a937-fcbfac901bd3" name="Out" connectedTo="85a80d6a-dc8e-4467-8b79-deab837b42d4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157926.721" CRS="WGS84" lon="433639.248"/>
          <point xsi:type="esdl:Point" lat="157924.376" CRS="WGS84" lon="433637.014"/>
          <point xsi:type="esdl:Point" lat="157922.925" CRS="WGS84" lon="433635.633"/>
          <point xsi:type="esdl:Point" lat="157921.444" CRS="WGS84" lon="433634.222"/>
          <point xsi:type="esdl:Point" lat="157920.163" CRS="WGS84" lon="433633.002"/>
          <point xsi:type="esdl:Point" lat="157919.096" CRS="WGS84" lon="433631.985"/>
          <point xsi:type="esdl:Point" lat="157918.214" CRS="WGS84" lon="433631.145"/>
          <point xsi:type="esdl:Point" lat="157915.526" CRS="WGS84" lon="433628.587"/>
          <point xsi:type="esdl:Point" lat="157913.932" CRS="WGS84" lon="433627.069"/>
          <point xsi:type="esdl:Point" lat="157912.708" CRS="WGS84" lon="433625.904"/>
          <point xsi:type="esdl:Point" lat="157912.932" CRS="WGS84" lon="433625.669"/>
          <point xsi:type="esdl:Point" lat="157914.559" CRS="WGS84" lon="433623.906"/>
          <point xsi:type="esdl:Point" lat="157916.435" CRS="WGS84" lon="433621.861"/>
          <point xsi:type="esdl:Point" lat="157917.253" CRS="WGS84" lon="433621.255"/>
          <point xsi:type="esdl:Point" lat="157920.541" CRS="WGS84" lon="433617.729"/>
          <point xsi:type="esdl:Point" lat="157920.849815426" CRS="WGS84" lon="433617.156690427"/>
          <point xsi:type="esdl:Point" lat="157921.109519995" CRS="WGS84" lon="433616.560486442"/>
          <point xsi:type="esdl:Point" lat="157921.31828193" CRS="WGS84" lon="433615.944593252"/>
          <point xsi:type="esdl:Point" lat="157921.474628771" CRS="WGS84" lon="433615.313354941"/>
          <point xsi:type="esdl:Point" lat="157921.577457754" CRS="WGS84" lon="433614.671223824"/>
          <point xsi:type="esdl:Point" lat="157921.626043598" CRS="WGS84" lon="433614.022729047"/>
          <point xsi:type="esdl:Point" lat="157921.620043609" CRS="WGS84" lon="433613.372444643"/>
          <point xsi:type="esdl:Point" lat="157921.559500109" CRS="WGS84" lon="433612.724957264"/>
          <point xsi:type="esdl:Point" lat="157921.444840129" CRS="WGS84" lon="433612.084833836"/>
          <point xsi:type="esdl:Point" lat="157921.276872401" CRS="WGS84" lon="433611.456589345"/>
          <point xsi:type="esdl:Point" lat="157921.056781652" CRS="WGS84" lon="433610.844654991"/>
          <point xsi:type="esdl:Point" lat="157920.78612025" CRS="WGS84" lon="433610.253346933"/>
          <point xsi:type="esdl:Point" lat="157920.466797251" CRS="WGS84" lon="433609.686835847"/>
          <point xsi:type="esdl:Point" lat="157920.101064938" CRS="WGS84" lon="433609.149117508"/>
          <point xsi:type="esdl:Point" lat="157919.691502932" CRS="WGS84" lon="433608.643984607"/>
          <point xsi:type="esdl:Point" lat="157919.241" CRS="WGS84" lon="433608.175"/>
          <point xsi:type="esdl:Point" lat="157910.704" CRS="WGS84" lon="433599.334"/>
          <point xsi:type="esdl:Point" lat="157909.548570959" CRS="WGS84" lon="433598.271857364"/>
          <point xsi:type="esdl:Point" lat="157908.428" CRS="WGS84" lon="433597.173"/>
          <point xsi:type="esdl:Point" lat="157907.793" CRS="WGS84" lon="433596.366"/>
          <point xsi:type="esdl:Point" lat="157906.748" CRS="WGS84" lon="433595.039"/>
          <point xsi:type="esdl:Point" lat="157905.427" CRS="WGS84" lon="433593.361"/>
          <point xsi:type="esdl:Point" lat="157905.37" CRS="WGS84" lon="433593.289"/>
          <point xsi:type="esdl:Point" lat="157904.336" CRS="WGS84" lon="433591.975"/>
          <point xsi:type="esdl:Point" lat="157902.418" CRS="WGS84" lon="433589.752"/>
          <point xsi:type="esdl:Point" lat="157902.1" CRS="WGS84" lon="433589.379"/>
          <point xsi:type="esdl:Point" lat="157901.801" CRS="WGS84" lon="433588.766"/>
          <point xsi:type="esdl:Point" lat="157901.343" CRS="WGS84" lon="433587.827"/>
          <point xsi:type="esdl:Point" lat="157900.928" CRS="WGS84" lon="433586.976"/>
          <point xsi:type="esdl:Point" lat="157900.542" CRS="WGS84" lon="433586.183"/>
          <point xsi:type="esdl:Point" lat="157900.347" CRS="WGS84" lon="433585.483"/>
          <point xsi:type="esdl:Point" lat="157899.567" CRS="WGS84" lon="433583.501"/>
          <point xsi:type="esdl:Point" lat="157899.294" CRS="WGS84" lon="433582.685"/>
          <point xsi:type="esdl:Point" lat="157898.731" CRS="WGS84" lon="433580.463"/>
          <point xsi:type="esdl:Point" lat="157898.256" CRS="WGS84" lon="433578.008"/>
          <point xsi:type="esdl:Point" lat="157898.102" CRS="WGS84" lon="433576.878"/>
          <point xsi:type="esdl:Point" lat="157897.894" CRS="WGS84" lon="433575.185"/>
          <point xsi:type="esdl:Point" lat="157897.492" CRS="WGS84" lon="433571.907"/>
          <point xsi:type="esdl:Point" lat="157897.364" CRS="WGS84" lon="433570.86"/>
          <point xsi:type="esdl:Point" lat="157897.537" CRS="WGS84" lon="433568.173"/>
          <point xsi:type="esdl:Point" lat="157897.424" CRS="WGS84" lon="433567.362"/>
          <point xsi:type="esdl:Point" lat="157897.232" CRS="WGS84" lon="433565.644"/>
          <point xsi:type="esdl:Point" lat="157896.977" CRS="WGS84" lon="433563.608"/>
          <point xsi:type="esdl:Point" lat="157896.828" CRS="WGS84" lon="433562.392"/>
          <point xsi:type="esdl:Point" lat="157896.776" CRS="WGS84" lon="433561.993"/>
          <point xsi:type="esdl:Point" lat="157896.582" CRS="WGS84" lon="433561.13"/>
          <point xsi:type="esdl:Point" lat="157896.467" CRS="WGS84" lon="433560.636"/>
          <point xsi:type="esdl:Point" lat="157896.282" CRS="WGS84" lon="433559.897"/>
          <point xsi:type="esdl:Point" lat="157896.06" CRS="WGS84" lon="433559.092"/>
          <point xsi:type="esdl:Point" lat="157895.75" CRS="WGS84" lon="433558.223"/>
          <point xsi:type="esdl:Point" lat="157895.579" CRS="WGS84" lon="433557.902"/>
          <point xsi:type="esdl:Point" lat="157895.391" CRS="WGS84" lon="433557.551"/>
          <point xsi:type="esdl:Point" lat="157895.134" CRS="WGS84" lon="433557.103"/>
          <point xsi:type="esdl:Point" lat="157894.863" CRS="WGS84" lon="433556.669"/>
          <point xsi:type="esdl:Point" lat="157894.447" CRS="WGS84" lon="433556.011"/>
          <point xsi:type="esdl:Point" lat="157894.226" CRS="WGS84" lon="433555.698"/>
          <point xsi:type="esdl:Point" lat="157893.871" CRS="WGS84" lon="433555.189"/>
          <point xsi:type="esdl:Point" lat="157893.48" CRS="WGS84" lon="433554.649"/>
          <point xsi:type="esdl:Point" lat="157892.981" CRS="WGS84" lon="433554.15"/>
          <point xsi:type="esdl:Point" lat="157892.549" CRS="WGS84" lon="433553.712"/>
          <point xsi:type="esdl:Point" lat="157892.19" CRS="WGS84" lon="433553.441"/>
          <point xsi:type="esdl:Point" lat="157884.269" CRS="WGS84" lon="433549.901"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_3" id="4b1d1f09-6ed6-4e73-88c0-610a23bc43cc">
        <port xsi:type="esdl:InPort" id="c1d89548-d10e-40c4-8e22-de34119d1c14" name="In" connectedTo="27842516-48ff-4016-85ac-eea7bfab07fa"/>
        <port xsi:type="esdl:OutPort" id="dbc1cec2-e535-4a65-a240-aff939dadab2" name="Out" connectedTo="28d53d00-f921-45cc-ba0f-bde13f143496"/>
        <geometry xsi:type="esdl:Point" lat="157883.431" CRS="WGS84" lon="433550.095"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.8601627752731168" name="lv_cable_trafo8_lvnetwork1_3_main_grid" id="3901d5ea-1e45-423c-b2a5-cdcacac3a93f" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="09ff3300-c555-4eac-9460-5489525d76bc" name="In" connectedTo="2f92e3ef-0240-4239-9472-f860c24d5411"/>
        <port xsi:type="esdl:OutPort" id="27842516-48ff-4016-85ac-eea7bfab07fa" name="Out" connectedTo="c1d89548-d10e-40c4-8e22-de34119d1c14"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157884.269" CRS="WGS84" lon="433549.901"/>
          <point xsi:type="esdl:Point" lat="157883.431" CRS="WGS84" lon="433550.095"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_4" id="8b134a91-ab55-4cae-834f-b28b5a5ff8c5">
        <port xsi:type="esdl:InPort" id="c243ebd2-a79e-477b-a6b1-acaa9231789b" name="In" connectedTo="cb3852a8-5405-468f-86c7-596bee85b8d2"/>
        <port xsi:type="esdl:OutPort" id="0e899b33-015e-4cbc-bd5b-68860a4b6afe" name="Out" connectedTo="65f3f4c0-06fb-44ed-948e-4f0329a689b2 37be2563-90c3-49d4-8fe5-ca0ec0a79769"/>
        <geometry xsi:type="esdl:Point" lat="157838.30250231898" CRS="WGS84" lon="433530.6870607319"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="49.12539930182201" name="lv_cable_trafo8_lvnetwork1_4_main_grid" id="719e8dbd-4d55-4240-8444-ee82c9e3a2a0" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="28d53d00-f921-45cc-ba0f-bde13f143496" name="In" connectedTo="dbc1cec2-e535-4a65-a240-aff939dadab2"/>
        <port xsi:type="esdl:OutPort" id="cb3852a8-5405-468f-86c7-596bee85b8d2" name="Out" connectedTo="c243ebd2-a79e-477b-a6b1-acaa9231789b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157883.431" CRS="WGS84" lon="433550.095"/>
          <point xsi:type="esdl:Point" lat="157880.529" CRS="WGS84" lon="433548.861"/>
          <point xsi:type="esdl:Point" lat="157863.077" CRS="WGS84" lon="433541.44"/>
          <point xsi:type="esdl:Point" lat="157861.031" CRS="WGS84" lon="433540.558"/>
          <point xsi:type="esdl:Point" lat="157857.445" CRS="WGS84" lon="433539.013"/>
          <point xsi:type="esdl:Point" lat="157856.067" CRS="WGS84" lon="433538.419"/>
          <point xsi:type="esdl:Point" lat="157841.024" CRS="WGS84" lon="433531.901"/>
          <point xsi:type="esdl:Point" lat="157840.399" CRS="WGS84" lon="433531.63"/>
          <point xsi:type="esdl:Point" lat="157838.30250231898" CRS="WGS84" lon="433530.6870607319"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.894797479968293" name="lv_cable_trafo8_lvnetwork1_to_home_5_arch6" id="636c857f-dd9c-48f0-afa3-b307a7d466ce" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="65f3f4c0-06fb-44ed-948e-4f0329a689b2" name="In" connectedTo="0e899b33-015e-4cbc-bd5b-68860a4b6afe"/>
        <port xsi:type="esdl:OutPort" id="5b0e4954-c8df-4771-a28a-aa944c331fb7" name="Out" connectedTo="8685a74f-d9d9-4203-992d-4d65ff48d621"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157844.002" CRS="WGS84" lon="433518.015"/>
          <point xsi:type="esdl:Point" lat="157838.30250231898" CRS="WGS84" lon="433530.6870607319"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome770" id="fbf204d5-5c2f-48f7-9420-b4c668ae9647">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="1df7e5a3-adc6-4eb3-9779-4c4afeef9498" name="In" connectedTo="45eac0d0-2c9b-484d-b4db-ba802e5822d7"/>
          <port xsi:type="esdl:OutPort" id="64682621-7fa1-46cc-a034-a52ce0a62213" name="Out" connectedTo="92f8e6f3-2d5d-4810-83c9-ce1fb44f5285"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="01503ebc-2944-4ee5-98bb-d0b4cc19313a" name="In" connectedTo="26ce5e46-4259-4862-ae8d-d2cc3dea7d90"/>
          <port xsi:type="esdl:OutPort" id="fd855000-eef0-480e-907a-7ccde3fd47e7" name="Out" connectedTo="acf55762-25e2-4356-90be-4a9ad204163b"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="164e7569-61ff-4ad7-b5ea-98588cbb8e66" name="In" connectedTo="619e4aad-0795-4e68-92c3-f1083de03cf4"/>
          <port xsi:type="esdl:OutPort" id="673737db-b2b9-4c33-ab67-568e09f183ea" name="Out" connectedTo="01ef75cf-0309-45a1-97aa-7b847e1cb010"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="055c58ce-df1d-4910-b1bd-b51fdfca41fc" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="92f8e6f3-2d5d-4810-83c9-ce1fb44f5285" name="In_Ph1" connectedTo="64682621-7fa1-46cc-a034-a52ce0a62213"/>
          <port xsi:type="esdl:InPort" id="acf55762-25e2-4356-90be-4a9ad204163b" name="In_Ph2" connectedTo="fd855000-eef0-480e-907a-7ccde3fd47e7"/>
          <port xsi:type="esdl:InPort" id="01ef75cf-0309-45a1-97aa-7b847e1cb010" name="In_Ph3" connectedTo="673737db-b2b9-4c33-ab67-568e09f183ea"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome770" id="6a49d58e-46f3-42cd-bce7-8dd8de3f11ee">
          <port xsi:type="esdl:InPort" id="8685a74f-d9d9-4203-992d-4d65ff48d621" name="In" connectedTo="5b0e4954-c8df-4771-a28a-aa944c331fb7"/>
          <port xsi:type="esdl:OutPort" id="45eac0d0-2c9b-484d-b4db-ba802e5822d7" name="OutPh1" connectedTo="1df7e5a3-adc6-4eb3-9779-4c4afeef9498"/>
          <port xsi:type="esdl:OutPort" id="26ce5e46-4259-4862-ae8d-d2cc3dea7d90" name="OutPh2" connectedTo="01503ebc-2944-4ee5-98bb-d0b4cc19313a"/>
          <port xsi:type="esdl:OutPort" id="619e4aad-0795-4e68-92c3-f1083de03cf4" name="OutPh3" connectedTo="164e7569-61ff-4ad7-b5ea-98588cbb8e66"/>
          <geometry xsi:type="esdl:Point" lat="157844.002" lon="433518.015"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_5" id="c0646aa5-36a4-4958-bfc1-24c654877125">
        <port xsi:type="esdl:InPort" id="250b6072-1b03-415d-9b59-ecfe4889e194" name="In" connectedTo="d7fecd0a-d0c9-4a55-b770-91fa66c891f0"/>
        <port xsi:type="esdl:OutPort" id="dcadba26-bcd9-4e86-866c-425b001d7ffb" name="Out" connectedTo="853350c6-4e51-4916-babd-740ea81aa8d2 04795e06-c860-48c4-8b6a-5df1fc3a2b8d"/>
        <geometry xsi:type="esdl:Point" lat="157837.112" CRS="WGS84" lon="433530.151"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.3056264842372705" name="lv_cable_trafo8_lvnetwork1_5_main_grid" id="37992b3e-c4dc-44a4-a622-c6751403e52b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="37be2563-90c3-49d4-8fe5-ca0ec0a79769" name="In" connectedTo="0e899b33-015e-4cbc-bd5b-68860a4b6afe"/>
        <port xsi:type="esdl:OutPort" id="d7fecd0a-d0c9-4a55-b770-91fa66c891f0" name="Out" connectedTo="250b6072-1b03-415d-9b59-ecfe4889e194"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157838.30250231898" CRS="WGS84" lon="433530.6870607319"/>
          <point xsi:type="esdl:Point" lat="157837.193" CRS="WGS84" lon="433530.188"/>
          <point xsi:type="esdl:Point" lat="157837.112" CRS="WGS84" lon="433530.151"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.878604280420086" name="lv_cable_trafo8_lvnetwork1_to_home_4_arch6" id="a5a9f8c8-8a64-4a87-bf40-d83cf9543b5b" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="853350c6-4e51-4916-babd-740ea81aa8d2" name="In" connectedTo="dcadba26-bcd9-4e86-866c-425b001d7ffb"/>
        <port xsi:type="esdl:OutPort" id="307624e6-5994-4e91-a018-ec5e90cdf120" name="Out" connectedTo="51cd2b70-1279-4c9c-8c8e-faa089aed4bb"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157842.66149684836" CRS="WGS84" lon="433517.4302004378"/>
          <point xsi:type="esdl:Point" lat="157837.112" CRS="WGS84" lon="433530.151"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome769" id="aa0a0efb-50f6-4794-bb82-ed12de42220c">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="1cc0f7a0-2c05-4c08-a05c-03b2e29a3515" name="In" connectedTo="a8053e64-7504-4c3d-9b60-6c6c4b41755d"/>
          <port xsi:type="esdl:OutPort" id="294f20ff-d3e9-40b0-ba25-4520e9c95aa3" name="Out" connectedTo="47519c57-53e3-44b6-a23e-964a3ab1c9a1"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="3ebfaadf-2809-4879-bef4-be8edeca7d40" name="In" connectedTo="fa21f633-963c-4542-9755-65b6e33b1b71"/>
          <port xsi:type="esdl:OutPort" id="bde60aea-3709-4b7a-a54b-a2ab252a7fe3" name="Out" connectedTo="e4324a18-6a47-40a6-b900-217fac38f156"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="ab115a38-8565-42b9-95e5-30175721a1c5" name="In" connectedTo="3208236c-d187-4019-b9f6-27ab1945f220"/>
          <port xsi:type="esdl:OutPort" id="23067cc2-9a85-4731-acd0-92599b4cfecc" name="Out" connectedTo="7b663b27-a9f2-4b60-b1d3-ddbf9ae56ebe"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="d2e2e83e-d005-45ec-a4b3-a819538e9dba" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="47519c57-53e3-44b6-a23e-964a3ab1c9a1" name="In_Ph1" connectedTo="294f20ff-d3e9-40b0-ba25-4520e9c95aa3"/>
          <port xsi:type="esdl:InPort" id="e4324a18-6a47-40a6-b900-217fac38f156" name="In_Ph2" connectedTo="bde60aea-3709-4b7a-a54b-a2ab252a7fe3"/>
          <port xsi:type="esdl:InPort" id="7b663b27-a9f2-4b60-b1d3-ddbf9ae56ebe" name="In_Ph3" connectedTo="23067cc2-9a85-4731-acd0-92599b4cfecc"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome769" id="2ed1fd78-f842-4523-b826-56043a14554c">
          <port xsi:type="esdl:InPort" id="51cd2b70-1279-4c9c-8c8e-faa089aed4bb" name="In" connectedTo="307624e6-5994-4e91-a018-ec5e90cdf120"/>
          <port xsi:type="esdl:OutPort" id="a8053e64-7504-4c3d-9b60-6c6c4b41755d" name="OutPh1" connectedTo="1cc0f7a0-2c05-4c08-a05c-03b2e29a3515"/>
          <port xsi:type="esdl:OutPort" id="fa21f633-963c-4542-9755-65b6e33b1b71" name="OutPh2" connectedTo="3ebfaadf-2809-4879-bef4-be8edeca7d40"/>
          <port xsi:type="esdl:OutPort" id="3208236c-d187-4019-b9f6-27ab1945f220" name="OutPh3" connectedTo="ab115a38-8565-42b9-95e5-30175721a1c5"/>
          <geometry xsi:type="esdl:Point" lat="157842.66149684836" lon="433517.4302004378"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_6" id="d2488b61-b28e-47da-967d-a74c4433bc0f">
        <port xsi:type="esdl:InPort" id="f1ab185c-5944-4d23-b7fd-3f0ecfb49176" name="In" connectedTo="1aca0e5e-9a8c-4dcc-aaba-df228fcb15bd"/>
        <port xsi:type="esdl:OutPort" id="510361dd-0b6e-41f6-8f6c-83fc35c020c8" name="Out" connectedTo="a0b8823b-dff5-4c75-9532-cad7d479833a f0f3bb37-a6b4-4d85-96f2-d6fe68c3628b"/>
        <geometry xsi:type="esdl:Point" lat="157828.82278800284" CRS="WGS84" lon="433527.1941135713"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.876387282412008" name="lv_cable_trafo8_lvnetwork1_6_main_grid" id="9d023ed7-9dc6-43ac-b1e1-fe88068b7866" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="04795e06-c860-48c4-8b6a-5df1fc3a2b8d" name="In" connectedTo="dcadba26-bcd9-4e86-866c-425b001d7ffb"/>
        <port xsi:type="esdl:OutPort" id="1aca0e5e-9a8c-4dcc-aaba-df228fcb15bd" name="Out" connectedTo="f1ab185c-5944-4d23-b7fd-3f0ecfb49176"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157837.112" CRS="WGS84" lon="433530.151"/>
          <point xsi:type="esdl:Point" lat="157836.686" CRS="WGS84" lon="433530.105"/>
          <point xsi:type="esdl:Point" lat="157835.024" CRS="WGS84" lon="433529.926"/>
          <point xsi:type="esdl:Point" lat="157833.029" CRS="WGS84" lon="433529.047"/>
          <point xsi:type="esdl:Point" lat="157828.82278800284" CRS="WGS84" lon="433527.1941135713"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.5079936197203727" name="lv_cable_trafo8_lvnetwork1_to_home_2_arch6" id="983a1ad0-7d78-498c-a077-ad877616218d" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="a0b8823b-dff5-4c75-9532-cad7d479833a" name="In" connectedTo="510361dd-0b6e-41f6-8f6c-83fc35c020c8"/>
        <port xsi:type="esdl:OutPort" id="28bf9e4c-2cfb-4d51-af9a-fdcaa2c895a0" name="Out" connectedTo="1ec0e5f5-fdc5-4683-9d9e-1823287ce0a6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157828.618" CRS="WGS84" lon="433527.659"/>
          <point xsi:type="esdl:Point" lat="157828.82278800284" CRS="WGS84" lon="433527.1941135713"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome767" id="2046947a-661b-4ddb-9f8c-d8fd15d88ae8">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="4533f862-226b-495c-81e8-45f17462208c" name="In" connectedTo="a22a7873-fdf7-42ad-bf4b-a9798faa8029"/>
          <port xsi:type="esdl:OutPort" id="963af52c-6f95-4003-ad4a-de1bfad8ccf3" name="Out" connectedTo="407e47f2-f4b3-403f-a131-891aae246801"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="86ea262a-7828-4695-a413-53814a22b00d" name="In" connectedTo="fe1b9f82-ded1-4486-989e-d783bbbe7b65"/>
          <port xsi:type="esdl:OutPort" id="bf9784f2-c610-4b74-9b22-8cb0ed174e29" name="Out" connectedTo="cf158bad-4ccd-4d86-a1dc-2e1952f39258"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="2a3805c2-4261-4190-bfb7-3bc92d850739" name="In" connectedTo="6759f00e-dc0f-4e11-8ef8-03025c9148db"/>
          <port xsi:type="esdl:OutPort" id="7436d2c9-ba1a-4412-b5a4-374bf2feb3c0" name="Out" connectedTo="93951a50-4cf3-41a4-a6b0-f18793c2e730"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="5d67230d-befd-4bb1-8d61-8bbecd429d87" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="407e47f2-f4b3-403f-a131-891aae246801" name="In_Ph1" connectedTo="963af52c-6f95-4003-ad4a-de1bfad8ccf3"/>
          <port xsi:type="esdl:InPort" id="cf158bad-4ccd-4d86-a1dc-2e1952f39258" name="In_Ph2" connectedTo="bf9784f2-c610-4b74-9b22-8cb0ed174e29"/>
          <port xsi:type="esdl:InPort" id="93951a50-4cf3-41a4-a6b0-f18793c2e730" name="In_Ph3" connectedTo="7436d2c9-ba1a-4412-b5a4-374bf2feb3c0"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome767" id="c9b0861d-c3ae-4af8-858c-d515f4f7d389">
          <port xsi:type="esdl:InPort" id="1ec0e5f5-fdc5-4683-9d9e-1823287ce0a6" name="In" connectedTo="28bf9e4c-2cfb-4d51-af9a-fdcaa2c895a0"/>
          <port xsi:type="esdl:OutPort" id="a22a7873-fdf7-42ad-bf4b-a9798faa8029" name="OutPh1" connectedTo="4533f862-226b-495c-81e8-45f17462208c"/>
          <port xsi:type="esdl:OutPort" id="fe1b9f82-ded1-4486-989e-d783bbbe7b65" name="OutPh2" connectedTo="86ea262a-7828-4695-a413-53814a22b00d"/>
          <port xsi:type="esdl:OutPort" id="6759f00e-dc0f-4e11-8ef8-03025c9148db" name="OutPh3" connectedTo="2a3805c2-4261-4190-bfb7-3bc92d850739"/>
          <geometry xsi:type="esdl:Point" lat="157828.618" lon="433527.659"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_7" id="65b78ad3-8476-44f7-8dee-01543bef70d5">
        <port xsi:type="esdl:InPort" id="adaa113d-279d-4fb9-8ab5-e30df2ab6833" name="In" connectedTo="98569c2c-72bf-4192-827c-4b9e95998f2b"/>
        <port xsi:type="esdl:OutPort" id="30410075-5c5a-49fc-b8af-eb2ff1eb2950" name="Out" connectedTo="c8bc6ea7-6ff6-436f-a6ef-7f4fd5ab9c75 1a54c17e-7107-4d1b-88de-2c587e9f6cad"/>
        <geometry xsi:type="esdl:Point" lat="157826.83165702465" CRS="WGS84" lon="433526.3166279335"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.175909836556895" name="lv_cable_trafo8_lvnetwork1_7_main_grid" id="f0dd64ee-aeb3-4fb8-b25f-103afd2b8440" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f0f3bb37-a6b4-4d85-96f2-d6fe68c3628b" name="In" connectedTo="510361dd-0b6e-41f6-8f6c-83fc35c020c8"/>
        <port xsi:type="esdl:OutPort" id="98569c2c-72bf-4192-827c-4b9e95998f2b" name="Out" connectedTo="adaa113d-279d-4fb9-8ab5-e30df2ab6833"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157828.82278800284" CRS="WGS84" lon="433527.1941135713"/>
          <point xsi:type="esdl:Point" lat="157826.83165702465" CRS="WGS84" lon="433526.3166279335"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="11.47752339091539" name="lv_cable_trafo8_lvnetwork1_to_home_0_arch6" id="08121195-d7d1-4f76-b519-52ffbc9a596a" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="c8bc6ea7-6ff6-436f-a6ef-7f4fd5ab9c75" name="In" connectedTo="30410075-5c5a-49fc-b8af-eb2ff1eb2950"/>
        <port xsi:type="esdl:OutPort" id="922eef85-a136-4f26-9175-2bb91c6ff593" name="Out" connectedTo="4759abe5-d1b7-49d6-9b02-656548d1af5f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157822.202" CRS="WGS84" lon="433536.819"/>
          <point xsi:type="esdl:Point" lat="157826.83165702465" CRS="WGS84" lon="433526.3166279335"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome765" id="6be1819e-e195-48aa-ab60-8896ec2de0cc">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="39d4feb4-0b67-4314-87d4-69c4843d73b1" name="In" connectedTo="9dc8b387-a508-4421-97ef-d32eb0c31c19"/>
          <port xsi:type="esdl:OutPort" id="bef170ee-1b1a-4d1e-bec0-27cf570c0c0e" name="Out" connectedTo="665a459c-bf5c-47d6-90b5-ee7055e2768f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="6572107f-0a6d-4d55-aebc-8b46531d2dd4" name="In" connectedTo="ffef64f5-4404-4d63-a633-00b81434e263"/>
          <port xsi:type="esdl:OutPort" id="0308989e-8096-46b9-8585-d724e5b1ffbe" name="Out" connectedTo="73f077fe-8956-47fc-bda5-165285b0e0e0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="d644ef61-390f-49e5-acd8-d43c3c13b7e5" name="In" connectedTo="b0a62e5f-4b3a-49f4-b472-2e8534f6ac9e"/>
          <port xsi:type="esdl:OutPort" id="9b941ed9-b6a9-4ab0-bc2a-3f12b7d8be8c" name="Out" connectedTo="fe1d4616-8852-40c6-b76f-a988a1684374"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="45095b8c-33c6-45f6-9265-e4b90efe9ac3" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="665a459c-bf5c-47d6-90b5-ee7055e2768f" name="In_Ph1" connectedTo="bef170ee-1b1a-4d1e-bec0-27cf570c0c0e"/>
          <port xsi:type="esdl:InPort" id="73f077fe-8956-47fc-bda5-165285b0e0e0" name="In_Ph2" connectedTo="0308989e-8096-46b9-8585-d724e5b1ffbe"/>
          <port xsi:type="esdl:InPort" id="fe1d4616-8852-40c6-b76f-a988a1684374" name="In_Ph3" connectedTo="9b941ed9-b6a9-4ab0-bc2a-3f12b7d8be8c"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome765" id="da7354fc-b42f-4414-ae34-1bb6c6990ba7">
          <port xsi:type="esdl:InPort" id="4759abe5-d1b7-49d6-9b02-656548d1af5f" name="In" connectedTo="922eef85-a136-4f26-9175-2bb91c6ff593"/>
          <port xsi:type="esdl:OutPort" id="9dc8b387-a508-4421-97ef-d32eb0c31c19" name="OutPh1" connectedTo="39d4feb4-0b67-4314-87d4-69c4843d73b1"/>
          <port xsi:type="esdl:OutPort" id="ffef64f5-4404-4d63-a633-00b81434e263" name="OutPh2" connectedTo="6572107f-0a6d-4d55-aebc-8b46531d2dd4"/>
          <port xsi:type="esdl:OutPort" id="b0a62e5f-4b3a-49f4-b472-2e8534f6ac9e" name="OutPh3" connectedTo="d644ef61-390f-49e5-acd8-d43c3c13b7e5"/>
          <geometry xsi:type="esdl:Point" lat="157822.202" lon="433536.819"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_8" id="0a8bc2b9-15a2-4926-af43-aa17c4ee4a8e">
        <port xsi:type="esdl:InPort" id="6bd5fd63-9ca5-4d35-922e-49bd823a6c45" name="In" connectedTo="9b6e1b78-68f9-4dc8-a1d9-889007ea409a"/>
        <port xsi:type="esdl:OutPort" id="c131508a-6fe4-4628-95d5-8eee9fffe70b" name="Out" connectedTo="806c714a-832a-4686-b059-f0761f423e92 0c7123a6-6821-4b08-8dab-9e849e6dfa81"/>
        <geometry xsi:type="esdl:Point" lat="157823.74290901818" CRS="WGS84" lon="433524.9558322186"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="3.375222840991356" name="lv_cable_trafo8_lvnetwork1_8_main_grid" id="b7c00fa6-e7de-4a94-8c6e-9b4124b55cf0" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="1a54c17e-7107-4d1b-88de-2c587e9f6cad" name="In" connectedTo="30410075-5c5a-49fc-b8af-eb2ff1eb2950"/>
        <port xsi:type="esdl:OutPort" id="9b6e1b78-68f9-4dc8-a1d9-889007ea409a" name="Out" connectedTo="6bd5fd63-9ca5-4d35-922e-49bd823a6c45"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157826.83165702465" CRS="WGS84" lon="433526.3166279335"/>
          <point xsi:type="esdl:Point" lat="157824.229" CRS="WGS84" lon="433525.17"/>
          <point xsi:type="esdl:Point" lat="157823.74290901818" CRS="WGS84" lon="433524.9558322186"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.972108900438694" name="lv_cable_trafo8_lvnetwork1_to_home_1_arch6" id="6f9fd735-f133-405f-82db-3489f761d63f" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="806c714a-832a-4686-b059-f0761f423e92" name="In" connectedTo="c131508a-6fe4-4628-95d5-8eee9fffe70b"/>
        <port xsi:type="esdl:OutPort" id="4c625c83-8cca-4468-8136-305d6cb49644" name="Out" connectedTo="2c215981-efd0-435d-90a3-7fb6fc5d5fe3"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157821.335" CRS="WGS84" lon="433530.421"/>
          <point xsi:type="esdl:Point" lat="157823.74290901818" CRS="WGS84" lon="433524.9558322186"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome766" id="c83334ed-8fa4-40f0-806b-12ddec25581e">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="9a2ae974-84e9-455e-8589-7610b1ac3600" name="In" connectedTo="4604df01-fce7-4b4f-8bc9-accef0aa41a1"/>
          <port xsi:type="esdl:OutPort" id="54015983-4b13-4c5d-ba7c-4c66b5815761" name="Out" connectedTo="7838b5c6-f0ef-49a8-994a-2ca051544a5e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="5d51b992-68c2-439b-bfee-6d0bca2fe4a4" name="In" connectedTo="8a498ce3-9e4a-42ec-89f6-04c3908b8d47"/>
          <port xsi:type="esdl:OutPort" id="3982e760-9b24-4bc4-8689-6270b078916f" name="Out" connectedTo="00c7d78f-1cb7-4985-9c23-d53951b6dab9"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="043008f3-50d4-432d-9c00-4a2e1abc2e48" name="In" connectedTo="936822b9-0bf5-46f1-be01-876874537555"/>
          <port xsi:type="esdl:OutPort" id="5945216c-aea7-4f45-8b51-a7807956ba1e" name="Out" connectedTo="1b1ff0b7-391d-430f-8944-81e5c8a864fe"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="33f00e9a-5865-4c07-8566-d599d5e883f6" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7838b5c6-f0ef-49a8-994a-2ca051544a5e" name="In_Ph1" connectedTo="54015983-4b13-4c5d-ba7c-4c66b5815761"/>
          <port xsi:type="esdl:InPort" id="00c7d78f-1cb7-4985-9c23-d53951b6dab9" name="In_Ph2" connectedTo="3982e760-9b24-4bc4-8689-6270b078916f"/>
          <port xsi:type="esdl:InPort" id="1b1ff0b7-391d-430f-8944-81e5c8a864fe" name="In_Ph3" connectedTo="5945216c-aea7-4f45-8b51-a7807956ba1e"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome766" id="c51fb1cc-d4be-4eff-8a89-325ab2fb3076">
          <port xsi:type="esdl:InPort" id="2c215981-efd0-435d-90a3-7fb6fc5d5fe3" name="In" connectedTo="4c625c83-8cca-4468-8136-305d6cb49644"/>
          <port xsi:type="esdl:OutPort" id="4604df01-fce7-4b4f-8bc9-accef0aa41a1" name="OutPh1" connectedTo="9a2ae974-84e9-455e-8589-7610b1ac3600"/>
          <port xsi:type="esdl:OutPort" id="8a498ce3-9e4a-42ec-89f6-04c3908b8d47" name="OutPh2" connectedTo="5d51b992-68c2-439b-bfee-6d0bca2fe4a4"/>
          <port xsi:type="esdl:OutPort" id="936822b9-0bf5-46f1-be01-876874537555" name="OutPh3" connectedTo="043008f3-50d4-432d-9c00-4a2e1abc2e48"/>
          <geometry xsi:type="esdl:Point" lat="157821.335" lon="433530.421"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_9" id="7e1f6ae8-8610-45b2-8f71-a90f1f967353">
        <port xsi:type="esdl:InPort" id="8916dfd1-a53c-42dc-aed6-80c8082db90c" name="In" connectedTo="7ef07416-c0fa-4350-a46c-a3625b64f0d9"/>
        <port xsi:type="esdl:OutPort" id="0f847873-ee9d-4e37-9e4f-3aad29691102" name="Out" connectedTo="6abc4b3b-8084-4c79-a254-e35cbc8575d9 3b1e6d81-358b-42ce-809b-ea30e867527e"/>
        <geometry xsi:type="esdl:Point" lat="157815.302" CRS="WGS84" lon="433521.235"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="9.224616896911577" name="lv_cable_trafo8_lvnetwork1_9_main_grid" id="1ecd65f2-8f13-40c8-bc44-9ffa094eff4e" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="0c7123a6-6821-4b08-8dab-9e849e6dfa81" name="In" connectedTo="c131508a-6fe4-4628-95d5-8eee9fffe70b"/>
        <port xsi:type="esdl:OutPort" id="7ef07416-c0fa-4350-a46c-a3625b64f0d9" name="Out" connectedTo="8916dfd1-a53c-42dc-aed6-80c8082db90c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157823.74290901818" CRS="WGS84" lon="433524.9558322186"/>
          <point xsi:type="esdl:Point" lat="157820.962" CRS="WGS84" lon="433523.73"/>
          <point xsi:type="esdl:Point" lat="157820.453" CRS="WGS84" lon="433523.506"/>
          <point xsi:type="esdl:Point" lat="157820.191" CRS="WGS84" lon="433523.391"/>
          <point xsi:type="esdl:Point" lat="157819.116" CRS="WGS84" lon="433522.917"/>
          <point xsi:type="esdl:Point" lat="157818.204" CRS="WGS84" lon="433522.515"/>
          <point xsi:type="esdl:Point" lat="157817.364" CRS="WGS84" lon="433522.144"/>
          <point xsi:type="esdl:Point" lat="157816.934" CRS="WGS84" lon="433521.955"/>
          <point xsi:type="esdl:Point" lat="157816.313" CRS="WGS84" lon="433521.681"/>
          <point xsi:type="esdl:Point" lat="157815.302" CRS="WGS84" lon="433521.235"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="9.730557794012409" name="lv_cable_trafo8_lvnetwork1_to_home_3_arch6" id="ed84380d-e2cc-4b3b-ac78-c269be6e9392" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="6abc4b3b-8084-4c79-a254-e35cbc8575d9" name="In" connectedTo="0f847873-ee9d-4e37-9e4f-3aad29691102"/>
        <port xsi:type="esdl:OutPort" id="90c5ada6-5e52-4b93-9a79-f69938c81352" name="Out" connectedTo="4c556996-3c6a-49d5-85c5-adc984759467"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157819.21228793229" CRS="WGS84" lon="433512.32470240287"/>
          <point xsi:type="esdl:Point" lat="157815.302" CRS="WGS84" lon="433521.235"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="2xhome768" id="5427e64a-ecfa-423a-a9a0-7e4291110d02">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="a1c92117-e51a-40f2-a8ea-e758c614a123" name="In" connectedTo="ab909607-bd63-43e5-bf51-21535a00ea5b"/>
          <port xsi:type="esdl:OutPort" id="4415d93f-e2ff-4603-ade9-c9df15376fa8" name="Out" connectedTo="c98781b0-18d9-4a62-bbaf-d3de34f9fb49"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="dce7adaf-dd71-45b8-a5e1-a468f745590e" name="In" connectedTo="23661275-245d-4c9d-b8c5-36dd809b8e8a"/>
          <port xsi:type="esdl:OutPort" id="cdec6d50-c73e-4018-9297-9badbcede368" name="Out" connectedTo="de784b7a-908f-4876-87d8-48a180540b98"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="618cd7ce-3949-4a40-9f9c-9b6ff453baae" name="In" connectedTo="ce6528c3-93a1-46f5-adf5-1a1193761056"/>
          <port xsi:type="esdl:OutPort" id="fc78835a-337c-44b4-bef8-f158384db41e" name="Out" connectedTo="b0b3372a-41e0-47cd-a7be-de823016827a"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="ecdcfc01-98b0-4959-a705-de9a2358d495" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="c98781b0-18d9-4a62-bbaf-d3de34f9fb49" name="In_Ph1" connectedTo="4415d93f-e2ff-4603-ade9-c9df15376fa8"/>
          <port xsi:type="esdl:InPort" id="de784b7a-908f-4876-87d8-48a180540b98" name="In_Ph2" connectedTo="cdec6d50-c73e-4018-9297-9badbcede368"/>
          <port xsi:type="esdl:InPort" id="b0b3372a-41e0-47cd-a7be-de823016827a" name="In_Ph3" connectedTo="fc78835a-337c-44b4-bef8-f158384db41e"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="2xhome768" id="51754c04-0b90-4df7-a9e8-4eddfccd400a">
          <port xsi:type="esdl:InPort" id="4c556996-3c6a-49d5-85c5-adc984759467" name="In" connectedTo="90c5ada6-5e52-4b93-9a79-f69938c81352"/>
          <port xsi:type="esdl:OutPort" id="ab909607-bd63-43e5-bf51-21535a00ea5b" name="OutPh1" connectedTo="a1c92117-e51a-40f2-a8ea-e758c614a123"/>
          <port xsi:type="esdl:OutPort" id="23661275-245d-4c9d-b8c5-36dd809b8e8a" name="OutPh2" connectedTo="dce7adaf-dd71-45b8-a5e1-a468f745590e"/>
          <port xsi:type="esdl:OutPort" id="ce6528c3-93a1-46f5-adf5-1a1193761056" name="OutPh3" connectedTo="618cd7ce-3949-4a40-9f9c-9b6ff453baae"/>
          <geometry xsi:type="esdl:Point" lat="157819.21228793229" lon="433512.32470240287"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo8_lvnetwork1_10" id="0d89bd42-be97-4122-9de3-29b34e828d7e">
        <port xsi:type="esdl:InPort" id="caf484fd-e8e5-471e-9a17-d5f339ea3523" name="In" connectedTo="8968c3fd-b645-45f5-82d5-8c8082b369e4"/>
        <port xsi:type="esdl:OutPort" id="1b4a2952-8cfa-42ae-985c-699cad375fde" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="157803.028" CRS="WGS84" lon="433516.112"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.300233268621385" name="lv_cable_trafo8_lvnetwork1_10_main_grid" id="40f4cc98-cf73-4ebe-a312-57a6e5ad7b78" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="3b1e6d81-358b-42ce-809b-ea30e867527e" name="In" connectedTo="0f847873-ee9d-4e37-9e4f-3aad29691102"/>
        <port xsi:type="esdl:OutPort" id="8968c3fd-b645-45f5-82d5-8c8082b369e4" name="Out" connectedTo="caf484fd-e8e5-471e-9a17-d5f339ea3523"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157815.302" CRS="WGS84" lon="433521.235"/>
          <point xsi:type="esdl:Point" lat="157803.028" CRS="WGS84" lon="433516.112"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo8_lvnetwork1" id="1ff97e24-d0bd-4a46-9758-8972d2301de0" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="dbb768c6-5490-4d5a-ae06-f2f5ee697f2f" name="Out" connectedTo="a11fdead-613d-44e4-b3f2-de536917467e"/>
        <geometry xsi:type="esdl:Point" lat="157926.64" CRS="WGS84" lon="433639.333"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo8_lvnetwork1" id="f8ac6668-99cd-40d9-8d88-9f064dfc98a4">
        <port xsi:type="esdl:InPort" id="a11fdead-613d-44e4-b3f2-de536917467e" name="In" connectedTo="dbb768c6-5490-4d5a-ae06-f2f5ee697f2f"/>
        <port xsi:type="esdl:OutPort" id="8fb85866-b6e9-4d5d-98df-963110a11bd0" name="Out" connectedTo="3943a739-b0ee-451c-8926-c8e21ccf3ce1"/>
        <geometry xsi:type="esdl:Point" lat="157926.64" CRS="WGS84" lon="433639.333"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer51" id="4017d810-47c2-4696-bea3-68fad9c38c8c" commissioningDate="1981-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="3943a739-b0ee-451c-8926-c8e21ccf3ce1" name="In" connectedTo="8fb85866-b6e9-4d5d-98df-963110a11bd0"/>
        <port xsi:type="esdl:OutPort" id="c15f3a5e-84a7-4acf-a5c5-74e059543f05" name="Out" connectedTo="f2836cd4-f5fd-47c1-b6cd-7be8437938dd"/>
        <geometry xsi:type="esdl:Point" lat="157926.64" CRS="WGS84" lon="433639.333"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint53" id="fb41acd9-f529-4007-a6b6-ad954d85d485">
        <port xsi:type="esdl:InPort" id="f2836cd4-f5fd-47c1-b6cd-7be8437938dd" name="In" connectedTo="c15f3a5e-84a7-4acf-a5c5-74e059543f05"/>
        <port xsi:type="esdl:OutPort" id="216d9023-95bd-4f44-a65c-6ddc66117d90" name="Out" connectedTo="3922761c-788a-45ec-ab0e-8d875d19007d"/>
        <geometry xsi:type="esdl:Point" lat="157926.64" CRS="WGS84" lon="433639.333"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
