<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="c4ca8e45-ed75-4545-ab71-7db055be56e2" description="Autogenerated based on gis data trafo4_lvnetwork2" name="trafo4_lvnetwork2">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="5b894fe2-a1a4-4eb0-bd92-fdd242216088"/>
  <instance xsi:type="esdl:Instance" id="5e81a156-cfb3-4491-96fa-16f0ef085222" name="Instance name">
    <area xsi:type="esdl:Area" id="c5133687-7a0f-48d0-b683-53bec6ac6fae" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_2" id="26d89a57-776d-4be6-9a12-fb1073c656cc">
        <port xsi:type="esdl:InPort" id="09b49d67-6d54-44c1-a854-246a2048a85a" name="In" connectedTo="ca6ddd1c-0469-4fd4-9f53-ccf4b2ab56fe"/>
        <port xsi:type="esdl:OutPort" id="956e8fdf-3f83-464f-84f9-e8eb0e8a9ef8" name="Out" connectedTo="24bc8c51-5355-436f-9c76-c56b890b20b9 2b799333-051c-424d-95b4-2fee47ad999b"/>
        <geometry xsi:type="esdl:Point" lat="158209.122" CRS="WGS84" lon="433218.715"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="32.593576849773164" name="lv_cable_trafo4_lvnetwork2_2_main_grid" id="3ef54e26-0119-4b62-bdb9-b36ed80f8a94" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="a57b3c7f-0216-4422-8ed1-0b949d064a24" name="In" connectedTo="dd03e995-3b79-4a24-8e08-95f175bed17d"/>
        <port xsi:type="esdl:OutPort" id="ca6ddd1c-0469-4fd4-9f53-ccf4b2ab56fe" name="Out" connectedTo="09b49d67-6d54-44c1-a854-246a2048a85a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158194.868" CRS="WGS84" lon="433199.184"/>
          <point xsi:type="esdl:Point" lat="158194.923" CRS="WGS84" lon="433200.635"/>
          <point xsi:type="esdl:Point" lat="158195.772" CRS="WGS84" lon="433200.601"/>
          <point xsi:type="esdl:Point" lat="158207.369" CRS="WGS84" lon="433200.133"/>
          <point xsi:type="esdl:Point" lat="158208.041" CRS="WGS84" lon="433211.809"/>
          <point xsi:type="esdl:Point" lat="158208.977" CRS="WGS84" lon="433217.786"/>
          <point xsi:type="esdl:Point" lat="158209.122" CRS="WGS84" lon="433218.715"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.0489542179922169" name="lv_cable_trafo4_lvnetwork2_to_home_0_arch5" id="79a9cbc9-c6cd-4404-878b-2cea6be6b930" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="24bc8c51-5355-436f-9c76-c56b890b20b9" name="In" connectedTo="956e8fdf-3f83-464f-84f9-e8eb0e8a9ef8"/>
        <port xsi:type="esdl:OutPort" id="9a5125f2-9590-4724-961e-cd9063ead4be" name="Out" connectedTo="bbfd31ff-5ff6-4443-98f4-57915d779eda"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158210.16843639288" CRS="WGS84" lon="433218.642365111"/>
          <point xsi:type="esdl:Point" lat="158209.122" CRS="WGS84" lon="433218.715"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="6xhome563" id="81ec518e-c811-4bae-9e5a-ac1fc6106dc4">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="bd70b11a-1b5b-4cc4-9eef-23366ede45d3" name="In" connectedTo="f0550245-94a9-4903-a8e3-ae1ee212a0d8"/>
          <port xsi:type="esdl:OutPort" id="4340b968-be2d-4561-ac09-9f23608d7bc5" name="Out" connectedTo="9d1e1d19-bde0-4a48-8fd9-df0d086a6625"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="09a1636a-bd23-4de1-9c43-54a656e96bcc" name="In" connectedTo="5ca89737-80ea-4219-9956-9a2cb7ea6124"/>
          <port xsi:type="esdl:OutPort" id="c1791837-f001-4615-8d00-6aa6af487858" name="Out" connectedTo="30e8eadb-dbb9-4e2f-ae8d-760c3319b510"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="2c52b36e-4312-49db-aac4-c6c63325414d" name="In" connectedTo="c12b8247-ec9d-4e9c-93b8-35cca6f4f03f"/>
          <port xsi:type="esdl:OutPort" id="ba18e2a9-7626-49b9-bd42-fff6bc02bfc9" name="Out" connectedTo="eef6bbad-a653-4ba9-887d-a84c4ba17b40"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="7693cac3-6dec-47e8-aede-f2bbeae6bbf7" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="9d1e1d19-bde0-4a48-8fd9-df0d086a6625" name="In_Ph1" connectedTo="4340b968-be2d-4561-ac09-9f23608d7bc5"/>
          <port xsi:type="esdl:InPort" id="30e8eadb-dbb9-4e2f-ae8d-760c3319b510" name="In_Ph2" connectedTo="c1791837-f001-4615-8d00-6aa6af487858"/>
          <port xsi:type="esdl:InPort" id="eef6bbad-a653-4ba9-887d-a84c4ba17b40" name="In_Ph3" connectedTo="ba18e2a9-7626-49b9-bd42-fff6bc02bfc9"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="6xhome563" id="c720f9b5-f4e1-4cd7-9ff5-108b5a8d6086">
          <port xsi:type="esdl:InPort" id="bbfd31ff-5ff6-4443-98f4-57915d779eda" name="In" connectedTo="9a5125f2-9590-4724-961e-cd9063ead4be"/>
          <port xsi:type="esdl:OutPort" id="f0550245-94a9-4903-a8e3-ae1ee212a0d8" name="OutPh1" connectedTo="bd70b11a-1b5b-4cc4-9eef-23366ede45d3"/>
          <port xsi:type="esdl:OutPort" id="5ca89737-80ea-4219-9956-9a2cb7ea6124" name="OutPh2" connectedTo="09a1636a-bd23-4de1-9c43-54a656e96bcc"/>
          <port xsi:type="esdl:OutPort" id="c12b8247-ec9d-4e9c-93b8-35cca6f4f03f" name="OutPh3" connectedTo="2c52b36e-4312-49db-aac4-c6c63325414d"/>
          <geometry xsi:type="esdl:Point" lat="158210.16843639288" lon="433218.642365111"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_3" id="17a60c54-4e0c-4b48-9229-90fc3f381934">
        <port xsi:type="esdl:InPort" id="995dedcd-2805-428f-85f9-606cdc57fa9c" name="In" connectedTo="25c5a6dd-a2b5-4c81-8702-dfe405559a54"/>
        <port xsi:type="esdl:OutPort" id="bd9ec239-5551-498f-a97e-a2f2e5340c5d" name="Out" connectedTo="b2ec8fc3-bc8c-4344-b016-91b1a6ba2925"/>
        <geometry xsi:type="esdl:Point" lat="158208.551" CRS="WGS84" lon="433222.662"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.0025834604445745" name="lv_cable_trafo4_lvnetwork2_3_main_grid" id="592c7d95-31c2-431a-8053-e9a95ca2d6bd" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="2b799333-051c-424d-95b4-2fee47ad999b" name="In" connectedTo="956e8fdf-3f83-464f-84f9-e8eb0e8a9ef8"/>
        <port xsi:type="esdl:OutPort" id="25c5a6dd-a2b5-4c81-8702-dfe405559a54" name="Out" connectedTo="995dedcd-2805-428f-85f9-606cdc57fa9c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158209.122" CRS="WGS84" lon="433218.715"/>
          <point xsi:type="esdl:Point" lat="158208.94972187" CRS="WGS84" lon="433219.336323187"/>
          <point xsi:type="esdl:Point" lat="158208.808" CRS="WGS84" lon="433219.968"/>
          <point xsi:type="esdl:Point" lat="158208.672367713" CRS="WGS84" lon="433220.7819656"/>
          <point xsi:type="esdl:Point" lat="158208.587" CRS="WGS84" lon="433221.607"/>
          <point xsi:type="esdl:Point" lat="158208.558848387" CRS="WGS84" lon="433222.133331734"/>
          <point xsi:type="esdl:Point" lat="158208.551" CRS="WGS84" lon="433222.662"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_4" id="45607cac-1ed8-486f-a64d-485397ed08f1">
        <port xsi:type="esdl:InPort" id="c178508f-6ed9-44a3-8984-3e128301751f" name="In" connectedTo="bd4498dd-372b-459e-8a48-fe00f31b4c7d"/>
        <port xsi:type="esdl:OutPort" id="7549ccb9-1f0d-4740-9b38-7a7956e0cddd" name="Out" connectedTo="bde17cb0-3b16-400a-8483-894014d3f4d6"/>
        <geometry xsi:type="esdl:Point" lat="158216.345" CRS="WGS84" lon="433231.245"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="16.01567678306605" name="lv_cable_trafo4_lvnetwork2_4_main_grid" id="6213539e-3a71-4665-a119-eb7902d1a157" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="b2ec8fc3-bc8c-4344-b016-91b1a6ba2925" name="In" connectedTo="bd9ec239-5551-498f-a97e-a2f2e5340c5d"/>
        <port xsi:type="esdl:OutPort" id="bd4498dd-372b-459e-8a48-fe00f31b4c7d" name="Out" connectedTo="c178508f-6ed9-44a3-8984-3e128301751f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158208.551" CRS="WGS84" lon="433222.662"/>
          <point xsi:type="esdl:Point" lat="158208.551695496" CRS="WGS84" lon="433222.753979404"/>
          <point xsi:type="esdl:Point" lat="158208.553" CRS="WGS84" lon="433222.846"/>
          <point xsi:type="esdl:Point" lat="158208.585" CRS="WGS84" lon="433223.259"/>
          <point xsi:type="esdl:Point" lat="158209.218" CRS="WGS84" lon="433231.517"/>
          <point xsi:type="esdl:Point" lat="158215.592" CRS="WGS84" lon="433231.21"/>
          <point xsi:type="esdl:Point" lat="158216.345" CRS="WGS84" lon="433231.245"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_5" id="18b3027b-8637-44e8-bc87-91b8bbaa0c28">
        <port xsi:type="esdl:InPort" id="fc3238f0-cf9e-4f79-ae3f-d1205f1ac99e" name="In" connectedTo="3cbe8351-24ae-4ba3-83b5-8f5e2f2893cf"/>
        <port xsi:type="esdl:OutPort" id="ba48439b-798b-4cb1-a1a1-05d1bb8b0255" name="Out" connectedTo="fa0d69f0-f6d4-4c72-8dff-08b369d5a0de"/>
        <geometry xsi:type="esdl:Point" lat="158216.944" CRS="WGS84" lon="433231.204"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.6004015322951309" name="lv_cable_trafo4_lvnetwork2_5_main_grid" id="105f92ab-972e-4241-b3da-7eb9f94d95af" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="bde17cb0-3b16-400a-8483-894014d3f4d6" name="In" connectedTo="7549ccb9-1f0d-4740-9b38-7a7956e0cddd"/>
        <port xsi:type="esdl:OutPort" id="3cbe8351-24ae-4ba3-83b5-8f5e2f2893cf" name="Out" connectedTo="fc3238f0-cf9e-4f79-ae3f-d1205f1ac99e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158216.345" CRS="WGS84" lon="433231.245"/>
          <point xsi:type="esdl:Point" lat="158216.944" CRS="WGS84" lon="433231.204"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_6" id="79666c01-266d-4d95-88a8-742b80a87554">
        <port xsi:type="esdl:InPort" id="c3bea528-471b-467c-9c0d-fa1923693297" name="In" connectedTo="cef4e72b-2fef-49a4-9fbf-8f3d53c31b72"/>
        <port xsi:type="esdl:OutPort" id="3e551af9-9645-4d6d-94a7-2056a336be17" name="Out" connectedTo="1625b130-3c95-4948-a707-05d1bfeb7e9d c2afef36-0ecc-4f42-b384-d42ccd939caa"/>
        <geometry xsi:type="esdl:Point" lat="158235.4216928686" CRS="WGS84" lon="433229.934299449"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="18.537694452862464" name="lv_cable_trafo4_lvnetwork2_6_main_grid" id="1295bcd4-9eed-49ae-a431-d435a158fab3" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="fa0d69f0-f6d4-4c72-8dff-08b369d5a0de" name="In" connectedTo="ba48439b-798b-4cb1-a1a1-05d1bb8b0255"/>
        <port xsi:type="esdl:OutPort" id="cef4e72b-2fef-49a4-9fbf-8f3d53c31b72" name="Out" connectedTo="c3bea528-471b-467c-9c0d-fa1923693297"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158216.944" CRS="WGS84" lon="433231.204"/>
          <point xsi:type="esdl:Point" lat="158220.147" CRS="WGS84" lon="433231.193"/>
          <point xsi:type="esdl:Point" lat="158222.232" CRS="WGS84" lon="433231.185"/>
          <point xsi:type="esdl:Point" lat="158227.072656872" CRS="WGS84" lon="433230.787817242"/>
          <point xsi:type="esdl:Point" lat="158231.907" CRS="WGS84" lon="433230.32"/>
          <point xsi:type="esdl:Point" lat="158232.141508271" CRS="WGS84" lon="433230.295578892"/>
          <point xsi:type="esdl:Point" lat="158232.376" CRS="WGS84" lon="433230.271"/>
          <point xsi:type="esdl:Point" lat="158235.084262875" CRS="WGS84" lon="433229.974093279"/>
          <point xsi:type="esdl:Point" lat="158235.4216928686" CRS="WGS84" lon="433229.934299449"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.0015938044850137" name="lv_cable_trafo4_lvnetwork2_to_home_16_arch5" id="bdd2f5fc-9d0a-4556-955c-e4b1c523301d" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="1625b130-3c95-4948-a707-05d1bfeb7e9d" name="In" connectedTo="3e551af9-9645-4d6d-94a7-2056a336be17"/>
        <port xsi:type="esdl:OutPort" id="e3a722f6-425c-4369-9bc8-8bfd89fd6c5d" name="Out" connectedTo="3b9c0d14-1ed1-4b99-bf2b-cce00d561820"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158235.539" CRS="WGS84" lon="433230.929"/>
          <point xsi:type="esdl:Point" lat="158235.4216928686" CRS="WGS84" lon="433229.934299449"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="28xhome579" id="1efb2ea5-23f5-4fc2-98db-f8a9d86f5962">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="dba5ba74-7e4e-4fae-b872-0d396d36a39a" name="In" connectedTo="4e6a823a-a69b-4de3-8425-bcff24d40fa3"/>
          <port xsi:type="esdl:OutPort" id="adb2ea44-2446-45f7-abc5-661ba847aae2" name="Out" connectedTo="2462b8a1-b073-45e5-bf46-38b2448fba75"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="cbcc5946-6a9f-4c62-88c5-bbd05aa412e8" name="In" connectedTo="463c3bdd-bb2d-4f96-8484-022a102d5827"/>
          <port xsi:type="esdl:OutPort" id="a3b25740-a7ec-4d2e-9782-aa88f26824a9" name="Out" connectedTo="98488ae4-e939-4012-a964-a9512aa35e7c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="b228dcdd-8912-4134-8afb-97f3603e0e2a" name="In" connectedTo="56f7e6b0-2ef3-4cf0-8047-b642ebfa8fb0"/>
          <port xsi:type="esdl:OutPort" id="4d9b4824-bafb-4f44-9355-3bbe86bceeac" name="Out" connectedTo="95a6925c-7809-41ed-b16e-553389cd4925"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="8b650bae-d1e7-4f05-9a4f-09b91c93312e" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="2462b8a1-b073-45e5-bf46-38b2448fba75" name="In_Ph1" connectedTo="adb2ea44-2446-45f7-abc5-661ba847aae2"/>
          <port xsi:type="esdl:InPort" id="98488ae4-e939-4012-a964-a9512aa35e7c" name="In_Ph2" connectedTo="a3b25740-a7ec-4d2e-9782-aa88f26824a9"/>
          <port xsi:type="esdl:InPort" id="95a6925c-7809-41ed-b16e-553389cd4925" name="In_Ph3" connectedTo="4d9b4824-bafb-4f44-9355-3bbe86bceeac"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="28xhome579" id="3f63131d-bbcb-4632-8f71-ca1d8cfa5e05">
          <port xsi:type="esdl:InPort" id="3b9c0d14-1ed1-4b99-bf2b-cce00d561820" name="In" connectedTo="e3a722f6-425c-4369-9bc8-8bfd89fd6c5d"/>
          <port xsi:type="esdl:OutPort" id="4e6a823a-a69b-4de3-8425-bcff24d40fa3" name="OutPh1" connectedTo="dba5ba74-7e4e-4fae-b872-0d396d36a39a"/>
          <port xsi:type="esdl:OutPort" id="463c3bdd-bb2d-4f96-8484-022a102d5827" name="OutPh2" connectedTo="cbcc5946-6a9f-4c62-88c5-bbd05aa412e8"/>
          <port xsi:type="esdl:OutPort" id="56f7e6b0-2ef3-4cf0-8047-b642ebfa8fb0" name="OutPh3" connectedTo="b228dcdd-8912-4134-8afb-97f3603e0e2a"/>
          <geometry xsi:type="esdl:Point" lat="158235.539" lon="433230.929"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_7" id="6d70f4a2-249b-4668-9bfb-a18d71d6b0cb">
        <port xsi:type="esdl:InPort" id="f809ea86-c306-4f55-9d10-395f7eb55e02" name="In" connectedTo="b9604877-1fce-4793-9182-5a385804dab6"/>
        <port xsi:type="esdl:OutPort" id="552405d4-2b7f-412c-96f5-61e97343115b" name="Out" connectedTo="2809fa17-b9c9-4dd0-94fe-3b20636d74fa be71938d-ff82-4f1e-861a-0dab77f2bf41"/>
        <geometry xsi:type="esdl:Point" lat="158245.63888339186" CRS="WGS84" lon="433228.5146777577"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.317777102623833" name="lv_cable_trafo4_lvnetwork2_7_main_grid" id="8655bb21-165b-4548-ae77-732ada7e713a" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="c2afef36-0ecc-4f42-b384-d42ccd939caa" name="In" connectedTo="3e551af9-9645-4d6d-94a7-2056a336be17"/>
        <port xsi:type="esdl:OutPort" id="b9604877-1fce-4793-9182-5a385804dab6" name="Out" connectedTo="f809ea86-c306-4f55-9d10-395f7eb55e02"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158235.4216928686" CRS="WGS84" lon="433229.934299449"/>
          <point xsi:type="esdl:Point" lat="158238.76818224" CRS="WGS84" lon="433229.533956145"/>
          <point xsi:type="esdl:Point" lat="158239.746" CRS="WGS84" lon="433229.41"/>
          <point xsi:type="esdl:Point" lat="158239.85" CRS="WGS84" lon="433229.397"/>
          <point xsi:type="esdl:Point" lat="158241.462024652" CRS="WGS84" lon="433229.185431373"/>
          <point xsi:type="esdl:Point" lat="158243.073" CRS="WGS84" lon="433228.966"/>
          <point xsi:type="esdl:Point" lat="158243.498" CRS="WGS84" lon="433228.891"/>
          <point xsi:type="esdl:Point" lat="158245.63888339186" CRS="WGS84" lon="433228.5146777577"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.1212532597224554" name="lv_cable_trafo4_lvnetwork2_to_home_1_arch5" id="f881ffdf-6d3e-43b0-9c8c-03b16ba3640c" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="2809fa17-b9c9-4dd0-94fe-3b20636d74fa" name="In" connectedTo="552405d4-2b7f-412c-96f5-61e97343115b"/>
        <port xsi:type="esdl:OutPort" id="1425fa16-d2e8-490a-824c-7562a8c2fe2e" name="Out" connectedTo="4fb1326f-83b1-4373-a2b0-db1f7e756ea4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158245.833" CRS="WGS84" lon="433229.619"/>
          <point xsi:type="esdl:Point" lat="158245.63888339186" CRS="WGS84" lon="433228.5146777577"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome564" id="776e1c0f-47e1-4105-aa63-b2cc1f9efd60">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="f8fa638b-22e1-490e-bce0-21f37a11e6d9" name="In" connectedTo="b0c3c871-647e-4e4d-a5d7-47e6fe022a2d"/>
          <port xsi:type="esdl:OutPort" id="83e27e94-9ffc-4789-8ad2-af3c8a6b159b" name="Out" connectedTo="4de9d77b-d7db-4450-bad6-408e5a658d47"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="2313c53b-d8f2-4669-8373-2702812264d5" name="In" connectedTo="943e3dc9-17c5-4b3f-a0f7-dbd7c5197a8c"/>
          <port xsi:type="esdl:OutPort" id="1d599171-a7f2-4dd7-92ed-11e13f8cad7f" name="Out" connectedTo="7b31e7f9-52a7-4911-b5a0-3c78311229c5"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="d91878d0-978f-410a-a428-5330a57c63ca" name="In" connectedTo="08c3a323-be4b-4c6a-be73-2aa1d4269008"/>
          <port xsi:type="esdl:OutPort" id="6dca3140-6f6e-485c-9e3d-8c50e2ba1e4f" name="Out" connectedTo="ac0e1f84-000d-476b-98b3-56c646e498d8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="eae416a6-1aca-4317-af3a-bf4b7bbfac9b" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="4de9d77b-d7db-4450-bad6-408e5a658d47" name="In_Ph1" connectedTo="83e27e94-9ffc-4789-8ad2-af3c8a6b159b"/>
          <port xsi:type="esdl:InPort" id="7b31e7f9-52a7-4911-b5a0-3c78311229c5" name="In_Ph2" connectedTo="1d599171-a7f2-4dd7-92ed-11e13f8cad7f"/>
          <port xsi:type="esdl:InPort" id="ac0e1f84-000d-476b-98b3-56c646e498d8" name="In_Ph3" connectedTo="6dca3140-6f6e-485c-9e3d-8c50e2ba1e4f"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome564" id="3df892ef-08c4-4b26-a7ab-a39d7b94cf0d">
          <port xsi:type="esdl:InPort" id="4fb1326f-83b1-4373-a2b0-db1f7e756ea4" name="In" connectedTo="1425fa16-d2e8-490a-824c-7562a8c2fe2e"/>
          <port xsi:type="esdl:OutPort" id="b0c3c871-647e-4e4d-a5d7-47e6fe022a2d" name="OutPh1" connectedTo="f8fa638b-22e1-490e-bce0-21f37a11e6d9"/>
          <port xsi:type="esdl:OutPort" id="943e3dc9-17c5-4b3f-a0f7-dbd7c5197a8c" name="OutPh2" connectedTo="2313c53b-d8f2-4669-8373-2702812264d5"/>
          <port xsi:type="esdl:OutPort" id="08c3a323-be4b-4c6a-be73-2aa1d4269008" name="OutPh3" connectedTo="d91878d0-978f-410a-a428-5330a57c63ca"/>
          <geometry xsi:type="esdl:Point" lat="158245.833" lon="433229.619"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_8" id="2b3f3bfb-72a8-48d8-9369-12c3d0913ffe">
        <port xsi:type="esdl:InPort" id="c1282c37-ca35-4989-bfef-1af38dd5972f" name="In" connectedTo="ceab07fc-4915-4f59-8f16-8907563d6be4"/>
        <port xsi:type="esdl:OutPort" id="4cec789e-e1de-4d5a-b995-2d44bc643fc7" name="Out" connectedTo="1268ce95-ac12-42d5-ac5a-eefedb0a2845 2129a1fb-3fbd-456f-b52e-d0d816e57c7a"/>
        <geometry xsi:type="esdl:Point" lat="158268.41272287705" CRS="WGS84" lon="433224.2704356658"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="23.166127813841598" name="lv_cable_trafo4_lvnetwork2_8_main_grid" id="f94dd78f-5813-4883-bdfe-dd0b79ffc191" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="be71938d-ff82-4f1e-861a-0dab77f2bf41" name="In" connectedTo="552405d4-2b7f-412c-96f5-61e97343115b"/>
        <port xsi:type="esdl:OutPort" id="ceab07fc-4915-4f59-8f16-8907563d6be4" name="Out" connectedTo="c1282c37-ca35-4989-bfef-1af38dd5972f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158245.63888339186" CRS="WGS84" lon="433228.5146777577"/>
          <point xsi:type="esdl:Point" lat="158247.036" CRS="WGS84" lon="433228.269"/>
          <point xsi:type="esdl:Point" lat="158248.449" CRS="WGS84" lon="433228.021"/>
          <point xsi:type="esdl:Point" lat="158249.482" CRS="WGS84" lon="433227.827"/>
          <point xsi:type="esdl:Point" lat="158254.011" CRS="WGS84" lon="433226.976"/>
          <point xsi:type="esdl:Point" lat="158260.944" CRS="WGS84" lon="433225.674"/>
          <point xsi:type="esdl:Point" lat="158261.67" CRS="WGS84" lon="433225.538"/>
          <point xsi:type="esdl:Point" lat="158261.732" CRS="WGS84" lon="433225.526"/>
          <point xsi:type="esdl:Point" lat="158267.25" CRS="WGS84" lon="433224.489"/>
          <point xsi:type="esdl:Point" lat="158268.41272287705" CRS="WGS84" lon="433224.2704356658"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.9000567443316136" name="lv_cable_trafo4_lvnetwork2_to_home_2_arch5" id="4d8b2c60-7df3-44a6-b2ec-bb0bf4eb4d0b" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="1268ce95-ac12-42d5-ac5a-eefedb0a2845" name="In" connectedTo="4cec789e-e1de-4d5a-b995-2d44bc643fc7"/>
        <port xsi:type="esdl:OutPort" id="be9e68f2-ad8f-42b5-9a71-5850d98cfb39" name="Out" connectedTo="452e9da2-3ab4-4d36-ae34-dcdc3d73a370"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158268.579" CRS="WGS84" lon="433225.155"/>
          <point xsi:type="esdl:Point" lat="158268.41272287705" CRS="WGS84" lon="433224.2704356658"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome565" id="5b94dfa9-7faa-440c-b3a9-22ef102f59b5">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="c7386d66-acb1-4b0d-b8b2-61bc1a9653fd" name="In" connectedTo="350a7e8b-04de-4863-998a-accbb5d43b10"/>
          <port xsi:type="esdl:OutPort" id="ac46afac-b2fb-48de-9cd4-d1acd681f8d7" name="Out" connectedTo="406f910b-58e4-48ad-910d-a944d75ef42d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="ddcfebf1-1ef8-4967-8259-cf9be53a79cd" name="In" connectedTo="1d21ca06-32d5-47f1-9da0-a531cdc28626"/>
          <port xsi:type="esdl:OutPort" id="dcc1a161-3da5-411d-b3af-223e4b9bd8f0" name="Out" connectedTo="735a4b8f-1e1c-4e0a-b4e6-465565bdf122"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="7dd6316a-cc6d-4db2-952a-7ddf5ca762e4" name="In" connectedTo="d6750f38-365a-44e1-a500-69f78df81884"/>
          <port xsi:type="esdl:OutPort" id="bb50e243-bc1a-4b29-bf48-dc2834276f96" name="Out" connectedTo="e0208550-03de-4603-b1bd-80ccde252c21"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="c5e20f2b-c16d-4f47-8433-59837ffba317" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="406f910b-58e4-48ad-910d-a944d75ef42d" name="In_Ph1" connectedTo="ac46afac-b2fb-48de-9cd4-d1acd681f8d7"/>
          <port xsi:type="esdl:InPort" id="735a4b8f-1e1c-4e0a-b4e6-465565bdf122" name="In_Ph2" connectedTo="dcc1a161-3da5-411d-b3af-223e4b9bd8f0"/>
          <port xsi:type="esdl:InPort" id="e0208550-03de-4603-b1bd-80ccde252c21" name="In_Ph3" connectedTo="bb50e243-bc1a-4b29-bf48-dc2834276f96"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome565" id="3c80c7d0-740c-4b40-ae43-44a6895cc9ca">
          <port xsi:type="esdl:InPort" id="452e9da2-3ab4-4d36-ae34-dcdc3d73a370" name="In" connectedTo="be9e68f2-ad8f-42b5-9a71-5850d98cfb39"/>
          <port xsi:type="esdl:OutPort" id="350a7e8b-04de-4863-998a-accbb5d43b10" name="OutPh1" connectedTo="c7386d66-acb1-4b0d-b8b2-61bc1a9653fd"/>
          <port xsi:type="esdl:OutPort" id="1d21ca06-32d5-47f1-9da0-a531cdc28626" name="OutPh2" connectedTo="ddcfebf1-1ef8-4967-8259-cf9be53a79cd"/>
          <port xsi:type="esdl:OutPort" id="d6750f38-365a-44e1-a500-69f78df81884" name="OutPh3" connectedTo="7dd6316a-cc6d-4db2-952a-7ddf5ca762e4"/>
          <geometry xsi:type="esdl:Point" lat="158268.579" lon="433225.155"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_9" id="83cf7141-2ef9-4983-b65e-2a9ffb823d98">
        <port xsi:type="esdl:InPort" id="56af7d27-c0f2-4c33-b2cd-e2c01f99bcb7" name="In" connectedTo="fea2a30a-918b-49b8-8d07-67f7b7f406e7"/>
        <port xsi:type="esdl:OutPort" id="2516d177-a4a9-45f5-8b0a-675b4fd6fff5" name="Out" connectedTo="5ddf9c1f-bef2-4373-b9db-93ab6abdfab4 c09c68bf-a8ea-4377-9449-304a91bb95f6"/>
        <geometry xsi:type="esdl:Point" lat="158283.68670594355" CRS="WGS84" lon="433221.6663042114"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="15.494388165965189" name="lv_cable_trafo4_lvnetwork2_9_main_grid" id="a9080720-d6a5-4848-b68b-d8f108881b6d" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="2129a1fb-3fbd-456f-b52e-d0d816e57c7a" name="In" connectedTo="4cec789e-e1de-4d5a-b995-2d44bc643fc7"/>
        <port xsi:type="esdl:OutPort" id="fea2a30a-918b-49b8-8d07-67f7b7f406e7" name="Out" connectedTo="56af7d27-c0f2-4c33-b2cd-e2c01f99bcb7"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158268.41272287705" CRS="WGS84" lon="433224.2704356658"/>
          <point xsi:type="esdl:Point" lat="158269.868" CRS="WGS84" lon="433224.022"/>
          <point xsi:type="esdl:Point" lat="158271.794" CRS="WGS84" lon="433223.694"/>
          <point xsi:type="esdl:Point" lat="158276.861" CRS="WGS84" lon="433222.83"/>
          <point xsi:type="esdl:Point" lat="158279.891" CRS="WGS84" lon="433222.314"/>
          <point xsi:type="esdl:Point" lat="158281.959" CRS="WGS84" lon="433221.961"/>
          <point xsi:type="esdl:Point" lat="158283.68670594355" CRS="WGS84" lon="433221.6663042114"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.7392202410534346" name="lv_cable_trafo4_lvnetwork2_to_home_10_arch5" id="61f8c9c7-6082-44ce-b928-c5ae686cd210" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="5ddf9c1f-bef2-4373-b9db-93ab6abdfab4" name="In" connectedTo="2516d177-a4a9-45f5-8b0a-675b4fd6fff5"/>
        <port xsi:type="esdl:OutPort" id="4a4fe2d4-81c4-453e-a3af-b8370c75b0ef" name="Out" connectedTo="f723ba59-ecb5-4b54-8cb0-c94af483826d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158283.811" CRS="WGS84" lon="433222.395"/>
          <point xsi:type="esdl:Point" lat="158283.68670594355" CRS="WGS84" lon="433221.6663042114"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome573" id="b7a5df6c-114b-4fbc-8888-3c4e82758a30">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="0bd9fe59-750f-4d04-bce8-2814f5ddaf48" name="In" connectedTo="77e18d47-b3b7-48f7-a502-2440823d9be3"/>
          <port xsi:type="esdl:OutPort" id="6bb576e1-a188-4c95-8cb0-6b06866e32bb" name="Out" connectedTo="85ca3927-341c-409d-a50f-3ed383fbe1e5"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="87dc6d53-9d02-40d3-8b00-4fdb18928e91" name="In" connectedTo="f6c983b1-a968-4ac4-9f43-c5885beea89b"/>
          <port xsi:type="esdl:OutPort" id="035dbdd2-61a3-4b9e-83c7-8d25618dd2b1" name="Out" connectedTo="87a88e78-88fd-49d7-b5e5-cdae427ec3c7"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="137fffb1-86ba-405a-9a36-dfb2be57e703" name="In" connectedTo="04047313-cb7b-4d54-ae96-188c246dba21"/>
          <port xsi:type="esdl:OutPort" id="de02aae0-2b45-4938-9e99-a37a433a6008" name="Out" connectedTo="77cde873-2d96-40bb-beff-c822e1be75c8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="03489dce-a62e-4f39-9af4-6cc1466fdcd3" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="85ca3927-341c-409d-a50f-3ed383fbe1e5" name="In_Ph1" connectedTo="6bb576e1-a188-4c95-8cb0-6b06866e32bb"/>
          <port xsi:type="esdl:InPort" id="87a88e78-88fd-49d7-b5e5-cdae427ec3c7" name="In_Ph2" connectedTo="035dbdd2-61a3-4b9e-83c7-8d25618dd2b1"/>
          <port xsi:type="esdl:InPort" id="77cde873-2d96-40bb-beff-c822e1be75c8" name="In_Ph3" connectedTo="de02aae0-2b45-4938-9e99-a37a433a6008"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome573" id="9afae6c6-8b3b-4054-ae3c-ae55ed875b2f">
          <port xsi:type="esdl:InPort" id="f723ba59-ecb5-4b54-8cb0-c94af483826d" name="In" connectedTo="4a4fe2d4-81c4-453e-a3af-b8370c75b0ef"/>
          <port xsi:type="esdl:OutPort" id="77e18d47-b3b7-48f7-a502-2440823d9be3" name="OutPh1" connectedTo="0bd9fe59-750f-4d04-bce8-2814f5ddaf48"/>
          <port xsi:type="esdl:OutPort" id="f6c983b1-a968-4ac4-9f43-c5885beea89b" name="OutPh2" connectedTo="87dc6d53-9d02-40d3-8b00-4fdb18928e91"/>
          <port xsi:type="esdl:OutPort" id="04047313-cb7b-4d54-ae96-188c246dba21" name="OutPh3" connectedTo="137fffb1-86ba-405a-9a36-dfb2be57e703"/>
          <geometry xsi:type="esdl:Point" lat="158283.811" lon="433222.395"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_10" id="fcdb187b-c7dc-47b2-bcf4-d3db84854ea4">
        <port xsi:type="esdl:InPort" id="c6645d4f-0d6d-4aff-b231-0f2b4919fa49" name="In" connectedTo="aaea3b85-f4fe-4fc7-8278-33b46697f246"/>
        <port xsi:type="esdl:OutPort" id="424d7728-f97f-452e-8e3c-f850e1e54d04" name="Out" connectedTo="d36b0ffa-a872-4d5b-aee0-f9394a40277e 128f835a-d982-41a1-9fbe-986059d73a6d"/>
        <geometry xsi:type="esdl:Point" lat="158285.94378257944" CRS="WGS84" lon="433221.28131336183"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.2896752814727854" name="lv_cable_trafo4_lvnetwork2_10_main_grid" id="9d51c683-9783-4579-9837-a6e502e6a9bf" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="c09c68bf-a8ea-4377-9449-304a91bb95f6" name="In" connectedTo="2516d177-a4a9-45f5-8b0a-675b4fd6fff5"/>
        <port xsi:type="esdl:OutPort" id="aaea3b85-f4fe-4fc7-8278-33b46697f246" name="Out" connectedTo="c6645d4f-0d6d-4aff-b231-0f2b4919fa49"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158283.68670594355" CRS="WGS84" lon="433221.6663042114"/>
          <point xsi:type="esdl:Point" lat="158285.94378257944" CRS="WGS84" lon="433221.28131336183"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.461785796662657" name="lv_cable_trafo4_lvnetwork2_to_home_3_arch5" id="78ccb3b8-a284-480a-a18f-12591f4a8513" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="d36b0ffa-a872-4d5b-aee0-f9394a40277e" name="In" connectedTo="424d7728-f97f-452e-8e3c-f850e1e54d04"/>
        <port xsi:type="esdl:OutPort" id="8d556374-6361-4496-9589-889927192dc1" name="Out" connectedTo="ea44022a-60df-483e-9605-3f5eec159008"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158284.521" CRS="WGS84" lon="433212.94"/>
          <point xsi:type="esdl:Point" lat="158285.94378257944" CRS="WGS84" lon="433221.28131336183"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome566" id="5b00215f-48cb-4994-9fca-acd494606dba">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="de7e1f1a-4b7e-4214-b2d8-74afd19348ea" name="In" connectedTo="394f1683-dfcd-4734-b1cc-cfb3dd2fc5aa"/>
          <port xsi:type="esdl:OutPort" id="a415d7a5-1a46-47f6-94e0-2773513e0638" name="Out" connectedTo="0e9267fa-adb4-475a-91c9-06cb56b0e6a2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="5d19a0e8-c902-4b4e-ae89-8a9271daf314" name="In" connectedTo="7d7e8727-61d8-41de-9446-92576c1e4709"/>
          <port xsi:type="esdl:OutPort" id="18fa725a-01ea-472a-9c5d-2e53f88e284a" name="Out" connectedTo="07258d16-67e8-4aff-a6d6-721bafeeaf98"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="079c4d99-4d83-4a1a-9d7c-66d621c385bb" name="In" connectedTo="6f1b9cb3-3cfb-48b2-b10c-7113b68e174c"/>
          <port xsi:type="esdl:OutPort" id="6e9bc52d-0e8c-45c9-b4bb-3aeff1765016" name="Out" connectedTo="617fdc96-dabd-4370-9e4e-0b573d60ed60"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="aa597490-068a-421f-ba2e-bd50df53b9e6" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="0e9267fa-adb4-475a-91c9-06cb56b0e6a2" name="In_Ph1" connectedTo="a415d7a5-1a46-47f6-94e0-2773513e0638"/>
          <port xsi:type="esdl:InPort" id="07258d16-67e8-4aff-a6d6-721bafeeaf98" name="In_Ph2" connectedTo="18fa725a-01ea-472a-9c5d-2e53f88e284a"/>
          <port xsi:type="esdl:InPort" id="617fdc96-dabd-4370-9e4e-0b573d60ed60" name="In_Ph3" connectedTo="6e9bc52d-0e8c-45c9-b4bb-3aeff1765016"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome566" id="9d5e8bc6-a44f-4e52-97c9-b92b4d3965f3">
          <port xsi:type="esdl:InPort" id="ea44022a-60df-483e-9605-3f5eec159008" name="In" connectedTo="8d556374-6361-4496-9589-889927192dc1"/>
          <port xsi:type="esdl:OutPort" id="394f1683-dfcd-4734-b1cc-cfb3dd2fc5aa" name="OutPh1" connectedTo="de7e1f1a-4b7e-4214-b2d8-74afd19348ea"/>
          <port xsi:type="esdl:OutPort" id="7d7e8727-61d8-41de-9446-92576c1e4709" name="OutPh2" connectedTo="5d19a0e8-c902-4b4e-ae89-8a9271daf314"/>
          <port xsi:type="esdl:OutPort" id="6f1b9cb3-3cfb-48b2-b10c-7113b68e174c" name="OutPh3" connectedTo="079c4d99-4d83-4a1a-9d7c-66d621c385bb"/>
          <geometry xsi:type="esdl:Point" lat="158284.521" lon="433212.94"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_11" id="df1af3b3-d996-4c3e-bbf9-f9df6308b060">
        <port xsi:type="esdl:InPort" id="994f630b-8044-40ee-bb86-803145a3dc5c" name="In" connectedTo="fd7774ba-7bbb-4bdb-a7f2-8f11c6abd8a9"/>
        <port xsi:type="esdl:OutPort" id="8253be70-ac39-4d5c-b477-c40413c88ebb" name="Out" connectedTo="d81b28df-81dd-4429-a3ec-d360eee80a8a 0f6b0c42-a4c7-4d9d-bf6e-13fe31309bc8 574f06da-0ea8-4875-b777-e9bcd21a61d7"/>
        <geometry xsi:type="esdl:Point" lat="158296.78531341467" CRS="WGS84" lon="433219.43264176894"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.998017027434875" name="lv_cable_trafo4_lvnetwork2_11_main_grid" id="2b179376-a976-4f55-bb08-df4e8bed50d0" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="128f835a-d982-41a1-9fbe-986059d73a6d" name="In" connectedTo="424d7728-f97f-452e-8e3c-f850e1e54d04"/>
        <port xsi:type="esdl:OutPort" id="fd7774ba-7bbb-4bdb-a7f2-8f11c6abd8a9" name="Out" connectedTo="994f630b-8044-40ee-bb86-803145a3dc5c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158285.94378257944" CRS="WGS84" lon="433221.28131336183"/>
          <point xsi:type="esdl:Point" lat="158289.919" CRS="WGS84" lon="433220.603"/>
          <point xsi:type="esdl:Point" lat="158293.082" CRS="WGS84" lon="433220.064"/>
          <point xsi:type="esdl:Point" lat="158296.78531341467" CRS="WGS84" lon="433219.43264176894"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.778500187223079" name="lv_cable_trafo4_lvnetwork2_to_home_5_arch5" id="1f3b4c3c-c9f3-4d8e-abdb-20ccc8be54ac" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="d81b28df-81dd-4429-a3ec-d360eee80a8a" name="In" connectedTo="8253be70-ac39-4d5c-b477-c40413c88ebb"/>
        <port xsi:type="esdl:OutPort" id="ac54722a-cc04-485d-ac51-034102e4351f" name="Out" connectedTo="7406e26b-18fa-403a-b1d0-3b536464ae0a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158295.31" CRS="WGS84" lon="433210.779"/>
          <point xsi:type="esdl:Point" lat="158296.78531341467" CRS="WGS84" lon="433219.43264176894"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="2xhome568" id="c81994ae-6b6a-4fa9-9e22-63a5ddb63fd3">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="13ae66cb-46e8-43e4-9b41-acbfbef0d0e8" name="In" connectedTo="473d3913-9e9d-400f-9421-c0f3dd612cc1"/>
          <port xsi:type="esdl:OutPort" id="95f2f34b-b4f1-4f20-9bc0-cc67ab6db6f0" name="Out" connectedTo="7fdc043a-cac5-4951-b6ff-f4a76b8b0a12"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="b1dd5665-88ce-42f6-923e-3ffeff803bf1" name="In" connectedTo="5761a195-1a56-434d-8887-ed7f12e91fb2"/>
          <port xsi:type="esdl:OutPort" id="6bfbbe87-67e5-4f02-91d5-318df9650f6d" name="Out" connectedTo="6f84dc80-a3d0-43ef-9f44-6c7c342070e2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="f400a067-c5d7-4c5e-9df5-a57590e6f560" name="In" connectedTo="d8451827-775e-42d2-af09-c3d5dde27cab"/>
          <port xsi:type="esdl:OutPort" id="e89c0df0-d3e0-411f-bbd1-8ddf61c72836" name="Out" connectedTo="9776af36-7fb9-4725-a64b-9804541d3677"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="1ae36a6a-e328-453b-9d2d-4a525374a307" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7fdc043a-cac5-4951-b6ff-f4a76b8b0a12" name="In_Ph1" connectedTo="95f2f34b-b4f1-4f20-9bc0-cc67ab6db6f0"/>
          <port xsi:type="esdl:InPort" id="6f84dc80-a3d0-43ef-9f44-6c7c342070e2" name="In_Ph2" connectedTo="6bfbbe87-67e5-4f02-91d5-318df9650f6d"/>
          <port xsi:type="esdl:InPort" id="9776af36-7fb9-4725-a64b-9804541d3677" name="In_Ph3" connectedTo="e89c0df0-d3e0-411f-bbd1-8ddf61c72836"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="2xhome568" id="54629354-0a73-4790-a57e-c7355ef285e9">
          <port xsi:type="esdl:InPort" id="7406e26b-18fa-403a-b1d0-3b536464ae0a" name="In" connectedTo="ac54722a-cc04-485d-ac51-034102e4351f"/>
          <port xsi:type="esdl:OutPort" id="473d3913-9e9d-400f-9421-c0f3dd612cc1" name="OutPh1" connectedTo="13ae66cb-46e8-43e4-9b41-acbfbef0d0e8"/>
          <port xsi:type="esdl:OutPort" id="5761a195-1a56-434d-8887-ed7f12e91fb2" name="OutPh2" connectedTo="b1dd5665-88ce-42f6-923e-3ffeff803bf1"/>
          <port xsi:type="esdl:OutPort" id="d8451827-775e-42d2-af09-c3d5dde27cab" name="OutPh3" connectedTo="f400a067-c5d7-4c5e-9df5-a57590e6f560"/>
          <geometry xsi:type="esdl:Point" lat="158295.31" lon="433210.779"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.5024221682448657" name="lv_cable_trafo4_lvnetwork2_to_home_4_arch5" id="0e408815-9560-4835-a72f-1b4c82807688" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="0f6b0c42-a4c7-4d9d-bf6e-13fe31309bc8" name="In" connectedTo="8253be70-ac39-4d5c-b477-c40413c88ebb"/>
        <port xsi:type="esdl:OutPort" id="7b4bd28c-bd4d-4025-865b-98626e2290a4" name="Out" connectedTo="a58662ec-b792-4775-9348-0173ee3327fb"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158296.881" CRS="WGS84" lon="433219.926"/>
          <point xsi:type="esdl:Point" lat="158296.79656300633" CRS="WGS84" lon="433219.43072388583"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="4xhome567" id="227ed092-2023-43bc-9ba3-65a167a2c27d">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="5886aada-4343-4e17-9a6a-e59acad44553" name="In" connectedTo="cca9f040-7431-4497-b083-8c9e70eb5c6d"/>
          <port xsi:type="esdl:OutPort" id="6865d513-b6c5-4344-b65f-780c279e2798" name="Out" connectedTo="1a05eba1-db6c-4a45-867f-091fc2b6bd69"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="ca691c85-4e73-41bb-8a0c-b15cb3bf3a01" name="In" connectedTo="d0133a83-221b-4921-b284-5e79b61efbf2"/>
          <port xsi:type="esdl:OutPort" id="a6d9c765-5d3c-4190-8c8a-3a775fe0a595" name="Out" connectedTo="c7a7590d-cea3-429d-81fc-5878162e81cf"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="56ddf227-b118-4859-94a8-8aa2c06b513d" name="In" connectedTo="aa247bcf-d729-44c1-85eb-a3479a7e4af0"/>
          <port xsi:type="esdl:OutPort" id="98220676-59bc-4438-b662-b9ee98fd1e42" name="Out" connectedTo="5c650d9b-4560-44e1-8f7e-ef2898334ffd"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="fb979a9e-0a35-42c5-8007-d092d2915001" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="1a05eba1-db6c-4a45-867f-091fc2b6bd69" name="In_Ph1" connectedTo="6865d513-b6c5-4344-b65f-780c279e2798"/>
          <port xsi:type="esdl:InPort" id="c7a7590d-cea3-429d-81fc-5878162e81cf" name="In_Ph2" connectedTo="a6d9c765-5d3c-4190-8c8a-3a775fe0a595"/>
          <port xsi:type="esdl:InPort" id="5c650d9b-4560-44e1-8f7e-ef2898334ffd" name="In_Ph3" connectedTo="98220676-59bc-4438-b662-b9ee98fd1e42"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="4xhome567" id="7bec95b8-f8b3-4311-b268-a9a7f8000a39">
          <port xsi:type="esdl:InPort" id="a58662ec-b792-4775-9348-0173ee3327fb" name="In" connectedTo="7b4bd28c-bd4d-4025-865b-98626e2290a4"/>
          <port xsi:type="esdl:OutPort" id="cca9f040-7431-4497-b083-8c9e70eb5c6d" name="OutPh1" connectedTo="5886aada-4343-4e17-9a6a-e59acad44553"/>
          <port xsi:type="esdl:OutPort" id="d0133a83-221b-4921-b284-5e79b61efbf2" name="OutPh2" connectedTo="ca691c85-4e73-41bb-8a0c-b15cb3bf3a01"/>
          <port xsi:type="esdl:OutPort" id="aa247bcf-d729-44c1-85eb-a3479a7e4af0" name="OutPh3" connectedTo="56ddf227-b118-4859-94a8-8aa2c06b513d"/>
          <geometry xsi:type="esdl:Point" lat="158296.881" lon="433219.926"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_12" id="f3d548e9-b823-47c0-89bd-2bb0d39b59df">
        <port xsi:type="esdl:InPort" id="5cdd72f7-b39a-4a54-9146-9216eacbf793" name="In" connectedTo="4c3450c7-a9f9-433c-acc2-28895491baf3"/>
        <port xsi:type="esdl:OutPort" id="3988c7f0-fa70-4fe7-b849-a960748bf0d9" name="Out" connectedTo="19f396dd-8c42-468b-8041-5b869787efce 3b9e1b36-69df-49b4-86b4-1ac2298d1b37"/>
        <geometry xsi:type="esdl:Point" lat="158301.68739181268" CRS="WGS84" lon="433218.59679655865"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.961415689344313" name="lv_cable_trafo4_lvnetwork2_12_main_grid" id="f3ca32e9-c092-41f4-a061-b5308ad5a557" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="574f06da-0ea8-4875-b777-e9bcd21a61d7" name="In" connectedTo="8253be70-ac39-4d5c-b477-c40413c88ebb"/>
        <port xsi:type="esdl:OutPort" id="4c3450c7-a9f9-433c-acc2-28895491baf3" name="Out" connectedTo="5cdd72f7-b39a-4a54-9146-9216eacbf793"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158296.79656300633" CRS="WGS84" lon="433219.43072388583"/>
          <point xsi:type="esdl:Point" lat="158298.344" CRS="WGS84" lon="433219.167"/>
          <point xsi:type="esdl:Point" lat="158298.61" CRS="WGS84" lon="433219.122"/>
          <point xsi:type="esdl:Point" lat="158299.024" CRS="WGS84" lon="433219.051"/>
          <point xsi:type="esdl:Point" lat="158299.973" CRS="WGS84" lon="433218.889"/>
          <point xsi:type="esdl:Point" lat="158301.68739181268" CRS="WGS84" lon="433218.59679655865"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.4678545302212734" name="lv_cable_trafo4_lvnetwork2_to_home_7_arch5" id="8eb1a0a2-0c39-4af6-9b35-d5b5a9e91c77" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="19f396dd-8c42-468b-8041-5b869787efce" name="In" connectedTo="3988c7f0-fa70-4fe7-b849-a960748bf0d9"/>
        <port xsi:type="esdl:OutPort" id="3d68f78c-13a6-462c-baa5-957447153999" name="Out" connectedTo="fdf8a948-2ab5-43d8-ab5d-1bf059f578a7"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158301.766" CRS="WGS84" lon="433219.058"/>
          <point xsi:type="esdl:Point" lat="158301.68739181268" CRS="WGS84" lon="433218.59679655865"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome570" id="7f9e329f-5293-4f63-841d-9dad227bde5d">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="f099840d-3bd1-4424-bc01-06dd7be18b46" name="In" connectedTo="fdd3a420-3e04-40dc-bf8c-81c2f6476263"/>
          <port xsi:type="esdl:OutPort" id="d69ed385-e2b5-43ed-8e24-6bf830b964b0" name="Out" connectedTo="436bd48b-1522-4d08-9631-9fc9f3519780"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="75d26d0d-6537-410d-be65-13e132c9dcc1" name="In" connectedTo="23e268a7-6b91-4439-bee9-ffeb7b43a93c"/>
          <port xsi:type="esdl:OutPort" id="5dc0267e-dc14-4b54-b682-0676552a90d6" name="Out" connectedTo="370ebbe8-1337-4706-9269-a86faeb1d4e2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="8692d180-5522-43f5-aa4f-fdcdb7a1486a" name="In" connectedTo="40d568d9-5caf-4c58-8d0a-b4796848bde0"/>
          <port xsi:type="esdl:OutPort" id="c312447a-56d5-4199-8a31-c20b0311496a" name="Out" connectedTo="a079ce0e-a8c4-4870-93c4-d552c7e9f0cd"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="1b2d4f0e-0299-4aa5-a249-1b1ca09cb3c9" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="436bd48b-1522-4d08-9631-9fc9f3519780" name="In_Ph1" connectedTo="d69ed385-e2b5-43ed-8e24-6bf830b964b0"/>
          <port xsi:type="esdl:InPort" id="370ebbe8-1337-4706-9269-a86faeb1d4e2" name="In_Ph2" connectedTo="5dc0267e-dc14-4b54-b682-0676552a90d6"/>
          <port xsi:type="esdl:InPort" id="a079ce0e-a8c4-4870-93c4-d552c7e9f0cd" name="In_Ph3" connectedTo="c312447a-56d5-4199-8a31-c20b0311496a"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome570" id="d04628a8-2fd0-494e-9120-6b16612fb1f6">
          <port xsi:type="esdl:InPort" id="fdf8a948-2ab5-43d8-ab5d-1bf059f578a7" name="In" connectedTo="3d68f78c-13a6-462c-baa5-957447153999"/>
          <port xsi:type="esdl:OutPort" id="fdd3a420-3e04-40dc-bf8c-81c2f6476263" name="OutPh1" connectedTo="f099840d-3bd1-4424-bc01-06dd7be18b46"/>
          <port xsi:type="esdl:OutPort" id="23e268a7-6b91-4439-bee9-ffeb7b43a93c" name="OutPh2" connectedTo="75d26d0d-6537-410d-be65-13e132c9dcc1"/>
          <port xsi:type="esdl:OutPort" id="40d568d9-5caf-4c58-8d0a-b4796848bde0" name="OutPh3" connectedTo="8692d180-5522-43f5-aa4f-fdcdb7a1486a"/>
          <geometry xsi:type="esdl:Point" lat="158301.766" lon="433219.058"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_13" id="503f059d-eca1-4e1d-9fd5-0c72a8fde95c">
        <port xsi:type="esdl:InPort" id="0a6eebe6-fce5-4bba-be32-4c7d7b66bce6" name="In" connectedTo="86a51cb5-dea7-406b-b37b-308a99e9ecb0"/>
        <port xsi:type="esdl:OutPort" id="7a410c28-6dd8-4532-bb8a-979600e8f068" name="Out" connectedTo="f2c85021-1484-4d8a-ab89-d5b5b17b8d92 7f55ffc0-d494-4636-80f7-2f7118475ea5"/>
        <geometry xsi:type="esdl:Point" lat="158303.168659001" CRS="WGS84" lon="433218.3443441713"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.5026259365017123" name="lv_cable_trafo4_lvnetwork2_13_main_grid" id="5029ff55-0501-48f0-91e6-b997bbb8ed4b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="3b9e1b36-69df-49b4-86b4-1ac2298d1b37" name="In" connectedTo="3988c7f0-fa70-4fe7-b849-a960748bf0d9"/>
        <port xsi:type="esdl:OutPort" id="86a51cb5-dea7-406b-b37b-308a99e9ecb0" name="Out" connectedTo="0a6eebe6-fce5-4bba-be32-4c7d7b66bce6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158301.68739181268" CRS="WGS84" lon="433218.59679655865"/>
          <point xsi:type="esdl:Point" lat="158303.159" CRS="WGS84" lon="433218.346"/>
          <point xsi:type="esdl:Point" lat="158303.168659001" CRS="WGS84" lon="433218.3443441713"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.828274857684214" name="lv_cable_trafo4_lvnetwork2_to_home_6_arch5" id="c1257de3-a167-4152-816c-2406441a8b5f" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="f2c85021-1484-4d8a-ab89-d5b5b17b8d92" name="In" connectedTo="7a410c28-6dd8-4532-bb8a-979600e8f068"/>
        <port xsi:type="esdl:OutPort" id="09d6898a-a49d-4087-a6fe-cdebe842ec79" name="Out" connectedTo="f246e3e4-86bf-476d-a276-e405f0267dc6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158301.677" CRS="WGS84" lon="433209.643"/>
          <point xsi:type="esdl:Point" lat="158303.168659001" CRS="WGS84" lon="433218.3443441713"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome569" id="26f62756-3713-437c-a5cc-296032ad0737">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="a07300cf-bac2-4084-924a-fe4c5c7dbeba" name="In" connectedTo="667ea167-188d-4f8f-81f4-712b7401061c"/>
          <port xsi:type="esdl:OutPort" id="cd6034d2-0488-4d4b-89cb-0f231ba9b89c" name="Out" connectedTo="6ba93ee8-485d-4566-85c6-fd01e58b573d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="4898c8cf-ce4d-4ba4-968c-f08f2efc3116" name="In" connectedTo="6839c713-b979-4445-a5e6-3c1b9c43c55d"/>
          <port xsi:type="esdl:OutPort" id="b4b70f3c-43fd-4625-a088-9d029677f7bc" name="Out" connectedTo="28805e3f-0b32-4f58-9938-a2710d8d0077"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="22c61f12-6d2b-44ff-8e9d-9b7cc9e0c18e" name="In" connectedTo="e7db37fa-bf23-4fe9-be30-59d900a3e6ae"/>
          <port xsi:type="esdl:OutPort" id="b6df33d4-3c78-439d-bbd3-7fbb368fd492" name="Out" connectedTo="bd8e1bf2-3560-4d33-9334-68a5c2e25ff2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="ccd05b58-f505-470c-9fbb-21b8e9481994" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="6ba93ee8-485d-4566-85c6-fd01e58b573d" name="In_Ph1" connectedTo="cd6034d2-0488-4d4b-89cb-0f231ba9b89c"/>
          <port xsi:type="esdl:InPort" id="28805e3f-0b32-4f58-9938-a2710d8d0077" name="In_Ph2" connectedTo="b4b70f3c-43fd-4625-a088-9d029677f7bc"/>
          <port xsi:type="esdl:InPort" id="bd8e1bf2-3560-4d33-9334-68a5c2e25ff2" name="In_Ph3" connectedTo="b6df33d4-3c78-439d-bbd3-7fbb368fd492"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome569" id="7a2cc2d7-c41b-4351-9a94-c1a27339fcdc">
          <port xsi:type="esdl:InPort" id="f246e3e4-86bf-476d-a276-e405f0267dc6" name="In" connectedTo="09d6898a-a49d-4087-a6fe-cdebe842ec79"/>
          <port xsi:type="esdl:OutPort" id="667ea167-188d-4f8f-81f4-712b7401061c" name="OutPh1" connectedTo="a07300cf-bac2-4084-924a-fe4c5c7dbeba"/>
          <port xsi:type="esdl:OutPort" id="6839c713-b979-4445-a5e6-3c1b9c43c55d" name="OutPh2" connectedTo="4898c8cf-ce4d-4ba4-968c-f08f2efc3116"/>
          <port xsi:type="esdl:OutPort" id="e7db37fa-bf23-4fe9-be30-59d900a3e6ae" name="OutPh3" connectedTo="22c61f12-6d2b-44ff-8e9d-9b7cc9e0c18e"/>
          <geometry xsi:type="esdl:Point" lat="158301.677" lon="433209.643"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_14" id="116a1354-ae3f-4989-bafb-df422a4d72c5">
        <port xsi:type="esdl:InPort" id="5d1e8129-e81b-4a20-9c96-c51fe444b42e" name="In" connectedTo="00aaf7ab-0f45-48dd-9e0c-3e1765f10f0b"/>
        <port xsi:type="esdl:OutPort" id="8306d141-22be-4faf-a2ae-d8ec6f2f4aae" name="Out" connectedTo="6ba41747-3532-4c54-883b-ee6f7c70a36e 050f70d6-b04f-4969-bace-0746c7c78f1e"/>
        <geometry xsi:type="esdl:Point" lat="158305.83510148196" CRS="WGS84" lon="433217.8891429175"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.705018361492688" name="lv_cable_trafo4_lvnetwork2_14_main_grid" id="a4aab3c0-cdc5-4952-bc0c-89d2f91781ea" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="7f55ffc0-d494-4636-80f7-2f7118475ea5" name="In" connectedTo="7a410c28-6dd8-4532-bb8a-979600e8f068"/>
        <port xsi:type="esdl:OutPort" id="00aaf7ab-0f45-48dd-9e0c-3e1765f10f0b" name="Out" connectedTo="5d1e8129-e81b-4a20-9c96-c51fe444b42e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158303.168659001" CRS="WGS84" lon="433218.3443441713"/>
          <point xsi:type="esdl:Point" lat="158304.252" CRS="WGS84" lon="433218.159"/>
          <point xsi:type="esdl:Point" lat="158305.83510148196" CRS="WGS84" lon="433217.8891429175"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.38026418830370534" name="lv_cable_trafo4_lvnetwork2_to_home_8_arch5" id="dd786227-abbd-4294-a983-b6f0b62a837e" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="6ba41747-3532-4c54-883b-ee6f7c70a36e" name="In" connectedTo="8306d141-22be-4faf-a2ae-d8ec6f2f4aae"/>
        <port xsi:type="esdl:OutPort" id="9ccb03a3-d8c6-4f8c-a1b6-9b6bc74706d3" name="Out" connectedTo="eef1daf0-1ddd-471c-b716-084e3d82b2af"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158305.899" CRS="WGS84" lon="433218.264"/>
          <point xsi:type="esdl:Point" lat="158305.83510148196" CRS="WGS84" lon="433217.8891429175"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome571" id="bdf344c6-0285-4fae-a1c0-8151bda87826">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="3c542829-3081-4cfe-a484-e8559c73848f" name="In" connectedTo="fcf451ea-954c-4a63-a4a6-9cd5855b163f"/>
          <port xsi:type="esdl:OutPort" id="1902d94e-4112-4289-9da7-ae6873a4e4d6" name="Out" connectedTo="e3ca9779-38bb-4fad-8e56-898f40754bba"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="e437cc44-cf22-406b-84fc-47edbaf24acb" name="In" connectedTo="8aba4345-2399-4735-8a92-61d1b551dc1c"/>
          <port xsi:type="esdl:OutPort" id="da506c04-2537-40cc-bcd1-9a68f3dd343e" name="Out" connectedTo="8a1d71dc-fcad-4a46-8c62-27916e4b1901"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="3bbd6e14-c63c-4687-9ecb-da93b3a42027" name="In" connectedTo="38c90116-85c7-4319-9928-e38510c8e454"/>
          <port xsi:type="esdl:OutPort" id="40435e60-0c81-4a30-8839-52667c778f9c" name="Out" connectedTo="549eb686-19a2-4049-b212-d88ad7b653de"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="c6511d73-4132-424f-a854-441e092e7ecc" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="e3ca9779-38bb-4fad-8e56-898f40754bba" name="In_Ph1" connectedTo="1902d94e-4112-4289-9da7-ae6873a4e4d6"/>
          <port xsi:type="esdl:InPort" id="8a1d71dc-fcad-4a46-8c62-27916e4b1901" name="In_Ph2" connectedTo="da506c04-2537-40cc-bcd1-9a68f3dd343e"/>
          <port xsi:type="esdl:InPort" id="549eb686-19a2-4049-b212-d88ad7b653de" name="In_Ph3" connectedTo="40435e60-0c81-4a30-8839-52667c778f9c"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome571" id="2d383666-7aea-4f72-8b33-4e5668e6f020">
          <port xsi:type="esdl:InPort" id="eef1daf0-1ddd-471c-b716-084e3d82b2af" name="In" connectedTo="9ccb03a3-d8c6-4f8c-a1b6-9b6bc74706d3"/>
          <port xsi:type="esdl:OutPort" id="fcf451ea-954c-4a63-a4a6-9cd5855b163f" name="OutPh1" connectedTo="3c542829-3081-4cfe-a484-e8559c73848f"/>
          <port xsi:type="esdl:OutPort" id="8aba4345-2399-4735-8a92-61d1b551dc1c" name="OutPh2" connectedTo="e437cc44-cf22-406b-84fc-47edbaf24acb"/>
          <port xsi:type="esdl:OutPort" id="38c90116-85c7-4319-9928-e38510c8e454" name="OutPh3" connectedTo="3bbd6e14-c63c-4687-9ecb-da93b3a42027"/>
          <geometry xsi:type="esdl:Point" lat="158305.899" lon="433218.264"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_15" id="40937b72-9764-4eb2-b693-ff70f34bddd6">
        <port xsi:type="esdl:InPort" id="e06aacd4-302b-4b77-8c56-ddf5aed1f871" name="In" connectedTo="c9875618-7bb6-470a-9db7-d6f236469282"/>
        <port xsi:type="esdl:OutPort" id="f81c96d7-922b-49fe-bc1b-cd5ee9f1e220" name="Out" connectedTo="46c18416-82cd-47df-b705-041777350ec4 0d109a8a-9f8c-412c-9e87-518b421bc8cb"/>
        <geometry xsi:type="esdl:Point" lat="158307.9236336284" CRS="WGS84" lon="433217.5328955752"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.1186974053967162" name="lv_cable_trafo4_lvnetwork2_15_main_grid" id="22561b8b-3aeb-40d6-8f34-e29399ee7fcb" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="050f70d6-b04f-4969-bace-0746c7c78f1e" name="In" connectedTo="8306d141-22be-4faf-a2ae-d8ec6f2f4aae"/>
        <port xsi:type="esdl:OutPort" id="c9875618-7bb6-470a-9db7-d6f236469282" name="Out" connectedTo="e06aacd4-302b-4b77-8c56-ddf5aed1f871"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158305.83510148196" CRS="WGS84" lon="433217.8891429175"/>
          <point xsi:type="esdl:Point" lat="158307.9236336284" CRS="WGS84" lon="433217.5328955752"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.902652356980004" name="lv_cable_trafo4_lvnetwork2_to_home_9_arch5" id="01d9adcf-b92e-47c6-b820-e96f98b7f837" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="46c18416-82cd-47df-b705-041777350ec4" name="In" connectedTo="f81c96d7-922b-49fe-bc1b-cd5ee9f1e220"/>
        <port xsi:type="esdl:OutPort" id="dd615ead-0e6b-4f2a-ace1-b8beb15a93e1" name="Out" connectedTo="016cb473-87fb-491b-9d9b-5f1632635d02"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158306.415" CRS="WGS84" lon="433208.759"/>
          <point xsi:type="esdl:Point" lat="158307.9236336284" CRS="WGS84" lon="433217.5328955752"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome572" id="0c7c2103-e5ac-4c2b-9cde-80538aaa7513">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="070cb474-57c9-4114-b917-4dedce43c588" name="In" connectedTo="3311c01a-9ca0-4c88-a54d-411bc2eee497"/>
          <port xsi:type="esdl:OutPort" id="a1b9e681-b258-4bda-92a1-ed6802a38096" name="Out" connectedTo="ed2ec912-0270-4a06-bc7a-b04a0fc6e2e6"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="5ccf3b46-fd1e-452d-a400-1b5738a70add" name="In" connectedTo="72a9d89b-d8eb-4cd2-b0cd-d950a2fcbc44"/>
          <port xsi:type="esdl:OutPort" id="bab329c6-34d3-4308-9805-a14f1b37ba85" name="Out" connectedTo="1d35d9b9-3cf4-4eb8-85ba-caac8f2be850"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="047d7d88-6fdf-450a-b6ec-2ff2959db6e5" name="In" connectedTo="37e35746-bc65-47bb-9b35-4530c7a07542"/>
          <port xsi:type="esdl:OutPort" id="1965469b-c67b-4afb-9624-886c05015d7a" name="Out" connectedTo="ce014adb-b33f-458f-869e-c9c945007db1"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b966c1b7-28a6-4c0b-b579-a0342aa4523d" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="ed2ec912-0270-4a06-bc7a-b04a0fc6e2e6" name="In_Ph1" connectedTo="a1b9e681-b258-4bda-92a1-ed6802a38096"/>
          <port xsi:type="esdl:InPort" id="1d35d9b9-3cf4-4eb8-85ba-caac8f2be850" name="In_Ph2" connectedTo="bab329c6-34d3-4308-9805-a14f1b37ba85"/>
          <port xsi:type="esdl:InPort" id="ce014adb-b33f-458f-869e-c9c945007db1" name="In_Ph3" connectedTo="1965469b-c67b-4afb-9624-886c05015d7a"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome572" id="f1c552f2-c24b-495b-9131-2bcaff646e64">
          <port xsi:type="esdl:InPort" id="016cb473-87fb-491b-9d9b-5f1632635d02" name="In" connectedTo="dd615ead-0e6b-4f2a-ace1-b8beb15a93e1"/>
          <port xsi:type="esdl:OutPort" id="3311c01a-9ca0-4c88-a54d-411bc2eee497" name="OutPh1" connectedTo="070cb474-57c9-4114-b917-4dedce43c588"/>
          <port xsi:type="esdl:OutPort" id="72a9d89b-d8eb-4cd2-b0cd-d950a2fcbc44" name="OutPh2" connectedTo="5ccf3b46-fd1e-452d-a400-1b5738a70add"/>
          <port xsi:type="esdl:OutPort" id="37e35746-bc65-47bb-9b35-4530c7a07542" name="OutPh3" connectedTo="047d7d88-6fdf-450a-b6ec-2ff2959db6e5"/>
          <geometry xsi:type="esdl:Point" lat="158306.415" lon="433208.759"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_16" id="792d3d83-c27f-4f1e-be3c-903a7b2e94e0">
        <port xsi:type="esdl:InPort" id="0c51296e-ba41-4764-a39a-386dd7502552" name="In" connectedTo="4116357e-0e10-4a16-a16a-6f3b67dcdcb8"/>
        <port xsi:type="esdl:OutPort" id="8ca1920b-4386-451e-923f-5c85f8490e18" name="Out" connectedTo="5ab78f76-eb03-4577-9588-475e977d30f2 4dd37d84-ce86-44ca-8d5a-0a7181f939e8"/>
        <geometry xsi:type="esdl:Point" lat="158311.5144286094" CRS="WGS84" lon="433216.92136438476"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="3.642496293457564" name="lv_cable_trafo4_lvnetwork2_16_main_grid" id="7c850a01-e046-43ce-ac4b-cda443db57a8" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="0d109a8a-9f8c-412c-9e87-518b421bc8cb" name="In" connectedTo="f81c96d7-922b-49fe-bc1b-cd5ee9f1e220"/>
        <port xsi:type="esdl:OutPort" id="4116357e-0e10-4a16-a16a-6f3b67dcdcb8" name="Out" connectedTo="0c51296e-ba41-4764-a39a-386dd7502552"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158307.9236336284" CRS="WGS84" lon="433217.5328955752"/>
          <point xsi:type="esdl:Point" lat="158308.656" CRS="WGS84" lon="433217.408"/>
          <point xsi:type="esdl:Point" lat="158311.012" CRS="WGS84" lon="433217.007"/>
          <point xsi:type="esdl:Point" lat="158311.5144286094" CRS="WGS84" lon="433216.92136438476"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.2593222587228865" name="lv_cable_trafo4_lvnetwork2_to_home_11_arch5" id="5990ea44-adfd-4dc6-aa72-f8c5a03e2a5a" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="5ab78f76-eb03-4577-9588-475e977d30f2" name="In" connectedTo="8ca1920b-4386-451e-923f-5c85f8490e18"/>
        <port xsi:type="esdl:OutPort" id="62f0d109-0320-450a-820b-c29d89f20918" name="Out" connectedTo="1aef3466-f740-408b-bcb1-dda32f55c50b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158311.558" CRS="WGS84" lon="433217.177"/>
          <point xsi:type="esdl:Point" lat="158311.5144286094" CRS="WGS84" lon="433216.92136438476"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome574" id="10fad44e-98a2-4e66-af83-bc307ebf6aa8">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="3584ac13-30d3-43d5-831c-15d7849fb464" name="In" connectedTo="97086ea8-b640-44f2-bfd6-6f30c610202c"/>
          <port xsi:type="esdl:OutPort" id="aca8d8ed-7c0f-4631-979b-e2ed94a1b2ce" name="Out" connectedTo="654c418d-d711-4fae-afab-0665753ccf31"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="a30e7aef-112f-4622-b19c-7680175c0576" name="In" connectedTo="400229a1-2df9-4654-aeac-83cf30d45081"/>
          <port xsi:type="esdl:OutPort" id="77677aa4-ae14-4168-8d9a-cae225537630" name="Out" connectedTo="3a6942e3-0613-407d-83a8-2282c48c6e71"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="6a39babc-86f1-40e4-8533-b787c206435e" name="In" connectedTo="fdbbc7c0-8d26-439a-8a1e-0352a57d63ec"/>
          <port xsi:type="esdl:OutPort" id="e6cd59c6-95ba-487a-adfc-3945bbc4140f" name="Out" connectedTo="1ad15617-be3b-4278-a0e8-11b3f1e1636c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="783d317a-4e8e-4c67-af1d-209eb53426bd" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="654c418d-d711-4fae-afab-0665753ccf31" name="In_Ph1" connectedTo="aca8d8ed-7c0f-4631-979b-e2ed94a1b2ce"/>
          <port xsi:type="esdl:InPort" id="3a6942e3-0613-407d-83a8-2282c48c6e71" name="In_Ph2" connectedTo="77677aa4-ae14-4168-8d9a-cae225537630"/>
          <port xsi:type="esdl:InPort" id="1ad15617-be3b-4278-a0e8-11b3f1e1636c" name="In_Ph3" connectedTo="e6cd59c6-95ba-487a-adfc-3945bbc4140f"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome574" id="7c7e4bc0-9307-4c5b-bbd5-8634c15cd9b8">
          <port xsi:type="esdl:InPort" id="1aef3466-f740-408b-bcb1-dda32f55c50b" name="In" connectedTo="62f0d109-0320-450a-820b-c29d89f20918"/>
          <port xsi:type="esdl:OutPort" id="97086ea8-b640-44f2-bfd6-6f30c610202c" name="OutPh1" connectedTo="3584ac13-30d3-43d5-831c-15d7849fb464"/>
          <port xsi:type="esdl:OutPort" id="400229a1-2df9-4654-aeac-83cf30d45081" name="OutPh2" connectedTo="a30e7aef-112f-4622-b19c-7680175c0576"/>
          <port xsi:type="esdl:OutPort" id="fdbbc7c0-8d26-439a-8a1e-0352a57d63ec" name="OutPh3" connectedTo="6a39babc-86f1-40e4-8533-b787c206435e"/>
          <geometry xsi:type="esdl:Point" lat="158311.558" lon="433217.177"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_17" id="704af9a7-a5ce-4d7f-9a42-3d0518ac3626">
        <port xsi:type="esdl:InPort" id="1dcb399b-c01b-4e7e-a764-ee5f8ed1cdba" name="In" connectedTo="0f4b8ec5-365c-4654-a073-0f32badbc552"/>
        <port xsi:type="esdl:OutPort" id="7d191a73-033d-47eb-9ed0-b308ce5201a6" name="Out" connectedTo="522e8f85-257f-485d-a8f8-f50bbaafe89a 8e5a4a88-d4c7-4254-ba90-51fcd3950e01"/>
        <geometry xsi:type="esdl:Point" lat="158312.14159770205" CRS="WGS84" lon="433216.81440968136"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.6362235293953813" name="lv_cable_trafo4_lvnetwork2_17_main_grid" id="9d2c6f75-8d68-4c0c-b930-feffeb98f202" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="4dd37d84-ce86-44ca-8d5a-0a7181f939e8" name="In" connectedTo="8ca1920b-4386-451e-923f-5c85f8490e18"/>
        <port xsi:type="esdl:OutPort" id="0f4b8ec5-365c-4654-a073-0f32badbc552" name="Out" connectedTo="1dcb399b-c01b-4e7e-a764-ee5f8ed1cdba"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158311.5144286094" CRS="WGS84" lon="433216.92136438476"/>
          <point xsi:type="esdl:Point" lat="158312.14159770205" CRS="WGS84" lon="433216.81440968136"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.970682058000916" name="lv_cable_trafo4_lvnetwork2_to_home_12_arch5" id="efae6c0a-1b8e-440c-9a34-6ee98dc06f33" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="522e8f85-257f-485d-a8f8-f50bbaafe89a" name="In" connectedTo="7d191a73-033d-47eb-9ed0-b308ce5201a6"/>
        <port xsi:type="esdl:OutPort" id="b1fd3ed1-edc3-4a7e-8bad-c340891c7fe2" name="Out" connectedTo="12493203-6585-4bfd-aefb-69c5f6bfe413"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158310.63" CRS="WGS84" lon="433207.972"/>
          <point xsi:type="esdl:Point" lat="158312.14159770205" CRS="WGS84" lon="433216.81440968136"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome575" id="140b1ced-9431-4d1e-a38b-56561b066174">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="6d70bbe7-f6f7-4263-b5aa-f0365e11b508" name="In" connectedTo="4a56b00d-0a18-44f3-9e34-7a6a73ee2413"/>
          <port xsi:type="esdl:OutPort" id="8e940771-0f92-466f-ae37-652df1e9da07" name="Out" connectedTo="3899a7ea-f13f-4b03-986d-514e762fbe43"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="4a3c47fd-1687-40d1-9a17-777ace986914" name="In" connectedTo="8b803bfa-b3d2-4f2b-a1f9-8f759a83e7da"/>
          <port xsi:type="esdl:OutPort" id="304173cf-4828-4ff7-ba6e-bd203d8a4e5e" name="Out" connectedTo="7cdc7d24-e06e-45e5-a253-23cb279ae038"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="085b7232-57b8-43bd-9165-b665fa270945" name="In" connectedTo="e414f786-893b-48c0-84f0-383236c6a2b3"/>
          <port xsi:type="esdl:OutPort" id="47ab37da-d5f0-4a41-a735-35e21c3bf4c7" name="Out" connectedTo="4624ae14-81a2-4662-b618-8194501ce1d7"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="86b81396-45e2-4e82-867f-30e3d8338726" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="3899a7ea-f13f-4b03-986d-514e762fbe43" name="In_Ph1" connectedTo="8e940771-0f92-466f-ae37-652df1e9da07"/>
          <port xsi:type="esdl:InPort" id="7cdc7d24-e06e-45e5-a253-23cb279ae038" name="In_Ph2" connectedTo="304173cf-4828-4ff7-ba6e-bd203d8a4e5e"/>
          <port xsi:type="esdl:InPort" id="4624ae14-81a2-4662-b618-8194501ce1d7" name="In_Ph3" connectedTo="47ab37da-d5f0-4a41-a735-35e21c3bf4c7"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome575" id="2a843224-1ff7-4dc6-8b5f-91685e9cc744">
          <port xsi:type="esdl:InPort" id="12493203-6585-4bfd-aefb-69c5f6bfe413" name="In" connectedTo="b1fd3ed1-edc3-4a7e-8bad-c340891c7fe2"/>
          <port xsi:type="esdl:OutPort" id="4a56b00d-0a18-44f3-9e34-7a6a73ee2413" name="OutPh1" connectedTo="6d70bbe7-f6f7-4263-b5aa-f0365e11b508"/>
          <port xsi:type="esdl:OutPort" id="8b803bfa-b3d2-4f2b-a1f9-8f759a83e7da" name="OutPh2" connectedTo="4a3c47fd-1687-40d1-9a17-777ace986914"/>
          <port xsi:type="esdl:OutPort" id="e414f786-893b-48c0-84f0-383236c6a2b3" name="OutPh3" connectedTo="085b7232-57b8-43bd-9165-b665fa270945"/>
          <geometry xsi:type="esdl:Point" lat="158310.63" lon="433207.972"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_18" id="dc0ab071-6ddd-44f2-b7a3-11d5c0c5e4fc">
        <port xsi:type="esdl:InPort" id="22ba3bdb-33f8-4fb8-b8e8-26277e0ebd03" name="In" connectedTo="479c3cd8-23f6-47bb-b23f-d99b477855b4"/>
        <port xsi:type="esdl:OutPort" id="a2da096c-5450-4903-8ee0-48046cb376c5" name="Out" connectedTo="9d2e7a88-d997-4c62-9f1e-db0f04478ad0 aa511ac9-33dd-4f21-96d7-7be83751ee23 463b9b7c-02df-46f6-bf42-faed3568d1e4"/>
        <geometry xsi:type="esdl:Point" lat="158316.62489759203" CRS="WGS84" lon="433216.0499204467"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.548013632273428" name="lv_cable_trafo4_lvnetwork2_18_main_grid" id="1a7f4f4d-4bb4-4f1f-9de2-b3ea08012f6b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="8e5a4a88-d4c7-4254-ba90-51fcd3950e01" name="In" connectedTo="7d191a73-033d-47eb-9ed0-b308ce5201a6"/>
        <port xsi:type="esdl:OutPort" id="479c3cd8-23f6-47bb-b23f-d99b477855b4" name="Out" connectedTo="22ba3bdb-33f8-4fb8-b8e8-26277e0ebd03"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158312.14159770205" CRS="WGS84" lon="433216.81440968136"/>
          <point xsi:type="esdl:Point" lat="158314.498" CRS="WGS84" lon="433216.413"/>
          <point xsi:type="esdl:Point" lat="158314.642" CRS="WGS84" lon="433216.388"/>
          <point xsi:type="esdl:Point" lat="158316.114" CRS="WGS84" lon="433216.137"/>
          <point xsi:type="esdl:Point" lat="158316.62489759203" CRS="WGS84" lon="433216.0499204467"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.20296502624074755" name="lv_cable_trafo4_lvnetwork2_to_home_13_arch5" id="25af1f37-ff25-4032-816c-a24e6b73c66f" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="9d2e7a88-d997-4c62-9f1e-db0f04478ad0" name="In" connectedTo="a2da096c-5450-4903-8ee0-48046cb376c5"/>
        <port xsi:type="esdl:OutPort" id="e735d86f-dc33-426c-8b33-f2a04c5e44a9" name="Out" connectedTo="7a5345e9-c7f5-41f9-b1c9-7b89024dd336"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158316.659" CRS="WGS84" lon="433216.25"/>
          <point xsi:type="esdl:Point" lat="158316.62489759203" CRS="WGS84" lon="433216.0499204467"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome576" id="4f6c4465-0965-453b-a268-7dce16b50189">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="b48055e0-c12c-4c24-9448-7636df5ffd32" name="In" connectedTo="1b7c1963-1009-4a16-9e5c-007fe8e817c2"/>
          <port xsi:type="esdl:OutPort" id="24b954af-b757-45be-97ce-9ba0b77c3a07" name="Out" connectedTo="5033517e-9867-4160-a601-f5a5c723f828"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="fe575f3d-3888-4bcc-873e-17e00c261346" name="In" connectedTo="500d04be-c4ea-4f7c-a5a3-593a7d3b2a83"/>
          <port xsi:type="esdl:OutPort" id="45de4269-bcdc-46e3-a80b-0d26f35d4e10" name="Out" connectedTo="6b762999-a093-4d8b-9c49-464eda9a6fb9"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="c7bbd229-e4ff-415f-8444-03fe9712c0ea" name="In" connectedTo="bbb83ea8-bda1-41ca-892d-44e8f4180eb4"/>
          <port xsi:type="esdl:OutPort" id="fbc104aa-36cd-43ab-bc44-7143a9c74034" name="Out" connectedTo="d5049daa-bb6b-4c05-a5ec-64179aebfccd"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b3e5879e-d85e-421a-bb04-453ff6f93375" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="5033517e-9867-4160-a601-f5a5c723f828" name="In_Ph1" connectedTo="24b954af-b757-45be-97ce-9ba0b77c3a07"/>
          <port xsi:type="esdl:InPort" id="6b762999-a093-4d8b-9c49-464eda9a6fb9" name="In_Ph2" connectedTo="45de4269-bcdc-46e3-a80b-0d26f35d4e10"/>
          <port xsi:type="esdl:InPort" id="d5049daa-bb6b-4c05-a5ec-64179aebfccd" name="In_Ph3" connectedTo="fbc104aa-36cd-43ab-bc44-7143a9c74034"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome576" id="ecb7ac94-fd15-4e45-904e-636c9101e90f">
          <port xsi:type="esdl:InPort" id="7a5345e9-c7f5-41f9-b1c9-7b89024dd336" name="In" connectedTo="e735d86f-dc33-426c-8b33-f2a04c5e44a9"/>
          <port xsi:type="esdl:OutPort" id="1b7c1963-1009-4a16-9e5c-007fe8e817c2" name="OutPh1" connectedTo="b48055e0-c12c-4c24-9448-7636df5ffd32"/>
          <port xsi:type="esdl:OutPort" id="500d04be-c4ea-4f7c-a5a3-593a7d3b2a83" name="OutPh2" connectedTo="fe575f3d-3888-4bcc-873e-17e00c261346"/>
          <port xsi:type="esdl:OutPort" id="bbb83ea8-bda1-41ca-892d-44e8f4180eb4" name="OutPh3" connectedTo="c7bbd229-e4ff-415f-8444-03fe9712c0ea"/>
          <geometry xsi:type="esdl:Point" lat="158316.659" lon="433216.25"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.20296502624074755" name="lv_cable_trafo4_lvnetwork2_to_home_15_arch5" id="31d7cc15-22eb-4dda-a12e-0327a558c615" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="aa511ac9-33dd-4f21-96d7-7be83751ee23" name="In" connectedTo="a2da096c-5450-4903-8ee0-48046cb376c5"/>
        <port xsi:type="esdl:OutPort" id="a75f37d6-f17c-4384-96d2-fd0aa8281300" name="Out" connectedTo="920ef242-0ea0-4c8b-bfc8-ed4b170e2c67"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158316.659" CRS="WGS84" lon="433216.25"/>
          <point xsi:type="esdl:Point" lat="158316.62489759203" CRS="WGS84" lon="433216.0499204467"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome578" id="38dea48d-f3af-4a9f-96f4-44ed67c97110">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="673fd798-af79-403d-9fab-1f63c3aadc4d" name="In" connectedTo="265270e9-780b-4ffe-9433-f9723e06f7f1"/>
          <port xsi:type="esdl:OutPort" id="aa0c5737-2cdc-44f2-a21e-0f748379740b" name="Out" connectedTo="eab33c6c-f07f-480c-8cc5-c615b50b8910"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="06c4107c-6da3-486c-afe8-dfeacdcaf16c" name="In" connectedTo="f90eebce-13ff-42f7-acbd-0ad2fd47e740"/>
          <port xsi:type="esdl:OutPort" id="008e85d1-d1fa-436c-965f-75bc9601e444" name="Out" connectedTo="ae37e700-a287-481b-b6e5-a250b8f756d9"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="82816a37-2c20-4b36-adc7-b67714294a90" name="In" connectedTo="8a8c254c-6fe1-46f7-b052-b0ba67251c90"/>
          <port xsi:type="esdl:OutPort" id="6c0f7b6a-478c-48fb-9e3c-57f115a4fcf7" name="Out" connectedTo="ea2c06af-02f2-4a40-9bd8-93aeb67f89d6"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="2b419879-ca65-4ca5-a915-2ce9ad30e2bf" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="eab33c6c-f07f-480c-8cc5-c615b50b8910" name="In_Ph1" connectedTo="aa0c5737-2cdc-44f2-a21e-0f748379740b"/>
          <port xsi:type="esdl:InPort" id="ae37e700-a287-481b-b6e5-a250b8f756d9" name="In_Ph2" connectedTo="008e85d1-d1fa-436c-965f-75bc9601e444"/>
          <port xsi:type="esdl:InPort" id="ea2c06af-02f2-4a40-9bd8-93aeb67f89d6" name="In_Ph3" connectedTo="6c0f7b6a-478c-48fb-9e3c-57f115a4fcf7"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome578" id="8c8fe43f-2c58-433d-b978-0c8c6a3b0ee0">
          <port xsi:type="esdl:InPort" id="920ef242-0ea0-4c8b-bfc8-ed4b170e2c67" name="In" connectedTo="a75f37d6-f17c-4384-96d2-fd0aa8281300"/>
          <port xsi:type="esdl:OutPort" id="265270e9-780b-4ffe-9433-f9723e06f7f1" name="OutPh1" connectedTo="673fd798-af79-403d-9fab-1f63c3aadc4d"/>
          <port xsi:type="esdl:OutPort" id="f90eebce-13ff-42f7-acbd-0ad2fd47e740" name="OutPh2" connectedTo="06c4107c-6da3-486c-afe8-dfeacdcaf16c"/>
          <port xsi:type="esdl:OutPort" id="8a8c254c-6fe1-46f7-b052-b0ba67251c90" name="OutPh3" connectedTo="82816a37-2c20-4b36-adc7-b67714294a90"/>
          <geometry xsi:type="esdl:Point" lat="158316.659" lon="433216.25"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_19" id="3998a82b-a9c6-41a5-ba63-a6330069b04f">
        <port xsi:type="esdl:InPort" id="fff65176-7938-40b5-9f4e-5c9efe4a1622" name="In" connectedTo="04dbc4a3-f27f-4087-b442-1e88f72a5a8e"/>
        <port xsi:type="esdl:OutPort" id="e4664079-fbfc-411a-9119-389c4b1753e7" name="Out" connectedTo="54fe093f-5f5d-4ee1-a639-983aa4452ebb f41e97f0-344c-4fee-bdb4-5cca83d85059"/>
        <geometry xsi:type="esdl:Point" lat="158320.85828686942" CRS="WGS84" lon="433215.32824034384"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.294462361159698" name="lv_cable_trafo4_lvnetwork2_19_main_grid" id="02088332-3e63-4790-b789-5dd8d8fa75f3" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="463b9b7c-02df-46f6-bf42-faed3568d1e4" name="In" connectedTo="a2da096c-5450-4903-8ee0-48046cb376c5"/>
        <port xsi:type="esdl:OutPort" id="04dbc4a3-f27f-4087-b442-1e88f72a5a8e" name="Out" connectedTo="fff65176-7938-40b5-9f4e-5c9efe4a1622"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158316.62489759203" CRS="WGS84" lon="433216.0499204467"/>
          <point xsi:type="esdl:Point" lat="158320.707" CRS="WGS84" lon="433215.354"/>
          <point xsi:type="esdl:Point" lat="158320.85828686942" CRS="WGS84" lon="433215.32824034384"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="9.21802764821811" name="lv_cable_trafo4_lvnetwork2_to_home_14_arch5" id="3713e0c7-d733-4343-83c1-eb4cd88f0ee3" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="54fe093f-5f5d-4ee1-a639-983aa4452ebb" name="In" connectedTo="e4664079-fbfc-411a-9119-389c4b1753e7"/>
        <port xsi:type="esdl:OutPort" id="553ef095-4019-492a-8eee-697c1d48712c" name="Out" connectedTo="436fa540-cb67-4877-87e1-ae1598dae5a3"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158319.311" CRS="WGS84" lon="433206.241"/>
          <point xsi:type="esdl:Point" lat="158320.85828686942" CRS="WGS84" lon="433215.32824034384"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="3xhome577" id="cad88feb-c613-4924-a94e-29ecae3fbb8f">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="d6400c00-c2a6-4fb0-9020-03b64e1935b0" name="In" connectedTo="4e1acdc3-5fe1-49b1-ba56-77d48152d5e7"/>
          <port xsi:type="esdl:OutPort" id="f51023a3-8b52-457b-997d-79d48c5ca467" name="Out" connectedTo="a9208a91-f397-4d85-a02a-733b4a61c010"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="7d45dbad-ed79-4993-a075-8205a9ee6750" name="In" connectedTo="dc2b82db-8993-4c84-81d1-a9866207a4ab"/>
          <port xsi:type="esdl:OutPort" id="cfeb6631-06ba-4b1f-aa7a-78ee98176772" name="Out" connectedTo="b8b1a502-dbaa-442d-899a-8f0ad87d0640"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="eedc3257-b27d-4db6-86a9-2090182378d3" name="In" connectedTo="809277ad-9dba-406b-8982-82837a281849"/>
          <port xsi:type="esdl:OutPort" id="3ab7c42b-552a-4e07-a53e-6edb84ef888a" name="Out" connectedTo="ef33b938-0042-46f6-b615-08123748c436"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="e47888e0-735a-4436-b258-02ff79585dff" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="a9208a91-f397-4d85-a02a-733b4a61c010" name="In_Ph1" connectedTo="f51023a3-8b52-457b-997d-79d48c5ca467"/>
          <port xsi:type="esdl:InPort" id="b8b1a502-dbaa-442d-899a-8f0ad87d0640" name="In_Ph2" connectedTo="cfeb6631-06ba-4b1f-aa7a-78ee98176772"/>
          <port xsi:type="esdl:InPort" id="ef33b938-0042-46f6-b615-08123748c436" name="In_Ph3" connectedTo="3ab7c42b-552a-4e07-a53e-6edb84ef888a"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="3xhome577" id="9b2d33b0-9728-4163-9a5d-826974fba605">
          <port xsi:type="esdl:InPort" id="436fa540-cb67-4877-87e1-ae1598dae5a3" name="In" connectedTo="553ef095-4019-492a-8eee-697c1d48712c"/>
          <port xsi:type="esdl:OutPort" id="4e1acdc3-5fe1-49b1-ba56-77d48152d5e7" name="OutPh1" connectedTo="d6400c00-c2a6-4fb0-9020-03b64e1935b0"/>
          <port xsi:type="esdl:OutPort" id="dc2b82db-8993-4c84-81d1-a9866207a4ab" name="OutPh2" connectedTo="7d45dbad-ed79-4993-a075-8205a9ee6750"/>
          <port xsi:type="esdl:OutPort" id="809277ad-9dba-406b-8982-82837a281849" name="OutPh3" connectedTo="eedc3257-b27d-4db6-86a9-2090182378d3"/>
          <geometry xsi:type="esdl:Point" lat="158319.311" lon="433206.241"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork2_20" id="59020ecf-eac2-4dce-91fa-ec95ca012f18">
        <port xsi:type="esdl:InPort" id="7f0ac0cc-80f5-42cc-824a-ab41e3a56f37" name="In" connectedTo="f28fe74f-dde8-42e6-b135-0d8298408736"/>
        <port xsi:type="esdl:OutPort" id="09e754d9-aab3-4d7b-803e-0e83ef0cbf3a" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158322.409" CRS="WGS84" lon="433215.064"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.573065215652869" name="lv_cable_trafo4_lvnetwork2_20_main_grid" id="08572ee0-e910-4e8d-b484-74f7b57f3d18" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f41e97f0-344c-4fee-bdb4-5cca83d85059" name="In" connectedTo="e4664079-fbfc-411a-9119-389c4b1753e7"/>
        <port xsi:type="esdl:OutPort" id="f28fe74f-dde8-42e6-b135-0d8298408736" name="Out" connectedTo="7f0ac0cc-80f5-42cc-824a-ab41e3a56f37"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158320.85828686942" CRS="WGS84" lon="433215.32824034384"/>
          <point xsi:type="esdl:Point" lat="158322.409" CRS="WGS84" lon="433215.064"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo4_lvnetwork2" id="f6c04a9a-e71f-44dc-a258-a1eff5233e9e" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="45ca044f-f57c-442f-ba9e-6f406444cabd" name="Out" connectedTo="156b5737-a515-41ab-bdbc-5070472b5ae0"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo4_lvnetwork2" id="12182d92-1f1e-4820-b143-ca6ae8f7df30">
        <port xsi:type="esdl:InPort" id="156b5737-a515-41ab-bdbc-5070472b5ae0" name="In" connectedTo="45ca044f-f57c-442f-ba9e-6f406444cabd"/>
        <port xsi:type="esdl:OutPort" id="e5a5be21-1b76-4027-9a4a-4fb4d8582b22" name="Out" connectedTo="2a027d86-6b8c-4a1a-999c-91214c891dd2"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer27" id="e31d6247-9301-47b1-9a92-8b7f9fc0eb48" commissioningDate="1971-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="2a027d86-6b8c-4a1a-999c-91214c891dd2" name="In" connectedTo="e5a5be21-1b76-4027-9a4a-4fb4d8582b22"/>
        <port xsi:type="esdl:OutPort" id="6bc5d05a-4e6e-4e7e-bc54-4506815d5502" name="Out" connectedTo="55fc00c8-785b-4375-84da-927f3fa29f39"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint29" id="38e86393-69a0-44b5-a931-dd7d3ee15a8c">
        <port xsi:type="esdl:InPort" id="55fc00c8-785b-4375-84da-927f3fa29f39" name="In" connectedTo="6bc5d05a-4e6e-4e7e-bc54-4506815d5502"/>
        <port xsi:type="esdl:OutPort" id="dd03e995-3b79-4a24-8e08-95f175bed17d" name="Out" connectedTo="a57b3c7f-0216-4422-8ed1-0b949d064a24"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
