<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="4fdcaf52-62e2-483f-ab2d-e8e5dc3c5343" description="Autogenerated based on gis data trafo1_lvnetwork3" name="trafo1_lvnetwork3">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="2c419fee-3183-468d-ad24-1627b1f18d9f"/>
  <instance xsi:type="esdl:Instance" id="44bdf779-9780-4fa0-b19f-adc037aa9d70" name="Instance name">
    <area xsi:type="esdl:Area" id="11d15ec7-24fd-4dde-8f1d-aa7fe0762283" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo1_lvnetwork3_2" id="cb507d7a-87e1-44c4-ab3e-3f2870367842">
        <port xsi:type="esdl:InPort" id="f3047ab8-8b65-4fb4-a2e2-92e7265d391e" name="In" connectedTo="3069aa5e-41ed-49be-828f-4bceda0d001b"/>
        <port xsi:type="esdl:OutPort" id="f7566b58-71d5-47d7-87d7-1dbf82fe150a" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158190.84" CRS="WGS84" lon="433707.001"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="48.07428560564955" name="lv_cable_trafo1_lvnetwork3_2_main_grid" id="4f52d3f0-66e0-4e6a-9aee-a604b540ae8c" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="9554953c-fed6-4f89-97b9-ac805c281459" name="In" connectedTo="1004a0a2-6a8d-4c91-ac57-a0095a36f776"/>
        <port xsi:type="esdl:OutPort" id="3069aa5e-41ed-49be-828f-4bceda0d001b" name="Out" connectedTo="f3047ab8-8b65-4fb4-a2e2-92e7265d391e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158225.427" CRS="WGS84" lon="433710.414"/>
          <point xsi:type="esdl:Point" lat="158225.45587965" CRS="WGS84" lon="433710.612226342"/>
          <point xsi:type="esdl:Point" lat="158225.455235947" CRS="WGS84" lon="433710.812561419"/>
          <point xsi:type="esdl:Point" lat="158225.425082918" CRS="WGS84" lon="433711.010639852"/>
          <point xsi:type="esdl:Point" lat="158225.36607761" CRS="WGS84" lon="433711.202145437"/>
          <point xsi:type="esdl:Point" lat="158225.27950577" CRS="WGS84" lon="433711.382905191"/>
          <point xsi:type="esdl:Point" lat="158225.167253833" CRS="WGS84" lon="433711.54898029"/>
          <point xsi:type="esdl:Point" lat="158225.031767812" CRS="WGS84" lon="433711.696751893"/>
          <point xsi:type="esdl:Point" lat="158224.876" CRS="WGS84" lon="433711.823"/>
          <point xsi:type="esdl:Point" lat="158224.70769601" CRS="WGS84" lon="433711.904483417"/>
          <point xsi:type="esdl:Point" lat="158224.530254987" CRS="WGS84" lon="433711.948570654"/>
          <point xsi:type="esdl:Point" lat="158224.352178863" CRS="WGS84" lon="433711.953149309"/>
          <point xsi:type="esdl:Point" lat="158224.182" CRS="WGS84" lon="433711.918"/>
          <point xsi:type="esdl:Point" lat="158223.977248924" CRS="WGS84" lon="433711.859185872"/>
          <point xsi:type="esdl:Point" lat="158223.764239084" CRS="WGS84" lon="433711.850744232"/>
          <point xsi:type="esdl:Point" lat="158223.555166051" CRS="WGS84" lon="433711.893158396"/>
          <point xsi:type="esdl:Point" lat="158223.362" CRS="WGS84" lon="433711.984"/>
          <point xsi:type="esdl:Point" lat="158223.356" CRS="WGS84" lon="433711.987"/>
          <point xsi:type="esdl:Point" lat="158223.343" CRS="WGS84" lon="433711.993"/>
          <point xsi:type="esdl:Point" lat="158223.321" CRS="WGS84" lon="433712.016"/>
          <point xsi:type="esdl:Point" lat="158220.2" CRS="WGS84" lon="433714.89"/>
          <point xsi:type="esdl:Point" lat="158219.934" CRS="WGS84" lon="433714.659"/>
          <point xsi:type="esdl:Point" lat="158217.298" CRS="WGS84" lon="433712.389"/>
          <point xsi:type="esdl:Point" lat="158208.565" CRS="WGS84" lon="433705.314"/>
          <point xsi:type="esdl:Point" lat="158203.903" CRS="WGS84" lon="433701.543"/>
          <point xsi:type="esdl:Point" lat="158198.325" CRS="WGS84" lon="433708.255"/>
          <point xsi:type="esdl:Point" lat="158197.364" CRS="WGS84" lon="433707.456"/>
          <point xsi:type="esdl:Point" lat="158192.967" CRS="WGS84" lon="433703.803"/>
          <point xsi:type="esdl:Point" lat="158190.84" CRS="WGS84" lon="433707.001"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo1_lvnetwork3" id="eeb5306e-32f5-4bba-bc00-6f38d1c5b7fe" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="76e73980-9471-4d51-9c1d-670a44b95317" name="Out" connectedTo="99bcde59-62e3-4990-a556-25befe84fc2c"/>
        <geometry xsi:type="esdl:Point" lat="158228.036" CRS="WGS84" lon="433707.268"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo1_lvnetwork3" id="67c3cb36-7cda-4c98-8637-a352180439ac">
        <port xsi:type="esdl:InPort" id="99bcde59-62e3-4990-a556-25befe84fc2c" name="In" connectedTo="76e73980-9471-4d51-9c1d-670a44b95317"/>
        <port xsi:type="esdl:OutPort" id="dfa23c68-d1ef-4f04-ab6e-bb4ce0d1ddf9" name="Out" connectedTo="dc05f774-a727-4fcb-bb89-624d56a289f6"/>
        <geometry xsi:type="esdl:Point" lat="158228.036" CRS="WGS84" lon="433707.268"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer10" id="d1b7282c-ee6e-4e2f-aef3-5cbe04be4eb0" commissioningDate="1935-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="dc05f774-a727-4fcb-bb89-624d56a289f6" name="In" connectedTo="dfa23c68-d1ef-4f04-ab6e-bb4ce0d1ddf9"/>
        <port xsi:type="esdl:OutPort" id="a0b6db41-a1f5-458f-9223-601473b31dd5" name="Out" connectedTo="577536be-17d4-4bf8-89bb-4c798c9eb97e"/>
        <geometry xsi:type="esdl:Point" lat="158228.036" CRS="WGS84" lon="433707.268"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint12" id="b35cb8f5-9c27-4105-b446-554956016c53">
        <port xsi:type="esdl:InPort" id="577536be-17d4-4bf8-89bb-4c798c9eb97e" name="In" connectedTo="a0b6db41-a1f5-458f-9223-601473b31dd5"/>
        <port xsi:type="esdl:OutPort" id="1004a0a2-6a8d-4c91-ac57-a0095a36f776" name="Out" connectedTo="9554953c-fed6-4f89-97b9-ac805c281459"/>
        <geometry xsi:type="esdl:Point" lat="158228.036" CRS="WGS84" lon="433707.268"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
