<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="f5eb99cd-4c58-4536-ba0e-2af7ae7fdd4a" description="Autogenerated based on gis data trafo2_lvnetwork5" name="trafo2_lvnetwork5">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="1cbac74e-803a-4b00-a7e8-06752d8ad02e"/>
  <instance xsi:type="esdl:Instance" id="996e6b32-f863-4575-b44a-7f4240ee0789" name="Instance name">
    <area xsi:type="esdl:Area" id="2634bd1b-e906-4af4-94a8-6f10e6d428fb" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_2" id="4dc16316-7de5-4ae5-b8e8-3e1cedb3e992">
        <port xsi:type="esdl:InPort" id="67734958-2fa4-40c4-899e-b7dc6bc362ba" name="In" connectedTo="8158f7e1-3e16-48b0-bcee-25a9f9a49c7c"/>
        <port xsi:type="esdl:OutPort" id="8c3adc25-f5be-4cc8-a801-69b0c130649a" name="Out" connectedTo="0e069847-cc8c-4442-8b24-11e0783847a8 f8d765f8-2edf-4f48-b366-6ec520564d3a"/>
        <geometry xsi:type="esdl:Point" lat="158351.06616151377" CRS="WGS84" lon="433448.71281287377"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="35.443993646489446" name="lv_cable_trafo2_lvnetwork5_2_main_grid" id="0c9435b4-72fd-4709-9a03-aa26105b21f9" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="239ac168-e349-4135-bebe-d1f5adff34f3" name="In" connectedTo="1fab438c-6a01-4b44-a0a8-7134058fbcf4"/>
        <port xsi:type="esdl:OutPort" id="8158f7e1-3e16-48b0-bcee-25a9f9a49c7c" name="Out" connectedTo="67734958-2fa4-40c4-899e-b7dc6bc362ba"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158330.093" CRS="WGS84" lon="433444.778"/>
          <point xsi:type="esdl:Point" lat="158328.742" CRS="WGS84" lon="433446.114"/>
          <point xsi:type="esdl:Point" lat="158337.616" CRS="WGS84" lon="433459.665"/>
          <point xsi:type="esdl:Point" lat="158341.536" CRS="WGS84" lon="433456.384"/>
          <point xsi:type="esdl:Point" lat="158351.06616151377" CRS="WGS84" lon="433448.71281287377"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.726851407081457" name="lv_cable_trafo2_lvnetwork5_to_home_11_arch6" id="9fb44bc7-c853-46cd-944a-8f7f5f1d69d4" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="0e069847-cc8c-4442-8b24-11e0783847a8" name="In" connectedTo="8c3adc25-f5be-4cc8-a801-69b0c130649a"/>
        <port xsi:type="esdl:OutPort" id="efe98a23-0bf9-460c-9d19-b74008da9ee3" name="Out" connectedTo="cfd8b2c2-e675-404a-a886-b88b395de66f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158352.776" CRS="WGS84" lon="433450.837"/>
          <point xsi:type="esdl:Point" lat="158351.06616151377" CRS="WGS84" lon="433448.71281287377"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome528" id="36df9327-c4cd-4c3d-b683-f7eeef2239ba">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="a31730e9-e8e0-4445-9d3a-a396147ac2d4" name="In" connectedTo="ed52695f-e290-44a1-963b-b900fdbdf1d2"/>
          <port xsi:type="esdl:OutPort" id="198b5193-a4d6-4088-8c55-e02a7a4f9855" name="Out" connectedTo="3def284b-3a23-4b2e-8eb7-ea2cd896d380"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="14f0173c-9b94-45cf-af5c-e11f4c7896e5" name="In" connectedTo="6f7e7f0d-c79d-43e6-8e8c-0a5fb62a401b"/>
          <port xsi:type="esdl:OutPort" id="8aba43b9-4899-4bad-b794-c1f81a7d3d8d" name="Out" connectedTo="fcb055c6-bed2-45aa-86eb-02826d667ae6"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="0e568f01-aed3-4335-9c30-337f172d8573" name="In" connectedTo="e56c9b6a-3a73-4ce5-a78d-9338f4f5e8ae"/>
          <port xsi:type="esdl:OutPort" id="c8bdb358-1666-4d90-ade6-ada016d43ea4" name="Out" connectedTo="81d316c2-7398-47d3-9aad-a35d8e084417"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b306bc8d-6b81-4640-9b75-6ad13412d69a" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="3def284b-3a23-4b2e-8eb7-ea2cd896d380" name="In_Ph1" connectedTo="198b5193-a4d6-4088-8c55-e02a7a4f9855"/>
          <port xsi:type="esdl:InPort" id="fcb055c6-bed2-45aa-86eb-02826d667ae6" name="In_Ph2" connectedTo="8aba43b9-4899-4bad-b794-c1f81a7d3d8d"/>
          <port xsi:type="esdl:InPort" id="81d316c2-7398-47d3-9aad-a35d8e084417" name="In_Ph3" connectedTo="c8bdb358-1666-4d90-ade6-ada016d43ea4"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome528" id="819ceaf8-1f4d-4557-a69a-ceda6ad82e49">
          <port xsi:type="esdl:InPort" id="cfd8b2c2-e675-404a-a886-b88b395de66f" name="In" connectedTo="efe98a23-0bf9-460c-9d19-b74008da9ee3"/>
          <port xsi:type="esdl:OutPort" id="ed52695f-e290-44a1-963b-b900fdbdf1d2" name="OutPh1" connectedTo="a31730e9-e8e0-4445-9d3a-a396147ac2d4"/>
          <port xsi:type="esdl:OutPort" id="6f7e7f0d-c79d-43e6-8e8c-0a5fb62a401b" name="OutPh2" connectedTo="14f0173c-9b94-45cf-af5c-e11f4c7896e5"/>
          <port xsi:type="esdl:OutPort" id="e56c9b6a-3a73-4ce5-a78d-9338f4f5e8ae" name="OutPh3" connectedTo="0e568f01-aed3-4335-9c30-337f172d8573"/>
          <geometry xsi:type="esdl:Point" lat="158352.776" lon="433450.837"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_3" id="e668958b-8975-4bf2-bbba-59d65c0c448a">
        <port xsi:type="esdl:InPort" id="fa4c9abf-c7bb-412b-ab8a-9d2ae3d4f99a" name="In" connectedTo="ccf717b2-3b4d-4d60-9d1a-bf45c2926adb"/>
        <port xsi:type="esdl:OutPort" id="dae269d8-8a86-4dff-8025-467be59822c3" name="Out" connectedTo="6b2ccdc3-c51e-4c8a-b4c5-681540293b01 d3b7b110-0d48-44a8-a57f-be3e50dcc250"/>
        <geometry xsi:type="esdl:Point" lat="158375.8485760547" CRS="WGS84" lon="433475.25186424155"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="51.45644700627038" name="lv_cable_trafo2_lvnetwork5_3_main_grid" id="259743f8-a6e6-4dbf-9aa0-d913e63bc96f" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f8d765f8-2edf-4f48-b366-6ec520564d3a" name="In" connectedTo="8c3adc25-f5be-4cc8-a801-69b0c130649a"/>
        <port xsi:type="esdl:OutPort" id="ccf717b2-3b4d-4d60-9d1a-bf45c2926adb" name="Out" connectedTo="fa4c9abf-c7bb-412b-ab8a-9d2ae3d4f99a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158351.06616151377" CRS="WGS84" lon="433448.71281287377"/>
          <point xsi:type="esdl:Point" lat="158358.38" CRS="WGS84" lon="433442.887"/>
          <point xsi:type="esdl:Point" lat="158361.505" CRS="WGS84" lon="433440.4"/>
          <point xsi:type="esdl:Point" lat="158367.241" CRS="WGS84" lon="433451.168"/>
          <point xsi:type="esdl:Point" lat="158370.548" CRS="WGS84" lon="433457.377"/>
          <point xsi:type="esdl:Point" lat="158371.609" CRS="WGS84" lon="433459.628"/>
          <point xsi:type="esdl:Point" lat="158372.384" CRS="WGS84" lon="433461.29"/>
          <point xsi:type="esdl:Point" lat="158373.12" CRS="WGS84" lon="433462.882"/>
          <point xsi:type="esdl:Point" lat="158373.733" CRS="WGS84" lon="433464.655"/>
          <point xsi:type="esdl:Point" lat="158373.771" CRS="WGS84" lon="433464.766"/>
          <point xsi:type="esdl:Point" lat="158374.161" CRS="WGS84" lon="433465.421"/>
          <point xsi:type="esdl:Point" lat="158374.342" CRS="WGS84" lon="433465.725"/>
          <point xsi:type="esdl:Point" lat="158375.503" CRS="WGS84" lon="433470.062"/>
          <point xsi:type="esdl:Point" lat="158375.768" CRS="WGS84" lon="433474.252"/>
          <point xsi:type="esdl:Point" lat="158375.792" CRS="WGS84" lon="433474.554"/>
          <point xsi:type="esdl:Point" lat="158375.8485760547" CRS="WGS84" lon="433475.25186424155"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.283583739137075" name="lv_cable_trafo2_lvnetwork5_to_home_4_arch6" id="a5a294f6-4188-4e51-a3c3-bb54c2c2f00b" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="6b2ccdc3-c51e-4c8a-b4c5-681540293b01" name="In" connectedTo="dae269d8-8a86-4dff-8025-467be59822c3"/>
        <port xsi:type="esdl:OutPort" id="33730093-4aef-40dd-8241-6451ec4cb184" name="Out" connectedTo="93db6b69-e9af-4beb-88ad-4f405fefbaa5"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158371.579" CRS="WGS84" lon="433475.598"/>
          <point xsi:type="esdl:Point" lat="158375.8485760547" CRS="WGS84" lon="433475.25186424155"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome521" id="74fcc867-e124-4e14-9df3-41533510600f">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="30ddad0b-cb3c-4331-8313-d4d42d64b93d" name="In" connectedTo="79e22e55-73ca-4f73-a4b2-8a82049d7237"/>
          <port xsi:type="esdl:OutPort" id="21f1123a-9b73-4008-8ad9-6146ea17d8e0" name="Out" connectedTo="53c1e548-9995-4c6a-8475-6a4dddcb8ca3"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="75fcddb2-91f6-4216-85ba-e2c310711d5c" name="In" connectedTo="4fdf21c9-0507-4029-80e3-66bbb5ad4568"/>
          <port xsi:type="esdl:OutPort" id="eaeef464-40fb-4bb0-bc37-2fd2828fc066" name="Out" connectedTo="458d226d-3ac1-4272-b16a-04d2aeae845a"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="55aeca0d-e0b9-47aa-8142-4a415553f839" name="In" connectedTo="01795904-7386-4779-8f68-857095030317"/>
          <port xsi:type="esdl:OutPort" id="bf59e837-c179-456b-9357-00f65d183293" name="Out" connectedTo="327ebf8f-9500-4c1a-ad00-d0d26cdde5c9"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="03ced30e-7de5-4078-8e72-470cebed841f" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="53c1e548-9995-4c6a-8475-6a4dddcb8ca3" name="In_Ph1" connectedTo="21f1123a-9b73-4008-8ad9-6146ea17d8e0"/>
          <port xsi:type="esdl:InPort" id="458d226d-3ac1-4272-b16a-04d2aeae845a" name="In_Ph2" connectedTo="eaeef464-40fb-4bb0-bc37-2fd2828fc066"/>
          <port xsi:type="esdl:InPort" id="327ebf8f-9500-4c1a-ad00-d0d26cdde5c9" name="In_Ph3" connectedTo="bf59e837-c179-456b-9357-00f65d183293"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome521" id="e55cc926-374d-4fab-8719-4522d1259496">
          <port xsi:type="esdl:InPort" id="93db6b69-e9af-4beb-88ad-4f405fefbaa5" name="In" connectedTo="33730093-4aef-40dd-8241-6451ec4cb184"/>
          <port xsi:type="esdl:OutPort" id="79e22e55-73ca-4f73-a4b2-8a82049d7237" name="OutPh1" connectedTo="30ddad0b-cb3c-4331-8313-d4d42d64b93d"/>
          <port xsi:type="esdl:OutPort" id="4fdf21c9-0507-4029-80e3-66bbb5ad4568" name="OutPh2" connectedTo="75fcddb2-91f6-4216-85ba-e2c310711d5c"/>
          <port xsi:type="esdl:OutPort" id="01795904-7386-4779-8f68-857095030317" name="OutPh3" connectedTo="55aeca0d-e0b9-47aa-8142-4a415553f839"/>
          <geometry xsi:type="esdl:Point" lat="158371.579" lon="433475.598"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_4" id="c84b8eba-dc84-4ea4-87f9-af9207886cf1">
        <port xsi:type="esdl:InPort" id="58c1ebfa-1ca7-4fe5-b81e-e9b9da8b5a38" name="In" connectedTo="a2516899-3154-400d-b5a1-a31fcfd2b4d7"/>
        <port xsi:type="esdl:OutPort" id="552f6ca4-ac7e-406c-8913-ced51e96ae46" name="Out" connectedTo="cb0352a1-0269-4591-8167-2f6136ed32d5 f6b68b66-8e14-49dc-ab97-28e79bdf8f82"/>
        <geometry xsi:type="esdl:Point" lat="158373.8865062504" CRS="WGS84" lon="433487.81734652"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="12.744061152331536" name="lv_cable_trafo2_lvnetwork5_4_main_grid" id="86bb0315-5e70-4260-b22f-66948bf92ed4" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="d3b7b110-0d48-44a8-a57f-be3e50dcc250" name="In" connectedTo="dae269d8-8a86-4dff-8025-467be59822c3"/>
        <port xsi:type="esdl:OutPort" id="a2516899-3154-400d-b5a1-a31fcfd2b4d7" name="Out" connectedTo="58c1ebfa-1ca7-4fe5-b81e-e9b9da8b5a38"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158375.8485760547" CRS="WGS84" lon="433475.25186424155"/>
          <point xsi:type="esdl:Point" lat="158374.334" CRS="WGS84" lon="433482.323"/>
          <point xsi:type="esdl:Point" lat="158374.124" CRS="WGS84" lon="433484.905"/>
          <point xsi:type="esdl:Point" lat="158373.899" CRS="WGS84" lon="433487.664"/>
          <point xsi:type="esdl:Point" lat="158373.8865062504" CRS="WGS84" lon="433487.81734652"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="3.7478839030676645" name="lv_cable_trafo2_lvnetwork5_to_home_9_arch6" id="c7744adf-eab4-4f52-bb68-8ebd7e8e2b82" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="cb0352a1-0269-4591-8167-2f6136ed32d5" name="In" connectedTo="552f6ca4-ac7e-406c-8913-ced51e96ae46"/>
        <port xsi:type="esdl:OutPort" id="9036a28e-3010-4f9e-9f8b-c4e0b9475129" name="Out" connectedTo="80d65734-dac5-4e4e-a1bd-d515f9232ccf"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158370.151" CRS="WGS84" lon="433487.513"/>
          <point xsi:type="esdl:Point" lat="158373.8865062504" CRS="WGS84" lon="433487.81734652"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome526" id="1f153430-80a2-4d3f-8220-e0a6de832491">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="c6da5479-a48c-448d-9e51-2dd6065e3d1f" name="In" connectedTo="d08fbdd9-b4c7-4bf4-830d-a68229c8d0dc"/>
          <port xsi:type="esdl:OutPort" id="2c7af03e-c5b1-4e74-bc62-a2f734fc2c35" name="Out" connectedTo="72a6d8c1-383f-4658-aab6-ee9416fa677d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="85867121-bde2-4386-96fb-0b920b8c1f21" name="In" connectedTo="e8f8f31f-105c-480a-8bb1-4b77ee899c3b"/>
          <port xsi:type="esdl:OutPort" id="98675df2-c8e6-481c-823f-34e24f9f48d4" name="Out" connectedTo="aa1ca1a0-f736-4c92-8661-6d11c4331267"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="113ba171-9c69-4e2a-8b57-f8106464a49c" name="In" connectedTo="1a338384-1f68-4cdf-b82d-5c25c36aa3e2"/>
          <port xsi:type="esdl:OutPort" id="27a736a4-947e-46e1-808a-31e9b0156dbe" name="Out" connectedTo="eaa82712-647d-40fc-b63a-ccff63f56a76"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="f146f3e3-f1de-4d75-b910-3d5854bda3bc" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="72a6d8c1-383f-4658-aab6-ee9416fa677d" name="In_Ph1" connectedTo="2c7af03e-c5b1-4e74-bc62-a2f734fc2c35"/>
          <port xsi:type="esdl:InPort" id="aa1ca1a0-f736-4c92-8661-6d11c4331267" name="In_Ph2" connectedTo="98675df2-c8e6-481c-823f-34e24f9f48d4"/>
          <port xsi:type="esdl:InPort" id="eaa82712-647d-40fc-b63a-ccff63f56a76" name="In_Ph3" connectedTo="27a736a4-947e-46e1-808a-31e9b0156dbe"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome526" id="e2f180e3-a87b-4964-937e-d7672149c40b">
          <port xsi:type="esdl:InPort" id="80d65734-dac5-4e4e-a1bd-d515f9232ccf" name="In" connectedTo="9036a28e-3010-4f9e-9f8b-c4e0b9475129"/>
          <port xsi:type="esdl:OutPort" id="d08fbdd9-b4c7-4bf4-830d-a68229c8d0dc" name="OutPh1" connectedTo="c6da5479-a48c-448d-9e51-2dd6065e3d1f"/>
          <port xsi:type="esdl:OutPort" id="e8f8f31f-105c-480a-8bb1-4b77ee899c3b" name="OutPh2" connectedTo="85867121-bde2-4386-96fb-0b920b8c1f21"/>
          <port xsi:type="esdl:OutPort" id="1a338384-1f68-4cdf-b82d-5c25c36aa3e2" name="OutPh3" connectedTo="113ba171-9c69-4e2a-8b57-f8106464a49c"/>
          <geometry xsi:type="esdl:Point" lat="158370.151" lon="433487.513"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_5" id="96dc3bd0-25b2-4dcc-b004-5f39c339a03e">
        <port xsi:type="esdl:InPort" id="24a4072c-7d8e-4c92-9fd9-6c756b00d0a6" name="In" connectedTo="e10a5167-32fe-4ad0-8b6b-9d2acfdfc2ec"/>
        <port xsi:type="esdl:OutPort" id="b06133a7-80c2-4bea-a23a-cfc32288f510" name="Out" connectedTo="cce9d0e0-9f7b-41c0-92a6-7977512ff612 a05073db-488a-4e5b-ab53-8d64963f20c6"/>
        <geometry xsi:type="esdl:Point" lat="158373.24997340137" CRS="WGS84" lon="433493.2497035513"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.4742432458644235" name="lv_cable_trafo2_lvnetwork5_5_main_grid" id="9da67912-85a7-4925-a6bc-056c1a23c33c" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f6b68b66-8e14-49dc-ab97-28e79bdf8f82" name="In" connectedTo="552f6ca4-ac7e-406c-8913-ced51e96ae46"/>
        <port xsi:type="esdl:OutPort" id="e10a5167-32fe-4ad0-8b6b-9d2acfdfc2ec" name="Out" connectedTo="24a4072c-7d8e-4c92-9fd9-6c756b00d0a6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158373.8865062504" CRS="WGS84" lon="433487.81734652"/>
          <point xsi:type="esdl:Point" lat="158373.63" CRS="WGS84" lon="433490.971"/>
          <point xsi:type="esdl:Point" lat="158373.24997340137" CRS="WGS84" lon="433493.2497035513"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="3.5665610761512103" name="lv_cable_trafo2_lvnetwork5_to_home_8_arch6" id="75adc7ca-eabf-438b-915b-29beb985edbf" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="cce9d0e0-9f7b-41c0-92a6-7977512ff612" name="In" connectedTo="b06133a7-80c2-4bea-a23a-cfc32288f510"/>
        <port xsi:type="esdl:OutPort" id="b6217918-060a-47cb-b62b-01c271188afb" name="Out" connectedTo="7ca609b7-5b08-4345-b78b-0710487dc619"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158369.732" CRS="WGS84" lon="433492.663"/>
          <point xsi:type="esdl:Point" lat="158373.24997340137" CRS="WGS84" lon="433493.2497035513"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome525" id="731f4a7a-4883-484d-83b9-b6b12cf69005">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="15fedbef-eb1c-4cb8-b766-16e24863aa91" name="In" connectedTo="5e36e816-96c1-48ee-8985-74e6ce45051f"/>
          <port xsi:type="esdl:OutPort" id="e937fa39-7984-422f-840f-4be28a4ec408" name="Out" connectedTo="dfd7d5d9-5ec8-4710-8e46-5ce22f83990e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="8fe0faa4-ff85-42cb-b442-805b34a379ab" name="In" connectedTo="97df30da-2bac-4ff8-8d3c-724b6b6ba91a"/>
          <port xsi:type="esdl:OutPort" id="b8d99717-4c26-4c75-8e29-29affdf47156" name="Out" connectedTo="63fa1cf0-6c85-4696-8afd-e12a70adfdec"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="f974d96a-a2cc-44ca-95a2-b22a6c21d4e8" name="In" connectedTo="4d3e858c-971b-45d1-a2c8-a6b27db3d394"/>
          <port xsi:type="esdl:OutPort" id="54b6f5e0-a218-4970-927c-d874b9ebd251" name="Out" connectedTo="61362bf1-282f-47c7-9146-62bc5079a701"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b6316fb3-c55d-4e06-ae34-fc619dd6a968" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="dfd7d5d9-5ec8-4710-8e46-5ce22f83990e" name="In_Ph1" connectedTo="e937fa39-7984-422f-840f-4be28a4ec408"/>
          <port xsi:type="esdl:InPort" id="63fa1cf0-6c85-4696-8afd-e12a70adfdec" name="In_Ph2" connectedTo="b8d99717-4c26-4c75-8e29-29affdf47156"/>
          <port xsi:type="esdl:InPort" id="61362bf1-282f-47c7-9146-62bc5079a701" name="In_Ph3" connectedTo="54b6f5e0-a218-4970-927c-d874b9ebd251"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome525" id="1f7dec89-0835-48a6-bcd2-06232066d1e5">
          <port xsi:type="esdl:InPort" id="7ca609b7-5b08-4345-b78b-0710487dc619" name="In" connectedTo="b6217918-060a-47cb-b62b-01c271188afb"/>
          <port xsi:type="esdl:OutPort" id="5e36e816-96c1-48ee-8985-74e6ce45051f" name="OutPh1" connectedTo="15fedbef-eb1c-4cb8-b766-16e24863aa91"/>
          <port xsi:type="esdl:OutPort" id="97df30da-2bac-4ff8-8d3c-724b6b6ba91a" name="OutPh2" connectedTo="8fe0faa4-ff85-42cb-b442-805b34a379ab"/>
          <port xsi:type="esdl:OutPort" id="4d3e858c-971b-45d1-a2c8-a6b27db3d394" name="OutPh3" connectedTo="f974d96a-a2cc-44ca-95a2-b22a6c21d4e8"/>
          <geometry xsi:type="esdl:Point" lat="158369.732" lon="433492.663"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_6" id="eaa35e2b-9b86-4ea1-8ecc-e73847ca2409">
        <port xsi:type="esdl:InPort" id="7855dd6e-3e02-4fdf-91ba-f90db03d65e6" name="In" connectedTo="cec95e3d-91f1-4817-81d1-0a4c28d7c695"/>
        <port xsi:type="esdl:OutPort" id="a5af7ac3-a7a6-47b5-89c8-bb34285f7621" name="Out" connectedTo="7ab89763-33b6-485d-9777-4bef24f8fa8f 95fc1157-9ed9-414a-9071-4a515c7379b0"/>
        <geometry xsi:type="esdl:Point" lat="158372.408259317" CRS="WGS84" lon="433498.30053928617"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.120490638966624" name="lv_cable_trafo2_lvnetwork5_6_main_grid" id="b71875d2-34d1-41e6-9440-7ebdcb6a51d5" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="a05073db-488a-4e5b-ab53-8d64963f20c6" name="In" connectedTo="b06133a7-80c2-4bea-a23a-cfc32288f510"/>
        <port xsi:type="esdl:OutPort" id="cec95e3d-91f1-4817-81d1-0a4c28d7c695" name="Out" connectedTo="7855dd6e-3e02-4fdf-91ba-f90db03d65e6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158373.24997340137" CRS="WGS84" lon="433493.2497035513"/>
          <point xsi:type="esdl:Point" lat="158372.886" CRS="WGS84" lon="433495.435"/>
          <point xsi:type="esdl:Point" lat="158372.408259317" CRS="WGS84" lon="433498.30053928617"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="3.1349399418741215" name="lv_cable_trafo2_lvnetwork5_to_home_7_arch6" id="fc78bcbf-16ec-4ab3-b7f1-0393bbe52dbb" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="7ab89763-33b6-485d-9777-4bef24f8fa8f" name="In" connectedTo="a5af7ac3-a7a6-47b5-89c8-bb34285f7621"/>
        <port xsi:type="esdl:OutPort" id="7cc5133b-2256-49bc-8573-3362a4b26cd4" name="Out" connectedTo="fbbc7942-68dd-4855-9b28-57f9ffe0a2c4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158369.316" CRS="WGS84" lon="433497.785"/>
          <point xsi:type="esdl:Point" lat="158372.408259317" CRS="WGS84" lon="433498.30053928617"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome524" id="6c001dab-3524-49bd-8dab-1357da142585">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="3b17828e-4748-4218-9f71-4b2e732c6dc3" name="In" connectedTo="40c068c9-3157-44ca-b8b3-6488af66f9e1"/>
          <port xsi:type="esdl:OutPort" id="a6ce26b8-17a0-4dec-b19f-de968130db28" name="Out" connectedTo="bb7e692c-1085-40b7-b782-9ee03d19d9d8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="b6068794-ce14-4714-8663-a530c70ab06e" name="In" connectedTo="2eac6a9f-73b0-4181-acb4-99428abfe0a8"/>
          <port xsi:type="esdl:OutPort" id="f9e207be-b2b8-4788-b319-d9112f1320d3" name="Out" connectedTo="becc8642-5c98-4879-89c3-1cce8ba713a1"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="4be54b36-5e25-422c-9238-bcf7b3129f83" name="In" connectedTo="6de02154-3762-44d6-844e-484bfae3b840"/>
          <port xsi:type="esdl:OutPort" id="02469a89-e562-4c0b-b4b3-a37a532e2cd7" name="Out" connectedTo="a148f57b-0943-4b6e-b38a-24387ce5cc40"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="598e844c-935a-44c4-91f6-53f07ed17eb8" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="bb7e692c-1085-40b7-b782-9ee03d19d9d8" name="In_Ph1" connectedTo="a6ce26b8-17a0-4dec-b19f-de968130db28"/>
          <port xsi:type="esdl:InPort" id="becc8642-5c98-4879-89c3-1cce8ba713a1" name="In_Ph2" connectedTo="f9e207be-b2b8-4788-b319-d9112f1320d3"/>
          <port xsi:type="esdl:InPort" id="a148f57b-0943-4b6e-b38a-24387ce5cc40" name="In_Ph3" connectedTo="02469a89-e562-4c0b-b4b3-a37a532e2cd7"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome524" id="426fbf13-e31c-4d00-b867-042b65d9b184">
          <port xsi:type="esdl:InPort" id="fbbc7942-68dd-4855-9b28-57f9ffe0a2c4" name="In" connectedTo="7cc5133b-2256-49bc-8573-3362a4b26cd4"/>
          <port xsi:type="esdl:OutPort" id="40c068c9-3157-44ca-b8b3-6488af66f9e1" name="OutPh1" connectedTo="3b17828e-4748-4218-9f71-4b2e732c6dc3"/>
          <port xsi:type="esdl:OutPort" id="2eac6a9f-73b0-4181-acb4-99428abfe0a8" name="OutPh2" connectedTo="b6068794-ce14-4714-8663-a530c70ab06e"/>
          <port xsi:type="esdl:OutPort" id="6de02154-3762-44d6-844e-484bfae3b840" name="OutPh3" connectedTo="4be54b36-5e25-422c-9238-bcf7b3129f83"/>
          <geometry xsi:type="esdl:Point" lat="158369.316" lon="433497.785"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_7" id="d509feb0-238c-43c3-a258-582b3eae75be">
        <port xsi:type="esdl:InPort" id="5f825f00-b39b-48e6-9d26-129ab32ac951" name="In" connectedTo="a6560d19-d6f3-4258-b115-7010c5bb04bb"/>
        <port xsi:type="esdl:OutPort" id="b10a99e9-6181-4df2-beb3-5f35d58f689d" name="Out" connectedTo="b3d1b438-cda5-41e0-a470-6530a8adc1d1 250cfcdc-3483-4bf3-a86c-5a644fde0e68"/>
        <geometry xsi:type="esdl:Point" lat="158371.50208424273" CRS="WGS84" lon="433503.7376263001"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.512083866470808" name="lv_cable_trafo2_lvnetwork5_7_main_grid" id="17979dba-a78c-4f9e-b166-c2028898edcc" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="95fc1157-9ed9-414a-9071-4a515c7379b0" name="In" connectedTo="a5af7ac3-a7a6-47b5-89c8-bb34285f7621"/>
        <port xsi:type="esdl:OutPort" id="a6560d19-d6f3-4258-b115-7010c5bb04bb" name="Out" connectedTo="5f825f00-b39b-48e6-9d26-129ab32ac951"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158372.408259317" CRS="WGS84" lon="433498.30053928617"/>
          <point xsi:type="esdl:Point" lat="158372.043" CRS="WGS84" lon="433500.493"/>
          <point xsi:type="esdl:Point" lat="158371.50208424273" CRS="WGS84" lon="433503.7376263001"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.551822743996403" name="lv_cable_trafo2_lvnetwork5_to_home_5_arch6" id="2faa6e57-86a2-451f-88d4-9c2cd13ef8b2" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="b3d1b438-cda5-41e0-a470-6530a8adc1d1" name="In" connectedTo="b10a99e9-6181-4df2-beb3-5f35d58f689d"/>
        <port xsi:type="esdl:OutPort" id="f307143d-095f-4a19-a9e5-3a5f36ff7854" name="Out" connectedTo="5004d4d7-2c2d-4e5b-9bbe-a674aabbd143"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158368.985" CRS="WGS84" lon="433503.318"/>
          <point xsi:type="esdl:Point" lat="158371.50208424273" CRS="WGS84" lon="433503.7376263001"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome522" id="3b32a44e-120f-4220-aa25-25c88e8b0cde">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="96a3d4a1-4a00-478b-acf7-f4e11bfb18f8" name="In" connectedTo="1e3d65b5-628d-414b-bc16-58b79e3b9390"/>
          <port xsi:type="esdl:OutPort" id="8ae074a7-7214-4522-8705-4f55afeafbe9" name="Out" connectedTo="02de0236-2ae2-4e19-a210-dbf92c23cc99"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="1443dc8d-ff97-49e9-bd25-15d2fdaa6193" name="In" connectedTo="da8d107a-c06c-4b7d-95c9-3bec68a5eb29"/>
          <port xsi:type="esdl:OutPort" id="13787a88-3dc4-4707-8f59-ed4890b08cea" name="Out" connectedTo="35d4ecd9-53e9-4831-b552-7084e85d9717"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="5b133dd9-7877-47eb-8136-8919b17d9cae" name="In" connectedTo="1afc002f-b215-4245-9b21-4ff1676bb046"/>
          <port xsi:type="esdl:OutPort" id="33fb7d9c-2f0c-4f6f-ad35-7bbc0909be2b" name="Out" connectedTo="26d8a1af-7c58-409b-a7b3-af0285b5371a"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="701799ed-8370-4c10-983e-37561933f5bd" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="02de0236-2ae2-4e19-a210-dbf92c23cc99" name="In_Ph1" connectedTo="8ae074a7-7214-4522-8705-4f55afeafbe9"/>
          <port xsi:type="esdl:InPort" id="35d4ecd9-53e9-4831-b552-7084e85d9717" name="In_Ph2" connectedTo="13787a88-3dc4-4707-8f59-ed4890b08cea"/>
          <port xsi:type="esdl:InPort" id="26d8a1af-7c58-409b-a7b3-af0285b5371a" name="In_Ph3" connectedTo="33fb7d9c-2f0c-4f6f-ad35-7bbc0909be2b"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome522" id="d28a9080-e7e2-4cd9-9e9b-146e47d202b8">
          <port xsi:type="esdl:InPort" id="5004d4d7-2c2d-4e5b-9bbe-a674aabbd143" name="In" connectedTo="f307143d-095f-4a19-a9e5-3a5f36ff7854"/>
          <port xsi:type="esdl:OutPort" id="1e3d65b5-628d-414b-bc16-58b79e3b9390" name="OutPh1" connectedTo="96a3d4a1-4a00-478b-acf7-f4e11bfb18f8"/>
          <port xsi:type="esdl:OutPort" id="da8d107a-c06c-4b7d-95c9-3bec68a5eb29" name="OutPh2" connectedTo="1443dc8d-ff97-49e9-bd25-15d2fdaa6193"/>
          <port xsi:type="esdl:OutPort" id="1afc002f-b215-4245-9b21-4ff1676bb046" name="OutPh3" connectedTo="5b133dd9-7877-47eb-8136-8919b17d9cae"/>
          <geometry xsi:type="esdl:Point" lat="158368.985" lon="433503.318"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_8" id="9ea9d2df-2b05-4a11-96a7-e2db330ab893">
        <port xsi:type="esdl:InPort" id="a9e943f2-4402-4ecc-969c-7e0ffacb79cd" name="In" connectedTo="648d7861-3667-4ba1-9127-7b97f2c28ae8"/>
        <port xsi:type="esdl:OutPort" id="c954a71d-315f-4096-aa85-cebec751ae2f" name="Out" connectedTo="d857c8fd-fc57-465b-8864-2543999f516c 396aa4c8-706f-4e6b-aa94-8c694055c15e 18a35bb0-5cf5-4496-8ce9-708993a71014"/>
        <geometry xsi:type="esdl:Point" lat="158358.167" CRS="WGS84" lon="433511.042"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="17.21478365575849" name="lv_cable_trafo2_lvnetwork5_8_main_grid" id="61d03c7c-af4c-425f-b819-2ec17c1efc9d" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="250cfcdc-3483-4bf3-a86c-5a644fde0e68" name="In" connectedTo="b10a99e9-6181-4df2-beb3-5f35d58f689d"/>
        <port xsi:type="esdl:OutPort" id="648d7861-3667-4ba1-9127-7b97f2c28ae8" name="Out" connectedTo="a9e943f2-4402-4ecc-969c-7e0ffacb79cd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158371.50208424273" CRS="WGS84" lon="433503.7376263001"/>
          <point xsi:type="esdl:Point" lat="158371.279760085" CRS="WGS84" lon="433504.906634197"/>
          <point xsi:type="esdl:Point" lat="158371.102981249" CRS="WGS84" lon="433505.574654727"/>
          <point xsi:type="esdl:Point" lat="158370.890185215" CRS="WGS84" lon="433506.232090083"/>
          <point xsi:type="esdl:Point" lat="158370.642" CRS="WGS84" lon="433506.877"/>
          <point xsi:type="esdl:Point" lat="158370.406932683" CRS="WGS84" lon="433507.310957156"/>
          <point xsi:type="esdl:Point" lat="158370.141043462" CRS="WGS84" lon="433507.726756298"/>
          <point xsi:type="esdl:Point" lat="158369.845728945" CRS="WGS84" lon="433508.122213399"/>
          <point xsi:type="esdl:Point" lat="158369.522540301" CRS="WGS84" lon="433508.49525128"/>
          <point xsi:type="esdl:Point" lat="158369.173175113" CRS="WGS84" lon="433508.843910524"/>
          <point xsi:type="esdl:Point" lat="158368.799468454" CRS="WGS84" lon="433509.166359762"/>
          <point xsi:type="esdl:Point" lat="158368.403383257" CRS="WGS84" lon="433509.460905297"/>
          <point xsi:type="esdl:Point" lat="158367.987" CRS="WGS84" lon="433509.726"/>
          <point xsi:type="esdl:Point" lat="158367.603725606" CRS="WGS84" lon="433509.937950446"/>
          <point xsi:type="esdl:Point" lat="158367.207855363" CRS="WGS84" lon="433510.124896199"/>
          <point xsi:type="esdl:Point" lat="158366.801016276" CRS="WGS84" lon="433510.286068923"/>
          <point xsi:type="esdl:Point" lat="158366.384880428" CRS="WGS84" lon="433510.420806206"/>
          <point xsi:type="esdl:Point" lat="158365.961158117" CRS="WGS84" lon="433510.528554286"/>
          <point xsi:type="esdl:Point" lat="158365.531590815" CRS="WGS84" lon="433510.608870324"/>
          <point xsi:type="esdl:Point" lat="158365.097944022" CRS="WGS84" lon="433510.661424227"/>
          <point xsi:type="esdl:Point" lat="158364.662" CRS="WGS84" lon="433510.686"/>
          <point xsi:type="esdl:Point" lat="158364.469" CRS="WGS84" lon="433510.697"/>
          <point xsi:type="esdl:Point" lat="158361.164" CRS="WGS84" lon="433510.878"/>
          <point xsi:type="esdl:Point" lat="158360.187" CRS="WGS84" lon="433510.931"/>
          <point xsi:type="esdl:Point" lat="158358.167" CRS="WGS84" lon="433511.042"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.3353171907663297" name="lv_cable_trafo2_lvnetwork5_to_home_2_arch6" id="21966109-ad8d-4429-ab17-5f1f86438886" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="d857c8fd-fc57-465b-8864-2543999f516c" name="In" connectedTo="c954a71d-315f-4096-aa85-cebec751ae2f"/>
        <port xsi:type="esdl:OutPort" id="253a5c12-6776-4c7a-9c4b-3bac6b83f280" name="Out" connectedTo="87a5db26-f85e-42c4-9ce1-b883399d0231"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158357.203" CRS="WGS84" lon="433510.118"/>
          <point xsi:type="esdl:Point" lat="158358.167" CRS="WGS84" lon="433511.042"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome519" id="ba62072f-e872-4f4f-865a-2aa7123be88e">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="969f6542-dcbb-4869-aa88-26a952b21c47" name="In" connectedTo="c11ae2a3-b474-41e3-a657-bd72abf4ceef"/>
          <port xsi:type="esdl:OutPort" id="ece18c8b-5165-4db0-8335-59ff2eade9d6" name="Out" connectedTo="d309885c-1ea0-48d5-8fba-201eae6ddc65"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="1f96007e-70cb-45b3-9890-57ccc46d9a46" name="In" connectedTo="015c718b-4037-44c3-877e-11386ae27401"/>
          <port xsi:type="esdl:OutPort" id="b31f53f6-c539-4143-a7b8-ed1380e211c3" name="Out" connectedTo="41c34bbf-26fb-46c1-be7f-1e0a90d0b6aa"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="363dfc23-f27e-4fca-aecf-08275c28d3bb" name="In" connectedTo="aa11841b-8e46-4017-a412-539df2c01b5b"/>
          <port xsi:type="esdl:OutPort" id="949683ba-eea4-43cf-ae42-af41cab91a4a" name="Out" connectedTo="054033cf-6555-42b4-a1da-3fdaf3a54eb3"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="1f7420ef-ea27-4450-9720-39d1190ab34f" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="d309885c-1ea0-48d5-8fba-201eae6ddc65" name="In_Ph1" connectedTo="ece18c8b-5165-4db0-8335-59ff2eade9d6"/>
          <port xsi:type="esdl:InPort" id="41c34bbf-26fb-46c1-be7f-1e0a90d0b6aa" name="In_Ph2" connectedTo="b31f53f6-c539-4143-a7b8-ed1380e211c3"/>
          <port xsi:type="esdl:InPort" id="054033cf-6555-42b4-a1da-3fdaf3a54eb3" name="In_Ph3" connectedTo="949683ba-eea4-43cf-ae42-af41cab91a4a"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome519" id="11ca1faa-161d-42e0-bb2d-9c2af754d056">
          <port xsi:type="esdl:InPort" id="87a5db26-f85e-42c4-9ce1-b883399d0231" name="In" connectedTo="253a5c12-6776-4c7a-9c4b-3bac6b83f280"/>
          <port xsi:type="esdl:OutPort" id="c11ae2a3-b474-41e3-a657-bd72abf4ceef" name="OutPh1" connectedTo="969f6542-dcbb-4869-aa88-26a952b21c47"/>
          <port xsi:type="esdl:OutPort" id="015c718b-4037-44c3-877e-11386ae27401" name="OutPh2" connectedTo="1f96007e-70cb-45b3-9890-57ccc46d9a46"/>
          <port xsi:type="esdl:OutPort" id="aa11841b-8e46-4017-a412-539df2c01b5b" name="OutPh3" connectedTo="363dfc23-f27e-4fca-aecf-08275c28d3bb"/>
          <geometry xsi:type="esdl:Point" lat="158357.203" lon="433510.118"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.9995488777246906" name="lv_cable_trafo2_lvnetwork5_to_home_6_arch6" id="794f2675-33da-4fd8-925e-dd9614922a55" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="396aa4c8-706f-4e6b-aa94-8c694055c15e" name="In" connectedTo="c954a71d-315f-4096-aa85-cebec751ae2f"/>
        <port xsi:type="esdl:OutPort" id="bff66100-99cf-4ce4-873f-4af4a0afc073" name="Out" connectedTo="3df78ff9-9ada-4ef8-95db-6d56d808845a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158358.0853810843" CRS="WGS84" lon="433510.0457890226"/>
          <point xsi:type="esdl:Point" lat="158358.167" CRS="WGS84" lon="433511.042"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome523" id="2f1a056d-a719-49db-bcd3-793d9eea8bf6">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="c67f06f9-21a6-4f18-9ff7-fd07cb146b2b" name="In" connectedTo="15900e0c-532a-499b-893a-148472842a25"/>
          <port xsi:type="esdl:OutPort" id="7457c75a-bd70-455f-86a7-594544f431dc" name="Out" connectedTo="bfef03e3-cb6b-4a97-a340-26f854fa412c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="ca8cadf8-1c4b-4e55-8dcf-f4402a6b2853" name="In" connectedTo="21f4be5a-2907-4c28-8501-9dcf46f0cb06"/>
          <port xsi:type="esdl:OutPort" id="d5c91996-a373-4043-b33e-2d5622445374" name="Out" connectedTo="905fada6-e160-42b4-a436-dae64e647791"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="7565cef6-358c-4b1a-be8f-891e06967d1d" name="In" connectedTo="8b5f023b-430a-41d9-9429-15aae41fc886"/>
          <port xsi:type="esdl:OutPort" id="719e6359-b1b2-4011-be35-f968a1780a72" name="Out" connectedTo="085bacbe-16c3-4ac2-a3ad-263c29c0e4ac"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="9b750136-285d-4130-8174-bce985f23052" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="bfef03e3-cb6b-4a97-a340-26f854fa412c" name="In_Ph1" connectedTo="7457c75a-bd70-455f-86a7-594544f431dc"/>
          <port xsi:type="esdl:InPort" id="905fada6-e160-42b4-a436-dae64e647791" name="In_Ph2" connectedTo="d5c91996-a373-4043-b33e-2d5622445374"/>
          <port xsi:type="esdl:InPort" id="085bacbe-16c3-4ac2-a3ad-263c29c0e4ac" name="In_Ph3" connectedTo="719e6359-b1b2-4011-be35-f968a1780a72"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome523" id="ca29674a-7917-45c9-a95d-bc0638c20513">
          <port xsi:type="esdl:InPort" id="3df78ff9-9ada-4ef8-95db-6d56d808845a" name="In" connectedTo="bff66100-99cf-4ce4-873f-4af4a0afc073"/>
          <port xsi:type="esdl:OutPort" id="15900e0c-532a-499b-893a-148472842a25" name="OutPh1" connectedTo="c67f06f9-21a6-4f18-9ff7-fd07cb146b2b"/>
          <port xsi:type="esdl:OutPort" id="21f4be5a-2907-4c28-8501-9dcf46f0cb06" name="OutPh2" connectedTo="ca8cadf8-1c4b-4e55-8dcf-f4402a6b2853"/>
          <port xsi:type="esdl:OutPort" id="8b5f023b-430a-41d9-9429-15aae41fc886" name="OutPh3" connectedTo="7565cef6-358c-4b1a-be8f-891e06967d1d"/>
          <geometry xsi:type="esdl:Point" lat="158358.0853810843" lon="433510.0457890226"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_9" id="82bf44e8-b775-4bc0-b1ea-4de8eace513c">
        <port xsi:type="esdl:InPort" id="9770a794-e7ec-47e2-a625-87c88533d60a" name="In" connectedTo="7afc47b3-62b3-42e3-b378-1e1afe604863"/>
        <port xsi:type="esdl:OutPort" id="791251ef-bb1a-4c5e-859a-e2b310a981a0" name="Out" connectedTo="62c69f77-b0f0-4b72-9d20-a8cf12a0e8c6 8345a013-da10-472c-9ffc-0c0d129c69a1"/>
        <geometry xsi:type="esdl:Point" lat="158358.927" CRS="WGS84" lon="433521.162"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.148497475017217" name="lv_cable_trafo2_lvnetwork5_9_main_grid" id="96234384-a547-49b2-926b-c5ce8de92d5b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="18a35bb0-5cf5-4496-8ce9-708993a71014" name="In" connectedTo="c954a71d-315f-4096-aa85-cebec751ae2f"/>
        <port xsi:type="esdl:OutPort" id="7afc47b3-62b3-42e3-b378-1e1afe604863" name="Out" connectedTo="9770a794-e7ec-47e2-a625-87c88533d60a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158358.167" CRS="WGS84" lon="433511.042"/>
          <point xsi:type="esdl:Point" lat="158358.851" CRS="WGS84" lon="433520.154"/>
          <point xsi:type="esdl:Point" lat="158358.927" CRS="WGS84" lon="433521.162"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.262730883076239" name="lv_cable_trafo2_lvnetwork5_to_home_10_arch6" id="b114e66a-ab9d-4f1e-9297-e6a9e15a12cb" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="62c69f77-b0f0-4b72-9d20-a8cf12a0e8c6" name="In" connectedTo="791251ef-bb1a-4c5e-859a-e2b310a981a0"/>
        <port xsi:type="esdl:OutPort" id="7627e86f-9af1-470f-b32a-7eca6557e806" name="Out" connectedTo="45296458-de84-4512-859e-c82cc8252135"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158359.32597878494" CRS="WGS84" lon="433526.40958537586"/>
          <point xsi:type="esdl:Point" lat="158358.927" CRS="WGS84" lon="433521.162"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome527" id="62bca472-6fcf-4603-acfb-4442295d608f">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="fda67f35-1bb5-44e7-ba84-cabd6b4c8c61" name="In" connectedTo="37c427bc-65e8-4c2b-b023-fe44e29c2600"/>
          <port xsi:type="esdl:OutPort" id="49eb687c-0146-4be2-9199-1e39d85c6312" name="Out" connectedTo="8421f452-37e0-40c8-b071-ff81b19ffcee"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="dd61116c-1406-42ad-81dd-c0af075a05a1" name="In" connectedTo="cf8cb790-ec16-44fe-888f-71ca108bf011"/>
          <port xsi:type="esdl:OutPort" id="7f274002-e7ca-4a33-97eb-a82c4c13fb59" name="Out" connectedTo="d5508a69-db69-4a18-83ed-bfe0cf83556d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="bd8f04d5-176e-4edb-91a7-a5af55cf96a8" name="In" connectedTo="05d65040-d50b-40dc-ac3a-1a46eda73c6a"/>
          <port xsi:type="esdl:OutPort" id="70cee0b8-3a91-473d-b01c-4ff72f3c580f" name="Out" connectedTo="e06d746e-4fa9-44e0-871f-7fc03b768f4d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b01f1135-c9e0-46b0-a913-ba6bf6e5f14c" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="8421f452-37e0-40c8-b071-ff81b19ffcee" name="In_Ph1" connectedTo="49eb687c-0146-4be2-9199-1e39d85c6312"/>
          <port xsi:type="esdl:InPort" id="d5508a69-db69-4a18-83ed-bfe0cf83556d" name="In_Ph2" connectedTo="7f274002-e7ca-4a33-97eb-a82c4c13fb59"/>
          <port xsi:type="esdl:InPort" id="e06d746e-4fa9-44e0-871f-7fc03b768f4d" name="In_Ph3" connectedTo="70cee0b8-3a91-473d-b01c-4ff72f3c580f"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome527" id="984174d7-6b58-4582-aa3b-47478721fda9">
          <port xsi:type="esdl:InPort" id="45296458-de84-4512-859e-c82cc8252135" name="In" connectedTo="7627e86f-9af1-470f-b32a-7eca6557e806"/>
          <port xsi:type="esdl:OutPort" id="37c427bc-65e8-4c2b-b023-fe44e29c2600" name="OutPh1" connectedTo="fda67f35-1bb5-44e7-ba84-cabd6b4c8c61"/>
          <port xsi:type="esdl:OutPort" id="cf8cb790-ec16-44fe-888f-71ca108bf011" name="OutPh2" connectedTo="dd61116c-1406-42ad-81dd-c0af075a05a1"/>
          <port xsi:type="esdl:OutPort" id="05d65040-d50b-40dc-ac3a-1a46eda73c6a" name="OutPh3" connectedTo="bd8f04d5-176e-4edb-91a7-a5af55cf96a8"/>
          <geometry xsi:type="esdl:Point" lat="158359.32597878494" lon="433526.40958537586"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_10" id="9ec94341-0199-4af2-9aec-5156d0da41ab">
        <port xsi:type="esdl:InPort" id="d869f76a-6c47-4621-9b71-413ceb33f2cd" name="In" connectedTo="dd07638f-e285-41a2-8861-f9cc463d3664"/>
        <port xsi:type="esdl:OutPort" id="b8547c30-6e51-4ab7-a872-4a98209fd99b" name="Out" connectedTo="b6d0eea3-8ee2-496d-ad4f-014695ae7eee f971cd52-d1c1-4906-b3d3-74415b12c012"/>
        <geometry xsi:type="esdl:Point" lat="158350.03544842653" CRS="WGS84" lon="433521.4084769804"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.927700724281111" name="lv_cable_trafo2_lvnetwork5_10_main_grid" id="b68a4cda-63ae-42cd-97b6-ceb4d4673882" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="8345a013-da10-472c-9ffc-0c0d129c69a1" name="In" connectedTo="791251ef-bb1a-4c5e-859a-e2b310a981a0"/>
        <port xsi:type="esdl:OutPort" id="dd07638f-e285-41a2-8861-f9cc463d3664" name="Out" connectedTo="d869f76a-6c47-4621-9b71-413ceb33f2cd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158358.927" CRS="WGS84" lon="433521.162"/>
          <point xsi:type="esdl:Point" lat="158356.121" CRS="WGS84" lon="433521.374"/>
          <point xsi:type="esdl:Point" lat="158352.144" CRS="WGS84" lon="433521.675"/>
          <point xsi:type="esdl:Point" lat="158350.03544842653" CRS="WGS84" lon="433521.4084769804"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="4.7721953797101255" name="lv_cable_trafo2_lvnetwork5_to_home_1_arch6" id="80b9e72a-f32a-4a76-a5bf-c3ce8440d02c" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="b6d0eea3-8ee2-496d-ad4f-014695ae7eee" name="In" connectedTo="b8547c30-6e51-4ab7-a872-4a98209fd99b"/>
        <port xsi:type="esdl:OutPort" id="fc263144-fe21-4b26-8e5c-be0d0eff542f" name="Out" connectedTo="4e2285dd-6d4d-41a7-be02-6600d5af9d2b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158349.437" CRS="WGS84" lon="433526.143"/>
          <point xsi:type="esdl:Point" lat="158350.03544842653" CRS="WGS84" lon="433521.4084769804"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome518" id="cde696de-d029-4929-880a-625210d7f1db">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="fff78f9c-061e-40a4-87ff-d9683edb0bde" name="In" connectedTo="afd0f883-a2cb-4741-b79a-e01bd413aae2"/>
          <port xsi:type="esdl:OutPort" id="f266fc5f-ffd0-4e92-9ed6-ca5f2338674e" name="Out" connectedTo="a0e08434-9af6-4c7c-80dc-a00ce382779a"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="19f4f219-65f0-434a-a5ee-ee4e7684fad4" name="In" connectedTo="0092f84e-69b3-4c84-be60-819a72b331db"/>
          <port xsi:type="esdl:OutPort" id="8820ec36-139b-49c1-93ad-45ddef34079c" name="Out" connectedTo="eb9bfa9e-dfa6-4569-98a6-002cf0d8dc5d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="9c5dbc0c-ba62-4282-9f1c-39b6769fa705" name="In" connectedTo="6cb5f8cb-1a0d-4b91-b72b-e70e99b0f144"/>
          <port xsi:type="esdl:OutPort" id="8a030c9d-7aa9-4b3e-9214-8d43ba8ce862" name="Out" connectedTo="1d76b573-7b11-4e49-94d8-ee1ee32f2f81"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="3828dc38-5e87-48bc-91c5-ad3be5260e8d" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="a0e08434-9af6-4c7c-80dc-a00ce382779a" name="In_Ph1" connectedTo="f266fc5f-ffd0-4e92-9ed6-ca5f2338674e"/>
          <port xsi:type="esdl:InPort" id="eb9bfa9e-dfa6-4569-98a6-002cf0d8dc5d" name="In_Ph2" connectedTo="8820ec36-139b-49c1-93ad-45ddef34079c"/>
          <port xsi:type="esdl:InPort" id="1d76b573-7b11-4e49-94d8-ee1ee32f2f81" name="In_Ph3" connectedTo="8a030c9d-7aa9-4b3e-9214-8d43ba8ce862"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome518" id="cd9e9dc4-4c97-400c-904f-e5f55d649d87">
          <port xsi:type="esdl:InPort" id="4e2285dd-6d4d-41a7-be02-6600d5af9d2b" name="In" connectedTo="fc263144-fe21-4b26-8e5c-be0d0eff542f"/>
          <port xsi:type="esdl:OutPort" id="afd0f883-a2cb-4741-b79a-e01bd413aae2" name="OutPh1" connectedTo="fff78f9c-061e-40a4-87ff-d9683edb0bde"/>
          <port xsi:type="esdl:OutPort" id="0092f84e-69b3-4c84-be60-819a72b331db" name="OutPh2" connectedTo="19f4f219-65f0-434a-a5ee-ee4e7684fad4"/>
          <port xsi:type="esdl:OutPort" id="6cb5f8cb-1a0d-4b91-b72b-e70e99b0f144" name="OutPh3" connectedTo="9c5dbc0c-ba62-4282-9f1c-39b6769fa705"/>
          <geometry xsi:type="esdl:Point" lat="158349.437" lon="433526.143"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_11" id="34f7971f-f5a0-4b93-9e48-8851b30f3cc6">
        <port xsi:type="esdl:InPort" id="54e5b5d5-bf7b-4156-a08c-7dd2af7dfac4" name="In" connectedTo="971adb56-0262-4722-95a2-1c5364670488"/>
        <port xsi:type="esdl:OutPort" id="6197389c-890e-40c2-9f78-733017717b16" name="Out" connectedTo="97b79273-3e57-46a4-a6d8-11b0bd2888bf 483cbe38-114a-4a9f-bfca-7a8d7ec5d40c"/>
        <geometry xsi:type="esdl:Point" lat="158319.80298772277" CRS="WGS84" lon="433530.5986283095"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="32.61980335404732" name="lv_cable_trafo2_lvnetwork5_11_main_grid" id="eee32b5b-0db7-4c78-9a5c-3bae9bba55d6" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f971cd52-d1c1-4906-b3d3-74415b12c012" name="In" connectedTo="b8547c30-6e51-4ab7-a872-4a98209fd99b"/>
        <port xsi:type="esdl:OutPort" id="971adb56-0262-4722-95a2-1c5364670488" name="Out" connectedTo="54e5b5d5-bf7b-4156-a08c-7dd2af7dfac4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158350.03544842653" CRS="WGS84" lon="433521.4084769804"/>
          <point xsi:type="esdl:Point" lat="158345.202" CRS="WGS84" lon="433521.581"/>
          <point xsi:type="esdl:Point" lat="158340.88" CRS="WGS84" lon="433521.943"/>
          <point xsi:type="esdl:Point" lat="158337.231" CRS="WGS84" lon="433522.248"/>
          <point xsi:type="esdl:Point" lat="158336.16191052" CRS="WGS84" lon="433522.346600615"/>
          <point xsi:type="esdl:Point" lat="158335.097579479" CRS="WGS84" lon="433522.488778777"/>
          <point xsi:type="esdl:Point" lat="158334.039766571" CRS="WGS84" lon="433522.674299417"/>
          <point xsi:type="esdl:Point" lat="158332.990220711" CRS="WGS84" lon="433522.902855809"/>
          <point xsi:type="esdl:Point" lat="158331.950677148" CRS="WGS84" lon="433523.174070072"/>
          <point xsi:type="esdl:Point" lat="158330.922854594" CRS="WGS84" lon="433523.4874938"/>
          <point xsi:type="esdl:Point" lat="158329.90845238" CRS="WGS84" lon="433523.842608798"/>
          <point xsi:type="esdl:Point" lat="158328.909147651" CRS="WGS84" lon="433524.238827944"/>
          <point xsi:type="esdl:Point" lat="158327.92659259" CRS="WGS84" lon="433524.675496155"/>
          <point xsi:type="esdl:Point" lat="158326.962411687" CRS="WGS84" lon="433525.151891473"/>
          <point xsi:type="esdl:Point" lat="158326.018199055" CRS="WGS84" lon="433525.66722626"/>
          <point xsi:type="esdl:Point" lat="158325.09551579" CRS="WGS84" lon="433526.220648494"/>
          <point xsi:type="esdl:Point" lat="158324.195887394" CRS="WGS84" lon="433526.811243185"/>
          <point xsi:type="esdl:Point" lat="158323.320801253" CRS="WGS84" lon="433527.438033884"/>
          <point xsi:type="esdl:Point" lat="158322.471704175" CRS="WGS84" lon="433528.099984297"/>
          <point xsi:type="esdl:Point" lat="158321.65" CRS="WGS84" lon="433528.796"/>
          <point xsi:type="esdl:Point" lat="158320.945048457" CRS="WGS84" lon="433529.441277947"/>
          <point xsi:type="esdl:Point" lat="158320.263645398" CRS="WGS84" lon="433530.111624096"/>
          <point xsi:type="esdl:Point" lat="158319.80298772277" CRS="WGS84" lon="433530.5986283095"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="6.326370955601013" name="lv_cable_trafo2_lvnetwork5_to_home_0_arch6" id="2a2a003a-a782-41b3-a16d-79af552f2684" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="97b79273-3e57-46a4-a6d8-11b0bd2888bf" name="In" connectedTo="6197389c-890e-40c2-9f78-733017717b16"/>
        <port xsi:type="esdl:OutPort" id="b1df5255-2d3c-43dc-b417-19e8b87babe3" name="Out" connectedTo="ad028767-21ce-444f-a72d-ea34a0e04298"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158324.399" CRS="WGS84" lon="433534.946"/>
          <point xsi:type="esdl:Point" lat="158319.80298772277" CRS="WGS84" lon="433530.5986283095"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome517" id="12a79f4c-f621-4ea6-aaca-17bd5913df55">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="0778ec75-7247-4511-8093-085e8f4cb18f" name="In" connectedTo="9d0b6ac8-13b6-4a1b-a25e-d129944fb1a7"/>
          <port xsi:type="esdl:OutPort" id="eb3e8da2-ef56-4a97-83cf-cce036e100a6" name="Out" connectedTo="89aad45b-7c83-46ad-a7ba-d682fa91d336"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="2512a974-0938-41d7-b5c3-4671083a4148" name="In" connectedTo="d3ad0c53-1bb0-44ed-bc73-9c8fd964706b"/>
          <port xsi:type="esdl:OutPort" id="f260a68b-e7f7-4925-9c2c-60aef4f5094a" name="Out" connectedTo="e49826d2-fd9e-45c5-a68d-0cb3ed73430d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="0031c9fe-9153-451d-bc07-75c2373e7b4c" name="In" connectedTo="4a9ddeac-0224-4b07-add8-c1cb564192fd"/>
          <port xsi:type="esdl:OutPort" id="8c1e1085-f2dd-4f01-9c25-707ae05bd8e8" name="Out" connectedTo="57bce54e-c834-4f4a-8f73-b618d8cf49b8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="59017bfa-8f98-4c8c-bab4-8a561fd0d249" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="89aad45b-7c83-46ad-a7ba-d682fa91d336" name="In_Ph1" connectedTo="eb3e8da2-ef56-4a97-83cf-cce036e100a6"/>
          <port xsi:type="esdl:InPort" id="e49826d2-fd9e-45c5-a68d-0cb3ed73430d" name="In_Ph2" connectedTo="f260a68b-e7f7-4925-9c2c-60aef4f5094a"/>
          <port xsi:type="esdl:InPort" id="57bce54e-c834-4f4a-8f73-b618d8cf49b8" name="In_Ph3" connectedTo="8c1e1085-f2dd-4f01-9c25-707ae05bd8e8"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome517" id="a1cd400d-1f03-42c8-8b10-30cd00c2ea6f">
          <port xsi:type="esdl:InPort" id="ad028767-21ce-444f-a72d-ea34a0e04298" name="In" connectedTo="b1df5255-2d3c-43dc-b417-19e8b87babe3"/>
          <port xsi:type="esdl:OutPort" id="9d0b6ac8-13b6-4a1b-a25e-d129944fb1a7" name="OutPh1" connectedTo="0778ec75-7247-4511-8093-085e8f4cb18f"/>
          <port xsi:type="esdl:OutPort" id="d3ad0c53-1bb0-44ed-bc73-9c8fd964706b" name="OutPh2" connectedTo="2512a974-0938-41d7-b5c3-4671083a4148"/>
          <port xsi:type="esdl:OutPort" id="4a9ddeac-0224-4b07-add8-c1cb564192fd" name="OutPh3" connectedTo="0031c9fe-9153-451d-bc07-75c2373e7b4c"/>
          <geometry xsi:type="esdl:Point" lat="158324.399" lon="433534.946"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_12" id="92751ca9-a129-4994-96ab-c7831e257888">
        <port xsi:type="esdl:InPort" id="b35126b5-d3f3-4dd9-bff1-4fc37a94f819" name="In" connectedTo="010bb4a8-4f43-40b4-8641-364680347b35"/>
        <port xsi:type="esdl:OutPort" id="838a46f2-088d-4f66-987d-ea23d48f74b2" name="Out" connectedTo="7c415845-70c2-4131-b126-6d92471c1b29"/>
        <geometry xsi:type="esdl:Point" lat="158315.404" CRS="WGS84" lon="433536.902"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="7.7100546954092" name="lv_cable_trafo2_lvnetwork5_12_main_grid" id="0e41ac49-1522-4c2a-a90c-64e71755e836" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="483cbe38-114a-4a9f-bfca-7a8d7ec5d40c" name="In" connectedTo="6197389c-890e-40c2-9f78-733017717b16"/>
        <port xsi:type="esdl:OutPort" id="010bb4a8-4f43-40b4-8641-364680347b35" name="Out" connectedTo="b35126b5-d3f3-4dd9-bff1-4fc37a94f819"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158319.80298772277" CRS="WGS84" lon="433530.5986283095"/>
          <point xsi:type="esdl:Point" lat="158318.975" CRS="WGS84" lon="433531.524"/>
          <point xsi:type="esdl:Point" lat="158318.411378368" CRS="WGS84" lon="433532.210746963"/>
          <point xsi:type="esdl:Point" lat="158317.870937412" CRS="WGS84" lon="433532.91602763"/>
          <point xsi:type="esdl:Point" lat="158317.354284432" CRS="WGS84" lon="433533.639049465"/>
          <point xsi:type="esdl:Point" lat="158316.862" CRS="WGS84" lon="433534.379"/>
          <point xsi:type="esdl:Point" lat="158315.404" CRS="WGS84" lon="433536.902"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork5_13" id="31ec51d8-d291-4009-802d-5b793f8c3c08">
        <port xsi:type="esdl:InPort" id="55fdebfe-6d8d-45cd-8ac1-d5a5edf2ada5" name="In" connectedTo="dd8be0ab-49bd-42fe-8dea-458afd1b97e1"/>
        <port xsi:type="esdl:OutPort" id="1d54ffc9-2d1e-4360-b9d4-4ac8e4892229" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158314.82" CRS="WGS84" lon="433538.446"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.8697878313166219" name="lv_cable_trafo2_lvnetwork5_13_main_grid" id="f3c5ab30-13ca-4a47-849d-4e1db9f049c9" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="7c415845-70c2-4131-b126-6d92471c1b29" name="In" connectedTo="838a46f2-088d-4f66-987d-ea23d48f74b2"/>
        <port xsi:type="esdl:OutPort" id="dd8be0ab-49bd-42fe-8dea-458afd1b97e1" name="Out" connectedTo="55fdebfe-6d8d-45cd-8ac1-d5a5edf2ada5"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158315.404" CRS="WGS84" lon="433536.902"/>
          <point xsi:type="esdl:Point" lat="158314.604" CRS="WGS84" lon="433538.286"/>
          <point xsi:type="esdl:Point" lat="158314.734" CRS="WGS84" lon="433538.36"/>
          <point xsi:type="esdl:Point" lat="158314.82" CRS="WGS84" lon="433538.446"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo2_lvnetwork5" id="1fb26c3c-8b14-4766-a136-b83fe844ff31" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="f433e624-3179-49b9-8f58-f25160702453" name="Out" connectedTo="ca6ed08b-194b-48ef-ada2-caa8ab3b3ace"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo2_lvnetwork5" id="d86ac8e0-e772-4a4c-9c47-aa9d318541cd">
        <port xsi:type="esdl:InPort" id="ca6ed08b-194b-48ef-ada2-caa8ab3b3ace" name="In" connectedTo="f433e624-3179-49b9-8f58-f25160702453"/>
        <port xsi:type="esdl:OutPort" id="4c0f60df-1909-4dfd-a06e-77f1d0a67393" name="Out" connectedTo="93deb253-f6a7-48e5-a656-c00ffb46836d"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer14" id="3263f08d-b543-4b3f-a27c-7cf826f9fc8a" commissioningDate="1994-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="93deb253-f6a7-48e5-a656-c00ffb46836d" name="In" connectedTo="4c0f60df-1909-4dfd-a06e-77f1d0a67393"/>
        <port xsi:type="esdl:OutPort" id="9d302ec1-5905-45cd-a639-bd5937b61b79" name="Out" connectedTo="a92c22dd-648d-4c4d-9770-bfcc1d16eaf7"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint16" id="bf70eda3-fa8d-4895-b852-1797e060121a">
        <port xsi:type="esdl:InPort" id="a92c22dd-648d-4c4d-9770-bfcc1d16eaf7" name="In" connectedTo="9d302ec1-5905-45cd-a639-bd5937b61b79"/>
        <port xsi:type="esdl:OutPort" id="1fab438c-6a01-4b44-a0a8-7134058fbcf4" name="Out" connectedTo="239ac168-e349-4135-bebe-d1f5adff34f3"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
