<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="2deeaabf-869b-4a14-9334-4be8641a9673" description="Autogenerated based on gis data trafo7_lvnetwork0" name="trafo7_lvnetwork0">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="2a68035c-b797-42f6-82f9-ca3ff07ae113"/>
  <instance xsi:type="esdl:Instance" id="f1a26cf9-a799-479e-9403-44975de721f1" name="Instance name">
    <area xsi:type="esdl:Area" id="50650332-e0d7-4c54-975a-36652a09a75d" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork0_2" id="8e28e727-daf3-4981-9d0d-ce03d3028e0e">
        <port xsi:type="esdl:InPort" id="9eccd431-b29e-4ca1-bcb5-e26cc5e9de04" name="In" connectedTo="cca10dff-4ad8-44f2-87f9-63296646fb86"/>
        <port xsi:type="esdl:OutPort" id="a36820d5-ba31-47f4-a28f-011e3b600fae" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="157821.275" CRS="WGS84" lon="433301.151"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="70.00811442322615" name="lv_cable_trafo7_lvnetwork0_2_main_grid" id="07350fa7-ec6b-472c-91a3-7fb71d6ae9ec" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f2a73366-69ab-4f12-a6c8-b0d8b5ad85e6" name="In" connectedTo="82741782-a491-4a5b-8373-c4d26b11749d"/>
        <port xsi:type="esdl:OutPort" id="cca10dff-4ad8-44f2-87f9-63296646fb86" name="Out" connectedTo="9eccd431-b29e-4ca1-bcb5-e26cc5e9de04"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157788.149" CRS="WGS84" lon="433362.559"/>
          <point xsi:type="esdl:Point" lat="157788.603" CRS="WGS84" lon="433361.163"/>
          <point xsi:type="esdl:Point" lat="157802.078" CRS="WGS84" lon="433338.873"/>
          <point xsi:type="esdl:Point" lat="157808.51" CRS="WGS84" lon="433329.85"/>
          <point xsi:type="esdl:Point" lat="157820.711" CRS="WGS84" lon="433302.215"/>
          <point xsi:type="esdl:Point" lat="157821.275" CRS="WGS84" lon="433301.151"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo7_lvnetwork0" id="86de4b2e-d392-4eac-b672-cc51335d7e74" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="f4431243-7bc3-46bb-8721-6c5921b18f82" name="Out" connectedTo="3cabd335-25df-4121-b2f2-b81a18520123"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo7_lvnetwork0" id="fc98f8d6-8bde-4aae-858c-2381ae438ea8">
        <port xsi:type="esdl:InPort" id="3cabd335-25df-4121-b2f2-b81a18520123" name="In" connectedTo="f4431243-7bc3-46bb-8721-6c5921b18f82"/>
        <port xsi:type="esdl:OutPort" id="83a41a84-776b-4ba7-9962-5443a46cfe85" name="Out" connectedTo="91ac3b3e-367e-472e-8b2d-422867aa1b4e"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer44" id="1ac6e4df-d950-45b4-af2a-9162b1560977" commissioningDate="1964-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="91ac3b3e-367e-472e-8b2d-422867aa1b4e" name="In" connectedTo="83a41a84-776b-4ba7-9962-5443a46cfe85"/>
        <port xsi:type="esdl:OutPort" id="e19aa11d-d91b-49da-9c40-a52d2f0a591d" name="Out" connectedTo="c8c99296-721e-44b5-b112-0c880e6089a3"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint46" id="f9d51b6f-7e0a-44d5-aae2-a4fa8b4997e0">
        <port xsi:type="esdl:InPort" id="c8c99296-721e-44b5-b112-0c880e6089a3" name="In" connectedTo="e19aa11d-d91b-49da-9c40-a52d2f0a591d"/>
        <port xsi:type="esdl:OutPort" id="82741782-a491-4a5b-8373-c4d26b11749d" name="Out" connectedTo="f2a73366-69ab-4f12-a6c8-b0d8b5ad85e6"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
