<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="9752dab5-1eff-41fa-a2fd-26eb7ecc9023" description="Autogenerated based on gis data trafo2_lvnetwork6" name="trafo2_lvnetwork6">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="aba6d699-89e8-4215-80a7-1f7b99f71798"/>
  <instance xsi:type="esdl:Instance" id="312bb865-d91d-4b4b-9e68-37f2c3d24c31" name="Instance name">
    <area xsi:type="esdl:Area" id="fb287a9b-f652-4b2b-bca6-fe038330ed93" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork6_2" id="1e4d3b59-4bda-4808-a54b-a6d191cf1543">
        <port xsi:type="esdl:InPort" id="64fe9d31-04b0-4e19-869c-e796b2b49330" name="In" connectedTo="499005c9-6366-4731-a822-87dbbfec22f5"/>
        <port xsi:type="esdl:OutPort" id="0217b8e1-123a-4c98-8e19-812e9e2bb9cd" name="Out" connectedTo="76d54d62-2691-40ef-a303-16af96cab327 fb6af208-0a43-4fac-850a-f8d77ec592df"/>
        <geometry xsi:type="esdl:Point" lat="158337.94934649314" CRS="WGS84" lon="433433.76953749894"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="21.519122638718144" name="lv_cable_trafo2_lvnetwork6_2_main_grid" id="5f3b9e37-d741-4132-bc90-82510794e0dc" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="b2eae8de-4328-4987-8b53-9ffc5416a138" name="In" connectedTo="1fab438c-6a01-4b44-a0a8-7134058fbcf4"/>
        <port xsi:type="esdl:OutPort" id="499005c9-6366-4731-a822-87dbbfec22f5" name="Out" connectedTo="64fe9d31-04b0-4e19-869c-e796b2b49330"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158331.309" CRS="WGS84" lon="433446.008"/>
          <point xsi:type="esdl:Point" lat="158330.941" CRS="WGS84" lon="433446.474"/>
          <point xsi:type="esdl:Point" lat="158330.818" CRS="WGS84" lon="433446.407"/>
          <point xsi:type="esdl:Point" lat="158327.482" CRS="WGS84" lon="433443.085"/>
          <point xsi:type="esdl:Point" lat="158326.774" CRS="WGS84" lon="433441.978"/>
          <point xsi:type="esdl:Point" lat="158326.512" CRS="WGS84" lon="433441.406"/>
          <point xsi:type="esdl:Point" lat="158326.76" CRS="WGS84" lon="433440.911"/>
          <point xsi:type="esdl:Point" lat="158329.092" CRS="WGS84" lon="433438.864"/>
          <point xsi:type="esdl:Point" lat="158336.884" CRS="WGS84" lon="433435.406"/>
          <point xsi:type="esdl:Point" lat="158337.94934649314" CRS="WGS84" lon="433433.76953749894"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.0" name="lv_cable_trafo2_lvnetwork6_to_home_3_arch6" id="08d6556f-39ad-400c-93c1-64d94317bce5" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="76d54d62-2691-40ef-a303-16af96cab327" name="In" connectedTo="0217b8e1-123a-4c98-8e19-812e9e2bb9cd"/>
        <port xsi:type="esdl:OutPort" id="a01e700c-e22e-4924-b1f5-b3a0b8da716c" name="Out" connectedTo="562b7e1c-e272-49e2-b3ce-b49be5b7a176"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158337.94934649314" CRS="WGS84" lon="433433.76953749894"/>
          <point xsi:type="esdl:Point" lat="158337.94934649314" CRS="WGS84" lon="433433.76953749894"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome532" id="6c18a149-e8a9-4793-90f6-9f32c1671565">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="2ae87083-9c5a-440d-b709-255d7e79a935" name="In" connectedTo="3524592a-ffb6-45ee-a3ba-5b90f2a24596"/>
          <port xsi:type="esdl:OutPort" id="31cabc42-5a3a-4e39-9f63-5e274a34d74f" name="Out" connectedTo="3abc6413-15eb-470f-87fa-075b638baeab"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="171d582d-899a-4ca9-8aa1-11ad861a41b3" name="In" connectedTo="7d90e149-a281-4986-94a6-20aeb9068984"/>
          <port xsi:type="esdl:OutPort" id="f42ae063-d6f3-47b9-9bd1-7ea4d448df84" name="Out" connectedTo="949e4ea1-8145-490a-8faa-2dd1b22571f5"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="151bdc5a-89c0-44cd-bf1c-cba02f04e435" name="In" connectedTo="a17120b1-c20f-4bbb-a1f8-fcf2fbfa7714"/>
          <port xsi:type="esdl:OutPort" id="9334920b-e72e-4abf-bb51-5b09a82905dc" name="Out" connectedTo="464bed16-fd60-44d5-9186-0bf83b1458c2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="c9eaaf76-0395-44fc-91f3-8c85e657f231" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="3abc6413-15eb-470f-87fa-075b638baeab" name="In_Ph1" connectedTo="31cabc42-5a3a-4e39-9f63-5e274a34d74f"/>
          <port xsi:type="esdl:InPort" id="949e4ea1-8145-490a-8faa-2dd1b22571f5" name="In_Ph2" connectedTo="f42ae063-d6f3-47b9-9bd1-7ea4d448df84"/>
          <port xsi:type="esdl:InPort" id="464bed16-fd60-44d5-9186-0bf83b1458c2" name="In_Ph3" connectedTo="9334920b-e72e-4abf-bb51-5b09a82905dc"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome532" id="a48fdf15-0763-4fd4-9e4e-7566dd1ead3e">
          <port xsi:type="esdl:InPort" id="562b7e1c-e272-49e2-b3ce-b49be5b7a176" name="In" connectedTo="a01e700c-e22e-4924-b1f5-b3a0b8da716c"/>
          <port xsi:type="esdl:OutPort" id="3524592a-ffb6-45ee-a3ba-5b90f2a24596" name="OutPh1" connectedTo="2ae87083-9c5a-440d-b709-255d7e79a935"/>
          <port xsi:type="esdl:OutPort" id="7d90e149-a281-4986-94a6-20aeb9068984" name="OutPh2" connectedTo="171d582d-899a-4ca9-8aa1-11ad861a41b3"/>
          <port xsi:type="esdl:OutPort" id="a17120b1-c20f-4bbb-a1f8-fcf2fbfa7714" name="OutPh3" connectedTo="151bdc5a-89c0-44cd-bf1c-cba02f04e435"/>
          <geometry xsi:type="esdl:Point" lat="158337.94934649314" lon="433433.76953749894"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork6_3" id="24ea4208-9c81-4e37-8d23-63e99ff733dd">
        <port xsi:type="esdl:InPort" id="7b004442-f5f1-4b58-aef7-309f49163976" name="In" connectedTo="fde5e29c-a29b-449b-8625-a3e5bca087f8"/>
        <port xsi:type="esdl:OutPort" id="c1e8da87-f80e-4b51-a50f-36b07a1b7ccb" name="Out" connectedTo="c20fe550-e643-4930-a7dc-3bceca2a5f2c e982ccdb-64dd-424d-817b-0dfbbe66fed5"/>
        <geometry xsi:type="esdl:Point" lat="158341.415" CRS="WGS84" lon="433428.446"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="6.352228406812726" name="lv_cable_trafo2_lvnetwork6_3_main_grid" id="a2b90222-1df1-451b-8c74-f2880a339b43" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="fb6af208-0a43-4fac-850a-f8d77ec592df" name="In" connectedTo="0217b8e1-123a-4c98-8e19-812e9e2bb9cd"/>
        <port xsi:type="esdl:OutPort" id="fde5e29c-a29b-449b-8625-a3e5bca087f8" name="Out" connectedTo="7b004442-f5f1-4b58-aef7-309f49163976"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158337.94934649314" CRS="WGS84" lon="433433.76953749894"/>
          <point xsi:type="esdl:Point" lat="158341.415" CRS="WGS84" lon="433428.446"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.538048494004301" name="lv_cable_trafo2_lvnetwork6_to_home_0_arch6" id="ca049c87-1e5f-42b2-9649-4d7ba9d8a199" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="c20fe550-e643-4930-a7dc-3bceca2a5f2c" name="In" connectedTo="c1e8da87-f80e-4b51-a50f-36b07a1b7ccb"/>
        <port xsi:type="esdl:OutPort" id="1ab559db-d749-49c7-ae8e-e8ddab5067c1" name="Out" connectedTo="0586ba96-23ed-4657-b32b-975a1519e39a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158343.62763312916" CRS="WGS84" lon="433429.68936028314"/>
          <point xsi:type="esdl:Point" lat="158341.415" CRS="WGS84" lon="433428.446"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome529" id="9eb425ff-765d-46d0-b9c9-ef6393644722">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="43a1db03-37dd-4039-bbb8-74b7c03658e8" name="In" connectedTo="1293ef38-28fa-46e2-8d3a-5f2172b7ecca"/>
          <port xsi:type="esdl:OutPort" id="db78d4a8-fbee-45f4-92bd-e87fb856e984" name="Out" connectedTo="717f7ca5-49a1-4457-a245-b3dabfa2bc33"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="ffe68adb-750e-4530-b0de-b28b630ed2b4" name="In" connectedTo="194ddc68-b5e9-4818-beb0-1dbc36fbf158"/>
          <port xsi:type="esdl:OutPort" id="37c43bd5-6204-4fb7-a96e-9c872ec68d6d" name="Out" connectedTo="27a865b5-257c-4c4d-90b1-fbbbd24e8757"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="263bfaab-694e-4575-a4d3-8541197e0052" name="In" connectedTo="195a3b73-f9c5-40e2-b1ba-46185d653842"/>
          <port xsi:type="esdl:OutPort" id="6316d66f-ed30-4b7a-b5b4-ba6268f74332" name="Out" connectedTo="134552bd-c092-4d89-a913-7aeeacc61c1d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="562961ab-c37e-43e5-af19-f4b089bd55cf" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="717f7ca5-49a1-4457-a245-b3dabfa2bc33" name="In_Ph1" connectedTo="db78d4a8-fbee-45f4-92bd-e87fb856e984"/>
          <port xsi:type="esdl:InPort" id="27a865b5-257c-4c4d-90b1-fbbbd24e8757" name="In_Ph2" connectedTo="37c43bd5-6204-4fb7-a96e-9c872ec68d6d"/>
          <port xsi:type="esdl:InPort" id="134552bd-c092-4d89-a913-7aeeacc61c1d" name="In_Ph3" connectedTo="6316d66f-ed30-4b7a-b5b4-ba6268f74332"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome529" id="a6f3349b-d95b-48d5-8bab-88e693d6ee4d">
          <port xsi:type="esdl:InPort" id="0586ba96-23ed-4657-b32b-975a1519e39a" name="In" connectedTo="1ab559db-d749-49c7-ae8e-e8ddab5067c1"/>
          <port xsi:type="esdl:OutPort" id="1293ef38-28fa-46e2-8d3a-5f2172b7ecca" name="OutPh1" connectedTo="43a1db03-37dd-4039-bbb8-74b7c03658e8"/>
          <port xsi:type="esdl:OutPort" id="194ddc68-b5e9-4818-beb0-1dbc36fbf158" name="OutPh2" connectedTo="ffe68adb-750e-4530-b0de-b28b630ed2b4"/>
          <port xsi:type="esdl:OutPort" id="195a3b73-f9c5-40e2-b1ba-46185d653842" name="OutPh3" connectedTo="263bfaab-694e-4575-a4d3-8541197e0052"/>
          <geometry xsi:type="esdl:Point" lat="158343.62763312916" lon="433429.68936028314"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork6_4" id="31b7b1aa-aeb2-4235-854c-0bf74b307713">
        <port xsi:type="esdl:InPort" id="a006cf90-2972-454d-804d-db7bfdcf6d6d" name="In" connectedTo="a35878c1-2774-4ee5-a14e-0deb450de7c5"/>
        <port xsi:type="esdl:OutPort" id="820a9593-feae-430b-a47a-44c3d21a4a73" name="Out" connectedTo="57053ba2-406b-43cd-8eed-51cbc3949594 86b31192-d2a4-43c7-800e-3dff1f41ce57"/>
        <geometry xsi:type="esdl:Point" lat="158429.55151419388" CRS="WGS84" lon="433446.4137718358"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="122.39496376955064" name="lv_cable_trafo2_lvnetwork6_4_main_grid" id="35929d24-66bc-4c26-9aa1-d22eb105f1a3" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="e982ccdb-64dd-424d-817b-0dfbbe66fed5" name="In" connectedTo="c1e8da87-f80e-4b51-a50f-36b07a1b7ccb"/>
        <port xsi:type="esdl:OutPort" id="a35878c1-2774-4ee5-a14e-0deb450de7c5" name="Out" connectedTo="a006cf90-2972-454d-804d-db7bfdcf6d6d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158341.415" CRS="WGS84" lon="433428.446"/>
          <point xsi:type="esdl:Point" lat="158343.517" CRS="WGS84" lon="433424.16"/>
          <point xsi:type="esdl:Point" lat="158347.685" CRS="WGS84" lon="433416.713"/>
          <point xsi:type="esdl:Point" lat="158348.487" CRS="WGS84" lon="433416.458"/>
          <point xsi:type="esdl:Point" lat="158349.085" CRS="WGS84" lon="433416.45"/>
          <point xsi:type="esdl:Point" lat="158352.557" CRS="WGS84" lon="433418.542"/>
          <point xsi:type="esdl:Point" lat="158355.799" CRS="WGS84" lon="433420.791"/>
          <point xsi:type="esdl:Point" lat="158358.367" CRS="WGS84" lon="433422.79"/>
          <point xsi:type="esdl:Point" lat="158364.125" CRS="WGS84" lon="433427.657"/>
          <point xsi:type="esdl:Point" lat="158368.85" CRS="WGS84" lon="433434.55"/>
          <point xsi:type="esdl:Point" lat="158374.713" CRS="WGS84" lon="433445.445"/>
          <point xsi:type="esdl:Point" lat="158376.306" CRS="WGS84" lon="433448.6"/>
          <point xsi:type="esdl:Point" lat="158379.224" CRS="WGS84" lon="433453.444"/>
          <point xsi:type="esdl:Point" lat="158384.101" CRS="WGS84" lon="433462.417"/>
          <point xsi:type="esdl:Point" lat="158384.537" CRS="WGS84" lon="433462.795"/>
          <point xsi:type="esdl:Point" lat="158385.106" CRS="WGS84" lon="433462.917"/>
          <point xsi:type="esdl:Point" lat="158387.803" CRS="WGS84" lon="433461.839"/>
          <point xsi:type="esdl:Point" lat="158398.041" CRS="WGS84" lon="433457.483"/>
          <point xsi:type="esdl:Point" lat="158401.095" CRS="WGS84" lon="433456.028"/>
          <point xsi:type="esdl:Point" lat="158402.753" CRS="WGS84" lon="433455.465"/>
          <point xsi:type="esdl:Point" lat="158406.827" CRS="WGS84" lon="433453.789"/>
          <point xsi:type="esdl:Point" lat="158410.458" CRS="WGS84" lon="433452.194"/>
          <point xsi:type="esdl:Point" lat="158414.197" CRS="WGS84" lon="433450.911"/>
          <point xsi:type="esdl:Point" lat="158417.925" CRS="WGS84" lon="433450.47"/>
          <point xsi:type="esdl:Point" lat="158425.285" CRS="WGS84" lon="433447.679"/>
          <point xsi:type="esdl:Point" lat="158429.55151419388" CRS="WGS84" lon="433446.4137718358"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.777183251902492" name="lv_cable_trafo2_lvnetwork6_to_home_1_arch6" id="b7b3380d-e9e7-4d34-9e83-417416d11a24" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="57053ba2-406b-43cd-8eed-51cbc3949594" name="In" connectedTo="820a9593-feae-430b-a47a-44c3d21a4a73"/>
        <port xsi:type="esdl:OutPort" id="46f8ce9e-ed18-4571-a473-e77cd5d6d0c8" name="Out" connectedTo="67ec98ed-8022-4b0b-8300-d0a2b57c03f7"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158427.909" CRS="WGS84" lon="433440.875"/>
          <point xsi:type="esdl:Point" lat="158429.55151419388" CRS="WGS84" lon="433446.4137718358"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="7xhome530" id="9c16edff-4972-48f5-b4f2-74ab5c22c929">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="ccb326c1-f575-4c5f-913b-a9ea6fb2f949" name="In" connectedTo="55f3c556-a0ec-4489-998e-eb6d0b17e742"/>
          <port xsi:type="esdl:OutPort" id="a5124b07-73d8-46f9-8553-ac8986c5e0fc" name="Out" connectedTo="0cec49d3-8536-4405-8a82-a6f97038ca04"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="d2e49638-7d25-44f7-9ce5-dcad2a2950d5" name="In" connectedTo="5c1c6c6a-d477-4742-a79d-788938a6fdeb"/>
          <port xsi:type="esdl:OutPort" id="eb78b10e-f77e-4cf8-b449-c886466029e4" name="Out" connectedTo="89bba288-c09a-43e9-a823-00c9617370c8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="69a17a54-0d19-449d-8022-4a5f9ac91620" name="In" connectedTo="62363103-2df4-4d1c-a67f-be99bb64f33e"/>
          <port xsi:type="esdl:OutPort" id="95096a33-68b6-4dab-89e9-1086e3938964" name="Out" connectedTo="60ecef39-be6c-4039-9e65-69a2a19b5910"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="87387e16-dae0-46be-acb0-c13fef721701" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="0cec49d3-8536-4405-8a82-a6f97038ca04" name="In_Ph1" connectedTo="a5124b07-73d8-46f9-8553-ac8986c5e0fc"/>
          <port xsi:type="esdl:InPort" id="89bba288-c09a-43e9-a823-00c9617370c8" name="In_Ph2" connectedTo="eb78b10e-f77e-4cf8-b449-c886466029e4"/>
          <port xsi:type="esdl:InPort" id="60ecef39-be6c-4039-9e65-69a2a19b5910" name="In_Ph3" connectedTo="95096a33-68b6-4dab-89e9-1086e3938964"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="7xhome530" id="089df27c-d841-44f6-be44-3d82ffd93c77">
          <port xsi:type="esdl:InPort" id="67ec98ed-8022-4b0b-8300-d0a2b57c03f7" name="In" connectedTo="46f8ce9e-ed18-4571-a473-e77cd5d6d0c8"/>
          <port xsi:type="esdl:OutPort" id="55f3c556-a0ec-4489-998e-eb6d0b17e742" name="OutPh1" connectedTo="ccb326c1-f575-4c5f-913b-a9ea6fb2f949"/>
          <port xsi:type="esdl:OutPort" id="5c1c6c6a-d477-4742-a79d-788938a6fdeb" name="OutPh2" connectedTo="d2e49638-7d25-44f7-9ce5-dcad2a2950d5"/>
          <port xsi:type="esdl:OutPort" id="62363103-2df4-4d1c-a67f-be99bb64f33e" name="OutPh3" connectedTo="69a17a54-0d19-449d-8022-4a5f9ac91620"/>
          <geometry xsi:type="esdl:Point" lat="158427.909" lon="433440.875"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork6_5" id="d459a4fa-2289-42f8-8c4a-1753f56ac036">
        <port xsi:type="esdl:InPort" id="72054aba-597d-4dcc-a13b-262b045b8535" name="In" connectedTo="7f08c61e-7839-4572-8832-5607d73ca5a3"/>
        <port xsi:type="esdl:OutPort" id="20aaabd4-f9c4-4d7b-a48e-a1be0cdda7ca" name="Out" connectedTo="fff738fb-19ed-452e-82b5-beb4eb31b64b ba004d06-a8e9-4d5c-9681-a1cfd76cd84a"/>
        <geometry xsi:type="esdl:Point" lat="158448.516" CRS="WGS84" lon="433442.92"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="19.316444252976392" name="lv_cable_trafo2_lvnetwork6_5_main_grid" id="d9a0cdb1-b2bc-4970-95dc-86faf7a5d75a" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="86b31192-d2a4-43c7-800e-3dff1f41ce57" name="In" connectedTo="820a9593-feae-430b-a47a-44c3d21a4a73"/>
        <port xsi:type="esdl:OutPort" id="7f08c61e-7839-4572-8832-5607d73ca5a3" name="Out" connectedTo="72054aba-597d-4dcc-a13b-262b045b8535"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158429.55151419388" CRS="WGS84" lon="433446.4137718358"/>
          <point xsi:type="esdl:Point" lat="158438.707" CRS="WGS84" lon="433444.155"/>
          <point xsi:type="esdl:Point" lat="158448.516" CRS="WGS84" lon="433442.92"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.9296446711124199" name="lv_cable_trafo2_lvnetwork6_to_home_2_arch6" id="9fcf264b-b75c-4cd0-8504-7851df841c8f" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="fff738fb-19ed-452e-82b5-beb4eb31b64b" name="In" connectedTo="20aaabd4-f9c4-4d7b-a48e-a1be0cdda7ca"/>
        <port xsi:type="esdl:OutPort" id="f6863ee8-7d06-4335-9682-9423ee4ddf09" name="Out" connectedTo="117a1558-b706-4f74-a770-c67f7e3efc2e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158448.42934450856" CRS="WGS84" lon="433441.9944028736"/>
          <point xsi:type="esdl:Point" lat="158448.516" CRS="WGS84" lon="433442.92"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome531" id="c0c6f4d1-e677-42c1-9e91-273a222e9298">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="3016cc8c-7710-48f6-baa7-ac531c189d1b" name="In" connectedTo="768219ab-9102-486d-ab0b-8fa6e581bc54"/>
          <port xsi:type="esdl:OutPort" id="1b2d3f92-e114-49c9-8814-a001d7ccadc2" name="Out" connectedTo="8017908c-7786-4004-8f1f-db56ef6fe4d9"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="b56b8412-8f22-4745-ab65-797e5dc9c5a5" name="In" connectedTo="ea7d6db0-b223-4a38-b6ee-1d9d4f34c265"/>
          <port xsi:type="esdl:OutPort" id="afb63fa9-07c2-4c2b-a9bf-22aa4a5449f0" name="Out" connectedTo="298331e5-757a-40b0-aaa9-0ef2d2fb5596"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="b11b5add-ce81-45fa-979a-0fc1e448d73b" name="In" connectedTo="c1a57611-1572-4131-b0bb-e320a93fd7e4"/>
          <port xsi:type="esdl:OutPort" id="c31edc43-b5ea-404b-88db-9374bf8d502f" name="Out" connectedTo="6f032af6-5a96-4b18-a0a4-4dea0215d6ed"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="1f9bdca5-98ef-410c-a3d5-a597d9ae4ecd" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="8017908c-7786-4004-8f1f-db56ef6fe4d9" name="In_Ph1" connectedTo="1b2d3f92-e114-49c9-8814-a001d7ccadc2"/>
          <port xsi:type="esdl:InPort" id="298331e5-757a-40b0-aaa9-0ef2d2fb5596" name="In_Ph2" connectedTo="afb63fa9-07c2-4c2b-a9bf-22aa4a5449f0"/>
          <port xsi:type="esdl:InPort" id="6f032af6-5a96-4b18-a0a4-4dea0215d6ed" name="In_Ph3" connectedTo="c31edc43-b5ea-404b-88db-9374bf8d502f"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome531" id="089bcf1d-b453-4e17-808e-de4a1704d1d8">
          <port xsi:type="esdl:InPort" id="117a1558-b706-4f74-a770-c67f7e3efc2e" name="In" connectedTo="f6863ee8-7d06-4335-9682-9423ee4ddf09"/>
          <port xsi:type="esdl:OutPort" id="768219ab-9102-486d-ab0b-8fa6e581bc54" name="OutPh1" connectedTo="3016cc8c-7710-48f6-baa7-ac531c189d1b"/>
          <port xsi:type="esdl:OutPort" id="ea7d6db0-b223-4a38-b6ee-1d9d4f34c265" name="OutPh2" connectedTo="b56b8412-8f22-4745-ab65-797e5dc9c5a5"/>
          <port xsi:type="esdl:OutPort" id="c1a57611-1572-4131-b0bb-e320a93fd7e4" name="OutPh3" connectedTo="b11b5add-ce81-45fa-979a-0fc1e448d73b"/>
          <geometry xsi:type="esdl:Point" lat="158448.42934450856" lon="433441.9944028736"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo2_lvnetwork6_6" id="95d09eb2-275b-4666-81f5-ca44bb7cbb99">
        <port xsi:type="esdl:InPort" id="044bf79c-94ff-4462-9e59-d2670f26fb74" name="In" connectedTo="c1a2abed-6041-484f-ac99-d75cb23e3a3d"/>
        <port xsi:type="esdl:OutPort" id="47e796c9-5879-47ac-bde4-4b6d570e1e88" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158462.07" CRS="WGS84" lon="433441.912"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.598688149688996" name="lv_cable_trafo2_lvnetwork6_6_main_grid" id="dbe23f0b-37b5-4b21-ad37-624e27f8e702" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="ba004d06-a8e9-4d5c-9681-a1cfd76cd84a" name="In" connectedTo="20aaabd4-f9c4-4d7b-a48e-a1be0cdda7ca"/>
        <port xsi:type="esdl:OutPort" id="c1a2abed-6041-484f-ac99-d75cb23e3a3d" name="Out" connectedTo="044bf79c-94ff-4462-9e59-d2670f26fb74"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158448.516" CRS="WGS84" lon="433442.92"/>
          <point xsi:type="esdl:Point" lat="158460.629" CRS="WGS84" lon="433441.9"/>
          <point xsi:type="esdl:Point" lat="158460.948" CRS="WGS84" lon="433441.873"/>
          <point xsi:type="esdl:Point" lat="158461.284" CRS="WGS84" lon="433441.885"/>
          <point xsi:type="esdl:Point" lat="158462.07" CRS="WGS84" lon="433441.912"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo2_lvnetwork6" id="4c9d33fd-5b61-4b9b-9c2a-75a36b9541c0" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="e05e043c-a854-42b4-8831-e6ff06c0d368" name="Out" connectedTo="7171a7ce-b4c1-4025-9f22-906de832f083"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo2_lvnetwork6" id="abf37122-981d-4588-8584-f99862e88159">
        <port xsi:type="esdl:InPort" id="7171a7ce-b4c1-4025-9f22-906de832f083" name="In" connectedTo="e05e043c-a854-42b4-8831-e6ff06c0d368"/>
        <port xsi:type="esdl:OutPort" id="efc40e6e-965d-4a10-bd70-4d67730213f9" name="Out" connectedTo="93deb253-f6a7-48e5-a656-c00ffb46836d"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer14" id="3263f08d-b543-4b3f-a27c-7cf826f9fc8a" commissioningDate="1994-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="93deb253-f6a7-48e5-a656-c00ffb46836d" name="In" connectedTo="efc40e6e-965d-4a10-bd70-4d67730213f9"/>
        <port xsi:type="esdl:OutPort" id="9d302ec1-5905-45cd-a639-bd5937b61b79" name="Out" connectedTo="a92c22dd-648d-4c4d-9770-bfcc1d16eaf7"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint16" id="bf70eda3-fa8d-4895-b852-1797e060121a">
        <port xsi:type="esdl:InPort" id="a92c22dd-648d-4c4d-9770-bfcc1d16eaf7" name="In" connectedTo="9d302ec1-5905-45cd-a639-bd5937b61b79"/>
        <port xsi:type="esdl:OutPort" id="1fab438c-6a01-4b44-a0a8-7134058fbcf4" name="Out" connectedTo="b2eae8de-4328-4987-8b53-9ffc5416a138"/>
        <geometry xsi:type="esdl:Point" lat="158327.442" CRS="WGS84" lon="433442.099"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
