<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="2949fb6b-e64f-4d96-a78f-09da47c074d7" description="Autogenerated based on gis data trafo4_lvnetwork3" name="trafo4_lvnetwork3">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="38352382-806f-4a91-bb1b-6c7738badd63"/>
  <instance xsi:type="esdl:Instance" id="8605844c-7640-4caa-a8a1-d181d39851fa" name="Instance name">
    <area xsi:type="esdl:Area" id="eaba339c-30a5-43a0-99f3-d9eae1abcf13" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_2" id="67067cbe-4ae7-410d-b1d4-dbf695bc5b8e">
        <port xsi:type="esdl:InPort" id="5fc17946-d87f-4fdd-a384-0322a2d4b49f" name="In" connectedTo="d7a92826-c882-4112-9e59-e0b67bb8c141"/>
        <port xsi:type="esdl:OutPort" id="fcf0ba13-9494-4228-bb7e-aa3927934caf" name="Out" connectedTo="96aa6bb5-a309-4911-bc19-928c41f2264b"/>
        <geometry xsi:type="esdl:Point" lat="158208.351" CRS="WGS84" lon="433222.676"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="36.6051458653157" name="lv_cable_trafo4_lvnetwork3_2_main_grid" id="eee7a8a1-077a-4c43-a856-6aa989135545" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="198af419-4a26-4543-a8f5-fd16b57d7549" name="In" connectedTo="dd03e995-3b79-4a24-8e08-95f175bed17d"/>
        <port xsi:type="esdl:OutPort" id="d7a92826-c882-4112-9e59-e0b67bb8c141" name="Out" connectedTo="5fc17946-d87f-4fdd-a384-0322a2d4b49f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158194.668" CRS="WGS84" lon="433199.192"/>
          <point xsi:type="esdl:Point" lat="158194.731" CRS="WGS84" lon="433200.843"/>
          <point xsi:type="esdl:Point" lat="158195.78" CRS="WGS84" lon="433200.801"/>
          <point xsi:type="esdl:Point" lat="158207.181" CRS="WGS84" lon="433200.341"/>
          <point xsi:type="esdl:Point" lat="158207.841" CRS="WGS84" lon="433211.821"/>
          <point xsi:type="esdl:Point" lat="158208.922" CRS="WGS84" lon="433218.729"/>
          <point xsi:type="esdl:Point" lat="158208.671092585" CRS="WGS84" lon="433219.688523059"/>
          <point xsi:type="esdl:Point" lat="158208.491697772" CRS="WGS84" lon="433220.66981672"/>
          <point xsi:type="esdl:Point" lat="158208.384803933" CRS="WGS84" lon="433221.667474561"/>
          <point xsi:type="esdl:Point" lat="158208.351" CRS="WGS84" lon="433222.676"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_3" id="d045b44c-2601-49b7-b2ca-fe1670cc0682">
        <port xsi:type="esdl:InPort" id="a6de8533-4e9e-4cc1-9205-911ef889774a" name="In" connectedTo="f54e386d-ab1b-4db0-a6ba-683bee4bc939"/>
        <port xsi:type="esdl:OutPort" id="c9e21870-3ca7-4cf3-a079-f0fa2ec70cf6" name="Out" connectedTo="2f3d7e4e-dd82-4d4c-a7f6-d9582c22fb51 7969b8df-ab08-47ac-9be1-2f7b372d6c1b"/>
        <geometry xsi:type="esdl:Point" lat="158241.4027093038" CRS="WGS84" lon="433228.88295243535"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="41.098767252490255" name="lv_cable_trafo4_lvnetwork3_3_main_grid" id="4f2bdf61-2630-47af-9c60-922595294ded" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="96aa6bb5-a309-4911-bc19-928c41f2264b" name="In" connectedTo="fcf0ba13-9494-4228-bb7e-aa3927934caf"/>
        <port xsi:type="esdl:OutPort" id="f54e386d-ab1b-4db0-a6ba-683bee4bc939" name="Out" connectedTo="a6de8533-4e9e-4cc1-9205-911ef889774a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158208.351" CRS="WGS84" lon="433222.676"/>
          <point xsi:type="esdl:Point" lat="158208.351239985" CRS="WGS84" lon="433222.760982815"/>
          <point xsi:type="esdl:Point" lat="158208.352" CRS="WGS84" lon="433222.846"/>
          <point xsi:type="esdl:Point" lat="158208.385" CRS="WGS84" lon="433223.275"/>
          <point xsi:type="esdl:Point" lat="158208.994" CRS="WGS84" lon="433231.227"/>
          <point xsi:type="esdl:Point" lat="158215.56" CRS="WGS84" lon="433230.91"/>
          <point xsi:type="esdl:Point" lat="158222.172" CRS="WGS84" lon="433230.885"/>
          <point xsi:type="esdl:Point" lat="158222.42" CRS="WGS84" lon="433230.87"/>
          <point xsi:type="esdl:Point" lat="158222.622" CRS="WGS84" lon="433230.856"/>
          <point xsi:type="esdl:Point" lat="158223.022" CRS="WGS84" lon="433230.824"/>
          <point xsi:type="esdl:Point" lat="158227.932879108" CRS="WGS84" lon="433230.408289603"/>
          <point xsi:type="esdl:Point" lat="158232.837057263" CRS="WGS84" lon="433229.919811885"/>
          <point xsi:type="esdl:Point" lat="158237.733456358" CRS="WGS84" lon="433229.358674232"/>
          <point xsi:type="esdl:Point" lat="158241.4027093038" CRS="WGS84" lon="433228.88295243535"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.475298921409582" name="lv_cable_trafo4_lvnetwork3_to_home_0_arch5" id="69b630d0-e5f0-466f-ac9f-cb966271c39d" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="2f3d7e4e-dd82-4d4c-a7f6-d9582c22fb51" name="In" connectedTo="c9e21870-3ca7-4cf3-a079-f0fa2ec70cf6"/>
        <port xsi:type="esdl:OutPort" id="c307f4b6-ae87-499a-9af0-71e0a8e2ec4c" name="Out" connectedTo="3853567e-664b-4270-aa06-33fd17e63a97"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158240.313" CRS="WGS84" lon="433220.478"/>
          <point xsi:type="esdl:Point" lat="158241.4027093038" CRS="WGS84" lon="433228.88295243535"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="5xhome580" id="3c82dd92-2b7e-4883-b4ac-6c8d36b1671a">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="e9a92e5d-bc1d-49ed-9726-a31d26095db5" name="In" connectedTo="4b038da0-931d-4ed9-aeb8-66c9d58820ea"/>
          <port xsi:type="esdl:OutPort" id="4d8e220f-56ee-4448-995b-7f0b203d2138" name="Out" connectedTo="d6618b07-1eca-47b4-a90c-266d12400e10"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="54606ff7-d53d-4a86-8ad4-8f0aa53aa4a5" name="In" connectedTo="90b67f41-19cb-4fae-94ea-946e5235d4e6"/>
          <port xsi:type="esdl:OutPort" id="516613aa-15e5-4e00-9478-64e51bc96b2c" name="Out" connectedTo="2bb4507e-e401-41df-9121-506fe7fadac8"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="c6b0f62a-9261-4429-8c4f-efa7dd41a2d5" name="In" connectedTo="b9e941b3-123b-4d2f-99c0-a86129b9ec22"/>
          <port xsi:type="esdl:OutPort" id="ce4e9565-6cc1-47dc-abba-c2f78b1057ea" name="Out" connectedTo="96d0efa6-38a0-4d75-9e5c-550a8ae51685"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="9bcda306-2d27-45bb-8bdc-61122cc8fef9" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="d6618b07-1eca-47b4-a90c-266d12400e10" name="In_Ph1" connectedTo="4d8e220f-56ee-4448-995b-7f0b203d2138"/>
          <port xsi:type="esdl:InPort" id="2bb4507e-e401-41df-9121-506fe7fadac8" name="In_Ph2" connectedTo="516613aa-15e5-4e00-9478-64e51bc96b2c"/>
          <port xsi:type="esdl:InPort" id="96d0efa6-38a0-4d75-9e5c-550a8ae51685" name="In_Ph3" connectedTo="ce4e9565-6cc1-47dc-abba-c2f78b1057ea"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="5xhome580" id="88994236-1724-4d32-a599-cec7417adfe2">
          <port xsi:type="esdl:InPort" id="3853567e-664b-4270-aa06-33fd17e63a97" name="In" connectedTo="c307f4b6-ae87-499a-9af0-71e0a8e2ec4c"/>
          <port xsi:type="esdl:OutPort" id="4b038da0-931d-4ed9-aeb8-66c9d58820ea" name="OutPh1" connectedTo="e9a92e5d-bc1d-49ed-9726-a31d26095db5"/>
          <port xsi:type="esdl:OutPort" id="90b67f41-19cb-4fae-94ea-946e5235d4e6" name="OutPh2" connectedTo="54606ff7-d53d-4a86-8ad4-8f0aa53aa4a5"/>
          <port xsi:type="esdl:OutPort" id="b9e941b3-123b-4d2f-99c0-a86129b9ec22" name="OutPh3" connectedTo="c6b0f62a-9261-4429-8c4f-efa7dd41a2d5"/>
          <geometry xsi:type="esdl:Point" lat="158240.313" lon="433220.478"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_4" id="6a734453-7075-4356-97c6-8d1ec15fd1c3">
        <port xsi:type="esdl:InPort" id="e98880ce-c915-4f07-8480-0c72ffad2f15" name="In" connectedTo="34608c09-647b-4d6d-9660-6d2b3f2b0849"/>
        <port xsi:type="esdl:OutPort" id="458a73d5-a5b3-4444-954d-a321ac0f0d5f" name="Out" connectedTo="39f8ba8f-2358-454c-b23e-42cbfa24afe8 52f6c4c3-dcc4-4376-9a44-d873bdc92f68"/>
        <geometry xsi:type="esdl:Point" lat="158251.3611034781" CRS="WGS84" lon="433227.16773345816"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.106703760091163" name="lv_cable_trafo4_lvnetwork3_4_main_grid" id="60cd3117-6ee4-44f9-9439-52f46f4a73ab" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="7969b8df-ab08-47ac-9be1-2f7b372d6c1b" name="In" connectedTo="c9e21870-3ca7-4cf3-a079-f0fa2ec70cf6"/>
        <port xsi:type="esdl:OutPort" id="34608c09-647b-4d6d-9660-6d2b3f2b0849" name="Out" connectedTo="e98880ce-c915-4f07-8480-0c72ffad2f15"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158241.4027093038" CRS="WGS84" lon="433228.88295243535"/>
          <point xsi:type="esdl:Point" lat="158242.827" CRS="WGS84" lon="433228.697"/>
          <point xsi:type="esdl:Point" lat="158243.085" CRS="WGS84" lon="433228.66"/>
          <point xsi:type="esdl:Point" lat="158248.399" CRS="WGS84" lon="433227.724"/>
          <point xsi:type="esdl:Point" lat="158251.3611034781" CRS="WGS84" lon="433227.16773345816"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.08971696161201" name="lv_cable_trafo4_lvnetwork3_to_home_1_arch5" id="5bc077c6-0ded-4d79-8fdd-35f5f02d4b0e" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="39f8ba8f-2358-454c-b23e-42cbfa24afe8" name="In" connectedTo="458a73d5-a5b3-4444-954d-a321ac0f0d5f"/>
        <port xsi:type="esdl:OutPort" id="4709c5a8-88fa-4545-9fb3-7fa7c12c1190" name="Out" connectedTo="d3b5f0b8-a0ce-4430-9d63-e8e68987ca9b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158249.868" CRS="WGS84" lon="433219.217"/>
          <point xsi:type="esdl:Point" lat="158251.3611034781" CRS="WGS84" lon="433227.16773345816"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="3xhome581" id="ebcc54ef-8644-4a7b-bc02-5f059ae333a2">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="47f70970-19b1-4062-8121-bdf1096858f7" name="In" connectedTo="78e6a686-273a-44ed-87b9-0ab6168ea235"/>
          <port xsi:type="esdl:OutPort" id="6817967e-26c6-4b30-82a7-9b44873200ad" name="Out" connectedTo="41095f82-960b-446c-9e75-1a857c37d5be"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="d65bdbfc-a970-4755-9682-159875b56bb6" name="In" connectedTo="3eb7fb82-4a76-49a8-bcb7-fb141ec393d5"/>
          <port xsi:type="esdl:OutPort" id="64263e2c-3ec3-418e-af5e-b9b8261b667c" name="Out" connectedTo="f8543e0d-34f5-4463-94a9-6d105ae6f892"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="db82024f-c9d6-4bcf-b0ad-e38ace7f021f" name="In" connectedTo="91309199-71cf-47c6-a67b-b6d00398ff67"/>
          <port xsi:type="esdl:OutPort" id="d65a0dea-84f2-4303-b4f8-55e94d0d1624" name="Out" connectedTo="d0366afe-3e43-41cd-97eb-c71e223f6240"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="782c78c9-927d-40e6-a568-36630cc3dac0" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="41095f82-960b-446c-9e75-1a857c37d5be" name="In_Ph1" connectedTo="6817967e-26c6-4b30-82a7-9b44873200ad"/>
          <port xsi:type="esdl:InPort" id="f8543e0d-34f5-4463-94a9-6d105ae6f892" name="In_Ph2" connectedTo="64263e2c-3ec3-418e-af5e-b9b8261b667c"/>
          <port xsi:type="esdl:InPort" id="d0366afe-3e43-41cd-97eb-c71e223f6240" name="In_Ph3" connectedTo="d65a0dea-84f2-4303-b4f8-55e94d0d1624"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="3xhome581" id="66059820-bcc7-49df-8b42-db4628580ae0">
          <port xsi:type="esdl:InPort" id="d3b5f0b8-a0ce-4430-9d63-e8e68987ca9b" name="In" connectedTo="4709c5a8-88fa-4545-9fb3-7fa7c12c1190"/>
          <port xsi:type="esdl:OutPort" id="78e6a686-273a-44ed-87b9-0ab6168ea235" name="OutPh1" connectedTo="47f70970-19b1-4062-8121-bdf1096858f7"/>
          <port xsi:type="esdl:OutPort" id="3eb7fb82-4a76-49a8-bcb7-fb141ec393d5" name="OutPh2" connectedTo="d65bdbfc-a970-4755-9682-159875b56bb6"/>
          <port xsi:type="esdl:OutPort" id="91309199-71cf-47c6-a67b-b6d00398ff67" name="OutPh3" connectedTo="db82024f-c9d6-4bcf-b0ad-e38ace7f021f"/>
          <geometry xsi:type="esdl:Point" lat="158249.868" lon="433219.217"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_5" id="b43b6616-aa3f-4c2c-858c-962e2d15f48c">
        <port xsi:type="esdl:InPort" id="d24731ac-0d3b-4003-ac76-bbf2885b96d6" name="In" connectedTo="57ef6def-9caa-4c7b-b8d3-b4b7813974db"/>
        <port xsi:type="esdl:OutPort" id="1928e6b5-cff7-41f4-a4af-668709fb0480" name="Out" connectedTo="af8091c5-d31c-4683-95da-3accb92f41e1 f0282ce6-d8b3-4e09-ab5b-7cedacc93ebe"/>
        <geometry xsi:type="esdl:Point" lat="158251.50134994645" CRS="WGS84" lon="433227.14139595226"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.1426980592209819" name="lv_cable_trafo4_lvnetwork3_5_main_grid" id="7a8f8f1e-724f-4fd7-a94e-8c7ffbd4b950" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="52f6c4c3-dcc4-4376-9a44-d873bdc92f68" name="In" connectedTo="458a73d5-a5b3-4444-954d-a321ac0f0d5f"/>
        <port xsi:type="esdl:OutPort" id="57ef6def-9caa-4c7b-b8d3-b4b7813974db" name="Out" connectedTo="d24731ac-0d3b-4003-ac76-bbf2885b96d6"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158251.3611034781" CRS="WGS84" lon="433227.16773345816"/>
          <point xsi:type="esdl:Point" lat="158251.50134994645" CRS="WGS84" lon="433227.14139595226"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.080216230595187" name="lv_cable_trafo4_lvnetwork3_to_home_2_arch5" id="195e99da-6578-4e10-9be8-8ec2640a0b6c" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="af8091c5-d31c-4683-95da-3accb92f41e1" name="In" connectedTo="1928e6b5-cff7-41f4-a4af-668709fb0480"/>
        <port xsi:type="esdl:OutPort" id="1f66153d-0cf6-45f0-8218-08c0e2d97cd6" name="Out" connectedTo="8e3e7c7c-e35e-4b03-9870-bc64d529048d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158250.01" CRS="WGS84" lon="433219.2"/>
          <point xsi:type="esdl:Point" lat="158251.50134994645" CRS="WGS84" lon="433227.14139595226"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="3xhome582" id="3c4be855-2dfc-4723-8731-9d8d3336ca94">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="57993155-215c-4ba0-b21e-c6f27463c599" name="In" connectedTo="fac53c67-dafc-4664-a47d-ead1804bc031"/>
          <port xsi:type="esdl:OutPort" id="612c409c-7588-4abb-8441-eb4bca2fb1f4" name="Out" connectedTo="f66a2670-33c0-4d07-b09c-dfd429ade077"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="4dcae8b4-b374-4223-9842-2f4b2980bf14" name="In" connectedTo="10613a62-9433-4698-959c-48399a0990e9"/>
          <port xsi:type="esdl:OutPort" id="a4f1b2db-0ca5-4981-a9ef-e2017cb0ffc8" name="Out" connectedTo="1ca6b916-e517-450f-af3a-234044ca4f66"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="38e88d25-1f24-4f21-96d6-b3730800149e" name="In" connectedTo="b0e86b64-9035-4fdf-a07a-ffbbb461598d"/>
          <port xsi:type="esdl:OutPort" id="113355ce-accc-4516-a5de-2307234feca5" name="Out" connectedTo="2954d7b1-e16a-4223-9455-b0cda0b9c441"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="5185cc19-9517-41e4-97da-ea18aa8b755b" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="f66a2670-33c0-4d07-b09c-dfd429ade077" name="In_Ph1" connectedTo="612c409c-7588-4abb-8441-eb4bca2fb1f4"/>
          <port xsi:type="esdl:InPort" id="1ca6b916-e517-450f-af3a-234044ca4f66" name="In_Ph2" connectedTo="a4f1b2db-0ca5-4981-a9ef-e2017cb0ffc8"/>
          <port xsi:type="esdl:InPort" id="2954d7b1-e16a-4223-9455-b0cda0b9c441" name="In_Ph3" connectedTo="113355ce-accc-4516-a5de-2307234feca5"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="3xhome582" id="5a8da34a-6318-4e75-ba26-fcddbaab9bf7">
          <port xsi:type="esdl:InPort" id="8e3e7c7c-e35e-4b03-9870-bc64d529048d" name="In" connectedTo="1f66153d-0cf6-45f0-8218-08c0e2d97cd6"/>
          <port xsi:type="esdl:OutPort" id="fac53c67-dafc-4664-a47d-ead1804bc031" name="OutPh1" connectedTo="57993155-215c-4ba0-b21e-c6f27463c599"/>
          <port xsi:type="esdl:OutPort" id="10613a62-9433-4698-959c-48399a0990e9" name="OutPh2" connectedTo="4dcae8b4-b374-4223-9842-2f4b2980bf14"/>
          <port xsi:type="esdl:OutPort" id="b0e86b64-9035-4fdf-a07a-ffbbb461598d" name="OutPh3" connectedTo="38e88d25-1f24-4f21-96d6-b3730800149e"/>
          <geometry xsi:type="esdl:Point" lat="158250.01" lon="433219.2"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_6" id="cde3ea38-2732-4100-85c5-6d9110e72eb0">
        <port xsi:type="esdl:InPort" id="1c69f46f-ffc9-4236-b359-749c956d1908" name="In" connectedTo="99b6e7fa-d9dd-4e8f-953e-c9004cebd4ab"/>
        <port xsi:type="esdl:OutPort" id="f19dbced-7229-4687-8443-47f377db387d" name="Out" connectedTo="217f719e-0449-4a99-99ce-7590ea37937d ce72c82e-c10e-4cb4-8c89-1a47340841e9"/>
        <geometry xsi:type="esdl:Point" lat="158256.63079980848" CRS="WGS84" lon="433226.17771372"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.219189556348709" name="lv_cable_trafo4_lvnetwork3_6_main_grid" id="53811319-13a7-497f-9178-f1cb5f881158" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f0282ce6-d8b3-4e09-ab5b-7cedacc93ebe" name="In" connectedTo="1928e6b5-cff7-41f4-a4af-668709fb0480"/>
        <port xsi:type="esdl:OutPort" id="99b6e7fa-d9dd-4e8f-953e-c9004cebd4ab" name="Out" connectedTo="1c69f46f-ffc9-4236-b359-749c956d1908"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158251.50134994645" CRS="WGS84" lon="433227.14139595226"/>
          <point xsi:type="esdl:Point" lat="158254.355" CRS="WGS84" lon="433226.605"/>
          <point xsi:type="esdl:Point" lat="158256.63079980848" CRS="WGS84" lon="433226.17771372"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.236150901182258" name="lv_cable_trafo4_lvnetwork3_to_home_4_arch5" id="ecf1f1ae-911c-42c8-bf22-7a5b41d4697d" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="217f719e-0449-4a99-99ce-7590ea37937d" name="In" connectedTo="f19dbced-7229-4687-8443-47f377db387d"/>
        <port xsi:type="esdl:OutPort" id="4ddb1c8f-8e3a-428b-9622-1537836b1164" name="Out" connectedTo="a7ed1da1-67c6-400a-a369-fa28ffb9ea4f"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158255.111" CRS="WGS84" lon="433218.083"/>
          <point xsi:type="esdl:Point" lat="158256.63079980848" CRS="WGS84" lon="433226.17771372"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="3xhome584" id="34866452-38ab-4c85-ae2c-f2c6f1617b43">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="6cb08789-4fdf-4635-84e5-cea80ec9afec" name="In" connectedTo="9462d5ef-8514-4d51-b598-f127aabda230"/>
          <port xsi:type="esdl:OutPort" id="71e29d34-68b6-46ac-8c2c-eccd69a1f315" name="Out" connectedTo="0152d655-2859-4726-af51-23a3c9d32f5f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="ac77797d-74f6-4a86-b0e0-7bb4ec0f9dcf" name="In" connectedTo="6d40aa59-bf6e-4013-9f21-c599aa1dc15f"/>
          <port xsi:type="esdl:OutPort" id="6c957074-5fff-4cd9-ae8d-8d8deec12520" name="Out" connectedTo="fdec6d92-96b5-4774-9840-9da3da4edcc1"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="11d70966-641a-421f-a544-fbd2533b73e4" name="In" connectedTo="ffb4d56a-25e4-42a5-a95a-6bec72955013"/>
          <port xsi:type="esdl:OutPort" id="fa7e29f2-bfa8-42e3-a995-119c491f0ff6" name="Out" connectedTo="0e6d7f9f-9403-4d72-b9cf-7445c5327330"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="0edf4480-52c6-4f17-9044-475091486987" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="0152d655-2859-4726-af51-23a3c9d32f5f" name="In_Ph1" connectedTo="71e29d34-68b6-46ac-8c2c-eccd69a1f315"/>
          <port xsi:type="esdl:InPort" id="fdec6d92-96b5-4774-9840-9da3da4edcc1" name="In_Ph2" connectedTo="6c957074-5fff-4cd9-ae8d-8d8deec12520"/>
          <port xsi:type="esdl:InPort" id="0e6d7f9f-9403-4d72-b9cf-7445c5327330" name="In_Ph3" connectedTo="fa7e29f2-bfa8-42e3-a995-119c491f0ff6"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="3xhome584" id="92b38a0f-85ac-431d-bce2-16b0374226e9">
          <port xsi:type="esdl:InPort" id="a7ed1da1-67c6-400a-a369-fa28ffb9ea4f" name="In" connectedTo="4ddb1c8f-8e3a-428b-9622-1537836b1164"/>
          <port xsi:type="esdl:OutPort" id="9462d5ef-8514-4d51-b598-f127aabda230" name="OutPh1" connectedTo="6cb08789-4fdf-4635-84e5-cea80ec9afec"/>
          <port xsi:type="esdl:OutPort" id="6d40aa59-bf6e-4013-9f21-c599aa1dc15f" name="OutPh2" connectedTo="ac77797d-74f6-4a86-b0e0-7bb4ec0f9dcf"/>
          <port xsi:type="esdl:OutPort" id="ffb4d56a-25e4-42a5-a95a-6bec72955013" name="OutPh3" connectedTo="11d70966-641a-421f-a544-fbd2533b73e4"/>
          <geometry xsi:type="esdl:Point" lat="158255.111" lon="433218.083"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_7" id="00bbb27b-2c52-4df1-a150-755f42834123">
        <port xsi:type="esdl:InPort" id="f54ebcd2-85bd-4b4c-96dd-ec9519121829" name="In" connectedTo="47e18810-1649-476b-a5d0-1eddb0851a19"/>
        <port xsi:type="esdl:OutPort" id="ba6f7ec7-1b67-41fd-8a9a-131103dd369a" name="Out" connectedTo="60049ca7-c338-4fec-85b1-d028c732393a 4d1af14d-7b71-4006-add9-dafd482f5b1a"/>
        <geometry xsi:type="esdl:Point" lat="158266.749" CRS="WGS84" lon="433224.278"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.294993313931807" name="lv_cable_trafo4_lvnetwork3_7_main_grid" id="26094e0b-ea80-4906-9ee5-ad8f2ab6a043" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="ce72c82e-c10e-4cb4-8c89-1a47340841e9" name="In" connectedTo="f19dbced-7229-4687-8443-47f377db387d"/>
        <port xsi:type="esdl:OutPort" id="47e18810-1649-476b-a5d0-1eddb0851a19" name="Out" connectedTo="f54ebcd2-85bd-4b4c-96dd-ec9519121829"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158256.63079980848" CRS="WGS84" lon="433226.17771372"/>
          <point xsi:type="esdl:Point" lat="158266.749" CRS="WGS84" lon="433224.278"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="9.355896750191663" name="lv_cable_trafo4_lvnetwork3_to_home_3_arch5" id="9c9f4e31-cecd-44cf-a10b-82005dab9336" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="60049ca7-c338-4fec-85b1-d028c732393a" name="In" connectedTo="ba6f7ec7-1b67-41fd-8a9a-131103dd369a"/>
        <port xsi:type="esdl:OutPort" id="2adf5e10-c24b-4b3a-8992-ffdd1a8603b4" name="Out" connectedTo="3cc84695-3865-45c2-a5a3-71f7467c6b56"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158267.019" CRS="WGS84" lon="433214.926"/>
          <point xsi:type="esdl:Point" lat="158266.749" CRS="WGS84" lon="433224.278"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="4xhome583" id="65a3647f-588f-47ed-9d6e-fc739b671ba8">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="bb3139df-09b4-4f11-aa96-45e5fe91f840" name="In" connectedTo="2ac956fd-e3ad-4ce8-a59c-dbabe5cbc242"/>
          <port xsi:type="esdl:OutPort" id="320b9ea5-7964-4a5e-9132-d0093af67e53" name="Out" connectedTo="7e2cdff6-acdc-4293-be1a-1503e724f7e7"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="2fae96c3-71a7-4e5a-adbf-ec86857bbdd5" name="In" connectedTo="55ae26a2-4541-4968-bb40-a3b7bf351fec"/>
          <port xsi:type="esdl:OutPort" id="f00d6448-107d-4921-b8e3-849ed6d8a648" name="Out" connectedTo="0ec948c5-1202-40d5-9fb7-231d343a0791"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="0ae543ad-9b42-47d9-a210-9d0f97f04f17" name="In" connectedTo="b203d07c-b9e0-4de0-9455-0d165a746779"/>
          <port xsi:type="esdl:OutPort" id="82ddea17-26cc-4529-ab97-1635e0414e4b" name="Out" connectedTo="54256c2b-d9c5-4871-afa6-afce1486bfa6"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="54d7195e-9715-4a48-8948-fd2cb9b07c3a" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7e2cdff6-acdc-4293-be1a-1503e724f7e7" name="In_Ph1" connectedTo="320b9ea5-7964-4a5e-9132-d0093af67e53"/>
          <port xsi:type="esdl:InPort" id="0ec948c5-1202-40d5-9fb7-231d343a0791" name="In_Ph2" connectedTo="f00d6448-107d-4921-b8e3-849ed6d8a648"/>
          <port xsi:type="esdl:InPort" id="54256c2b-d9c5-4871-afa6-afce1486bfa6" name="In_Ph3" connectedTo="82ddea17-26cc-4529-ab97-1635e0414e4b"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="4xhome583" id="8aab760a-66b1-4de8-8a87-6e2c243cbd13">
          <port xsi:type="esdl:InPort" id="3cc84695-3865-45c2-a5a3-71f7467c6b56" name="In" connectedTo="2adf5e10-c24b-4b3a-8992-ffdd1a8603b4"/>
          <port xsi:type="esdl:OutPort" id="2ac956fd-e3ad-4ce8-a59c-dbabe5cbc242" name="OutPh1" connectedTo="bb3139df-09b4-4f11-aa96-45e5fe91f840"/>
          <port xsi:type="esdl:OutPort" id="55ae26a2-4541-4968-bb40-a3b7bf351fec" name="OutPh2" connectedTo="2fae96c3-71a7-4e5a-adbf-ec86857bbdd5"/>
          <port xsi:type="esdl:OutPort" id="b203d07c-b9e0-4de0-9455-0d165a746779" name="OutPh3" connectedTo="0ae543ad-9b42-47d9-a210-9d0f97f04f17"/>
          <geometry xsi:type="esdl:Point" lat="158267.019" lon="433214.926"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_8" id="35931a52-b69d-4a7d-895c-64155e87c0be">
        <port xsi:type="esdl:InPort" id="5aabc259-f00c-4d35-8922-dedcc6d24847" name="In" connectedTo="8e640ab3-481d-470d-80b2-5bebfc963285"/>
        <port xsi:type="esdl:OutPort" id="181b531e-7cc0-4047-a02e-13a1c2a4420a" name="Out" connectedTo="912a5b52-e0f9-4e52-bbf2-2cc784b4a258"/>
        <geometry xsi:type="esdl:Point" lat="158275.394" CRS="WGS84" lon="433270.173"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="47.125882006979786" name="lv_cable_trafo4_lvnetwork3_8_main_grid" id="275f5027-07df-4edb-a867-ce6bc80c1257" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="4d1af14d-7b71-4006-add9-dafd482f5b1a" name="In" connectedTo="ba6f7ec7-1b67-41fd-8a9a-131103dd369a"/>
        <port xsi:type="esdl:OutPort" id="8e640ab3-481d-470d-80b2-5bebfc963285" name="Out" connectedTo="5aabc259-f00c-4d35-8922-dedcc6d24847"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158266.749" CRS="WGS84" lon="433224.278"/>
          <point xsi:type="esdl:Point" lat="158268.731" CRS="WGS84" lon="433235.798"/>
          <point xsi:type="esdl:Point" lat="158271.175" CRS="WGS84" lon="433250.0"/>
          <point xsi:type="esdl:Point" lat="158271.685" CRS="WGS84" lon="433252.965"/>
          <point xsi:type="esdl:Point" lat="158271.901" CRS="WGS84" lon="433254.768"/>
          <point xsi:type="esdl:Point" lat="158272.378" CRS="WGS84" lon="433258.755"/>
          <point xsi:type="esdl:Point" lat="158273.656" CRS="WGS84" lon="433265.949"/>
          <point xsi:type="esdl:Point" lat="158274.148" CRS="WGS84" lon="433268.718"/>
          <point xsi:type="esdl:Point" lat="158275.275" CRS="WGS84" lon="433269.472"/>
          <point xsi:type="esdl:Point" lat="158275.394" CRS="WGS84" lon="433270.173"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_9" id="5409f124-1689-4783-ae87-ba256f13ec99">
        <port xsi:type="esdl:InPort" id="e9a2956e-cea4-43ae-bb63-85d07011d284" name="In" connectedTo="86171fee-6e98-43fa-bffd-321045c9f188"/>
        <port xsi:type="esdl:OutPort" id="cf8a42ba-0214-4571-bf45-0b64ce034f23" name="Out" connectedTo="d9e84b0b-9f9a-40ba-84f8-eafb8b378208"/>
        <geometry xsi:type="esdl:Point" lat="158275.386" CRS="WGS84" lon="433269.708"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.4889796243748361" name="lv_cable_trafo4_lvnetwork3_9_main_grid" id="eaa1ea4b-27f4-48ad-8ecf-dc4186ab04c8" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="912a5b52-e0f9-4e52-bbf2-2cc784b4a258" name="In" connectedTo="181b531e-7cc0-4047-a02e-13a1c2a4420a"/>
        <port xsi:type="esdl:OutPort" id="86171fee-6e98-43fa-bffd-321045c9f188" name="Out" connectedTo="e9a2956e-cea4-43ae-bb63-85d07011d284"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158275.394" CRS="WGS84" lon="433270.173"/>
          <point xsi:type="esdl:Point" lat="158275.465" CRS="WGS84" lon="433269.984"/>
          <point xsi:type="esdl:Point" lat="158275.386" CRS="WGS84" lon="433269.708"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_10" id="3408460b-9b32-4209-9651-b4faa7338a37">
        <port xsi:type="esdl:InPort" id="debcd19f-e146-4236-a606-3b7aea76a8db" name="In" connectedTo="9c16deb7-b650-4960-beb8-beb0feb1e935"/>
        <port xsi:type="esdl:OutPort" id="6b346bf7-67eb-4fe2-bb6f-e046ff21c34f" name="Out" connectedTo="a547e73e-8726-49a8-a16b-34ff38a82e61"/>
        <geometry xsi:type="esdl:Point" lat="158276.635" CRS="WGS84" lon="433279.805"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="10.581936013406112" name="lv_cable_trafo4_lvnetwork3_10_main_grid" id="7b0d3596-82c4-4096-a86a-f455432355c6" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="d9e84b0b-9f9a-40ba-84f8-eafb8b378208" name="In" connectedTo="cf8a42ba-0214-4571-bf45-0b64ce034f23"/>
        <port xsi:type="esdl:OutPort" id="9c16deb7-b650-4960-beb8-beb0feb1e935" name="Out" connectedTo="debcd19f-e146-4236-a606-3b7aea76a8db"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158275.394" CRS="WGS84" lon="433270.173"/>
          <point xsi:type="esdl:Point" lat="158275.246" CRS="WGS84" lon="433270.198"/>
          <point xsi:type="esdl:Point" lat="158275.595" CRS="WGS84" lon="433272.251"/>
          <point xsi:type="esdl:Point" lat="158276.095" CRS="WGS84" lon="433273.433"/>
          <point xsi:type="esdl:Point" lat="158277.272" CRS="WGS84" lon="433279.751"/>
          <point xsi:type="esdl:Point" lat="158276.635" CRS="WGS84" lon="433279.805"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_11" id="f102489b-1278-4807-b4b7-142e49cafc04">
        <port xsi:type="esdl:InPort" id="fa2f1084-b193-407d-a007-ab6489464de9" name="In" connectedTo="c8c05c12-67f7-4a16-9de9-1b719ffd48a2"/>
        <port xsi:type="esdl:OutPort" id="bfc6c497-ffac-451f-b1b6-e968d45a1c4e" name="Out" connectedTo="6e33cddc-332f-4ca4-b112-3248a3e2d600"/>
        <geometry xsi:type="esdl:Point" lat="158239.89" CRS="WGS84" lon="433285.787"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="37.22874457881642" name="lv_cable_trafo4_lvnetwork3_11_main_grid" id="d95ce918-2d28-45ca-91e1-d3818846927f" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="a547e73e-8726-49a8-a16b-34ff38a82e61" name="In" connectedTo="6b346bf7-67eb-4fe2-bb6f-e046ff21c34f"/>
        <port xsi:type="esdl:OutPort" id="c8c05c12-67f7-4a16-9de9-1b719ffd48a2" name="Out" connectedTo="fa2f1084-b193-407d-a007-ab6489464de9"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158276.635" CRS="WGS84" lon="433279.805"/>
          <point xsi:type="esdl:Point" lat="158274.98" CRS="WGS84" lon="433280.074"/>
          <point xsi:type="esdl:Point" lat="158274.188" CRS="WGS84" lon="433280.203"/>
          <point xsi:type="esdl:Point" lat="158271.191" CRS="WGS84" lon="433280.691"/>
          <point xsi:type="esdl:Point" lat="158265.691" CRS="WGS84" lon="433281.587"/>
          <point xsi:type="esdl:Point" lat="158265.457" CRS="WGS84" lon="433281.625"/>
          <point xsi:type="esdl:Point" lat="158262.219" CRS="WGS84" lon="433282.152"/>
          <point xsi:type="esdl:Point" lat="158259.661" CRS="WGS84" lon="433282.568"/>
          <point xsi:type="esdl:Point" lat="158257.743" CRS="WGS84" lon="433282.88"/>
          <point xsi:type="esdl:Point" lat="158257.555" CRS="WGS84" lon="433282.911"/>
          <point xsi:type="esdl:Point" lat="158254.793" CRS="WGS84" lon="433283.361"/>
          <point xsi:type="esdl:Point" lat="158249.063" CRS="WGS84" lon="433284.294"/>
          <point xsi:type="esdl:Point" lat="158247.661" CRS="WGS84" lon="433284.522"/>
          <point xsi:type="esdl:Point" lat="158247.502" CRS="WGS84" lon="433284.548"/>
          <point xsi:type="esdl:Point" lat="158241.978" CRS="WGS84" lon="433285.447"/>
          <point xsi:type="esdl:Point" lat="158241.502" CRS="WGS84" lon="433285.524"/>
          <point xsi:type="esdl:Point" lat="158239.89" CRS="WGS84" lon="433285.787"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo4_lvnetwork3_12" id="ff3b98b1-257c-4b20-940b-70baad03b6e8">
        <port xsi:type="esdl:InPort" id="7a32ee79-a8cb-4e9c-b5a5-e8c2deb9d343" name="In" connectedTo="0619067c-3ad0-4086-85cf-100dcd349c50"/>
        <port xsi:type="esdl:OutPort" id="25773ecd-cec5-4a69-9dd3-4cfe0ef344cf" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158232.731" CRS="WGS84" lon="433287.443"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="7.34803500689952" name="lv_cable_trafo4_lvnetwork3_12_main_grid" id="e618957e-847e-448a-9d8e-8cdc699125f5" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="6e33cddc-332f-4ca4-b112-3248a3e2d600" name="In" connectedTo="bfc6c497-ffac-451f-b1b6-e968d45a1c4e"/>
        <port xsi:type="esdl:OutPort" id="0619067c-3ad0-4086-85cf-100dcd349c50" name="Out" connectedTo="7a32ee79-a8cb-4e9c-b5a5-e8c2deb9d343"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158239.89" CRS="WGS84" lon="433285.787"/>
          <point xsi:type="esdl:Point" lat="158238.543" CRS="WGS84" lon="433286.099"/>
          <point xsi:type="esdl:Point" lat="158236.537" CRS="WGS84" lon="433286.563"/>
          <point xsi:type="esdl:Point" lat="158235.416" CRS="WGS84" lon="433286.822"/>
          <point xsi:type="esdl:Point" lat="158232.731" CRS="WGS84" lon="433287.443"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo4_lvnetwork3" id="acd1b692-0fe2-44d2-a35b-d090849b8b07" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="3e614a11-6759-4151-bcde-fbb7e4a1a7e3" name="Out" connectedTo="d93f2827-626b-49d1-96ea-3f7f1deb80e0"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo4_lvnetwork3" id="a449e5a2-c65e-4ce3-8834-c641a327eb80">
        <port xsi:type="esdl:InPort" id="d93f2827-626b-49d1-96ea-3f7f1deb80e0" name="In" connectedTo="3e614a11-6759-4151-bcde-fbb7e4a1a7e3"/>
        <port xsi:type="esdl:OutPort" id="c4164191-b2c4-45c3-ab1b-52cd3680bfeb" name="Out" connectedTo="2a027d86-6b8c-4a1a-999c-91214c891dd2"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer27" id="e31d6247-9301-47b1-9a92-8b7f9fc0eb48" commissioningDate="1971-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="2a027d86-6b8c-4a1a-999c-91214c891dd2" name="In" connectedTo="c4164191-b2c4-45c3-ab1b-52cd3680bfeb"/>
        <port xsi:type="esdl:OutPort" id="6bc5d05a-4e6e-4e7e-bc54-4506815d5502" name="Out" connectedTo="55fc00c8-785b-4375-84da-927f3fa29f39"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint29" id="38e86393-69a0-44b5-a931-dd7d3ee15a8c">
        <port xsi:type="esdl:InPort" id="55fc00c8-785b-4375-84da-927f3fa29f39" name="In" connectedTo="6bc5d05a-4e6e-4e7e-bc54-4506815d5502"/>
        <port xsi:type="esdl:OutPort" id="dd03e995-3b79-4a24-8e08-95f175bed17d" name="Out" connectedTo="198af419-4a26-4543-a8f5-fd16b57d7549"/>
        <geometry xsi:type="esdl:Point" lat="158191.14" CRS="WGS84" lon="433199.326"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
