<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="3410365b-fc94-49ca-9bb5-918d20fa458e" description="Autogenerated based on gis data trafo7_lvnetwork6" name="trafo7_lvnetwork6">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="481a651e-0613-429e-bdfd-9cc37c1d7b60"/>
  <instance xsi:type="esdl:Instance" id="31b22c1f-2220-4577-b55d-01bacd63a163" name="Instance name">
    <area xsi:type="esdl:Area" id="6e364add-a1fe-494f-8250-2ee0039bbbac" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_2" id="4398c163-05e7-49da-a758-de7834574a38">
        <port xsi:type="esdl:InPort" id="c627421f-9dc9-4fff-bbee-59d4b2afdf88" name="In" connectedTo="da8d1df1-329e-4b5f-a3d6-c5e47389cfef"/>
        <port xsi:type="esdl:OutPort" id="529098f0-7802-4263-b3d8-9685d707c2b7" name="Out" connectedTo="b9855411-486d-4c3e-9022-f75a908f2eb5"/>
        <geometry xsi:type="esdl:Point" lat="157783.663" CRS="WGS84" lon="433365.878"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.6531142240967296" name="lv_cable_trafo7_lvnetwork6_2_main_grid" id="f8ede358-8f49-42d2-8974-8dfd24937572" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="6e845a3f-7095-4f6d-ae06-67625a74cb6f" name="In" connectedTo="82741782-a491-4a5b-8373-c4d26b11749d"/>
        <port xsi:type="esdl:OutPort" id="da8d1df1-329e-4b5f-a3d6-c5e47389cfef" name="Out" connectedTo="c627421f-9dc9-4fff-bbee-59d4b2afdf88"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157782.49" CRS="WGS84" lon="433364.005"/>
          <point xsi:type="esdl:Point" lat="157782.307" CRS="WGS84" lon="433364.473"/>
          <point xsi:type="esdl:Point" lat="157782.291" CRS="WGS84" lon="433364.616"/>
          <point xsi:type="esdl:Point" lat="157782.344" CRS="WGS84" lon="433364.891"/>
          <point xsi:type="esdl:Point" lat="157782.498" CRS="WGS84" lon="433365.228"/>
          <point xsi:type="esdl:Point" lat="157782.599" CRS="WGS84" lon="433365.365"/>
          <point xsi:type="esdl:Point" lat="157782.732" CRS="WGS84" lon="433365.47"/>
          <point xsi:type="esdl:Point" lat="157783.663" CRS="WGS84" lon="433365.878"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_3" id="c2ed3b0d-cee4-4e7f-8ba9-6ce172342615">
        <port xsi:type="esdl:InPort" id="ccbc2a8c-4f54-4822-8595-1c55393c08a0" name="In" connectedTo="434213dd-ea40-441a-9457-2b482cc3fdf6"/>
        <port xsi:type="esdl:OutPort" id="5ca18408-281b-4b0c-8bf1-4b48fb813ea1" name="Out" connectedTo="d575815c-1e36-4716-86ca-82247c43090b"/>
        <geometry xsi:type="esdl:Point" lat="157819.379" CRS="WGS84" lon="433447.064"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="123.05047759757096" name="lv_cable_trafo7_lvnetwork6_3_main_grid" id="17650fb4-0822-436c-b0df-53bca6358b59" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="b9855411-486d-4c3e-9022-f75a908f2eb5" name="In" connectedTo="529098f0-7802-4263-b3d8-9685d707c2b7"/>
        <port xsi:type="esdl:OutPort" id="434213dd-ea40-441a-9457-2b482cc3fdf6" name="Out" connectedTo="ccbc2a8c-4f54-4822-8595-1c55393c08a0"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157783.663" CRS="WGS84" lon="433365.878"/>
          <point xsi:type="esdl:Point" lat="157784.883" CRS="WGS84" lon="433366.394"/>
          <point xsi:type="esdl:Point" lat="157785.908" CRS="WGS84" lon="433367.204"/>
          <point xsi:type="esdl:Point" lat="157812.069" CRS="WGS84" lon="433378.55"/>
          <point xsi:type="esdl:Point" lat="157822.26" CRS="WGS84" lon="433383.288"/>
          <point xsi:type="esdl:Point" lat="157824.516" CRS="WGS84" lon="433384.277"/>
          <point xsi:type="esdl:Point" lat="157832.272" CRS="WGS84" lon="433387.712"/>
          <point xsi:type="esdl:Point" lat="157824.864" CRS="WGS84" lon="433405.085"/>
          <point xsi:type="esdl:Point" lat="157824.258" CRS="WGS84" lon="433406.461"/>
          <point xsi:type="esdl:Point" lat="157822.133" CRS="WGS84" lon="433411.285"/>
          <point xsi:type="esdl:Point" lat="157822.012" CRS="WGS84" lon="433411.577"/>
          <point xsi:type="esdl:Point" lat="157820.966" CRS="WGS84" lon="433414.188"/>
          <point xsi:type="esdl:Point" lat="157819.691" CRS="WGS84" lon="433417.589"/>
          <point xsi:type="esdl:Point" lat="157817.738" CRS="WGS84" lon="433424.29"/>
          <point xsi:type="esdl:Point" lat="157816.734" CRS="WGS84" lon="433427.728"/>
          <point xsi:type="esdl:Point" lat="157814.613" CRS="WGS84" lon="433434.994"/>
          <point xsi:type="esdl:Point" lat="157814.102" CRS="WGS84" lon="433437.361"/>
          <point xsi:type="esdl:Point" lat="157814.001" CRS="WGS84" lon="433439.133"/>
          <point xsi:type="esdl:Point" lat="157814.257" CRS="WGS84" lon="433441.1"/>
          <point xsi:type="esdl:Point" lat="157814.55" CRS="WGS84" lon="433443.452"/>
          <point xsi:type="esdl:Point" lat="157814.656" CRS="WGS84" lon="433444.305"/>
          <point xsi:type="esdl:Point" lat="157815.179" CRS="WGS84" lon="433448.514"/>
          <point xsi:type="esdl:Point" lat="157815.198" CRS="WGS84" lon="433448.663"/>
          <point xsi:type="esdl:Point" lat="157815.347" CRS="WGS84" lon="433448.644"/>
          <point xsi:type="esdl:Point" lat="157815.781" CRS="WGS84" lon="433448.588"/>
          <point xsi:type="esdl:Point" lat="157816.586" CRS="WGS84" lon="433448.483"/>
          <point xsi:type="esdl:Point" lat="157816.953" CRS="WGS84" lon="433448.435"/>
          <point xsi:type="esdl:Point" lat="157817.822" CRS="WGS84" lon="433448.323"/>
          <point xsi:type="esdl:Point" lat="157818.545" CRS="WGS84" lon="433448.232"/>
          <point xsi:type="esdl:Point" lat="157818.876" CRS="WGS84" lon="433448.161"/>
          <point xsi:type="esdl:Point" lat="157819.1" CRS="WGS84" lon="433448.113"/>
          <point xsi:type="esdl:Point" lat="157819.322" CRS="WGS84" lon="433448.065"/>
          <point xsi:type="esdl:Point" lat="157819.463" CRS="WGS84" lon="433447.958"/>
          <point xsi:type="esdl:Point" lat="157819.54" CRS="WGS84" lon="433447.86"/>
          <point xsi:type="esdl:Point" lat="157819.583" CRS="WGS84" lon="433447.777"/>
          <point xsi:type="esdl:Point" lat="157819.616" CRS="WGS84" lon="433447.676"/>
          <point xsi:type="esdl:Point" lat="157819.63" CRS="WGS84" lon="433447.532"/>
          <point xsi:type="esdl:Point" lat="157819.62" CRS="WGS84" lon="433447.437"/>
          <point xsi:type="esdl:Point" lat="157819.58" CRS="WGS84" lon="433447.309"/>
          <point xsi:type="esdl:Point" lat="157819.515" CRS="WGS84" lon="433447.197"/>
          <point xsi:type="esdl:Point" lat="157819.46" CRS="WGS84" lon="433447.133"/>
          <point xsi:type="esdl:Point" lat="157819.379" CRS="WGS84" lon="433447.064"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_4" id="d12f97ca-e29c-47f9-b636-019526f71462">
        <port xsi:type="esdl:InPort" id="01f956f8-637b-466e-b61e-e4fb03379ece" name="In" connectedTo="386ecc4c-b43f-43f7-863b-3d0669175cb1"/>
        <port xsi:type="esdl:OutPort" id="0e678c2e-32ec-405f-8e5a-c11e9726c8e0" name="Out" connectedTo="c3694052-6161-4b75-9289-ce929fce685a 0597cdbd-6922-4ca4-be4f-332e921c5eac"/>
        <geometry xsi:type="esdl:Point" lat="157820.257" CRS="WGS84" lon="433447.475"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.1465230037169103" name="lv_cable_trafo7_lvnetwork6_4_main_grid" id="c721496e-c1ed-438c-8a62-1d490c7c484c" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="d575815c-1e36-4716-86ca-82247c43090b" name="In" connectedTo="5ca18408-281b-4b0c-8bf1-4b48fb813ea1"/>
        <port xsi:type="esdl:OutPort" id="386ecc4c-b43f-43f7-863b-3d0669175cb1" name="Out" connectedTo="01f956f8-637b-466e-b61e-e4fb03379ece"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157819.379" CRS="WGS84" lon="433447.064"/>
          <point xsi:type="esdl:Point" lat="157819.576" CRS="WGS84" lon="433447.004"/>
          <point xsi:type="esdl:Point" lat="157819.679" CRS="WGS84" lon="433446.972"/>
          <point xsi:type="esdl:Point" lat="157819.8" CRS="WGS84" lon="433446.986"/>
          <point xsi:type="esdl:Point" lat="157819.928" CRS="WGS84" lon="433447.03"/>
          <point xsi:type="esdl:Point" lat="157819.983" CRS="WGS84" lon="433447.06"/>
          <point xsi:type="esdl:Point" lat="157820.063" CRS="WGS84" lon="433447.119"/>
          <point xsi:type="esdl:Point" lat="157820.116" CRS="WGS84" lon="433447.172"/>
          <point xsi:type="esdl:Point" lat="157820.171" CRS="WGS84" lon="433447.245"/>
          <point xsi:type="esdl:Point" lat="157820.207" CRS="WGS84" lon="433447.311"/>
          <point xsi:type="esdl:Point" lat="157820.236" CRS="WGS84" lon="433447.383"/>
          <point xsi:type="esdl:Point" lat="157820.257" CRS="WGS84" lon="433447.475"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.8779804366962057" name="lv_cable_trafo7_lvnetwork6_to_home_0_arch6" id="031710d8-767c-4427-9596-053ea012b8dc" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="c3694052-6161-4b75-9289-ce929fce685a" name="In" connectedTo="0e678c2e-32ec-405f-8e5a-c11e9726c8e0"/>
        <port xsi:type="esdl:OutPort" id="eb26a91b-7f1d-45c9-a69f-c3f4da4a5785" name="Out" connectedTo="e68dd698-caa0-4257-86a9-82515ea9a009"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157821.12859096244" CRS="WGS84" lon="433447.3692699596"/>
          <point xsi:type="esdl:Point" lat="157820.257" CRS="WGS84" lon="433447.475"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="2xhome734" id="bfc384e8-4406-4af1-a826-64e4bfa5c14a">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="b6fb2736-4348-4c0d-a0ab-17077e9c7c58" name="In" connectedTo="1c96d52e-f6d9-4569-8d09-8ca1c2aa3ae0"/>
          <port xsi:type="esdl:OutPort" id="5c40bfa2-1a30-4c46-8ae9-a36a897b81fe" name="Out" connectedTo="3d871d87-ff41-4160-8121-ff42e8fbdd25"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="c46b9a18-3a7a-4a33-b874-ef571b1c2dec" name="In" connectedTo="504798aa-2d7f-4f3f-b54b-defc0a921f3e"/>
          <port xsi:type="esdl:OutPort" id="a3f66ae1-e1e7-48b5-9930-59c3a119c3fa" name="Out" connectedTo="d81f17b3-7051-4ee0-acca-f82b73f15c1b"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="e200bd4c-e16a-46e3-ba44-d499d85c202c" name="In" connectedTo="afc2d8b2-cabc-4d75-8d7a-058198521b2d"/>
          <port xsi:type="esdl:OutPort" id="5e65a9a0-f468-4878-a32b-0050696a1e09" name="Out" connectedTo="b3a3fef9-f05e-408f-bb1f-5c7b4510e7d4"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="c52f1f99-2131-4f7f-8f5a-8544d602a00c" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="3d871d87-ff41-4160-8121-ff42e8fbdd25" name="In_Ph1" connectedTo="5c40bfa2-1a30-4c46-8ae9-a36a897b81fe"/>
          <port xsi:type="esdl:InPort" id="d81f17b3-7051-4ee0-acca-f82b73f15c1b" name="In_Ph2" connectedTo="a3f66ae1-e1e7-48b5-9930-59c3a119c3fa"/>
          <port xsi:type="esdl:InPort" id="b3a3fef9-f05e-408f-bb1f-5c7b4510e7d4" name="In_Ph3" connectedTo="5e65a9a0-f468-4878-a32b-0050696a1e09"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="2xhome734" id="daa7171c-d07a-49a9-97e8-c81bbd7b6aa4">
          <port xsi:type="esdl:InPort" id="e68dd698-caa0-4257-86a9-82515ea9a009" name="In" connectedTo="eb26a91b-7f1d-45c9-a69f-c3f4da4a5785"/>
          <port xsi:type="esdl:OutPort" id="1c96d52e-f6d9-4569-8d09-8ca1c2aa3ae0" name="OutPh1" connectedTo="b6fb2736-4348-4c0d-a0ab-17077e9c7c58"/>
          <port xsi:type="esdl:OutPort" id="504798aa-2d7f-4f3f-b54b-defc0a921f3e" name="OutPh2" connectedTo="c46b9a18-3a7a-4a33-b874-ef571b1c2dec"/>
          <port xsi:type="esdl:OutPort" id="afc2d8b2-cabc-4d75-8d7a-058198521b2d" name="OutPh3" connectedTo="e200bd4c-e16a-46e3-ba44-d499d85c202c"/>
          <geometry xsi:type="esdl:Point" lat="157821.12859096244" lon="433447.3692699596"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_5" id="f782e273-0d2e-403a-a930-de8eb05457ab">
        <port xsi:type="esdl:InPort" id="9c37a928-e5c0-4bd3-bbe8-d34c5b6c7e9b" name="In" connectedTo="9e982ddf-5f33-44ff-af2f-a4ffcf9f0a4c"/>
        <port xsi:type="esdl:OutPort" id="7ea5ff91-e3dc-4025-b44d-c759ce32cc9a" name="Out" connectedTo="7178e1a1-1822-4351-b739-30e874dc1d7f"/>
        <geometry xsi:type="esdl:Point" lat="157798.81" CRS="WGS84" lon="433504.447"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="67.72573902836088" name="lv_cable_trafo7_lvnetwork6_5_main_grid" id="653e2556-47cd-45a4-af70-ee7c56cac9ff" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="0597cdbd-6922-4ca4-be4f-332e921c5eac" name="In" connectedTo="0e678c2e-32ec-405f-8e5a-c11e9726c8e0"/>
        <port xsi:type="esdl:OutPort" id="9e982ddf-5f33-44ff-af2f-a4ffcf9f0a4c" name="Out" connectedTo="9c37a928-e5c0-4bd3-bbe8-d34c5b6c7e9b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157820.257" CRS="WGS84" lon="433447.475"/>
          <point xsi:type="esdl:Point" lat="157820.263" CRS="WGS84" lon="433447.552"/>
          <point xsi:type="esdl:Point" lat="157820.258" CRS="WGS84" lon="433447.634"/>
          <point xsi:type="esdl:Point" lat="157820.25" CRS="WGS84" lon="433447.682"/>
          <point xsi:type="esdl:Point" lat="157820.227" CRS="WGS84" lon="433447.761"/>
          <point xsi:type="esdl:Point" lat="157820.205" CRS="WGS84" lon="433447.811"/>
          <point xsi:type="esdl:Point" lat="157820.175" CRS="WGS84" lon="433447.865"/>
          <point xsi:type="esdl:Point" lat="157820.129" CRS="WGS84" lon="433447.929"/>
          <point xsi:type="esdl:Point" lat="157820.06" CRS="WGS84" lon="433447.998"/>
          <point xsi:type="esdl:Point" lat="157819.941" CRS="WGS84" lon="433448.075"/>
          <point xsi:type="esdl:Point" lat="157819.868" CRS="WGS84" lon="433448.105"/>
          <point xsi:type="esdl:Point" lat="157819.672" CRS="WGS84" lon="433448.147"/>
          <point xsi:type="esdl:Point" lat="157819.381" CRS="WGS84" lon="433448.209"/>
          <point xsi:type="esdl:Point" lat="157818.544" CRS="WGS84" lon="433448.388"/>
          <point xsi:type="esdl:Point" lat="157818.02" CRS="WGS84" lon="433448.448"/>
          <point xsi:type="esdl:Point" lat="157817.365" CRS="WGS84" lon="433448.533"/>
          <point xsi:type="esdl:Point" lat="157816.057" CRS="WGS84" lon="433448.703"/>
          <point xsi:type="esdl:Point" lat="157815.217" CRS="WGS84" lon="433448.812"/>
          <point xsi:type="esdl:Point" lat="157815.374" CRS="WGS84" lon="433452.055"/>
          <point xsi:type="esdl:Point" lat="157815.838" CRS="WGS84" lon="433461.619"/>
          <point xsi:type="esdl:Point" lat="157812.041" CRS="WGS84" lon="433462.598"/>
          <point xsi:type="esdl:Point" lat="157811.961" CRS="WGS84" lon="433462.617"/>
          <point xsi:type="esdl:Point" lat="157811.286389452" CRS="WGS84" lon="433462.81794973"/>
          <point xsi:type="esdl:Point" lat="157810.632970816" CRS="WGS84" lon="433463.079729198"/>
          <point xsi:type="esdl:Point" lat="157810.006218135" CRS="WGS84" lon="433463.400145337"/>
          <point xsi:type="esdl:Point" lat="157809.411382053" CRS="WGS84" lon="433463.776513846"/>
          <point xsi:type="esdl:Point" lat="157808.853445834" CRS="WGS84" lon="433464.205681684"/>
          <point xsi:type="esdl:Point" lat="157808.33708361" CRS="WGS84" lon="433464.684053481"/>
          <point xsi:type="esdl:Point" lat="157807.866621226" CRS="WGS84" lon="433465.207621658"/>
          <point xsi:type="esdl:Point" lat="157807.446" CRS="WGS84" lon="433465.772"/>
          <point xsi:type="esdl:Point" lat="157807.411" CRS="WGS84" lon="433465.818"/>
          <point xsi:type="esdl:Point" lat="157807.12000771" CRS="WGS84" lon="433466.227301245"/>
          <point xsi:type="esdl:Point" lat="157806.852192812" CRS="WGS84" lon="433466.652132374"/>
          <point xsi:type="esdl:Point" lat="157806.608381729" CRS="WGS84" lon="433467.091182444"/>
          <point xsi:type="esdl:Point" lat="157806.389326813" CRS="WGS84" lon="433467.543096637"/>
          <point xsi:type="esdl:Point" lat="157806.195704022" CRS="WGS84" lon="433468.006480436"/>
          <point xsi:type="esdl:Point" lat="157806.028110837" CRS="WGS84" lon="433468.479903934"/>
          <point xsi:type="esdl:Point" lat="157805.887064416" CRS="WGS84" lon="433468.961906242"/>
          <point xsi:type="esdl:Point" lat="157805.773" CRS="WGS84" lon="433469.451"/>
          <point xsi:type="esdl:Point" lat="157803.809" CRS="WGS84" lon="433479.314"/>
          <point xsi:type="esdl:Point" lat="157799.695" CRS="WGS84" lon="433500.0"/>
          <point xsi:type="esdl:Point" lat="157799.607" CRS="WGS84" lon="433500.44"/>
          <point xsi:type="esdl:Point" lat="157799.007" CRS="WGS84" lon="433503.457"/>
          <point xsi:type="esdl:Point" lat="157798.907" CRS="WGS84" lon="433503.96"/>
          <point xsi:type="esdl:Point" lat="157798.81" CRS="WGS84" lon="433504.447"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_6" id="96b69b8e-2d81-45d2-a740-b531b8b42b5b">
        <port xsi:type="esdl:InPort" id="091dd22e-b8bd-495f-af39-bb09389d892d" name="In" connectedTo="4b22a145-87b7-4e95-9e2f-a80a1c9e49ba"/>
        <port xsi:type="esdl:OutPort" id="c845f726-4e2e-456a-8619-e31711f205c0" name="Out" connectedTo="f2dacde2-5b40-4365-bfef-95d6d7edfdf3"/>
        <geometry xsi:type="esdl:Point" lat="157797.065" CRS="WGS84" lon="433516.123"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="12.246644895526906" name="lv_cable_trafo7_lvnetwork6_6_main_grid" id="008bdeb8-41db-4652-945d-e5afb5fb6211" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="7178e1a1-1822-4351-b739-30e874dc1d7f" name="In" connectedTo="7ea5ff91-e3dc-4025-b44d-c759ce32cc9a"/>
        <port xsi:type="esdl:OutPort" id="4b22a145-87b7-4e95-9e2f-a80a1c9e49ba" name="Out" connectedTo="091dd22e-b8bd-495f-af39-bb09389d892d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157798.81" CRS="WGS84" lon="433504.447"/>
          <point xsi:type="esdl:Point" lat="157798.726" CRS="WGS84" lon="433504.872"/>
          <point xsi:type="esdl:Point" lat="157799.368" CRS="WGS84" lon="433505.359"/>
          <point xsi:type="esdl:Point" lat="157797.065" CRS="WGS84" lon="433516.123"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_7" id="b18a6462-ac2a-450d-8170-bbeee299ed11">
        <port xsi:type="esdl:InPort" id="94eb04ad-52e3-4fc7-9194-e48b2331943d" name="In" connectedTo="85b4ff2c-5bdf-4be5-943c-cf4bcf14a6be"/>
        <port xsi:type="esdl:OutPort" id="72ddaa81-0e20-42d4-b7a9-d4e79b58234e" name="Out" connectedTo="227df35e-0874-40a7-9136-27b0dbd4f90e 5f80e06e-44ff-4cb2-b97c-f93a962c1c81"/>
        <geometry xsi:type="esdl:Point" lat="157765.97125479503" CRS="WGS84" lon="433593.22928621375"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="83.17004881643024" name="lv_cable_trafo7_lvnetwork6_7_main_grid" id="d67216ca-86fb-4c30-846c-a9d3339ddf03" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f2dacde2-5b40-4365-bfef-95d6d7edfdf3" name="In" connectedTo="c845f726-4e2e-456a-8619-e31711f205c0"/>
        <port xsi:type="esdl:OutPort" id="85b4ff2c-5bdf-4be5-943c-cf4bcf14a6be" name="Out" connectedTo="94eb04ad-52e3-4fc7-9194-e48b2331943d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157797.065" CRS="WGS84" lon="433516.123"/>
          <point xsi:type="esdl:Point" lat="157793.997" CRS="WGS84" lon="433524.475"/>
          <point xsi:type="esdl:Point" lat="157788.235" CRS="WGS84" lon="433540.16"/>
          <point xsi:type="esdl:Point" lat="157779.493" CRS="WGS84" lon="433562.516"/>
          <point xsi:type="esdl:Point" lat="157765.97125479503" CRS="WGS84" lon="433593.22928621375"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="21.181323295890255" name="lv_cable_trafo7_lvnetwork6_to_home_5_arch6" id="8fc0e9d0-e9a9-47b5-a733-67c1c4a0a515" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="227df35e-0874-40a7-9136-27b0dbd4f90e" name="In" connectedTo="72ddaa81-0e20-42d4-b7a9-d4e79b58234e"/>
        <port xsi:type="esdl:OutPort" id="8270d78a-bec5-4fc1-aa61-aea6b3b856b0" name="Out" connectedTo="9c5547bd-5796-4352-b744-4942f769d6d0"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157785.357" CRS="WGS84" lon="433601.764"/>
          <point xsi:type="esdl:Point" lat="157765.97125479503" CRS="WGS84" lon="433593.22928621375"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome739" id="2dd89d3c-406e-469a-8f4d-63024a9bf5fb">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="5486e2ca-6347-4cb0-936d-7604dc8ce15c" name="In" connectedTo="305087f0-65bd-45fb-bba4-7139e53e82fb"/>
          <port xsi:type="esdl:OutPort" id="961d4c42-dd2c-490d-8ea0-9c1f0983d85c" name="Out" connectedTo="061bb376-528c-40e4-a49e-fe6a1988a29f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="de2d1fde-ed87-45f3-a6a5-4389f0e512ad" name="In" connectedTo="1ae425ba-863c-489d-b2e6-c154fcc4ab65"/>
          <port xsi:type="esdl:OutPort" id="facb2f04-3595-42c5-b784-52d17f7d17af" name="Out" connectedTo="73f79fb4-7f20-4886-99b4-6929f1480f17"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="252d45f3-2db1-479b-8388-ae6401614d70" name="In" connectedTo="bca0014f-bf63-43b7-80ab-632cde80e5e3"/>
          <port xsi:type="esdl:OutPort" id="26623175-b266-45d2-b0a6-3639dfa248de" name="Out" connectedTo="e96d2153-74b3-4824-854a-4cb740c760ad"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="b9ca1519-8b97-411e-ba1d-23d7619b9615" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="061bb376-528c-40e4-a49e-fe6a1988a29f" name="In_Ph1" connectedTo="961d4c42-dd2c-490d-8ea0-9c1f0983d85c"/>
          <port xsi:type="esdl:InPort" id="73f79fb4-7f20-4886-99b4-6929f1480f17" name="In_Ph2" connectedTo="facb2f04-3595-42c5-b784-52d17f7d17af"/>
          <port xsi:type="esdl:InPort" id="e96d2153-74b3-4824-854a-4cb740c760ad" name="In_Ph3" connectedTo="26623175-b266-45d2-b0a6-3639dfa248de"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome739" id="80faeab3-7705-4870-ba76-eee4e20f5dc5">
          <port xsi:type="esdl:InPort" id="9c5547bd-5796-4352-b744-4942f769d6d0" name="In" connectedTo="8270d78a-bec5-4fc1-aa61-aea6b3b856b0"/>
          <port xsi:type="esdl:OutPort" id="305087f0-65bd-45fb-bba4-7139e53e82fb" name="OutPh1" connectedTo="5486e2ca-6347-4cb0-936d-7604dc8ce15c"/>
          <port xsi:type="esdl:OutPort" id="1ae425ba-863c-489d-b2e6-c154fcc4ab65" name="OutPh2" connectedTo="de2d1fde-ed87-45f3-a6a5-4389f0e512ad"/>
          <port xsi:type="esdl:OutPort" id="bca0014f-bf63-43b7-80ab-632cde80e5e3" name="OutPh3" connectedTo="252d45f3-2db1-479b-8388-ae6401614d70"/>
          <geometry xsi:type="esdl:Point" lat="157785.357" lon="433601.764"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_8" id="3106347d-4fe2-4d6f-bc86-ef6970c1816f">
        <port xsi:type="esdl:InPort" id="e2bf64f1-efcc-4436-ab99-6cdd0a256e8e" name="In" connectedTo="575215c8-a0e7-4c2c-9edf-c9fc6b29160f"/>
        <port xsi:type="esdl:OutPort" id="dfe0df80-a9d5-44fc-a919-762f6aedc212" name="Out" connectedTo="2c68680c-da1d-4022-93cf-f7058f616571 fad144a5-eb6c-4253-8f80-3752e2e57615 420a1adf-57cd-48a8-86de-6498dc3fab44 8d834bc0-e614-4486-98da-560d8cc601cf e1aa9292-f7a3-4c04-8fd8-981703a347e2"/>
        <geometry xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="41.869536128458556" name="lv_cable_trafo7_lvnetwork6_8_main_grid" id="1f722725-1f2e-432f-a5e7-4a27f655233a" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="5f80e06e-44ff-4cb2-b97c-f93a962c1c81" name="In" connectedTo="72ddaa81-0e20-42d4-b7a9-d4e79b58234e"/>
        <port xsi:type="esdl:OutPort" id="575215c8-a0e7-4c2c-9edf-c9fc6b29160f" name="Out" connectedTo="e2bf64f1-efcc-4436-ab99-6cdd0a256e8e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157765.97125479503" CRS="WGS84" lon="433593.22928621375"/>
          <point xsi:type="esdl:Point" lat="157761.589" CRS="WGS84" lon="433603.708"/>
          <point xsi:type="esdl:Point" lat="157761.317" CRS="WGS84" lon="433604.278"/>
          <point xsi:type="esdl:Point" lat="157759.376" CRS="WGS84" lon="433608.347"/>
          <point xsi:type="esdl:Point" lat="157755.812" CRS="WGS84" lon="433615.819"/>
          <point xsi:type="esdl:Point" lat="157755.597" CRS="WGS84" lon="433616.269"/>
          <point xsi:type="esdl:Point" lat="157768.158" CRS="WGS84" lon="433624.994"/>
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.2048404184807415" name="lv_cable_trafo7_lvnetwork6_to_home_1_arch6" id="d19d9e4a-c706-4055-9e53-c91dda1c8275" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="2c68680c-da1d-4022-93cf-f7058f616571" name="In" connectedTo="dfe0df80-a9d5-44fc-a919-762f6aedc212"/>
        <port xsi:type="esdl:OutPort" id="759b5378-7d84-44ff-8285-ff25877842b5" name="Out" connectedTo="a90af954-6f1b-4259-ada2-d70a3d2fd8fe"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157773.9641809664" CRS="WGS84" lon="433627.89006706286"/>
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome735" id="3efe749f-64e2-4053-9e86-5d67313250d4">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="7f22283c-5e02-4cac-8e27-7d364f1d7b56" name="In" connectedTo="3aa13273-85e2-4bff-8860-be8e067a4939"/>
          <port xsi:type="esdl:OutPort" id="33ff4209-7ef9-4eda-a081-414dcfada14a" name="Out" connectedTo="bd13c7ad-1277-40c3-9616-f10a6d234624"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="5fbbda7a-0ef4-49eb-bf38-726afdc95c9f" name="In" connectedTo="7d71a66d-9f56-4c39-b412-af2d5a18f3c4"/>
          <port xsi:type="esdl:OutPort" id="12bd823c-2125-4d45-9624-5495e226b67b" name="Out" connectedTo="f4072662-4d6a-4380-ae87-8b9913925f98"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="4976061e-336e-4aff-8f3a-6fa3ddfb529f" name="In" connectedTo="c0c01636-166e-4038-b790-0c063ad96c84"/>
          <port xsi:type="esdl:OutPort" id="5e352bc8-cfd7-4eba-a77b-aaa7a1864acb" name="Out" connectedTo="5514fca1-0b6c-4c69-a360-00735325daa6"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="1c5fc4d4-0309-4ba8-acb5-d8bb418904a1" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="bd13c7ad-1277-40c3-9616-f10a6d234624" name="In_Ph1" connectedTo="33ff4209-7ef9-4eda-a081-414dcfada14a"/>
          <port xsi:type="esdl:InPort" id="f4072662-4d6a-4380-ae87-8b9913925f98" name="In_Ph2" connectedTo="12bd823c-2125-4d45-9624-5495e226b67b"/>
          <port xsi:type="esdl:InPort" id="5514fca1-0b6c-4c69-a360-00735325daa6" name="In_Ph3" connectedTo="5e352bc8-cfd7-4eba-a77b-aaa7a1864acb"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome735" id="ab508cd1-0849-44fa-b06d-1a26ca3caf89">
          <port xsi:type="esdl:InPort" id="a90af954-6f1b-4259-ada2-d70a3d2fd8fe" name="In" connectedTo="759b5378-7d84-44ff-8285-ff25877842b5"/>
          <port xsi:type="esdl:OutPort" id="3aa13273-85e2-4bff-8860-be8e067a4939" name="OutPh1" connectedTo="7f22283c-5e02-4cac-8e27-7d364f1d7b56"/>
          <port xsi:type="esdl:OutPort" id="7d71a66d-9f56-4c39-b412-af2d5a18f3c4" name="OutPh2" connectedTo="5fbbda7a-0ef4-49eb-bf38-726afdc95c9f"/>
          <port xsi:type="esdl:OutPort" id="c0c01636-166e-4038-b790-0c063ad96c84" name="OutPh3" connectedTo="4976061e-336e-4aff-8f3a-6fa3ddfb529f"/>
          <geometry xsi:type="esdl:Point" lat="157773.9641809664" lon="433627.89006706286"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.208325103181437" name="lv_cable_trafo7_lvnetwork6_to_home_2_arch6" id="6a5cae53-3bf4-476b-ac6e-b2c2f562c937" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="fad144a5-eb6c-4253-8f80-3752e2e57615" name="In" connectedTo="dfe0df80-a9d5-44fc-a919-762f6aedc212"/>
        <port xsi:type="esdl:OutPort" id="6c037c4e-be92-4952-a245-43401d08025e" name="Out" connectedTo="b5a5894c-73cc-4f99-af8b-730945c7841b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157776.591" CRS="WGS84" lon="433622.112"/>
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome736" id="4955f938-57e1-49b3-9d6e-e66d34ea5d7e">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="cb8a4385-a427-4cf4-8f65-32d3418d07bc" name="In" connectedTo="ce2943b7-d13c-4700-b2ea-01a0fced8a14"/>
          <port xsi:type="esdl:OutPort" id="27f1a797-3c27-4681-aed4-7281ee11ba83" name="Out" connectedTo="dc10e2a2-db27-401c-ada7-572436729d44"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="fd741b86-039c-4bba-9ae9-551e16d75305" name="In" connectedTo="50ae237b-f790-4f2b-aa90-b44594162bcb"/>
          <port xsi:type="esdl:OutPort" id="33d812b5-8a02-4aae-af14-86f521b2a630" name="Out" connectedTo="878bb5df-8e9d-41d5-900d-18e6a4fa253e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="0e80f7f5-f39a-44e8-bb64-2805f6c84a1a" name="In" connectedTo="36eb4550-b95d-4955-aae9-bab79468a793"/>
          <port xsi:type="esdl:OutPort" id="af4963e7-66ba-4d17-8458-f7486f815f4c" name="Out" connectedTo="f60cf53d-98b8-4e5b-83ef-2eb16f8c760e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="e89c1292-333d-4bfb-ac66-272db783eae3" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="dc10e2a2-db27-401c-ada7-572436729d44" name="In_Ph1" connectedTo="27f1a797-3c27-4681-aed4-7281ee11ba83"/>
          <port xsi:type="esdl:InPort" id="878bb5df-8e9d-41d5-900d-18e6a4fa253e" name="In_Ph2" connectedTo="33d812b5-8a02-4aae-af14-86f521b2a630"/>
          <port xsi:type="esdl:InPort" id="f60cf53d-98b8-4e5b-83ef-2eb16f8c760e" name="In_Ph3" connectedTo="af4963e7-66ba-4d17-8458-f7486f815f4c"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome736" id="b43c0aa6-94f9-49d5-bc0e-69dac9e0d43e">
          <port xsi:type="esdl:InPort" id="b5a5894c-73cc-4f99-af8b-730945c7841b" name="In" connectedTo="6c037c4e-be92-4952-a245-43401d08025e"/>
          <port xsi:type="esdl:OutPort" id="ce2943b7-d13c-4700-b2ea-01a0fced8a14" name="OutPh1" connectedTo="cb8a4385-a427-4cf4-8f65-32d3418d07bc"/>
          <port xsi:type="esdl:OutPort" id="50ae237b-f790-4f2b-aa90-b44594162bcb" name="OutPh2" connectedTo="fd741b86-039c-4bba-9ae9-551e16d75305"/>
          <port xsi:type="esdl:OutPort" id="36eb4550-b95d-4955-aae9-bab79468a793" name="OutPh3" connectedTo="0e80f7f5-f39a-44e8-bb64-2805f6c84a1a"/>
          <geometry xsi:type="esdl:Point" lat="157776.591" lon="433622.112"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.160911100670987" name="lv_cable_trafo7_lvnetwork6_to_home_3_arch6" id="198dafca-bbd3-4c81-89f0-348c95f34749" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="420a1adf-57cd-48a8-86de-6498dc3fab44" name="In" connectedTo="dfe0df80-a9d5-44fc-a919-762f6aedc212"/>
        <port xsi:type="esdl:OutPort" id="64789ff7-e06f-4696-8491-b7124244dd98" name="Out" connectedTo="5c031cf9-7599-44ec-9377-ab0ceca68867"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157778.967" CRS="WGS84" lon="433616.886"/>
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome737" id="fcb40da4-1936-4b03-a2fa-a7cbc84d30bc">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="8efd069a-5e77-4359-984d-a76ed631a6ef" name="In" connectedTo="abde98fd-af98-42c7-b429-ca479871461c"/>
          <port xsi:type="esdl:OutPort" id="ce4f285d-b418-4062-b705-e5dcb3ca84cb" name="Out" connectedTo="7402dd94-bcb6-422f-8cbb-9dedda6b77db"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="8458acf0-f7b5-48d5-acf7-2fe0be078437" name="In" connectedTo="6531e077-a408-49d1-8551-05499fff8d33"/>
          <port xsi:type="esdl:OutPort" id="29f74a36-8568-4dcf-9e0c-38b03c7834b5" name="Out" connectedTo="00dd6378-38b0-4c8f-a239-66b403dc9307"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="a9006230-8b20-430b-933a-3a1b8c5558fa" name="In" connectedTo="348546d4-7fdf-42f0-b219-c55887f6c8bf"/>
          <port xsi:type="esdl:OutPort" id="636013e8-be38-4e9d-bb52-a85070034804" name="Out" connectedTo="f0401676-28b4-41b6-bae9-24ee155fc0ea"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="41455c0e-cee9-47b0-a960-297d05bea46b" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7402dd94-bcb6-422f-8cbb-9dedda6b77db" name="In_Ph1" connectedTo="ce4f285d-b418-4062-b705-e5dcb3ca84cb"/>
          <port xsi:type="esdl:InPort" id="00dd6378-38b0-4c8f-a239-66b403dc9307" name="In_Ph2" connectedTo="29f74a36-8568-4dcf-9e0c-38b03c7834b5"/>
          <port xsi:type="esdl:InPort" id="f0401676-28b4-41b6-bae9-24ee155fc0ea" name="In_Ph3" connectedTo="636013e8-be38-4e9d-bb52-a85070034804"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome737" id="a00178e3-bf84-451d-9b72-b24beeea35ab">
          <port xsi:type="esdl:InPort" id="5c031cf9-7599-44ec-9377-ab0ceca68867" name="In" connectedTo="64789ff7-e06f-4696-8491-b7124244dd98"/>
          <port xsi:type="esdl:OutPort" id="abde98fd-af98-42c7-b429-ca479871461c" name="OutPh1" connectedTo="8efd069a-5e77-4359-984d-a76ed631a6ef"/>
          <port xsi:type="esdl:OutPort" id="6531e077-a408-49d1-8551-05499fff8d33" name="OutPh2" connectedTo="8458acf0-f7b5-48d5-acf7-2fe0be078437"/>
          <port xsi:type="esdl:OutPort" id="348546d4-7fdf-42f0-b219-c55887f6c8bf" name="OutPh3" connectedTo="a9006230-8b20-430b-933a-3a1b8c5558fa"/>
          <geometry xsi:type="esdl:Point" lat="157778.967" lon="433616.886"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="18.025628893311225" name="lv_cable_trafo7_lvnetwork6_to_home_4_arch6" id="314f0630-0a99-43a0-8085-d63c71a524f9" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="8d834bc0-e614-4486-98da-560d8cc601cf" name="In" connectedTo="dfe0df80-a9d5-44fc-a919-762f6aedc212"/>
        <port xsi:type="esdl:OutPort" id="8396a13a-628a-4e4c-ac17-ebe18c7b2208" name="Out" connectedTo="13ac597c-87c8-4fb1-bba8-db358cdd32a9"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157781.107" CRS="WGS84" lon="433612.18"/>
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome738" id="38dec074-9e49-4f74-8214-77aa99578fcd">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="55a1e957-35bc-477a-a2f4-bd9594ec3c1b" name="In" connectedTo="787ee80c-2211-41a9-a6b5-308aaf7ef6d7"/>
          <port xsi:type="esdl:OutPort" id="8cd199de-c584-409e-a0e8-23917ef710ac" name="Out" connectedTo="d63b0062-5e24-4598-90e1-82ba115f9f98"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="70d9b808-0681-4ec8-8519-ece578630c13" name="In" connectedTo="a9bcece2-55ed-4504-9e1d-7dd68f048fc0"/>
          <port xsi:type="esdl:OutPort" id="7f751b13-d69e-4243-8a29-ae9b643ed59b" name="Out" connectedTo="f5b9b759-7a26-43f4-8191-de9fec610843"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="c8513446-0b9a-49f8-8fb4-9d1d621a2109" name="In" connectedTo="b3e9d33c-2417-4003-8c9b-aeec307236c4"/>
          <port xsi:type="esdl:OutPort" id="5ec4af66-257c-43d3-bdb7-575b7efb7989" name="Out" connectedTo="71d7d2b7-9cb5-44c0-aa84-f13c2b2832d2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="41850efa-f9f3-4e35-a594-c961f8fc8dd3" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="d63b0062-5e24-4598-90e1-82ba115f9f98" name="In_Ph1" connectedTo="8cd199de-c584-409e-a0e8-23917ef710ac"/>
          <port xsi:type="esdl:InPort" id="f5b9b759-7a26-43f4-8191-de9fec610843" name="In_Ph2" connectedTo="7f751b13-d69e-4243-8a29-ae9b643ed59b"/>
          <port xsi:type="esdl:InPort" id="71d7d2b7-9cb5-44c0-aa84-f13c2b2832d2" name="In_Ph3" connectedTo="5ec4af66-257c-43d3-bdb7-575b7efb7989"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome738" id="682dcb4b-973c-42e9-9692-9bb94afbd7f0">
          <port xsi:type="esdl:InPort" id="13ac597c-87c8-4fb1-bba8-db358cdd32a9" name="In" connectedTo="8396a13a-628a-4e4c-ac17-ebe18c7b2208"/>
          <port xsi:type="esdl:OutPort" id="787ee80c-2211-41a9-a6b5-308aaf7ef6d7" name="OutPh1" connectedTo="55a1e957-35bc-477a-a2f4-bd9594ec3c1b"/>
          <port xsi:type="esdl:OutPort" id="a9bcece2-55ed-4504-9e1d-7dd68f048fc0" name="OutPh2" connectedTo="70d9b808-0681-4ec8-8519-ece578630c13"/>
          <port xsi:type="esdl:OutPort" id="b3e9d33c-2417-4003-8c9b-aeec307236c4" name="OutPh3" connectedTo="c8513446-0b9a-49f8-8fb4-9d1d621a2109"/>
          <geometry xsi:type="esdl:Point" lat="157781.107" lon="433612.18"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_9" id="0fa4e3cf-f85c-4dc7-b34b-3364ad630907">
        <port xsi:type="esdl:InPort" id="91093d61-55c5-4b5f-8383-f6b5372f163e" name="In" connectedTo="e0ad8518-2709-4c8d-874d-9f985087a170"/>
        <port xsi:type="esdl:OutPort" id="99f2717e-265f-43b0-a9d5-d27596665f4f" name="Out" connectedTo="b22c4393-6f8b-4141-9ddc-530b25ec4459"/>
        <geometry xsi:type="esdl:Point" lat="157764.444" CRS="WGS84" lon="433633.072"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.756978459982484" name="lv_cable_trafo7_lvnetwork6_9_main_grid" id="b962b5ac-b934-470c-bdc5-31d782f73189" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="e1aa9292-f7a3-4c04-8fd8-981703a347e2" name="In" connectedTo="dfe0df80-a9d5-44fc-a919-762f6aedc212"/>
        <port xsi:type="esdl:OutPort" id="e0ad8518-2709-4c8d-874d-9f985087a170" name="Out" connectedTo="91093d61-55c5-4b5f-8383-f6b5372f163e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157769.226" CRS="WGS84" lon="433625.736"/>
          <point xsi:type="esdl:Point" lat="157764.507" CRS="WGS84" lon="433632.972"/>
          <point xsi:type="esdl:Point" lat="157764.444" CRS="WGS84" lon="433633.072"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo7_lvnetwork6_10" id="9332141b-bff4-451d-bdf6-609b2d11a88d">
        <port xsi:type="esdl:InPort" id="6384c73f-611b-455b-aac4-7875b12aafbd" name="In" connectedTo="5925d63b-5ca1-4bac-a291-a0d900215f31"/>
        <port xsi:type="esdl:OutPort" id="6b76070a-846b-465d-bcba-7ebb8db548fe" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="157802.104" CRS="WGS84" lon="433515.727"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="7.116801483699323" name="lv_cable_trafo7_lvnetwork6_10_main_grid" id="c01515b3-9967-4bae-941f-065e0db3592b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="b22c4393-6f8b-4141-9ddc-530b25ec4459" name="In" connectedTo="99f2717e-265f-43b0-a9d5-d27596665f4f"/>
        <port xsi:type="esdl:OutPort" id="5925d63b-5ca1-4bac-a291-a0d900215f31" name="Out" connectedTo="6384c73f-611b-455b-aac4-7875b12aafbd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157797.065" CRS="WGS84" lon="433516.123"/>
          <point xsi:type="esdl:Point" lat="157797.314" CRS="WGS84" lon="433515.675"/>
          <point xsi:type="esdl:Point" lat="157797.697" CRS="WGS84" lon="433513.887"/>
          <point xsi:type="esdl:Point" lat="157802.104" CRS="WGS84" lon="433515.727"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo7_lvnetwork6" id="2fb4f048-aa3a-4b6b-84a5-88cab7dc0650" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="7950fee4-2d82-4688-b7ed-38dcf84d8d19" name="Out" connectedTo="8c04884b-6f1e-47f2-b648-34069fa9f497"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo7_lvnetwork6" id="64847537-ce12-41ba-b0be-7556df5494b5">
        <port xsi:type="esdl:InPort" id="8c04884b-6f1e-47f2-b648-34069fa9f497" name="In" connectedTo="7950fee4-2d82-4688-b7ed-38dcf84d8d19"/>
        <port xsi:type="esdl:OutPort" id="531140bd-2ad8-4c99-b046-0cf27ce4dfd9" name="Out" connectedTo="91ac3b3e-367e-472e-8b2d-422867aa1b4e"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer44" id="1ac6e4df-d950-45b4-af2a-9162b1560977" commissioningDate="1964-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="91ac3b3e-367e-472e-8b2d-422867aa1b4e" name="In" connectedTo="531140bd-2ad8-4c99-b046-0cf27ce4dfd9"/>
        <port xsi:type="esdl:OutPort" id="e19aa11d-d91b-49da-9c40-a52d2f0a591d" name="Out" connectedTo="c8c99296-721e-44b5-b112-0c880e6089a3"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint46" id="f9d51b6f-7e0a-44d5-aae2-a4fa8b4997e0">
        <port xsi:type="esdl:InPort" id="c8c99296-721e-44b5-b112-0c880e6089a3" name="In" connectedTo="e19aa11d-d91b-49da-9c40-a52d2f0a591d"/>
        <port xsi:type="esdl:OutPort" id="82741782-a491-4a5b-8373-c4d26b11749d" name="Out" connectedTo="6e845a3f-7095-4f6d-ae06-67625a74cb6f"/>
        <geometry xsi:type="esdl:Point" lat="157787.211" CRS="WGS84" lon="433362.476"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
