<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="38854095-7f97-4d25-9c13-5baedb0fd9a0" description="Autogenerated based on gis data trafo14_lvnetwork2" name="trafo14_lvnetwork2">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="9d0280b4-45ea-4314-93af-2ba351629ac3"/>
  <instance xsi:type="esdl:Instance" id="ddf8c6ee-ddfb-4bec-a75a-2a0fcc7e944a" name="Instance name">
    <area xsi:type="esdl:Area" id="aa7c6fac-4489-440c-a4ea-da5176d759f0" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_2" id="125fc2bf-fb3f-4033-9166-9b3abbd86436">
        <port xsi:type="esdl:InPort" id="f1406dac-f100-4b52-9e6c-11dddc7aeab2" name="In" connectedTo="bab7e590-5599-4720-ab7c-66af932abb22"/>
        <port xsi:type="esdl:OutPort" id="ee459f60-ccd2-411a-877d-3c3c25728e41" name="Out" connectedTo="50cf7496-b145-41aa-afeb-be4bde8b773d"/>
        <geometry xsi:type="esdl:Point" lat="158103.258" CRS="WGS84" lon="434478.695"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="34.7754871186267" name="lv_cable_trafo14_lvnetwork2_2_main_grid" id="b6a3609d-21fe-4e2e-b6b9-48d103ed5973" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="d112fd6e-5a5a-4a53-991b-fffde280d5bd" name="In" connectedTo="d638a3a9-19b9-4a95-bc3b-7b6893e1f4a7"/>
        <port xsi:type="esdl:OutPort" id="bab7e590-5599-4720-ab7c-66af932abb22" name="Out" connectedTo="f1406dac-f100-4b52-9e6c-11dddc7aeab2"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158126.218" CRS="WGS84" lon="434493.643"/>
          <point xsi:type="esdl:Point" lat="158125.671" CRS="WGS84" lon="434493.208"/>
          <point xsi:type="esdl:Point" lat="158122.56" CRS="WGS84" lon="434497.123"/>
          <point xsi:type="esdl:Point" lat="158110.738" CRS="WGS84" lon="434487.728"/>
          <point xsi:type="esdl:Point" lat="158112.293" CRS="WGS84" lon="434485.772"/>
          <point xsi:type="esdl:Point" lat="158111.748" CRS="WGS84" lon="434485.339"/>
          <point xsi:type="esdl:Point" lat="158103.258" CRS="WGS84" lon="434478.695"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_3" id="f4b72e61-48e7-4e1e-af89-b0df9bc93af5">
        <port xsi:type="esdl:InPort" id="f8148f3d-8e2d-43f2-84de-04839fe6bcb5" name="In" connectedTo="fa500289-e24e-4cd1-b4b8-62d4ad858fe7"/>
        <port xsi:type="esdl:OutPort" id="c40f9b9d-2c4e-4d1a-ab8d-5c1afea144a4" name="Out" connectedTo="504cb089-94cd-45b2-873b-c43f312267d5 1f6eb794-0063-4aae-9e83-57c77cc2e7fe"/>
        <geometry xsi:type="esdl:Point" lat="158078.76946322454" CRS="WGS84" lon="434463.42787390656"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="29.46919444198648" name="lv_cable_trafo14_lvnetwork2_3_main_grid" id="fec4e345-9309-41c8-af4c-1905b394c009" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="50cf7496-b145-41aa-afeb-be4bde8b773d" name="In" connectedTo="ee459f60-ccd2-411a-877d-3c3c25728e41"/>
        <port xsi:type="esdl:OutPort" id="fa500289-e24e-4cd1-b4b8-62d4ad858fe7" name="Out" connectedTo="f8148f3d-8e2d-43f2-84de-04839fe6bcb5"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158103.258" CRS="WGS84" lon="434478.695"/>
          <point xsi:type="esdl:Point" lat="158101.727" CRS="WGS84" lon="434477.487"/>
          <point xsi:type="esdl:Point" lat="158101.461604778" CRS="WGS84" lon="434477.644414954"/>
          <point xsi:type="esdl:Point" lat="158101.176304717" CRS="WGS84" lon="434477.761932448"/>
          <point xsi:type="esdl:Point" lat="158100.877054958" CRS="WGS84" lon="434477.83709951"/>
          <point xsi:type="esdl:Point" lat="158100.570101819" CRS="WGS84" lon="434477.868347156"/>
          <point xsi:type="esdl:Point" lat="158100.261852413" CRS="WGS84" lon="434477.855023148"/>
          <point xsi:type="esdl:Point" lat="158099.958740909" CRS="WGS84" lon="434477.797405601"/>
          <point xsi:type="esdl:Point" lat="158099.667094232" CRS="WGS84" lon="434477.696697181"/>
          <point xsi:type="esdl:Point" lat="158099.393" CRS="WGS84" lon="434477.555"/>
          <point xsi:type="esdl:Point" lat="158097.54" CRS="WGS84" lon="434476.093"/>
          <point xsi:type="esdl:Point" lat="158093.402" CRS="WGS84" lon="434472.828"/>
          <point xsi:type="esdl:Point" lat="158089.956" CRS="WGS84" lon="434470.109"/>
          <point xsi:type="esdl:Point" lat="158078.76946322454" CRS="WGS84" lon="434463.42787390656"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="7.864423316164522" name="lv_cable_trafo14_lvnetwork2_to_home_8_arch3" id="c4989465-5cf7-4383-8cbd-6c95f5c6fcca" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="504cb089-94cd-45b2-873b-c43f312267d5" name="In" connectedTo="c40f9b9d-2c4e-4d1a-ab8d-5c1afea144a4"/>
        <port xsi:type="esdl:OutPort" id="54407406-80a4-4649-9c8c-cecca942299e" name="Out" connectedTo="9d4fe773-a93c-4e16-b719-cca402560c53"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158082.802" CRS="WGS84" lon="434456.676"/>
          <point xsi:type="esdl:Point" lat="158078.76946322454" CRS="WGS84" lon="434463.42787390656"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1619" id="dca3d628-5ff3-4def-9f31-cc1cf7482ae2">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="195c137b-a3c3-4db9-b6b1-2b592fa79632" name="In" connectedTo="0b8ea7c8-564a-46de-8f72-2bfde02026dc"/>
          <port xsi:type="esdl:OutPort" id="1c67dc8c-4ce7-4a1b-abca-d656f222ac59" name="Out" connectedTo="7ca0b094-8877-4a8e-9cfa-49519d3d9194"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="8b6ab262-cf35-4cc5-86ff-d4503dd4700a" name="In" connectedTo="87c361f8-e4ef-46cc-ae71-d24a96bdc528"/>
          <port xsi:type="esdl:OutPort" id="c9a63997-7e06-459b-84c7-3f7f850fc421" name="Out" connectedTo="a25a8c55-b965-4d69-857d-b100657d62d3"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="3743bfc0-da77-4d24-bf20-a95ed4ff4655" name="In" connectedTo="90264041-311d-429b-9ae9-3866a0722ce9"/>
          <port xsi:type="esdl:OutPort" id="2d71669d-6591-4569-8b1b-226547a9fbe9" name="Out" connectedTo="4fe01117-1b6c-44cb-b185-0d7a4d5beb4c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="7e206886-293c-453a-ad94-520709ea8faa" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7ca0b094-8877-4a8e-9cfa-49519d3d9194" name="In_Ph1" connectedTo="1c67dc8c-4ce7-4a1b-abca-d656f222ac59"/>
          <port xsi:type="esdl:InPort" id="a25a8c55-b965-4d69-857d-b100657d62d3" name="In_Ph2" connectedTo="c9a63997-7e06-459b-84c7-3f7f850fc421"/>
          <port xsi:type="esdl:InPort" id="4fe01117-1b6c-44cb-b185-0d7a4d5beb4c" name="In_Ph3" connectedTo="2d71669d-6591-4569-8b1b-226547a9fbe9"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1619" id="fa16b358-c9b4-44df-a1b4-e322e5515337">
          <port xsi:type="esdl:InPort" id="9d4fe773-a93c-4e16-b719-cca402560c53" name="In" connectedTo="54407406-80a4-4649-9c8c-cecca942299e"/>
          <port xsi:type="esdl:OutPort" id="0b8ea7c8-564a-46de-8f72-2bfde02026dc" name="OutPh1" connectedTo="195c137b-a3c3-4db9-b6b1-2b592fa79632"/>
          <port xsi:type="esdl:OutPort" id="87c361f8-e4ef-46cc-ae71-d24a96bdc528" name="OutPh2" connectedTo="8b6ab262-cf35-4cc5-86ff-d4503dd4700a"/>
          <port xsi:type="esdl:OutPort" id="90264041-311d-429b-9ae9-3866a0722ce9" name="OutPh3" connectedTo="3743bfc0-da77-4d24-bf20-a95ed4ff4655"/>
          <geometry xsi:type="esdl:Point" lat="158082.802" lon="434456.676"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_4" id="c3ea58af-eb54-45ce-803d-d343d06d5312">
        <port xsi:type="esdl:InPort" id="fac3cfc4-6912-4b6e-b014-1d50087534ef" name="In" connectedTo="395561ff-dc39-497d-8048-a436db0ca955"/>
        <port xsi:type="esdl:OutPort" id="c02996c1-68ed-4441-b488-1995844e9cc9" name="Out" connectedTo="17b37cad-f386-4a59-a3d8-e8b1a487c77a 568ca056-957e-4588-9c47-30f288c1ccbd"/>
        <geometry xsi:type="esdl:Point" lat="158072.95145636075" CRS="WGS84" lon="434460.1705752884"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="7.0008126697413715" name="lv_cable_trafo14_lvnetwork2_4_main_grid" id="c9a2faac-1084-4fcb-93de-5fbc790de675" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="1f6eb794-0063-4aae-9e83-57c77cc2e7fe" name="In" connectedTo="c40f9b9d-2c4e-4d1a-ab8d-5c1afea144a4"/>
        <port xsi:type="esdl:OutPort" id="395561ff-dc39-497d-8048-a436db0ca955" name="Out" connectedTo="fac3cfc4-6912-4b6e-b014-1d50087534ef"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158078.76946322454" CRS="WGS84" lon="434463.42787390656"/>
          <point xsi:type="esdl:Point" lat="158077.364" CRS="WGS84" lon="434463.595"/>
          <point xsi:type="esdl:Point" lat="158073.854" CRS="WGS84" lon="434460.871"/>
          <point xsi:type="esdl:Point" lat="158072.95145636075" CRS="WGS84" lon="434460.1705752884"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.834784445730584" name="lv_cable_trafo14_lvnetwork2_to_home_7_arch3" id="a2545a0d-87a7-4866-a283-9808a11090ad" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="17b37cad-f386-4a59-a3d8-e8b1a487c77a" name="In" connectedTo="c02996c1-68ed-4441-b488-1995844e9cc9"/>
        <port xsi:type="esdl:OutPort" id="ef486f69-f719-4af8-bf7e-908c74f8a4e9" name="Out" connectedTo="7568a5b7-793e-4655-9bb5-cbde5a0c433c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158078.368" CRS="WGS84" lon="434453.191"/>
          <point xsi:type="esdl:Point" lat="158072.95145636075" CRS="WGS84" lon="434460.1705752884"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1618" id="f549f032-fcc9-403d-86bd-6f8a862319bb">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="324c021f-b8be-49e6-967a-c7aae5afad74" name="In" connectedTo="0d048d7f-8ab3-4c89-9c7a-89f231f8cce7"/>
          <port xsi:type="esdl:OutPort" id="c39b3334-4872-44ff-aefd-e7a77085d58e" name="Out" connectedTo="422d8307-3d72-4d8d-93d0-a6ffee6b7adc"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="53076ffa-aaae-4168-8b11-eb03f3546db3" name="In" connectedTo="4edbfc88-c093-4b65-a7ef-b7122e15e124"/>
          <port xsi:type="esdl:OutPort" id="ff5cce42-5de1-4660-bd06-ad10b077662e" name="Out" connectedTo="349b92a9-1dd2-48c0-9b96-f500d6558d71"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="6581f665-f2f1-4cd8-8865-5ae8b8d65147" name="In" connectedTo="0ee19a9d-a950-4b07-815b-78ac6ab1dc51"/>
          <port xsi:type="esdl:OutPort" id="1e025adc-0230-4594-a480-e5c890587d69" name="Out" connectedTo="ed801865-10d7-4fd9-974c-91024da3db60"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="658c4bf1-fdc4-40e5-8d44-d99039793912" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="422d8307-3d72-4d8d-93d0-a6ffee6b7adc" name="In_Ph1" connectedTo="c39b3334-4872-44ff-aefd-e7a77085d58e"/>
          <port xsi:type="esdl:InPort" id="349b92a9-1dd2-48c0-9b96-f500d6558d71" name="In_Ph2" connectedTo="ff5cce42-5de1-4660-bd06-ad10b077662e"/>
          <port xsi:type="esdl:InPort" id="ed801865-10d7-4fd9-974c-91024da3db60" name="In_Ph3" connectedTo="1e025adc-0230-4594-a480-e5c890587d69"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1618" id="0128104d-7e05-4bff-82fa-939ce491f5af">
          <port xsi:type="esdl:InPort" id="7568a5b7-793e-4655-9bb5-cbde5a0c433c" name="In" connectedTo="ef486f69-f719-4af8-bf7e-908c74f8a4e9"/>
          <port xsi:type="esdl:OutPort" id="0d048d7f-8ab3-4c89-9c7a-89f231f8cce7" name="OutPh1" connectedTo="324c021f-b8be-49e6-967a-c7aae5afad74"/>
          <port xsi:type="esdl:OutPort" id="4edbfc88-c093-4b65-a7ef-b7122e15e124" name="OutPh2" connectedTo="53076ffa-aaae-4168-8b11-eb03f3546db3"/>
          <port xsi:type="esdl:OutPort" id="0ee19a9d-a950-4b07-815b-78ac6ab1dc51" name="OutPh3" connectedTo="6581f665-f2f1-4cd8-8865-5ae8b8d65147"/>
          <geometry xsi:type="esdl:Point" lat="158078.368" lon="434453.191"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_5" id="e2c29e15-52a3-4e9c-a21d-7c55f085bf31">
        <port xsi:type="esdl:InPort" id="dab42645-229e-47fa-83bd-839b7da45ff9" name="In" connectedTo="5d06edf3-5ba6-4656-8e78-4ceb734f6863"/>
        <port xsi:type="esdl:OutPort" id="c36e9432-edf7-4720-a943-584b1eb393d9" name="Out" connectedTo="693b65b8-3f61-4922-959a-abb9fa79a5eb 6647b906-9242-4b88-9c17-e141a8d866ba"/>
        <geometry xsi:type="esdl:Point" lat="158068.6539525884" CRS="WGS84" lon="434456.8352842159"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.439917757788895" name="lv_cable_trafo14_lvnetwork2_5_main_grid" id="5fe8543a-22dc-4d04-9927-2c5fcb4f0b06" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="568ca056-957e-4588-9c47-30f288c1ccbd" name="In" connectedTo="c02996c1-68ed-4441-b488-1995844e9cc9"/>
        <port xsi:type="esdl:OutPort" id="5d06edf3-5ba6-4656-8e78-4ceb734f6863" name="Out" connectedTo="dab42645-229e-47fa-83bd-839b7da45ff9"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158072.95145636075" CRS="WGS84" lon="434460.1705752884"/>
          <point xsi:type="esdl:Point" lat="158068.6539525884" CRS="WGS84" lon="434456.8352842159"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.867665504589768" name="lv_cable_trafo14_lvnetwork2_to_home_6_arch3" id="a3895515-f713-4b2b-b31b-f331d6abe9a7" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="693b65b8-3f61-4922-959a-abb9fa79a5eb" name="In" connectedTo="c36e9432-edf7-4720-a943-584b1eb393d9"/>
        <port xsi:type="esdl:OutPort" id="c5157a7b-8175-4e21-8230-a7291a16e1c8" name="Out" connectedTo="76425049-d7af-4d61-895d-bcdf5747b353"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158074.091" CRS="WGS84" lon="434449.83"/>
          <point xsi:type="esdl:Point" lat="158068.6539525884" CRS="WGS84" lon="434456.8352842159"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1617" id="a61ec21c-8bfa-4175-a21c-c8173c852a94">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="bd352b4a-a0aa-43f4-a069-0a5297f67cb1" name="In" connectedTo="310a8862-3232-4c24-a044-ae72edc20243"/>
          <port xsi:type="esdl:OutPort" id="2362e7e5-e7a0-495e-a56e-d117f2cde95f" name="Out" connectedTo="f09816ad-094a-46f9-8d0c-bcf499fd4dde"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="5d752b08-1a1d-45bb-b1cd-e77941c6d984" name="In" connectedTo="5656d97b-7468-4d7f-b086-dd733d5c9aad"/>
          <port xsi:type="esdl:OutPort" id="5641f374-7d3b-4b68-b908-ca28bed9da53" name="Out" connectedTo="b0d914e2-8e8e-48d3-840e-f187be0d013f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="440973e9-c6f7-4271-b277-ca306845670d" name="In" connectedTo="f16bc2b4-2132-4159-9def-ee8df9f37193"/>
          <port xsi:type="esdl:OutPort" id="c7cf724d-1853-472e-85a8-b558af020a8e" name="Out" connectedTo="6f87aa8b-3707-470d-b7dd-32971ff2d6c7"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="4f7eb372-51b2-4575-b06f-91cee18bdb49" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="f09816ad-094a-46f9-8d0c-bcf499fd4dde" name="In_Ph1" connectedTo="2362e7e5-e7a0-495e-a56e-d117f2cde95f"/>
          <port xsi:type="esdl:InPort" id="b0d914e2-8e8e-48d3-840e-f187be0d013f" name="In_Ph2" connectedTo="5641f374-7d3b-4b68-b908-ca28bed9da53"/>
          <port xsi:type="esdl:InPort" id="6f87aa8b-3707-470d-b7dd-32971ff2d6c7" name="In_Ph3" connectedTo="c7cf724d-1853-472e-85a8-b558af020a8e"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1617" id="1c96a838-1793-4cc4-be83-88827479f395">
          <port xsi:type="esdl:InPort" id="76425049-d7af-4d61-895d-bcdf5747b353" name="In" connectedTo="c5157a7b-8175-4e21-8230-a7291a16e1c8"/>
          <port xsi:type="esdl:OutPort" id="310a8862-3232-4c24-a044-ae72edc20243" name="OutPh1" connectedTo="bd352b4a-a0aa-43f4-a069-0a5297f67cb1"/>
          <port xsi:type="esdl:OutPort" id="5656d97b-7468-4d7f-b086-dd733d5c9aad" name="OutPh2" connectedTo="5d752b08-1a1d-45bb-b1cd-e77941c6d984"/>
          <port xsi:type="esdl:OutPort" id="f16bc2b4-2132-4159-9def-ee8df9f37193" name="OutPh3" connectedTo="440973e9-c6f7-4271-b277-ca306845670d"/>
          <geometry xsi:type="esdl:Point" lat="158074.091" lon="434449.83"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_6" id="b3d7da59-57b1-463c-9148-663dfc084e39">
        <port xsi:type="esdl:InPort" id="e62521b9-dfed-4631-bd14-68ed524bb08d" name="In" connectedTo="db6ff324-603a-4a3c-b172-2c358574d6e9"/>
        <port xsi:type="esdl:OutPort" id="b0dffdda-1880-4eaf-b499-7341d95ae12e" name="Out" connectedTo="1899fb3e-4353-441c-afdf-7e3f1c3d54b8 c67e2f81-36b1-42f9-a955-57faca05d3ed"/>
        <geometry xsi:type="esdl:Point" lat="158064.33676507353" CRS="WGS84" lon="434453.48439422814"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.465031880870988" name="lv_cable_trafo14_lvnetwork2_6_main_grid" id="94e74757-decd-4c03-b7bd-767e858377f2" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="6647b906-9242-4b88-9c17-e141a8d866ba" name="In" connectedTo="c36e9432-edf7-4720-a943-584b1eb393d9"/>
        <port xsi:type="esdl:OutPort" id="db6ff324-603a-4a3c-b172-2c358574d6e9" name="Out" connectedTo="e62521b9-dfed-4631-bd14-68ed524bb08d"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158068.6539525884" CRS="WGS84" lon="434456.8352842159"/>
          <point xsi:type="esdl:Point" lat="158064.367" CRS="WGS84" lon="434453.508"/>
          <point xsi:type="esdl:Point" lat="158064.33676507353" CRS="WGS84" lon="434453.48439422814"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.900329129666806" name="lv_cable_trafo14_lvnetwork2_to_home_5_arch3" id="39052f18-408a-4e35-9817-d327270e3347" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="1899fb3e-4353-441c-afdf-7e3f1c3d54b8" name="In" connectedTo="b0dffdda-1880-4eaf-b499-7341d95ae12e"/>
        <port xsi:type="esdl:OutPort" id="ddb54916-8755-4446-ae1a-3edf9462e81f" name="Out" connectedTo="1b6d60de-9c5e-4820-b346-fb072265f5cd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158069.814" CRS="WGS84" lon="434446.469"/>
          <point xsi:type="esdl:Point" lat="158064.33676507353" CRS="WGS84" lon="434453.48439422814"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1616" id="98182f61-4031-475e-b217-32f509b11bb3">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="7938a3f6-60fd-4f51-a0b0-0671f762f668" name="In" connectedTo="484b569c-d1c5-44f8-9c16-04f66a703ed9"/>
          <port xsi:type="esdl:OutPort" id="93ee9ead-574f-402b-8bd7-e02c03a6535a" name="Out" connectedTo="35a6e914-b45c-44de-949d-2cd5e009cbc1"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="d18737ca-b9c0-4077-b503-66eec5826e97" name="In" connectedTo="0bdc702e-ed9c-4b83-a687-56b4c4b66fd8"/>
          <port xsi:type="esdl:OutPort" id="1c986e71-ae52-4088-9f45-2b7e792205ad" name="Out" connectedTo="ba4ae8a8-a494-42d4-8123-402bbd66f016"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="0c4fe563-481c-4c46-8f80-43a8e41d146b" name="In" connectedTo="840898d3-03bc-45e8-a0e3-d18ca9fafe36"/>
          <port xsi:type="esdl:OutPort" id="2e296ba0-bd04-4194-a1a9-65d698ac3a63" name="Out" connectedTo="1e3e043b-044a-477f-8f7f-d844effea6a4"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="246ecf3a-2057-458b-81f5-98a760a27a6d" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="35a6e914-b45c-44de-949d-2cd5e009cbc1" name="In_Ph1" connectedTo="93ee9ead-574f-402b-8bd7-e02c03a6535a"/>
          <port xsi:type="esdl:InPort" id="ba4ae8a8-a494-42d4-8123-402bbd66f016" name="In_Ph2" connectedTo="1c986e71-ae52-4088-9f45-2b7e792205ad"/>
          <port xsi:type="esdl:InPort" id="1e3e043b-044a-477f-8f7f-d844effea6a4" name="In_Ph3" connectedTo="2e296ba0-bd04-4194-a1a9-65d698ac3a63"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1616" id="d862a8b6-466b-456d-a0c2-5eaeb5acf0ad">
          <port xsi:type="esdl:InPort" id="1b6d60de-9c5e-4820-b346-fb072265f5cd" name="In" connectedTo="ddb54916-8755-4446-ae1a-3edf9462e81f"/>
          <port xsi:type="esdl:OutPort" id="484b569c-d1c5-44f8-9c16-04f66a703ed9" name="OutPh1" connectedTo="7938a3f6-60fd-4f51-a0b0-0671f762f668"/>
          <port xsi:type="esdl:OutPort" id="0bdc702e-ed9c-4b83-a687-56b4c4b66fd8" name="OutPh2" connectedTo="d18737ca-b9c0-4077-b503-66eec5826e97"/>
          <port xsi:type="esdl:OutPort" id="840898d3-03bc-45e8-a0e3-d18ca9fafe36" name="OutPh3" connectedTo="0c4fe563-481c-4c46-8f80-43a8e41d146b"/>
          <geometry xsi:type="esdl:Point" lat="158069.814" lon="434446.469"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_7" id="f0ec0e40-e18d-41e6-a608-021cb8442cf9">
        <port xsi:type="esdl:InPort" id="ebf23526-7d05-44d6-9097-01a840e9eff7" name="In" connectedTo="4027fa84-c4f1-4cb9-844d-cb704bd04e5e"/>
        <port xsi:type="esdl:OutPort" id="cdded502-dbd3-4588-8f67-2a1a81415d31" name="Out" connectedTo="a2f167ae-f06f-470f-a198-62c1b4f42cca a764ccde-0b7e-496c-bcd7-6c44a5e240bf"/>
        <geometry xsi:type="esdl:Point" lat="158060.04702975933" CRS="WGS84" lon="434450.13466681127"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.442655862104405" name="lv_cable_trafo14_lvnetwork2_7_main_grid" id="18b2356e-8472-482f-964c-0aad26fede1f" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="c67e2f81-36b1-42f9-a955-57faca05d3ed" name="In" connectedTo="b0dffdda-1880-4eaf-b499-7341d95ae12e"/>
        <port xsi:type="esdl:OutPort" id="4027fa84-c4f1-4cb9-844d-cb704bd04e5e" name="Out" connectedTo="ebf23526-7d05-44d6-9097-01a840e9eff7"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158064.33676507353" CRS="WGS84" lon="434453.48439422814"/>
          <point xsi:type="esdl:Point" lat="158060.04702975933" CRS="WGS84" lon="434450.13466681127"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.916436551637196" name="lv_cable_trafo14_lvnetwork2_to_home_4_arch3" id="b121ba9a-583b-4db4-8300-9e11f3a41fdf" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="a2f167ae-f06f-470f-a198-62c1b4f42cca" name="In" connectedTo="cdded502-dbd3-4588-8f67-2a1a81415d31"/>
        <port xsi:type="esdl:OutPort" id="802ef5f8-490a-4cfd-ab93-591fd923a7eb" name="Out" connectedTo="53469571-1f5c-4d56-b3e7-53b2aa530d09"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158065.536" CRS="WGS84" lon="434443.108"/>
          <point xsi:type="esdl:Point" lat="158060.04702975933" CRS="WGS84" lon="434450.13466681127"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1615" id="ba3b01b2-c43d-464b-854e-2bb7e3f714ac">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="a923bfd6-7564-4cc3-ae0c-7cd644271a53" name="In" connectedTo="f740d573-d960-41de-ada6-eb2693c044e0"/>
          <port xsi:type="esdl:OutPort" id="df09b869-2c9f-49cb-b0d9-ed95eea3ed58" name="Out" connectedTo="d1048642-6005-4e27-a0d8-3f3a4c8700fa"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="e5101336-14b7-4a02-8b1e-e55e5c131bf2" name="In" connectedTo="6d198bac-6450-4293-bf48-85cdcaa84a2f"/>
          <port xsi:type="esdl:OutPort" id="3c938445-b2d1-49e2-9fdb-0f149a10503c" name="Out" connectedTo="b37af7f4-547d-42aa-9443-127775c7115f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="91167702-2d0e-491c-9dc9-a8b3a4edef56" name="In" connectedTo="03f610db-aec7-420e-a034-cc53d062f459"/>
          <port xsi:type="esdl:OutPort" id="1369a2c5-15b4-49ce-9290-56def00a4c10" name="Out" connectedTo="d14749c5-6c7a-44ff-8c59-b492ab92127f"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="5afd2982-5db0-4872-b134-23c303412ebe" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="d1048642-6005-4e27-a0d8-3f3a4c8700fa" name="In_Ph1" connectedTo="df09b869-2c9f-49cb-b0d9-ed95eea3ed58"/>
          <port xsi:type="esdl:InPort" id="b37af7f4-547d-42aa-9443-127775c7115f" name="In_Ph2" connectedTo="3c938445-b2d1-49e2-9fdb-0f149a10503c"/>
          <port xsi:type="esdl:InPort" id="d14749c5-6c7a-44ff-8c59-b492ab92127f" name="In_Ph3" connectedTo="1369a2c5-15b4-49ce-9290-56def00a4c10"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1615" id="4b6e3a4d-52e4-4f4c-9114-9e74a8ac3ccc">
          <port xsi:type="esdl:InPort" id="53469571-1f5c-4d56-b3e7-53b2aa530d09" name="In" connectedTo="802ef5f8-490a-4cfd-ab93-591fd923a7eb"/>
          <port xsi:type="esdl:OutPort" id="f740d573-d960-41de-ada6-eb2693c044e0" name="OutPh1" connectedTo="a923bfd6-7564-4cc3-ae0c-7cd644271a53"/>
          <port xsi:type="esdl:OutPort" id="6d198bac-6450-4293-bf48-85cdcaa84a2f" name="OutPh2" connectedTo="e5101336-14b7-4a02-8b1e-e55e5c131bf2"/>
          <port xsi:type="esdl:OutPort" id="03f610db-aec7-420e-a034-cc53d062f459" name="OutPh3" connectedTo="91167702-2d0e-491c-9dc9-a8b3a4edef56"/>
          <geometry xsi:type="esdl:Point" lat="158065.536" lon="434443.108"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_8" id="d74d684c-5703-48a0-bbce-97205b1cc5f6">
        <port xsi:type="esdl:InPort" id="845e27e6-3ca0-4a31-b2c9-36e111a29f04" name="In" connectedTo="c385d392-fa54-4b72-9a0b-26121164f358"/>
        <port xsi:type="esdl:OutPort" id="f1d57fc0-b215-4b0c-bc57-29cb803db31c" name="Out" connectedTo="252821f6-330e-409d-bc46-47a4d0c83816 841237ce-e2f3-4535-a34e-9fef08d1c83a"/>
        <geometry xsi:type="esdl:Point" lat="158055.76059047194" CRS="WGS84" lon="434446.7865946078"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.439039367759839" name="lv_cable_trafo14_lvnetwork2_8_main_grid" id="b533d983-0153-4394-ac20-433261ea125b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="a764ccde-0b7e-496c-bcd7-6c44a5e240bf" name="In" connectedTo="cdded502-dbd3-4588-8f67-2a1a81415d31"/>
        <port xsi:type="esdl:OutPort" id="c385d392-fa54-4b72-9a0b-26121164f358" name="Out" connectedTo="845e27e6-3ca0-4a31-b2c9-36e111a29f04"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158060.04702975933" CRS="WGS84" lon="434450.13466681127"/>
          <point xsi:type="esdl:Point" lat="158055.76059047194" CRS="WGS84" lon="434446.7865946078"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.933223369529314" name="lv_cable_trafo14_lvnetwork2_to_home_3_arch3" id="bd39d14c-36ce-4adb-a94c-8b7c00a6d541" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="252821f6-330e-409d-bc46-47a4d0c83816" name="In" connectedTo="f1d57fc0-b215-4b0c-bc57-29cb803db31c"/>
        <port xsi:type="esdl:OutPort" id="3cf8e73f-7949-4214-a9a1-0a7c1ffe1ed2" name="Out" connectedTo="1c40eba5-295b-4bb5-aaa8-b74d0a68d697"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158061.259" CRS="WGS84" lon="434439.746"/>
          <point xsi:type="esdl:Point" lat="158055.76059047194" CRS="WGS84" lon="434446.7865946078"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1614" id="c08adc1d-fe87-4284-843c-7b44556dfeeb">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="fd1d21d0-e9d4-4a1b-b9e9-7273eaa055ea" name="In" connectedTo="f90f4782-a55d-456d-818b-1c0aef196c99"/>
          <port xsi:type="esdl:OutPort" id="0c8f1b36-fa8a-4cfc-a726-0dcdc823f98e" name="Out" connectedTo="074a0168-588a-4b43-99a6-4881a331fd89"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="a001771e-9223-46ba-9bfc-dce42b746923" name="In" connectedTo="4a07b4ae-0f46-4d98-92c2-967a02074cac"/>
          <port xsi:type="esdl:OutPort" id="aaae7fd5-fe69-49b6-9525-12caef1c1a13" name="Out" connectedTo="b51328b0-d447-4c15-b330-34bffe5e057b"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="39ac639f-2f3c-484f-aa7f-df5e1d1b786b" name="In" connectedTo="5feb3327-aabb-43cd-8eb1-350cf4a614d6"/>
          <port xsi:type="esdl:OutPort" id="32c38028-3432-4b38-95b1-7ccd455cb39f" name="Out" connectedTo="afc46dcf-c928-495e-ab64-9eca0e9141ec"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="458b9001-7b8f-4d62-805f-e798c2fb49af" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="074a0168-588a-4b43-99a6-4881a331fd89" name="In_Ph1" connectedTo="0c8f1b36-fa8a-4cfc-a726-0dcdc823f98e"/>
          <port xsi:type="esdl:InPort" id="b51328b0-d447-4c15-b330-34bffe5e057b" name="In_Ph2" connectedTo="aaae7fd5-fe69-49b6-9525-12caef1c1a13"/>
          <port xsi:type="esdl:InPort" id="afc46dcf-c928-495e-ab64-9eca0e9141ec" name="In_Ph3" connectedTo="32c38028-3432-4b38-95b1-7ccd455cb39f"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1614" id="6072bc69-7573-46ef-86f5-4def89b4a8b2">
          <port xsi:type="esdl:InPort" id="1c40eba5-295b-4bb5-aaa8-b74d0a68d697" name="In" connectedTo="3cf8e73f-7949-4214-a9a1-0a7c1ffe1ed2"/>
          <port xsi:type="esdl:OutPort" id="f90f4782-a55d-456d-818b-1c0aef196c99" name="OutPh1" connectedTo="fd1d21d0-e9d4-4a1b-b9e9-7273eaa055ea"/>
          <port xsi:type="esdl:OutPort" id="4a07b4ae-0f46-4d98-92c2-967a02074cac" name="OutPh2" connectedTo="a001771e-9223-46ba-9bfc-dce42b746923"/>
          <port xsi:type="esdl:OutPort" id="5feb3327-aabb-43cd-8eb1-350cf4a614d6" name="OutPh3" connectedTo="39ac639f-2f3c-484f-aa7f-df5e1d1b786b"/>
          <geometry xsi:type="esdl:Point" lat="158061.259" lon="434439.746"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_9" id="14b05e88-df49-4787-976d-49c553a0dbce">
        <port xsi:type="esdl:InPort" id="256299dc-59ec-405e-a0a3-10e629d25afd" name="In" connectedTo="ef2bbc06-9874-4315-8adb-364521b19dc0"/>
        <port xsi:type="esdl:OutPort" id="db9922b3-8eb3-4c2f-96a6-b87eb82267fc" name="Out" connectedTo="ca6ddc86-e2ca-4628-84d8-1a9d3689a556 88f96791-7996-4732-b812-d01c58e10ef1"/>
        <geometry xsi:type="esdl:Point" lat="158051.47342952536" CRS="WGS84" lon="434443.4384593455"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.43964692941318" name="lv_cable_trafo14_lvnetwork2_9_main_grid" id="d7bdd895-2d2b-4b3a-a789-e8f7d7a4dde0" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="841237ce-e2f3-4535-a34e-9fef08d1c83a" name="In" connectedTo="f1d57fc0-b215-4b0c-bc57-29cb803db31c"/>
        <port xsi:type="esdl:OutPort" id="ef2bbc06-9874-4315-8adb-364521b19dc0" name="Out" connectedTo="256299dc-59ec-405e-a0a3-10e629d25afd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158055.76059047194" CRS="WGS84" lon="434446.7865946078"/>
          <point xsi:type="esdl:Point" lat="158051.47342952536" CRS="WGS84" lon="434443.4384593455"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="8.949616607000827" name="lv_cable_trafo14_lvnetwork2_to_home_2_arch3" id="b741ff0f-5156-44d2-a3a6-599110f635bd" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="ca6ddc86-e2ca-4628-84d8-1a9d3689a556" name="In" connectedTo="db9922b3-8eb3-4c2f-96a6-b87eb82267fc"/>
        <port xsi:type="esdl:OutPort" id="6f969afc-7346-428f-9ae1-8a1ed3eece0b" name="Out" connectedTo="19d4f063-b9cd-4f95-9fd8-0991b7e4ea68"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158056.982" CRS="WGS84" lon="434436.385"/>
          <point xsi:type="esdl:Point" lat="158051.47342952536" CRS="WGS84" lon="434443.4384593455"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1613" id="56ef87cf-c2ec-45a4-ae7f-66acbc7294ec">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="e3f58b83-9181-409b-8088-e7e2c83a3892" name="In" connectedTo="3d2a20aa-09ea-451f-bd43-994a3168a45a"/>
          <port xsi:type="esdl:OutPort" id="67af0f3d-9983-4c85-8846-aad5e3161bcc" name="Out" connectedTo="8aa3840b-247a-4af2-a004-8fac833becc2"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="88ceb64e-55ac-42c3-b774-34a3550856f0" name="In" connectedTo="cb70f2b6-9386-4751-b8de-8a489a460a33"/>
          <port xsi:type="esdl:OutPort" id="814c08a3-b19e-4ffb-8219-e330809442ac" name="Out" connectedTo="984a59b6-8429-441b-80dd-3207a0f42392"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="988d15dd-53e0-40d6-b7ce-560b7c825a45" name="In" connectedTo="10f47b11-0d84-40f8-9818-34eb6fcc83d0"/>
          <port xsi:type="esdl:OutPort" id="affdf055-c1de-46ee-8eb1-0b2a0e6d794c" name="Out" connectedTo="de29384b-c7e9-4088-8d7a-679099e8d3ff"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="bacdf5f5-8e1c-4aa2-82fb-5932b45ad613" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="8aa3840b-247a-4af2-a004-8fac833becc2" name="In_Ph1" connectedTo="67af0f3d-9983-4c85-8846-aad5e3161bcc"/>
          <port xsi:type="esdl:InPort" id="984a59b6-8429-441b-80dd-3207a0f42392" name="In_Ph2" connectedTo="814c08a3-b19e-4ffb-8219-e330809442ac"/>
          <port xsi:type="esdl:InPort" id="de29384b-c7e9-4088-8d7a-679099e8d3ff" name="In_Ph3" connectedTo="affdf055-c1de-46ee-8eb1-0b2a0e6d794c"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1613" id="8ed3df1f-f436-4eeb-956f-24b50b9a089e">
          <port xsi:type="esdl:InPort" id="19d4f063-b9cd-4f95-9fd8-0991b7e4ea68" name="In" connectedTo="6f969afc-7346-428f-9ae1-8a1ed3eece0b"/>
          <port xsi:type="esdl:OutPort" id="3d2a20aa-09ea-451f-bd43-994a3168a45a" name="OutPh1" connectedTo="e3f58b83-9181-409b-8088-e7e2c83a3892"/>
          <port xsi:type="esdl:OutPort" id="cb70f2b6-9386-4751-b8de-8a489a460a33" name="OutPh2" connectedTo="88ceb64e-55ac-42c3-b774-34a3550856f0"/>
          <port xsi:type="esdl:OutPort" id="10f47b11-0d84-40f8-9818-34eb6fcc83d0" name="OutPh3" connectedTo="988d15dd-53e0-40d6-b7ce-560b7c825a45"/>
          <geometry xsi:type="esdl:Point" lat="158056.982" lon="434436.385"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_10" id="7d8948cb-4c93-4bfc-b40f-9147e3481b09">
        <port xsi:type="esdl:InPort" id="71de1d43-5cb7-430d-958c-f307a5bfc0eb" name="In" connectedTo="a7fc2fb4-503c-4714-99b2-4f6d42085a2f"/>
        <port xsi:type="esdl:OutPort" id="0e1a4065-e066-410e-9f34-153ea4369400" name="Out" connectedTo="c714e55d-513f-42a3-b237-f611baa4e0cc e858d994-6dbd-4101-bcd7-61d731ae0ccb"/>
        <geometry xsi:type="esdl:Point" lat="158043.68" CRS="WGS84" lon="434425.931"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="26.150579761988766" name="lv_cable_trafo14_lvnetwork2_10_main_grid" id="b6f9da3e-bb5b-45f5-9a7c-c6d6145d9b5f" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="88f96791-7996-4732-b812-d01c58e10ef1" name="In" connectedTo="db9922b3-8eb3-4c2f-96a6-b87eb82267fc"/>
        <port xsi:type="esdl:OutPort" id="a7fc2fb4-503c-4714-99b2-4f6d42085a2f" name="Out" connectedTo="71de1d43-5cb7-430d-958c-f307a5bfc0eb"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158051.47342952536" CRS="WGS84" lon="434443.4384593455"/>
          <point xsi:type="esdl:Point" lat="158037.96" CRS="WGS84" lon="434432.885"/>
          <point xsi:type="esdl:Point" lat="158038.536" CRS="WGS84" lon="434432.153"/>
          <point xsi:type="esdl:Point" lat="158043.68" CRS="WGS84" lon="434425.931"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="6.039149580063963" name="lv_cable_trafo14_lvnetwork2_to_home_0_arch3" id="20a44bf4-a365-4c54-9f35-751e9c4ba180" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="c714e55d-513f-42a3-b237-f611baa4e0cc" name="In" connectedTo="0e1a4065-e066-410e-9f34-153ea4369400"/>
        <port xsi:type="esdl:OutPort" id="aa1c1657-8ae4-4595-95c1-76e3f8b33203" name="Out" connectedTo="5d1df01e-793c-4afa-927c-cd8f6c199517"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158048.42836551522" CRS="WGS84" lon="434429.66253488313"/>
          <point xsi:type="esdl:Point" lat="158043.68" CRS="WGS84" lon="434425.931"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1611" id="579591f6-5c2e-4bd9-b2ea-d3592fb0ab3a">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="e6a3d10b-684d-48be-a1fe-a665ebcbe94d" name="In" connectedTo="15abaef4-cd8e-48fd-9e96-56ae7c3d221d"/>
          <port xsi:type="esdl:OutPort" id="d6e50804-f41f-4890-bbbc-cc2c76d531ac" name="Out" connectedTo="44b0a37a-b81b-4af4-a796-1e548edc8112"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="8165a90e-93fe-45ed-b33b-56f0679ad3a0" name="In" connectedTo="5ccfbb15-8fb0-483d-be67-048714bc6894"/>
          <port xsi:type="esdl:OutPort" id="abcbdee4-79a2-482e-8786-ed851a43c839" name="Out" connectedTo="9e80be00-fb1c-44d7-99cf-49f305c665ad"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="6a23bb2d-03ed-425e-a895-c0900eaa7299" name="In" connectedTo="926bcece-5fe7-4f97-a5d5-6eb65b5d1be3"/>
          <port xsi:type="esdl:OutPort" id="46c85b87-2983-444c-92ea-7e96996e8955" name="Out" connectedTo="d4a9ae17-23c3-4a97-a7f0-8e7608c9235e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="96c4001f-73aa-4d93-9f73-c468b2580930" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="44b0a37a-b81b-4af4-a796-1e548edc8112" name="In_Ph1" connectedTo="d6e50804-f41f-4890-bbbc-cc2c76d531ac"/>
          <port xsi:type="esdl:InPort" id="9e80be00-fb1c-44d7-99cf-49f305c665ad" name="In_Ph2" connectedTo="abcbdee4-79a2-482e-8786-ed851a43c839"/>
          <port xsi:type="esdl:InPort" id="d4a9ae17-23c3-4a97-a7f0-8e7608c9235e" name="In_Ph3" connectedTo="46c85b87-2983-444c-92ea-7e96996e8955"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1611" id="ff06c59e-1f6c-43f6-9261-f8cb503f89e7">
          <port xsi:type="esdl:InPort" id="5d1df01e-793c-4afa-927c-cd8f6c199517" name="In" connectedTo="aa1c1657-8ae4-4595-95c1-76e3f8b33203"/>
          <port xsi:type="esdl:OutPort" id="15abaef4-cd8e-48fd-9e96-56ae7c3d221d" name="OutPh1" connectedTo="e6a3d10b-684d-48be-a1fe-a665ebcbe94d"/>
          <port xsi:type="esdl:OutPort" id="5ccfbb15-8fb0-483d-be67-048714bc6894" name="OutPh2" connectedTo="8165a90e-93fe-45ed-b33b-56f0679ad3a0"/>
          <port xsi:type="esdl:OutPort" id="926bcece-5fe7-4f97-a5d5-6eb65b5d1be3" name="OutPh3" connectedTo="6a23bb2d-03ed-425e-a895-c0900eaa7299"/>
          <geometry xsi:type="esdl:Point" lat="158048.42836551522" lon="434429.66253488313"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_11" id="d7aacbdf-a623-4a66-ac61-298ad3c1ebaf">
        <port xsi:type="esdl:InPort" id="5a85a428-fa2c-4914-8c0d-54037e3603fa" name="In" connectedTo="53642f20-6369-4abb-ae6c-0155c07c310e"/>
        <port xsi:type="esdl:OutPort" id="29e54d56-0e15-43e6-b4aa-a5a2c18be4eb" name="Out" connectedTo="30ee7997-4b4a-4e48-a946-b61d2a131b68 8711744f-ef71-4f66-9dc4-13d48dc3df41"/>
        <geometry xsi:type="esdl:Point" lat="158047.378" CRS="WGS84" lon="434421.225"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="5.985118211036593" name="lv_cable_trafo14_lvnetwork2_11_main_grid" id="19f3ffc1-514e-4a8b-aec1-01eb43f7551d" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="e858d994-6dbd-4101-bcd7-61d731ae0ccb" name="In" connectedTo="0e1a4065-e066-410e-9f34-153ea4369400"/>
        <port xsi:type="esdl:OutPort" id="53642f20-6369-4abb-ae6c-0155c07c310e" name="Out" connectedTo="5a85a428-fa2c-4914-8c0d-54037e3603fa"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158043.68" CRS="WGS84" lon="434425.931"/>
          <point xsi:type="esdl:Point" lat="158047.378" CRS="WGS84" lon="434421.225"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.39920402518090436" name="lv_cable_trafo14_lvnetwork2_to_home_1_arch3" id="ea40626d-7843-4a4d-9c92-b7e1b86eb508" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="30ee7997-4b4a-4e48-a946-b61d2a131b68" name="In" connectedTo="29e54d56-0e15-43e6-b4aa-a5a2c18be4eb"/>
        <port xsi:type="esdl:OutPort" id="5aafad1b-d195-4a0a-ae96-bf45eb21c06b" name="Out" connectedTo="388d0fc8-0d47-48a1-97a3-c617a576392c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158047.69189999803" CRS="WGS84" lon="434421.4716386931"/>
          <point xsi:type="esdl:Point" lat="158047.378" CRS="WGS84" lon="434421.225"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="1xhome1612" id="5daa0bde-3f92-419b-a4bb-a6124a053fdb">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="4e763edb-862d-4517-b6ed-9cb922df65aa" name="In" connectedTo="a8fd96b0-c4af-4734-9dd3-9466576775b3"/>
          <port xsi:type="esdl:OutPort" id="6e616aa6-10df-4cf4-9ddd-9c9c8bca6fdf" name="Out" connectedTo="7bdbed22-401a-466b-9110-cda91f36ee47"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="880cb727-2920-4bc1-962e-9230ec2d2692" name="In" connectedTo="9c91da9e-d343-48b5-bffe-d301be3b7d65"/>
          <port xsi:type="esdl:OutPort" id="93956550-c0ad-45b5-b1ad-e351ca36aea5" name="Out" connectedTo="e7807d4c-3029-4f7e-bc9b-ca14f088ad0d"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="da9a93e2-f170-4335-86ca-1d66d2e3277d" name="In" connectedTo="095f881d-9216-4d4a-b7f0-4dfd2fb756c0"/>
          <port xsi:type="esdl:OutPort" id="1071d535-6534-46a4-80d8-e124b90c6538" name="Out" connectedTo="4ac05812-b75a-4683-a589-5dd3014d33da"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="ee9fe34c-913e-4b7a-a06a-c48daa424d96" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="7bdbed22-401a-466b-9110-cda91f36ee47" name="In_Ph1" connectedTo="6e616aa6-10df-4cf4-9ddd-9c9c8bca6fdf"/>
          <port xsi:type="esdl:InPort" id="e7807d4c-3029-4f7e-bc9b-ca14f088ad0d" name="In_Ph2" connectedTo="93956550-c0ad-45b5-b1ad-e351ca36aea5"/>
          <port xsi:type="esdl:InPort" id="4ac05812-b75a-4683-a589-5dd3014d33da" name="In_Ph3" connectedTo="1071d535-6534-46a4-80d8-e124b90c6538"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="1xhome1612" id="fa1abfcb-b2a9-4554-9f3d-8185b99f97ad">
          <port xsi:type="esdl:InPort" id="388d0fc8-0d47-48a1-97a3-c617a576392c" name="In" connectedTo="5aafad1b-d195-4a0a-ae96-bf45eb21c06b"/>
          <port xsi:type="esdl:OutPort" id="a8fd96b0-c4af-4734-9dd3-9466576775b3" name="OutPh1" connectedTo="4e763edb-862d-4517-b6ed-9cb922df65aa"/>
          <port xsi:type="esdl:OutPort" id="9c91da9e-d343-48b5-bffe-d301be3b7d65" name="OutPh2" connectedTo="880cb727-2920-4bc1-962e-9230ec2d2692"/>
          <port xsi:type="esdl:OutPort" id="095f881d-9216-4d4a-b7f0-4dfd2fb756c0" name="OutPh3" connectedTo="da9a93e2-f170-4335-86ca-1d66d2e3277d"/>
          <geometry xsi:type="esdl:Point" lat="158047.69189999803" lon="434421.4716386931"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_12" id="3aa9df3a-78fa-4719-9e84-f0b5fb3cee31">
        <port xsi:type="esdl:InPort" id="c4285c76-1a64-4ac0-b46c-88f08ffc0aab" name="In" connectedTo="eb93e5a9-4360-42fc-8c7e-fa28ae3ea421"/>
        <port xsi:type="esdl:OutPort" id="39bb8f3c-d6fe-425d-8444-5ce797124f81" name="Out" connectedTo="8e33956b-aa7b-4c32-bc44-f346d55ef95a"/>
        <geometry xsi:type="esdl:Point" lat="158057.807" CRS="WGS84" lon="434404.935"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="21.39443071043416" name="lv_cable_trafo14_lvnetwork2_12_main_grid" id="02714fa4-4f0c-4cf3-b6e5-ebb34f7f2765" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="8711744f-ef71-4f66-9dc4-13d48dc3df41" name="In" connectedTo="29e54d56-0e15-43e6-b4aa-a5a2c18be4eb"/>
        <port xsi:type="esdl:OutPort" id="eb93e5a9-4360-42fc-8c7e-fa28ae3ea421" name="Out" connectedTo="c4285c76-1a64-4ac0-b46c-88f08ffc0aab"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158047.378" CRS="WGS84" lon="434421.225"/>
          <point xsi:type="esdl:Point" lat="158047.412" CRS="WGS84" lon="434421.181"/>
          <point xsi:type="esdl:Point" lat="158049.591" CRS="WGS84" lon="434418.408"/>
          <point xsi:type="esdl:Point" lat="158059.257" CRS="WGS84" lon="434405.782"/>
          <point xsi:type="esdl:Point" lat="158057.964" CRS="WGS84" lon="434404.74"/>
          <point xsi:type="esdl:Point" lat="158057.807" CRS="WGS84" lon="434404.935"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo14_lvnetwork2_13" id="353cd633-4247-47e9-9367-4b1f1487b42c">
        <port xsi:type="esdl:InPort" id="736c7ef3-40ba-4c9f-9939-6480faed6e56" name="In" connectedTo="9e98a469-b63d-46f6-a101-192084b8cf05"/>
        <port xsi:type="esdl:OutPort" id="96f9dd6d-5fd8-4c3f-b6e1-0cc39e316a60" name="Out"/>
        <geometry xsi:type="esdl:Point" lat="158057.345" CRS="WGS84" lon="434405.451"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.6961415426224825" name="lv_cable_trafo14_lvnetwork2_13_main_grid" id="173fb01d-c6c2-4630-a8f6-53e395f9d9eb" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="8e33956b-aa7b-4c32-bc44-f346d55ef95a" name="In" connectedTo="39bb8f3c-d6fe-425d-8444-5ce797124f81"/>
        <port xsi:type="esdl:OutPort" id="9e98a469-b63d-46f6-a101-192084b8cf05" name="Out" connectedTo="736c7ef3-40ba-4c9f-9939-6480faed6e56"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="158057.807" CRS="WGS84" lon="434404.935"/>
          <point xsi:type="esdl:Point" lat="158057.461" CRS="WGS84" lon="434405.364"/>
          <point xsi:type="esdl:Point" lat="158057.345" CRS="WGS84" lon="434405.451"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo14_lvnetwork2" id="97a36283-f0f2-4643-b3d6-08664fa9b344" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="506a9ff1-d745-4db8-b429-3facf61ae3c6" name="Out" connectedTo="76e8dc6f-28db-495d-a303-a15dbadbf0c8"/>
        <geometry xsi:type="esdl:Point" lat="158127.633" CRS="WGS84" lon="434491.863"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo14_lvnetwork2" id="dbf1373c-fd38-4e03-9b50-b076a216d8a7">
        <port xsi:type="esdl:InPort" id="76e8dc6f-28db-495d-a303-a15dbadbf0c8" name="In" connectedTo="506a9ff1-d745-4db8-b429-3facf61ae3c6"/>
        <port xsi:type="esdl:OutPort" id="9329beb5-740f-470f-818e-c12e367f1c40" name="Out" connectedTo="920f4b68-8c22-4f47-8739-1aaaf2761623"/>
        <geometry xsi:type="esdl:Point" lat="158127.633" CRS="WGS84" lon="434491.863"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer84" id="758d3666-fb19-47a2-8503-6e619d43d26c" commissioningDate="1975-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="920f4b68-8c22-4f47-8739-1aaaf2761623" name="In" connectedTo="9329beb5-740f-470f-818e-c12e367f1c40"/>
        <port xsi:type="esdl:OutPort" id="ebda4eda-176e-49da-9ca6-660881cd64fb" name="Out" connectedTo="c4638b65-6f9b-49b5-b13c-0dbe74a9eee4"/>
        <geometry xsi:type="esdl:Point" lat="158127.633" CRS="WGS84" lon="434491.863"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint86" id="f0afdb8d-3a91-4c26-973b-354807871586">
        <port xsi:type="esdl:InPort" id="c4638b65-6f9b-49b5-b13c-0dbe74a9eee4" name="In" connectedTo="ebda4eda-176e-49da-9ca6-660881cd64fb"/>
        <port xsi:type="esdl:OutPort" id="d638a3a9-19b9-4a95-bc3b-7b6893e1f4a7" name="Out" connectedTo="d112fd6e-5a5a-4a53-991b-fffde280d5bd"/>
        <geometry xsi:type="esdl:Point" lat="158127.633" CRS="WGS84" lon="434491.863"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
