<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="ddaefe9a-9f84-4e48-9883-c9989fb2b9ee" description="Autogenerated based on gis data trafo10_lvnetwork3" name="trafo10_lvnetwork3">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="09cc0890-2574-4d4e-a1be-4e3a78075f6f"/>
  <instance xsi:type="esdl:Instance" id="113e96c2-760f-494b-9f94-e0f344862c88" name="Instance name">
    <area xsi:type="esdl:Area" id="9fb7aee1-d8c0-45ab-91e1-628450cc0d48" name="Area name">
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_2" id="8531be27-4c5b-4c1e-826c-7a801f772e3b">
        <port xsi:type="esdl:InPort" id="174db766-840e-4629-8981-e9b6b98c5a65" name="In" connectedTo="eabcaf2f-7c4b-467a-b4b3-95df57ba3747"/>
        <port xsi:type="esdl:OutPort" id="e28a71e9-8f6e-495d-a958-16d8dba900f9" name="Out" connectedTo="8ab0ba08-30af-4d5f-9ee6-e72a8d28af4c"/>
        <geometry xsi:type="esdl:Point" lat="157556.336" CRS="WGS84" lon="434048.805"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="61.07737563839494" name="lv_cable_trafo10_lvnetwork3_2_main_grid" id="027a51ba-7370-496f-9ed2-43b86610a27d" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="dfeb3880-fe03-4789-89a8-2a512f818c10" name="In" connectedTo="456d2307-ee17-4369-bac3-3ec4112f581d"/>
        <port xsi:type="esdl:OutPort" id="eabcaf2f-7c4b-467a-b4b3-95df57ba3747" name="Out" connectedTo="174db766-840e-4629-8981-e9b6b98c5a65"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157561.78" CRS="WGS84" lon="433996.569"/>
          <point xsi:type="esdl:Point" lat="157558.087" CRS="WGS84" lon="434007.397"/>
          <point xsi:type="esdl:Point" lat="157567.359" CRS="WGS84" lon="434010.55"/>
          <point xsi:type="esdl:Point" lat="157564.282" CRS="WGS84" lon="434019.798"/>
          <point xsi:type="esdl:Point" lat="157563.59" CRS="WGS84" lon="434023.627"/>
          <point xsi:type="esdl:Point" lat="157561.253" CRS="WGS84" lon="434031.33"/>
          <point xsi:type="esdl:Point" lat="157560.75" CRS="WGS84" lon="434033.186"/>
          <point xsi:type="esdl:Point" lat="157560.588" CRS="WGS84" lon="434033.785"/>
          <point xsi:type="esdl:Point" lat="157560.042" CRS="WGS84" lon="434035.8"/>
          <point xsi:type="esdl:Point" lat="157559.58" CRS="WGS84" lon="434037.503"/>
          <point xsi:type="esdl:Point" lat="157559.423" CRS="WGS84" lon="434038.084"/>
          <point xsi:type="esdl:Point" lat="157557.626" CRS="WGS84" lon="434044.713"/>
          <point xsi:type="esdl:Point" lat="157556.336" CRS="WGS84" lon="434048.805"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_3" id="2194dcee-3e3b-44dd-8623-8a2d06b963fe">
        <port xsi:type="esdl:InPort" id="de2fc3d2-72e3-4839-bcbb-9114a19caecf" name="In" connectedTo="e651d1c3-b003-4e50-904c-3b24740700d1"/>
        <port xsi:type="esdl:OutPort" id="4bd27b81-953b-43d3-85a6-4bfd2441c8e4" name="Out" connectedTo="948d301d-14df-48be-bc79-45703cca16dd da4c43f2-1991-4b3a-a9c1-308055bacd6e"/>
        <geometry xsi:type="esdl:Point" lat="157570.85789451736" CRS="WGS84" lon="434054.7417834998"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="15.842531764899178" name="lv_cable_trafo10_lvnetwork3_3_main_grid" id="d8d610b0-62f0-48de-8fbb-8375298162e0" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="8ab0ba08-30af-4d5f-9ee6-e72a8d28af4c" name="In" connectedTo="e28a71e9-8f6e-495d-a958-16d8dba900f9"/>
        <port xsi:type="esdl:OutPort" id="e651d1c3-b003-4e50-904c-3b24740700d1" name="Out" connectedTo="de2fc3d2-72e3-4839-bcbb-9114a19caecf"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157556.336" CRS="WGS84" lon="434048.805"/>
          <point xsi:type="esdl:Point" lat="157556.44" CRS="WGS84" lon="434048.838"/>
          <point xsi:type="esdl:Point" lat="157556.395" CRS="WGS84" lon="434048.989"/>
          <point xsi:type="esdl:Point" lat="157564.823" CRS="WGS84" lon="434052.588"/>
          <point xsi:type="esdl:Point" lat="157566.28" CRS="WGS84" lon="434053.21"/>
          <point xsi:type="esdl:Point" lat="157567.054" CRS="WGS84" lon="434053.469"/>
          <point xsi:type="esdl:Point" lat="157570.85789451736" CRS="WGS84" lon="434054.7417834998"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.2577828364304986" name="lv_cable_trafo10_lvnetwork3_to_home_0_arch3" id="04bba85b-0c53-4711-afd1-33b9b256cf17" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="948d301d-14df-48be-bc79-45703cca16dd" name="In" connectedTo="4bd27b81-953b-43d3-85a6-4bfd2441c8e4"/>
        <port xsi:type="esdl:OutPort" id="8a696ec1-71b3-4900-971f-c357263e23bd" name="Out" connectedTo="646b06f2-06fe-4e4c-9abf-84ecc2050680"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157571.257" CRS="WGS84" lon="434053.549"/>
          <point xsi:type="esdl:Point" lat="157570.85789451736" CRS="WGS84" lon="434054.7417834998"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="12xhome888" id="6b23e883-d6f4-45d3-bf67-f65354c73789">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="9fe0d91e-dac0-4be5-aaf0-7505cdd482f3" name="In" connectedTo="342cb5a1-bc04-4e4d-9c7a-ab0daa1b871c"/>
          <port xsi:type="esdl:OutPort" id="b49e0f62-9478-48d5-a970-44041c0f37ab" name="Out" connectedTo="fd51c596-f3b8-45e7-a6e7-8bb44e331032"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="6b3a8a27-6759-4122-8c23-d326f2b09634" name="In" connectedTo="8c3b0ac4-a5bc-4cd9-96bb-15e5639e2211"/>
          <port xsi:type="esdl:OutPort" id="3cc8f2b8-bc11-429e-af44-c3127a2c76db" name="Out" connectedTo="6431aca8-9931-4921-b23f-b32543eb58d4"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="575013ed-3e28-4962-af3b-b690a4eae192" name="In" connectedTo="f3f00869-385a-4bac-8940-89c636ca5a73"/>
          <port xsi:type="esdl:OutPort" id="6f2b10c5-7104-439d-97f6-d5465e421905" name="Out" connectedTo="76c160e3-0ecc-4977-b3bb-90b5397675c0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="563e58ec-13cb-48ba-b227-bc09bec7d238" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="fd51c596-f3b8-45e7-a6e7-8bb44e331032" name="In_Ph1" connectedTo="b49e0f62-9478-48d5-a970-44041c0f37ab"/>
          <port xsi:type="esdl:InPort" id="6431aca8-9931-4921-b23f-b32543eb58d4" name="In_Ph2" connectedTo="3cc8f2b8-bc11-429e-af44-c3127a2c76db"/>
          <port xsi:type="esdl:InPort" id="76c160e3-0ecc-4977-b3bb-90b5397675c0" name="In_Ph3" connectedTo="6f2b10c5-7104-439d-97f6-d5465e421905"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="12xhome888" id="5874216c-bd1a-4f11-ad64-5d9122cff185">
          <port xsi:type="esdl:InPort" id="646b06f2-06fe-4e4c-9abf-84ecc2050680" name="In" connectedTo="8a696ec1-71b3-4900-971f-c357263e23bd"/>
          <port xsi:type="esdl:OutPort" id="342cb5a1-bc04-4e4d-9c7a-ab0daa1b871c" name="OutPh1" connectedTo="9fe0d91e-dac0-4be5-aaf0-7505cdd482f3"/>
          <port xsi:type="esdl:OutPort" id="8c3b0ac4-a5bc-4cd9-96bb-15e5639e2211" name="OutPh2" connectedTo="6b3a8a27-6759-4122-8c23-d326f2b09634"/>
          <port xsi:type="esdl:OutPort" id="f3f00869-385a-4bac-8940-89c636ca5a73" name="OutPh3" connectedTo="575013ed-3e28-4962-af3b-b690a4eae192"/>
          <geometry xsi:type="esdl:Point" lat="157571.257" lon="434053.549"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_4" id="8c83bc10-8b44-44bf-aa06-da369b0660a3">
        <port xsi:type="esdl:InPort" id="d8c2e454-a887-4af3-8950-6851887188fd" name="In" connectedTo="234b0f81-62c3-42af-b49d-f224c99ca047"/>
        <port xsi:type="esdl:OutPort" id="0ee6d315-41d5-463e-b868-0d831cd71ae3" name="Out" connectedTo="dc59c253-8652-4e05-81d4-8d2f07f1e43c"/>
        <geometry xsi:type="esdl:Point" lat="157583.579" CRS="WGS84" lon="434059.173"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="13.472605136733483" name="lv_cable_trafo10_lvnetwork3_4_main_grid" id="c2502026-ec57-4648-8e83-7abfc1051e18" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="da4c43f2-1991-4b3a-a9c1-308055bacd6e" name="In" connectedTo="4bd27b81-953b-43d3-85a6-4bfd2441c8e4"/>
        <port xsi:type="esdl:OutPort" id="234b0f81-62c3-42af-b49d-f224c99ca047" name="Out" connectedTo="d8c2e454-a887-4af3-8950-6851887188fd"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157570.85789451736" CRS="WGS84" lon="434054.7417834998"/>
          <point xsi:type="esdl:Point" lat="157573.14" CRS="WGS84" lon="434055.506"/>
          <point xsi:type="esdl:Point" lat="157574.491" CRS="WGS84" lon="434055.958"/>
          <point xsi:type="esdl:Point" lat="157579.078" CRS="WGS84" lon="434057.493"/>
          <point xsi:type="esdl:Point" lat="157582.809" CRS="WGS84" lon="434058.886"/>
          <point xsi:type="esdl:Point" lat="157583.579" CRS="WGS84" lon="434059.173"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_5" id="f05086b9-3a3e-405d-99cf-c1275a8f3775">
        <port xsi:type="esdl:InPort" id="48eb6728-1de1-4f4e-a8f7-9280ddce1c7c" name="In" connectedTo="080cd8eb-9327-4d45-97c8-2005aec9b7da"/>
        <port xsi:type="esdl:OutPort" id="49fc02f0-7ca9-417e-a09e-2ccd44f26ab7" name="Out" connectedTo="f5dd96a1-93c6-4338-aeb0-5c96dcc2fc2a"/>
        <geometry xsi:type="esdl:Point" lat="157556.176" CRS="WGS84" lon="434049.31"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.5297405025159212" name="lv_cable_trafo10_lvnetwork3_5_main_grid" id="b5b122c5-7ed5-428b-a707-b3fb6fa2b620" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="dc59c253-8652-4e05-81d4-8d2f07f1e43c" name="In" connectedTo="0ee6d315-41d5-463e-b868-0d831cd71ae3"/>
        <port xsi:type="esdl:OutPort" id="080cd8eb-9327-4d45-97c8-2005aec9b7da" name="Out" connectedTo="48eb6728-1de1-4f4e-a8f7-9280ddce1c7c"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157556.336" CRS="WGS84" lon="434048.805"/>
          <point xsi:type="esdl:Point" lat="157556.176" CRS="WGS84" lon="434049.31"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_6" id="5ce4b9d0-c731-4c67-b1bd-e10593597e90">
        <port xsi:type="esdl:InPort" id="a1c4ec71-b65d-4c16-9607-e6140b449692" name="In" connectedTo="7a60a9cc-6b2a-471f-a74b-7e485c300075"/>
        <port xsi:type="esdl:OutPort" id="d0de0daf-1efa-40ab-baef-4820e6a7e5ed" name="Out" connectedTo="a188a8a2-ff0b-43a6-ba4d-74ea1e2afbc0 bdcd7883-6fb7-4602-a8b2-35e34eb8e16e"/>
        <geometry xsi:type="esdl:Point" lat="157537.834" CRS="WGS84" lon="434058.364"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="29.92240225763293" name="lv_cable_trafo10_lvnetwork3_6_main_grid" id="d3947971-3bf2-401f-a5cf-c51972305ee5" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f5dd96a1-93c6-4338-aeb0-5c96dcc2fc2a" name="In" connectedTo="49fc02f0-7ca9-417e-a09e-2ccd44f26ab7"/>
        <port xsi:type="esdl:OutPort" id="7a60a9cc-6b2a-471f-a74b-7e485c300075" name="Out" connectedTo="a1c4ec71-b65d-4c16-9607-e6140b449692"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157556.176" CRS="WGS84" lon="434049.31"/>
          <point xsi:type="esdl:Point" lat="157555.959" CRS="WGS84" lon="434049.242"/>
          <point xsi:type="esdl:Point" lat="157556.04" CRS="WGS84" lon="434048.984"/>
          <point xsi:type="esdl:Point" lat="157550.739" CRS="WGS84" lon="434045.932"/>
          <point xsi:type="esdl:Point" lat="157544.844" CRS="WGS84" lon="434043.427"/>
          <point xsi:type="esdl:Point" lat="157544.681967854" CRS="WGS84" lon="434043.393330022"/>
          <point xsi:type="esdl:Point" lat="157544.516461678" CRS="WGS84" lon="434043.390781543"/>
          <point xsi:type="esdl:Point" lat="157544.353410999" CRS="WGS84" lon="434043.419445868"/>
          <point xsi:type="esdl:Point" lat="157544.198657367" CRS="WGS84" lon="434043.47829605"/>
          <point xsi:type="esdl:Point" lat="157544.057745083" CRS="WGS84" lon="434043.565223687"/>
          <point xsi:type="esdl:Point" lat="157543.935722554" CRS="WGS84" lon="434043.677114457"/>
          <point xsi:type="esdl:Point" lat="157543.836961434" CRS="WGS84" lon="434043.809959693"/>
          <point xsi:type="esdl:Point" lat="157543.765" CRS="WGS84" lon="434043.959"/>
          <point xsi:type="esdl:Point" lat="157543.689" CRS="WGS84" lon="434044.144"/>
          <point xsi:type="esdl:Point" lat="157543.338" CRS="WGS84" lon="434045.006"/>
          <point xsi:type="esdl:Point" lat="157542.635" CRS="WGS84" lon="434046.734"/>
          <point xsi:type="esdl:Point" lat="157542.51" CRS="WGS84" lon="434047.041"/>
          <point xsi:type="esdl:Point" lat="157542.214" CRS="WGS84" lon="434047.769"/>
          <point xsi:type="esdl:Point" lat="157541.164" CRS="WGS84" lon="434050.35"/>
          <point xsi:type="esdl:Point" lat="157540.857" CRS="WGS84" lon="434051.089"/>
          <point xsi:type="esdl:Point" lat="157540.503" CRS="WGS84" lon="434051.942"/>
          <point xsi:type="esdl:Point" lat="157539.305" CRS="WGS84" lon="434054.825"/>
          <point xsi:type="esdl:Point" lat="157538.077" CRS="WGS84" lon="434057.78"/>
          <point xsi:type="esdl:Point" lat="157537.834" CRS="WGS84" lon="434058.364"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.2377697685768936" name="lv_cable_trafo10_lvnetwork3_to_home_1_arch3" id="e671e80a-64d4-4085-800d-32b360409b1b" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="a188a8a2-ff0b-43a6-ba4d-74ea1e2afbc0" name="In" connectedTo="d0de0daf-1efa-40ab-baef-4820e6a7e5ed"/>
        <port xsi:type="esdl:OutPort" id="662704d9-f536-43ea-a673-7818a8843f78" name="Out" connectedTo="f2baae68-2edc-4754-b26a-0aef86d1b354"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157536.691" CRS="WGS84" lon="434057.889"/>
          <point xsi:type="esdl:Point" lat="157537.834" CRS="WGS84" lon="434058.364"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="12xhome889" id="b4d17b7f-4589-4470-97d3-dfbc1b61d603">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="116e276c-475e-417b-bb11-bc4de98c08a1" name="In" connectedTo="ef6ccf9d-6d6d-4c58-8395-1500a0331262"/>
          <port xsi:type="esdl:OutPort" id="e6f39d55-5582-4672-97e0-c2d6233605a8" name="Out" connectedTo="abeb7ce2-f0cd-4fe9-ab25-64535212ed0a"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="85162815-f8fc-4d4d-a3b5-6587999f9856" name="In" connectedTo="4890c1b4-38d0-4de3-a906-15cc39928211"/>
          <port xsi:type="esdl:OutPort" id="67dc0b1d-b6d7-4757-bf92-0613e5956875" name="Out" connectedTo="ddbed607-80ca-4f94-8f5b-cf2611307a1b"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="bca53116-974b-4b5c-8508-8be09a915472" name="In" connectedTo="2989918a-8dec-41ff-8c9e-9d81814bbf10"/>
          <port xsi:type="esdl:OutPort" id="70058c9c-89d3-4ec4-919f-6b33a8c81891" name="Out" connectedTo="3509d638-2fee-43da-aba9-dc2dcc1b0b6c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="32a11504-eb7c-43b3-a0c3-56ddfe111715" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="abeb7ce2-f0cd-4fe9-ab25-64535212ed0a" name="In_Ph1" connectedTo="e6f39d55-5582-4672-97e0-c2d6233605a8"/>
          <port xsi:type="esdl:InPort" id="ddbed607-80ca-4f94-8f5b-cf2611307a1b" name="In_Ph2" connectedTo="67dc0b1d-b6d7-4757-bf92-0613e5956875"/>
          <port xsi:type="esdl:InPort" id="3509d638-2fee-43da-aba9-dc2dcc1b0b6c" name="In_Ph3" connectedTo="70058c9c-89d3-4ec4-919f-6b33a8c81891"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="12xhome889" id="0e7057f8-8edc-4ffe-b6c4-c19282a788cb">
          <port xsi:type="esdl:InPort" id="f2baae68-2edc-4754-b26a-0aef86d1b354" name="In" connectedTo="662704d9-f536-43ea-a673-7818a8843f78"/>
          <port xsi:type="esdl:OutPort" id="ef6ccf9d-6d6d-4c58-8395-1500a0331262" name="OutPh1" connectedTo="116e276c-475e-417b-bb11-bc4de98c08a1"/>
          <port xsi:type="esdl:OutPort" id="4890c1b4-38d0-4de3-a906-15cc39928211" name="OutPh2" connectedTo="85162815-f8fc-4d4d-a3b5-6587999f9856"/>
          <port xsi:type="esdl:OutPort" id="2989918a-8dec-41ff-8c9e-9d81814bbf10" name="OutPh3" connectedTo="bca53116-974b-4b5c-8508-8be09a915472"/>
          <geometry xsi:type="esdl:Point" lat="157536.691" lon="434057.889"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_7" id="7d695db2-5ada-4370-8ccc-e4fd65259782">
        <port xsi:type="esdl:InPort" id="db70e31d-225d-445d-bd5f-bbe6955626f9" name="In" connectedTo="38cdbd92-b72c-48f8-8268-d33bf293c835"/>
        <port xsi:type="esdl:OutPort" id="e0f6e475-a01b-476d-b1d6-e6800f07a5d9" name="Out" connectedTo="268ccb41-e1ef-4bd2-8f56-1d18d8d54261"/>
        <geometry xsi:type="esdl:Point" lat="157533.743" CRS="WGS84" lon="434068.594"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="11.018433946134666" name="lv_cable_trafo10_lvnetwork3_7_main_grid" id="c9497a91-18a8-4cd1-a642-628a4d6d08ad" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="bdcd7883-6fb7-4602-a8b2-35e34eb8e16e" name="In" connectedTo="d0de0daf-1efa-40ab-baef-4820e6a7e5ed"/>
        <port xsi:type="esdl:OutPort" id="38cdbd92-b72c-48f8-8268-d33bf293c835" name="Out" connectedTo="db70e31d-225d-445d-bd5f-bbe6955626f9"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157537.834" CRS="WGS84" lon="434058.364"/>
          <point xsi:type="esdl:Point" lat="157535.987" CRS="WGS84" lon="434062.81"/>
          <point xsi:type="esdl:Point" lat="157535.268" CRS="WGS84" lon="434064.663"/>
          <point xsi:type="esdl:Point" lat="157534.332" CRS="WGS84" lon="434067.075"/>
          <point xsi:type="esdl:Point" lat="157534.187" CRS="WGS84" lon="434067.448"/>
          <point xsi:type="esdl:Point" lat="157533.743" CRS="WGS84" lon="434068.594"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_8" id="09c15b22-7b93-442d-9f68-5e525d6ab7d7">
        <port xsi:type="esdl:InPort" id="c52ffbb1-fba9-48d5-b37e-58209435b8ff" name="In" connectedTo="8471b7aa-e839-4d1e-b967-221bde7fa22b"/>
        <port xsi:type="esdl:OutPort" id="ed510276-fe43-4b32-b937-fcb2c3682781" name="Out" connectedTo="f53c5d55-3b0e-4441-aa89-e4287bc68ae0"/>
        <geometry xsi:type="esdl:Point" lat="157569.401" CRS="WGS84" lon="434089.542"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="64.37696150634565" name="lv_cable_trafo10_lvnetwork3_8_main_grid" id="3141a8d2-5c81-4a08-9880-78d1e3a601fe" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="268ccb41-e1ef-4bd2-8f56-1d18d8d54261" name="In" connectedTo="e0f6e475-a01b-476d-b1d6-e6800f07a5d9"/>
        <port xsi:type="esdl:OutPort" id="8471b7aa-e839-4d1e-b967-221bde7fa22b" name="Out" connectedTo="c52ffbb1-fba9-48d5-b37e-58209435b8ff"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157556.176" CRS="WGS84" lon="434049.31"/>
          <point xsi:type="esdl:Point" lat="157555.734" CRS="WGS84" lon="434050.714"/>
          <point xsi:type="esdl:Point" lat="157554.028" CRS="WGS84" lon="434056.907"/>
          <point xsi:type="esdl:Point" lat="157550.497" CRS="WGS84" lon="434068.765"/>
          <point xsi:type="esdl:Point" lat="157547.409" CRS="WGS84" lon="434078.718"/>
          <point xsi:type="esdl:Point" lat="157545.58" CRS="WGS84" lon="434088.232"/>
          <point xsi:type="esdl:Point" lat="157554.827" CRS="WGS84" lon="434088.286"/>
          <point xsi:type="esdl:Point" lat="157564.321" CRS="WGS84" lon="434088.186"/>
          <point xsi:type="esdl:Point" lat="157569.401" CRS="WGS84" lon="434089.542"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_9" id="0bf92557-086b-47ea-8e38-e2cb14213b10">
        <port xsi:type="esdl:InPort" id="4780cb56-2a3a-48f8-87de-3ca789dccc07" name="In" connectedTo="4323fde4-7973-4cac-b9ee-e9ba761402c6"/>
        <port xsi:type="esdl:OutPort" id="02e72cd4-dc6c-4990-895e-a0ec4fe24c61" name="Out" connectedTo="6633652a-4f2d-4bf0-b165-ca8a3dea9df6"/>
        <geometry xsi:type="esdl:Point" lat="157572.188" CRS="WGS84" lon="434090.387"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="2.9122832966339063" name="lv_cable_trafo10_lvnetwork3_9_main_grid" id="908ea713-00e1-42d5-8532-83b60d4fb652" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="f53c5d55-3b0e-4441-aa89-e4287bc68ae0" name="In" connectedTo="ed510276-fe43-4b32-b937-fcb2c3682781"/>
        <port xsi:type="esdl:OutPort" id="4323fde4-7973-4cac-b9ee-e9ba761402c6" name="Out" connectedTo="4780cb56-2a3a-48f8-87de-3ca789dccc07"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157569.401" CRS="WGS84" lon="434089.542"/>
          <point xsi:type="esdl:Point" lat="157572.188" CRS="WGS84" lon="434090.387"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_10" id="f9b0d7d4-3938-4dac-97e9-001e0adb10f8">
        <port xsi:type="esdl:InPort" id="6bfd3ea1-3c33-435e-83cb-a4258554f72e" name="In" connectedTo="c325a813-da11-44f1-a710-e42639e7b8f3"/>
        <port xsi:type="esdl:OutPort" id="bfe4dad3-3e60-4459-9470-cf8c74b14ff9" name="Out" connectedTo="6613a127-89a2-4fe3-b4e3-ed2d5c5789b4 0462f32f-2a4d-4ad4-9e05-0534d934c262"/>
        <geometry xsi:type="esdl:Point" lat="157605.26399943887" CRS="WGS84" lon="434068.7950862503"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="55.798152201510035" name="lv_cable_trafo10_lvnetwork3_10_main_grid" id="282d10e3-f6fe-4e92-aecf-839ca4af6aeb" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="6633652a-4f2d-4bf0-b165-ca8a3dea9df6" name="In" connectedTo="02e72cd4-dc6c-4990-895e-a0ec4fe24c61"/>
        <port xsi:type="esdl:OutPort" id="c325a813-da11-44f1-a710-e42639e7b8f3" name="Out" connectedTo="6bfd3ea1-3c33-435e-83cb-a4258554f72e"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157569.401" CRS="WGS84" lon="434089.542"/>
          <point xsi:type="esdl:Point" lat="157571.253" CRS="WGS84" lon="434089.357"/>
          <point xsi:type="esdl:Point" lat="157571.553939844" CRS="WGS84" lon="434089.234886032"/>
          <point xsi:type="esdl:Point" lat="157571.838488396" CRS="WGS84" lon="434089.078335016"/>
          <point xsi:type="esdl:Point" lat="157572.102722735" CRS="WGS84" lon="434088.88950524"/>
          <point xsi:type="esdl:Point" lat="157572.343" CRS="WGS84" lon="434088.671"/>
          <point xsi:type="esdl:Point" lat="157573.14" CRS="WGS84" lon="434087.249"/>
          <point xsi:type="esdl:Point" lat="157573.228876376" CRS="WGS84" lon="434087.148612579"/>
          <point xsi:type="esdl:Point" lat="157573.334385511" CRS="WGS84" lon="434087.065951066"/>
          <point xsi:type="esdl:Point" lat="157573.453060054" CRS="WGS84" lon="434087.003731971"/>
          <point xsi:type="esdl:Point" lat="157573.581" CRS="WGS84" lon="434086.964"/>
          <point xsi:type="esdl:Point" lat="157578.24" CRS="WGS84" lon="434087.082"/>
          <point xsi:type="esdl:Point" lat="157579.39" CRS="WGS84" lon="434087.111"/>
          <point xsi:type="esdl:Point" lat="157588.32" CRS="WGS84" lon="434087.337"/>
          <point xsi:type="esdl:Point" lat="157596.339" CRS="WGS84" lon="434087.539"/>
          <point xsi:type="esdl:Point" lat="157597.424" CRS="WGS84" lon="434087.566"/>
          <point xsi:type="esdl:Point" lat="157602.628" CRS="WGS84" lon="434087.791"/>
          <point xsi:type="esdl:Point" lat="157603.84" CRS="WGS84" lon="434087.844"/>
          <point xsi:type="esdl:Point" lat="157604.939" CRS="WGS84" lon="434087.891"/>
          <point xsi:type="esdl:Point" lat="157605.106" CRS="WGS84" lon="434079.756"/>
          <point xsi:type="esdl:Point" lat="157605.19" CRS="WGS84" lon="434075.662"/>
          <point xsi:type="esdl:Point" lat="157605.233" CRS="WGS84" lon="434073.56"/>
          <point xsi:type="esdl:Point" lat="157605.26399943887" CRS="WGS84" lon="434068.7950862503"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="0.9090197976837548" name="lv_cable_trafo10_lvnetwork3_to_home_3_arch3" id="4fd3a3d9-ca62-4851-8fc4-79fab31f1081" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="6613a127-89a2-4fe3-b4e3-ed2d5c5789b4" name="In" connectedTo="bfe4dad3-3e60-4459-9470-cf8c74b14ff9"/>
        <port xsi:type="esdl:OutPort" id="bec68d95-8df0-4898-a591-a4b52a315437" name="Out" connectedTo="30f4c25a-ef23-4291-b2a2-f1667791c9d4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157606.173" CRS="WGS84" lon="434068.801"/>
          <point xsi:type="esdl:Point" lat="157605.26399943887" CRS="WGS84" lon="434068.7950862503"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="12xhome891" id="78ddf528-47b0-4456-974b-6d66757a0b82">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="b3660d5d-b7e4-46e8-a17d-9d366cfd2351" name="In" connectedTo="06142952-59ab-45a2-bb6f-9ff2b3d4967f"/>
          <port xsi:type="esdl:OutPort" id="ff0d1d88-8317-45b6-82e2-6a2465d47f8e" name="Out" connectedTo="28744a76-6f07-4c7a-a9cd-f559ad4a02be"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="a8eec252-aaed-433c-a071-e00e4726b282" name="In" connectedTo="24f0d2c7-bb4f-4996-a112-b314704addf3"/>
          <port xsi:type="esdl:OutPort" id="6e058dba-9f8a-4a54-a023-5d3df1ecc05c" name="Out" connectedTo="9ff3354e-4823-42e8-895c-3f76bae47d12"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="5dd4c160-31e0-43a9-9982-a500e150c2d8" name="In" connectedTo="dd3f23ce-4a74-4bf1-ade5-3ca7838b90af"/>
          <port xsi:type="esdl:OutPort" id="8fbb297d-b5a6-4d8a-9038-50c1d743eefe" name="Out" connectedTo="d1bf6ace-e4e5-4082-863e-b544ed54256e"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="89470d24-23c6-4164-b27c-0440ba2c5615" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="28744a76-6f07-4c7a-a9cd-f559ad4a02be" name="In_Ph1" connectedTo="ff0d1d88-8317-45b6-82e2-6a2465d47f8e"/>
          <port xsi:type="esdl:InPort" id="9ff3354e-4823-42e8-895c-3f76bae47d12" name="In_Ph2" connectedTo="6e058dba-9f8a-4a54-a023-5d3df1ecc05c"/>
          <port xsi:type="esdl:InPort" id="d1bf6ace-e4e5-4082-863e-b544ed54256e" name="In_Ph3" connectedTo="8fbb297d-b5a6-4d8a-9038-50c1d743eefe"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="12xhome891" id="2b790a9e-f121-46fc-a306-1f3f41c41f0d">
          <port xsi:type="esdl:InPort" id="30f4c25a-ef23-4291-b2a2-f1667791c9d4" name="In" connectedTo="bec68d95-8df0-4898-a591-a4b52a315437"/>
          <port xsi:type="esdl:OutPort" id="06142952-59ab-45a2-bb6f-9ff2b3d4967f" name="OutPh1" connectedTo="b3660d5d-b7e4-46e8-a17d-9d366cfd2351"/>
          <port xsi:type="esdl:OutPort" id="24f0d2c7-bb4f-4996-a112-b314704addf3" name="OutPh2" connectedTo="a8eec252-aaed-433c-a071-e00e4726b282"/>
          <port xsi:type="esdl:OutPort" id="dd3f23ce-4a74-4bf1-ade5-3ca7838b90af" name="OutPh3" connectedTo="5dd4c160-31e0-43a9-9982-a500e150c2d8"/>
          <geometry xsi:type="esdl:Point" lat="157606.173" lon="434068.801"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_11" id="91eee66a-0e07-4529-b81e-6b1c36b1c1c1">
        <port xsi:type="esdl:InPort" id="27ad7866-4683-4ab9-8fc7-252c988838d1" name="In" connectedTo="57d126c8-5cd0-4e6a-b12e-b9a1cd617354"/>
        <port xsi:type="esdl:OutPort" id="c275136c-6e3e-4fff-bc72-bcc45e11ee20" name="Out" connectedTo="a17089b4-b634-4b5d-8451-7b16cff33226"/>
        <geometry xsi:type="esdl:Point" lat="157605.323" CRS="WGS84" lon="434059.52"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="9.275275647577597" name="lv_cable_trafo10_lvnetwork3_11_main_grid" id="aecedc51-8479-4d89-b8c9-ad16131b411c" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="0462f32f-2a4d-4ad4-9e05-0534d934c262" name="In" connectedTo="bfe4dad3-3e60-4459-9470-cf8c74b14ff9"/>
        <port xsi:type="esdl:OutPort" id="57d126c8-5cd0-4e6a-b12e-b9a1cd617354" name="Out" connectedTo="27ad7866-4683-4ab9-8fc7-252c988838d1"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157605.26399943887" CRS="WGS84" lon="434068.7950862503"/>
          <point xsi:type="esdl:Point" lat="157605.269" CRS="WGS84" lon="434067.953"/>
          <point xsi:type="esdl:Point" lat="157605.282" CRS="WGS84" lon="434065.953"/>
          <point xsi:type="esdl:Point" lat="157605.288" CRS="WGS84" lon="434064.962"/>
          <point xsi:type="esdl:Point" lat="157605.321" CRS="WGS84" lon="434059.964"/>
          <point xsi:type="esdl:Point" lat="157605.323" CRS="WGS84" lon="434059.579"/>
          <point xsi:type="esdl:Point" lat="157605.323" CRS="WGS84" lon="434059.52"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Joint" name="lv_node_trafo10_lvnetwork3_12" id="6ce055b2-6738-4547-80cf-c7d001a20947">
        <port xsi:type="esdl:InPort" id="07a6fad2-0969-4be7-8ee9-990de901f1b2" name="In" connectedTo="21e0a122-57d0-426e-ba64-0a0ff95988f5"/>
        <port xsi:type="esdl:OutPort" id="aa653b43-41bd-4b0f-8dd2-9fcfaefa9ce1" name="Out" connectedTo="f2b1cf76-86fb-4b21-87e0-d11ebbea3923"/>
        <geometry xsi:type="esdl:Point" lat="157600.022" CRS="WGS84" lon="434145.783"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="81.68929186902987" name="lv_cable_trafo10_lvnetwork3_12_main_grid" id="9d77fdc1-910c-4e1c-995d-e22b01c8f99b" assetType="lv_line">
        <port xsi:type="esdl:InPort" id="a17089b4-b634-4b5d-8451-7b16cff33226" name="In" connectedTo="c275136c-6e3e-4fff-bc72-bcc45e11ee20"/>
        <port xsi:type="esdl:OutPort" id="21e0a122-57d0-426e-ba64-0a0ff95988f5" name="Out" connectedTo="07a6fad2-0969-4be7-8ee9-990de901f1b2"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157572.188" CRS="WGS84" lon="434090.387"/>
          <point xsi:type="esdl:Point" lat="157574.023" CRS="WGS84" lon="434091.155"/>
          <point xsi:type="esdl:Point" lat="157574.029" CRS="WGS84" lon="434092.515"/>
          <point xsi:type="esdl:Point" lat="157574.064" CRS="WGS84" lon="434100.126"/>
          <point xsi:type="esdl:Point" lat="157574.097" CRS="WGS84" lon="434107.338"/>
          <point xsi:type="esdl:Point" lat="157574.122" CRS="WGS84" lon="434109.839"/>
          <point xsi:type="esdl:Point" lat="157583.908" CRS="WGS84" lon="434109.989"/>
          <point xsi:type="esdl:Point" lat="157585.102" CRS="WGS84" lon="434110.007"/>
          <point xsi:type="esdl:Point" lat="157588.907" CRS="WGS84" lon="434110.065"/>
          <point xsi:type="esdl:Point" lat="157594.891" CRS="WGS84" lon="434110.156"/>
          <point xsi:type="esdl:Point" lat="157599.577" CRS="WGS84" lon="434110.228"/>
          <point xsi:type="esdl:Point" lat="157599.578" CRS="WGS84" lon="434110.293"/>
          <point xsi:type="esdl:Point" lat="157599.59" CRS="WGS84" lon="434111.207"/>
          <point xsi:type="esdl:Point" lat="157599.614" CRS="WGS84" lon="434113.142"/>
          <point xsi:type="esdl:Point" lat="157599.627" CRS="WGS84" lon="434114.191"/>
          <point xsi:type="esdl:Point" lat="157599.643" CRS="WGS84" lon="434115.455"/>
          <point xsi:type="esdl:Point" lat="157599.663" CRS="WGS84" lon="434117.113"/>
          <point xsi:type="esdl:Point" lat="157599.714" CRS="WGS84" lon="434121.147"/>
          <point xsi:type="esdl:Point" lat="157599.776" CRS="WGS84" lon="434126.092"/>
          <point xsi:type="esdl:Point" lat="157599.777" CRS="WGS84" lon="434126.155"/>
          <point xsi:type="esdl:Point" lat="157599.839" CRS="WGS84" lon="434131.125"/>
          <point xsi:type="esdl:Point" lat="157599.876" CRS="WGS84" lon="434134.085"/>
          <point xsi:type="esdl:Point" lat="157599.889" CRS="WGS84" lon="434135.146"/>
          <point xsi:type="esdl:Point" lat="157599.914" CRS="WGS84" lon="434137.182"/>
          <point xsi:type="esdl:Point" lat="157599.938" CRS="WGS84" lon="434139.105"/>
          <point xsi:type="esdl:Point" lat="157599.939" CRS="WGS84" lon="434139.155"/>
          <point xsi:type="esdl:Point" lat="157599.988" CRS="WGS84" lon="434143.101"/>
          <point xsi:type="esdl:Point" lat="157599.988" CRS="WGS84" lon="434143.133"/>
          <point xsi:type="esdl:Point" lat="157599.989" CRS="WGS84" lon="434143.176"/>
          <point xsi:type="esdl:Point" lat="157600.022" CRS="WGS84" lon="434145.783"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" length="1.3014301185707322" name="lv_cable_trafo10_lvnetwork3_to_home_2_arch3" id="4942c8eb-21ee-4bae-a945-d72348530230" assetType="lv_line_to_home">
        <port xsi:type="esdl:InPort" id="f2b1cf76-86fb-4b21-87e0-d11ebbea3923" name="In" connectedTo="aa653b43-41bd-4b0f-8dd2-9fcfaefa9ce1"/>
        <port xsi:type="esdl:OutPort" id="37c277ba-a90f-4a7e-ae75-01071ec5d818" name="Out" connectedTo="4e38b881-4bb4-4dc2-b932-b05d49814c9b"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" lat="157601.3232726871" CRS="WGS84" lon="434145.8032422169"/>
          <point xsi:type="esdl:Point" lat="157600.022" CRS="WGS84" lon="434145.783"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="30xhome890" id="9db96291-0e49-4433-8522-47561db0e653">
        <asset xsi:type="esdl:ElectricityNetwork" name="ph1">
          <port xsi:type="esdl:InPort" id="749f1df5-290e-4461-ba90-3c040cb02638" name="In" connectedTo="9bf3271f-a5ac-4ffc-b70f-e324e9e07af1"/>
          <port xsi:type="esdl:OutPort" id="1cccdaed-733d-490f-ac07-4bf942f05bc4" name="Out" connectedTo="30487fd4-1a9a-40f9-aca7-1bbb67f0c095"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph2">
          <port xsi:type="esdl:InPort" id="bfcbc6fb-605f-473b-a511-efdcbd0856fe" name="In" connectedTo="68c283aa-a9ca-42cb-a9e0-eadfc1f62f17"/>
          <port xsi:type="esdl:OutPort" id="130fa1ef-46b1-4cd4-abe2-705da3af4348" name="Out" connectedTo="9536c28f-f6b5-4427-a9cc-2f5a2dd03a80"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ph3">
          <port xsi:type="esdl:InPort" id="34a9d639-cac4-4766-8241-19037785fc7a" name="In" connectedTo="f37f33ee-98f5-4dec-9b1a-3d9a956ef9db"/>
          <port xsi:type="esdl:OutPort" id="9d97e52b-b622-4c85-aea4-4d1e5b5e0d35" name="Out" connectedTo="9d4c8b00-09d5-4d0a-8ef2-1e78322b1a5c"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="demand" id="58a80273-60f0-4304-a1fc-bf5af5712917" assetType="home_demand">
          <port xsi:type="esdl:InPort" id="30487fd4-1a9a-40f9-aca7-1bbb67f0c095" name="In_Ph1" connectedTo="1cccdaed-733d-490f-ac07-4bf942f05bc4"/>
          <port xsi:type="esdl:InPort" id="9536c28f-f6b5-4427-a9cc-2f5a2dd03a80" name="In_Ph2" connectedTo="130fa1ef-46b1-4cd4-abe2-705da3af4348"/>
          <port xsi:type="esdl:InPort" id="9d4c8b00-09d5-4d0a-8ef2-1e78322b1a5c" name="In_Ph3" connectedTo="9d97e52b-b622-4c85-aea4-4d1e5b5e0d35"/>
        </asset>
        <asset xsi:type="esdl:EConnection" name="30xhome890" id="31dbe2b4-a5d3-4480-bb37-b71d6bcfa3ac">
          <port xsi:type="esdl:InPort" id="4e38b881-4bb4-4dc2-b932-b05d49814c9b" name="In" connectedTo="37c277ba-a90f-4a7e-ae75-01071ec5d818"/>
          <port xsi:type="esdl:OutPort" id="9bf3271f-a5ac-4ffc-b70f-e324e9e07af1" name="OutPh1" connectedTo="749f1df5-290e-4461-ba90-3c040cb02638"/>
          <port xsi:type="esdl:OutPort" id="68c283aa-a9ca-42cb-a9e0-eadfc1f62f17" name="OutPh2" connectedTo="bfcbc6fb-605f-473b-a511-efdcbd0856fe"/>
          <port xsi:type="esdl:OutPort" id="f37f33ee-98f5-4dec-9b1a-3d9a956ef9db" name="OutPh3" connectedTo="34a9d639-cac4-4766-8241-19037785fc7a"/>
          <geometry xsi:type="esdl:Point" lat="157601.3232726871" lon="434145.8032422169"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:Import" name="mv_import_trafo10_lvnetwork3" id="3b59ee27-9a66-4863-8600-15f9dba7ca4d" assetType="10.0">
        <port xsi:type="esdl:OutPort" id="572483a4-fd1f-4086-9143-5e8a32b56b1a" name="Out" connectedTo="8db28a54-9a2c-45d2-8623-5bdc1153dc3f"/>
        <geometry xsi:type="esdl:Point" lat="157562.546" CRS="WGS84" lon="433996.815"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="mv_import_joint_trafo10_lvnetwork3" id="6b3611c8-720e-4389-8cab-fde414998776">
        <port xsi:type="esdl:InPort" id="8db28a54-9a2c-45d2-8623-5bdc1153dc3f" name="In" connectedTo="572483a4-fd1f-4086-9143-5e8a32b56b1a"/>
        <port xsi:type="esdl:OutPort" id="d0793acf-01da-440a-b3fe-404df78c8e75" name="Out" connectedTo="d3f32e80-8440-4c55-b023-18dd1107596f"/>
        <geometry xsi:type="esdl:Point" lat="157562.546" CRS="WGS84" lon="433996.815"/>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.4" voltagePrimary="10.0" name="transformer63" id="00340261-99c8-46b4-81d6-d8494e1f14d2" commissioningDate="1991-01-01T00:00:00.000000" assetType="testtrafotype">
        <port xsi:type="esdl:InPort" id="d3f32e80-8440-4c55-b023-18dd1107596f" name="In" connectedTo="d0793acf-01da-440a-b3fe-404df78c8e75"/>
        <port xsi:type="esdl:OutPort" id="268a0a66-2b80-491c-8c1f-ada7a1988f14" name="Out" connectedTo="08a854cb-9744-42ea-acac-8d6b1d1869d8"/>
        <geometry xsi:type="esdl:Point" lat="157562.546" CRS="WGS84" lon="433996.815"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="lvjoint65" id="c79b2608-1f7b-45a2-825e-2a0172ebdc31">
        <port xsi:type="esdl:InPort" id="08a854cb-9744-42ea-acac-8d6b1d1869d8" name="In" connectedTo="268a0a66-2b80-491c-8c1f-ada7a1988f14"/>
        <port xsi:type="esdl:OutPort" id="456d2307-ee17-4369-bac3-3ec4112f581d" name="Out" connectedTo="dfeb3880-fe03-4789-89a8-2a512f818c10"/>
        <geometry xsi:type="esdl:Point" lat="157562.546" CRS="WGS84" lon="433996.815"/>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
